document.getElementById("vocab-title").textContent = "生词(HSK3)：ពាក្យថ្មី";

const words = [
  { word: "啊", pinyin: "a", khmer: "អា!/សំនើច" },
  { word: "阿姨", pinyin: "ā yí", khmer: "មីង" },
  { word: "矮", pinyin: "ǎi", khmer: "ទាប/តឿ" },
  { word: "爱好", pinyin: "ài hào", khmer: "ចំណង់ចំណូលចិត្ត" },
  { word: "安静", pinyin: "ān jìng", khmer: "ស្ងៀមស្ងាត់" },
  { word: "把", pinyin: "bǎ", khmer: "តោះ" },
  { word: "搬", pinyin: "bān", khmer: "ផ្លាស់ទី" },
  { word: "班", pinyin: "bān", khmer: "ថ្នាក់" },
  { word: "办法", pinyin: "bàn fǎ", khmer: "វិធីសាស្រ្ត" },
  { word: "办公室", pinyin: "bàn gōng shì", khmer: "ការិយាល័យ" },
  { word: "半", pinyin: "bàn", khmer: "ពាក់កណ្តាល/កន្លះ" },
  { word: "帮忙", pinyin: "bāng máng", khmer: "ជួយ" },
  { word: "包", pinyin: "bāo", khmer: "កាបូប" },
  { word: "饱", pinyin: "bǎo", khmer: "ឆ្អាត/ពេញ" },
  { word: "北方", pinyin: "běi fāng", khmer: "ខាងជើង" },
  { word: "被", pinyin: "bèi", khmer: "ត្រូវបាន/ភួយ" },
  { word: "鼻子", pinyin: "bí zi", khmer: "ច្រមុះ" },
  { word: "比较", pinyin: "bǐ jiào", khmer: "ប្រៀបធៀប" },
  { word: "比赛", pinyin: "bǐ sài", khmer: "ប្រកួតប្រជែង" },
  { word: "笔记本", pinyin: "bǐ jì běn", khmer: "សៀវភៅកត់ត្រា" },
  { word: "必须", pinyin: "bì xū", khmer: "ត្រូវតែ" },
  { word: "变化", pinyin: "biàn huà", khmer: "ភាពខុសគ្នា" },
  { word: "别人", pinyin: "bié rén", khmer: "អ្នក​ផ្សេង" },
  { word: "冰箱", pinyin: "bīng xiāng", khmer: "ទូទឹកកក" },
  { word: "不但…而且…", pinyin: "bù dàn … ér qiě …", khmer: "មិន​ត្រឹមតែ​ប៉ុណ្ណោះទេ​.........ថែមទាំង…" },
  { word: "菜单", pinyin: "cài dān", khmer: "ម៉ឺនុយ" },
  { word: "参加", pinyin: "cān jiā", khmer: "ចូលរួម" },
  { word: "草", pinyin: "cǎo", khmer: "ស្មៅ" },
  { word: "层", pinyin: "céng", khmer: "ជាន់" },
  { word: "差", pinyin: "chà", khmer: "ខុស/អាក្រក់/នៅខ្វះ" },
  { word: "超市", pinyin: "chāo shì", khmer: "ផ្សារទំនើប" },
  { word: "衬衫", pinyin: "chèn shān", khmer: "អាវ" },
  { word: "城市", pinyin: "chéng shì", khmer: "ទីក្រុង" },
  { word: "成绩", pinyin: "chéng jì", khmer: "ថ្នាក់" },
  { word: "迟到", pinyin: "chí dào", khmer: "យឺត" },
  { word: "除了", pinyin: "chú le", khmer: "ក្រៅពី" },
  { word: "船", pinyin: "chuán", khmer: "សាឡាង" },
  { word: "春", pinyin: "chūn", khmer: "និទាឃរដូវ" },
  { word: "词典", pinyin: "cí diǎn", khmer: "វចនានុក្រម" },
  { word: "聪明", pinyin: "cōng ming", khmer: "ឆ្លាត" },
  { word: "打扫", pinyin: "dǎ sǎo", khmer: "សំអាត" },
  { word: "打算", pinyin: "dǎ suàn", khmer: "មានបំណង/គ្រោង" },
  { word: "带", pinyin: "dài", khmer: "នាំ" },
  { word: "担心", pinyin: "dān xīn", khmer: "បារម្ភ" },
  { word: "蛋糕", pinyin: "dàn gāo", khmer: "នំខេក" },
  { word: "当然", pinyin: "dāng rán", khmer: "ពិតប្រាកដ​ណាស់" },
  { word: "地", pinyin: "de", khmer: "ដី (ភាគល្អិត)" },
  { word: "灯", pinyin: "dēng", khmer: "ពន្លឺ/អំពូល" },
  { word: "地方", pinyin: "dì fang", khmer: "ទីកន្លែង" },
  { word: "地铁", pinyin: "dì tiě", khmer: "រថភ្លើងក្រោមដី" },
  { word: "地图", pinyin: "dì tú", khmer: "ផែនទី" },
  { word: "电梯", pinyin: "diàn tī", khmer: "ជណ្តើរប្រអប់" },
  { word: "电子邮件", pinyin: "diàn zǐ yóu jiàn", khmer: "អ៊ីមែល" },
  { word: "东", pinyin: "dōng", khmer: "ខាងកើត" },
  { word: "冬", pinyin: "dōng", khmer: "រដូវរងារ" },
  { word: "动物", pinyin: "dòng wù", khmer: "សត្វ" },
  { word: "短", pinyin: "duǎn", khmer: "ខ្លី" },
  { word: "段", pinyin: "duàn", khmer: "ចម្រៀក" },
  { word: "锻炼", pinyin: "duàn liàn", khmer: "ហាត់ប្រាណ" },
  { word: "多么", pinyin: "duō me", khmer: "ប៉ុន្មាន" },
  { word: "饿", pinyin: "è", khmer: "ឃ្លាន" },
  { word: "耳朵", pinyin: "ěr duo", khmer: "ត្រចៀក" },
  { word: "发", pinyin: "fā", khmer: "សក់" },
  { word: "发烧", pinyin: "fā shāo", khmer: "គ្រុន" },
  { word: "发现", pinyin: "fā xiàn", khmer: "រកឃើញ/ចាប់អារម្មណ៍" },
  { word: "方便", pinyin: "fāng biàn", khmer: "ភាពងាយស្រួល" },
  { word: "放", pinyin: "fàng", khmer: "ដាក់" },
  { word: "放心", pinyin: "fàng xīn", khmer: "បង្រ្កាបចិត្ត" },
  { word: "分", pinyin: "fēn", khmer: "នាទី" },
  { word: "复习", pinyin: "fù xí", khmer: "ពិនិត្យឡើងវិញ" },
  { word: "附近", pinyin: "fù jìn", khmer: "នៅ​ជិត" },
  { word: "干净", pinyin: "gān jìng", khmer: "ស្អាត" },
  { word: "感冒", pinyin: "gǎn mào", khmer: "ត្រជាក់" },
  { word: "感兴趣", pinyin: "gǎn xìng qù", khmer: "ចាប់អារម្មណ៍​លើ" },
  { word: "刚才", pinyin: "gāng cái", khmer: "ឥឡូវនេះ" },
  { word: "个子", pinyin: "gè zi", khmer: "កម្ពស់" },
  { word: "根据", pinyin: "gēn jù", khmer: "យោង​ទៅ​តាម" },
  { word: "跟", pinyin: "gēn", khmer: "ជាមួយ" },
  { word: "更", pinyin: "gèng", khmer: "ច្រើនទៀត" },
  { word: "公斤", pinyin: "gōng jīn", khmer: "គឺឡូក្រាម" },
  { word: "公园", pinyin: "gōng yuán", khmer: "ឧទ្យាន/សួន" },
  { word: "故事", pinyin: "gù shi", khmer: "រឿង" },
  { word: "刮风", pinyin: "guā fēng", khmer: "ខ្យល់" },
  { word: "关", pinyin: "guān", khmer: "បិទ" },
  { word: "关系", pinyin: "guān xì", khmer: "ទំនាក់ទំនង" },
  { word: "关心", pinyin: "guān xīn", khmer: "ការព្រួយបារម្ភ" },
  { word: "关于", pinyin: "guān yú", khmer: "អំពី" },
  { word: "国家", pinyin: "guó jiā", khmer: "ប្រទេស" },
  { word: "过", pinyin: "guò", khmer: "ឆ្លងកាត់ (កិរិយាស័ព្ទ)" },
  { word: "过去", pinyin: "guò qu", khmer: "អតីតកាល/ទៅ" },
  { word: "还是", pinyin: "hái shì", khmer: "នៅតែមាន" },
  { word: "害怕", pinyin: "hài pà", khmer: "ខ្លាច" },
  { word: "黑板", pinyin: "hēi bǎn", khmer: "ក្តារខៀន" },
  { word: "后来", pinyin: "hòu lái", khmer: "ក្រោយមក" },
  { word: "护照", pinyin: "hù zhào", khmer: "លិខិតឆ្លងដែន" },
  { word: "花", pinyin: "huā", khmer: "ផ្កា (កិរិយាស័ព្ទ)" },
  { word: "花", pinyin: "huā", khmer: "ផ្កា (នាម)" },
  { word: "画", pinyin: "huà", khmer: "គំនូរ" },
  { word: "坏", pinyin: "huài", khmer: "អាក្រក់" },
  { word: "欢迎", pinyin: "huān yíng", khmer: "សូមស្វាគមន៍" },
  { word: "环境", pinyin: "huán jìng", khmer: "តំបន់ជុំវិញ" },
  { word: "还", pinyin: "hái", khmer: " នៅតែ / ក៏មាន / ក៏ដែរ" },
  { word: "换", pinyin: "huàn", khmer: "ផ្លាស់ប្តូរ" },
  { word: "黄河", pinyin: "huáng hé", khmer: "ទន្លេលឿង" },
  { word: "回答", pinyin: "huí dá", khmer: "ឆ្លើយតប/ចម្លើយ" },
  { word: "会议", pinyin: "huì yì", khmer: "ប្រជុំ" },
  { word: "或者", pinyin: "huò zhě", khmer: "ឬ" },
  { word: "几乎", pinyin: "jī hū", khmer: "ជិត" },
  { word: "机会", pinyin: "jī huì", khmer: "ឱកាស" },
  { word: "极", pinyin: "jí", khmer: "ជាលំដាប់" },
  { word: "季节", pinyin: "jì jié", khmer: "រដូវកាល" },
  { word: "记得", pinyin: "jì de", khmer: "ចងចាំ" },
  { word: "检查", pinyin: "jiǎn chá", khmer: "ការត្រួតពិនិត្យ" },
  { word: "简单", pinyin: "jiǎn dān", khmer: "សាមញ្ញ" },
  { word: "健康", pinyin: "jiàn kāng", khmer: "សុខភាព" },
  { word: "见面", pinyin: "jiàn miàn", khmer: "ជួប" },
  { word: "讲", pinyin: "jiǎng", khmer: "និយាយ" },
  { word: "教", pinyin: "jiào", khmer: "បង្រៀន" },
  { word: "脚", pinyin: "jiǎo", khmer: "ជើង" },
  { word: "角", pinyin: "jiǎo", khmer: "មុំ" },
  { word: "接", pinyin: "jiē", khmer: "ទទួល/ភ្ជាប់/បន្ត" },
  { word: "街道", pinyin: "jiē dào", khmer: "ផ្លូវ" },
  { word: "结婚", pinyin: "jié hūn", khmer: "រៀបការ" },
  { word: "结束", pinyin: "jié shù", khmer: "បញ្ចប់" },
  { word: "节目", pinyin: "jié mù", khmer: "កម្មវិធី" },
  { word: "节日", pinyin: "jié rì", khmer: "ពិធីបុណ្យ" },
  { word: "解决", pinyin: "jiě jué", khmer: "ដោះស្រាយ" },
  { word: "借", pinyin: "jiè", khmer: "ខ្ចី" },
  { word: "经常", pinyin: "jīng cháng", khmer: "ជាញឹកញាប់" },
  { word: "经过", pinyin: "jīng guò", khmer: "បន្ទាប់ពី" },
  { word: "经理", pinyin: "jīng lǐ", khmer: "អ្នកគ្រប់គ្រង" },
  { word: "久", pinyin: "jiǔ", khmer: "យូរ" },
  { word: "旧", pinyin: "jiù", khmer: "ចាស់" },
  { word: "句子", pinyin: "jù zi", khmer: "ប្រយោគ" },
  { word: "决定", pinyin: "jué dìng", khmer: "សម្រេចចិត្ត" },
  { word: "可爱", pinyin: "kě ài", khmer: "គួរឱ្យស្រឡាញ់" },
  { word: "渴", pinyin: "kě", khmer: "ផឹក" },
  { word: "刻", pinyin: "kè", khmer: "កន្លះ(១៥នាទីម៉ោងកន្លះ" },
  { word: "客人", pinyin: "kè rén", khmer: "ភ្ញៀវ" },
  { word: "空调", pinyin: "kōng tiáo", khmer: "ម៉ាស៊ីនត្រជាក់" },
  { word: "口", pinyin: "kǒu", khmer: "មាត់" },
  { word: "哭", pinyin: "kū", khmer: "យំ" },
  { word: "裤子", pinyin: "kù zi", khmer: "ខោ" },
  { word: "筷子", pinyin: "kuài zi", khmer: "ចង្កឹះ" },
  { word: "蓝", pinyin: "lán", khmer: "ខៀវ" },
  { word: "老", pinyin: "lǎo", khmer: "ចាស់" },
  { word: "离开", pinyin: "lí kāi", khmer: "ទៅ​ឆ្ងាយ" },
  { word: "礼物", pinyin: "lǐ wù", khmer: "អំណោយ/កាដូរ" },
  { word: "历史", pinyin: "lì shǐ", khmer: "ប្រវត្តិសាស្រ្ត" },
  { word: "脸", pinyin: "liǎn", khmer: "មុខ" },
  { word: "练习", pinyin: "liàn xí", khmer: "ធ្វើលំហាត់ប្រាណ" },
  { word: "辆", pinyin: "liàng", khmer: "យានយន្ត" },
  { word: "聊天", pinyin: "liáo tiān", khmer: "ជជែកជាមួយ" },
  { word: "了解", pinyin: "liǎo jiě", khmer: "យល់ដឹង/យល់ច្បាស់" },
  { word: "邻居", pinyin: "lín jū", khmer: "អ្នកជិតខាង" },
  { word: "留学", pinyin: "liú xué", khmer: "សិក្សា​នៅ​បរទេស" },
  { word: "楼", pinyin: "lóu", khmer: "ជាន់" },
  { word: "绿", pinyin: "lǜ", khmer: "បៃតង" },
  { word: "马", pinyin: "mǎ", khmer: "សេះ" },
  { word: "马上", pinyin: "mǎ shàng", khmer: "ភ្លាម" },
  { word: "满意", pinyin: "mǎn yì", khmer: "ការពេញចិត្ត" },
  { word: "帽子", pinyin: "mào zi", khmer: "មួក" },
  { word: "米", pinyin: "mǐ", khmer: "ម៉ែត្រ" },
  { word: "面包", pinyin: "miàn bāo", khmer: "នំបុ័ង" },
  { word: "明白", pinyin: "míng bai", khmer: "យល់" },
  { word: "拿", pinyin: "ná", khmer: "យក" },
  { word: "奶奶", pinyin: "nǎi nai", khmer: "ជីដូន" },
  { word: "南", pinyin: "nán", khmer: "ខាងត្បូង" },
  { word: "难", pinyin: "nán", khmer: "ពិបាក" },
  { word: "难过", pinyin: "nán guò", khmer: "សោកសៅ/សេដ" },
  { word: "年级", pinyin: "nián jí", khmer: "ថ្នាក់" },
  { word: "年轻", pinyin: "nián qīng", khmer: "វ័យក្មេង" },
  { word: "鸟", pinyin: "niǎo", khmer: "បក្សី" },
  { word: "努力", pinyin: "nǔ lì", khmer: "ខិតខំប្រឹងប្រែង​" },
  { word: "爬山", pinyin: "pá shān", khmer: "ការ​ឡើងភ្នំ" },
  { word: "盘子", pinyin: "pán zi", khmer: "ចាន" },
  { word: "胖", pinyin: "pàng", khmer: "ធាត់" },
  { word: "啤酒", pinyin: "pí jiǔ", khmer: "ស្រាបៀរ" },
  { word: "皮鞋", pinyin: "pí xié", khmer: "ស្បែកជើង​ស្បែក" },
  { word: "瓶子", pinyin: "píng zi", khmer: "ដប" },
  { word: "其实", pinyin: "qí shí", khmer: "ពិតប្រាកដ" },
  { word: "其他", pinyin: "qí tā", khmer: "ផ្សេងទៀត" },
  { word: "奇怪", pinyin: "qí guài", khmer: "ចម្លែក" },
  { word: "骑", pinyin: "qí", khmer: "ជិះ" },
  { word: "起飞", pinyin: "qǐ fēi", khmer: "ហោះចេញ" },
  { word: "起来", pinyin: "qǐ lái", khmer: "កើតឡើង" },
  { word: "清楚", pinyin: "qīng chu", khmer: "ច្បាស់" },
  { word: "请假", pinyin: "qǐng jià", khmer: "ស្នើសុំការឈប់សម្រាក" },
  { word: "秋", pinyin: "qiū", khmer: "រដូវស្លឹកឈើជ្រុះ" },
  { word: "裙子", pinyin: "qún zi", khmer: "សំពត់" },
  { word: "然后", pinyin: "rán hòu", khmer: "បន្ទាប់មក" },
  { word: "热情", pinyin: "rè qíng", khmer: "ភាពរីករាយ/កក់ក្តៅ" },
  { word: "认为", pinyin: "rèn wéi", khmer: "គិតថា" },
  { word: "认真", pinyin: "rèn zhēn", khmer: "យកចិត្តទុកដាក់/ត្រឹមត្រូវ" },
  { word: "容易", pinyin: "róng yì", khmer: "ងាយស្រួល" },
  { word: "如果", pinyin: "rú guǒ", khmer: "ប្រសិនបើ" },
  { word: "伞", pinyin: "sǎn", khmer: "ឆ័ត្រ" },
  { word: "上网", pinyin: "shàng wǎng", khmer: "អី​ន​ធើ​ណែត" },
  { word: "声音", pinyin: "shēng yīn", khmer: "សំឡេង" },
  { word: "生气", pinyin: "shēng qì", khmer: "បើកឡើង" },
  { word: "世界", pinyin: "shì jiè", khmer: "ពិភពលោក" },
  { word: "试", pinyin: "shì", khmer: "សាកល្បង" },
  { word: "瘦", pinyin: "shòu", khmer: "ស្គម" },
  { word: "叔叔", pinyin: "shū shu", khmer: "ពូ" },
  { word: "舒服", pinyin: "shū fu", khmer: "មាន​ផា​សុខភាព" },
  { "word": "数学", "pinyin": "shù xué", "khmer": "គណិតវិទ្យា" },
  { "word": "树", "pinyin": "shù", "khmer": "ដើមឈើ" },
  { "word": "刷牙", "pinyin": "shuā yá", "khmer": "ដុសធ្មេញ​" },
  { "word": "双", "pinyin": "shuāng", "khmer": "គូរ" },
  { "word": "水平", "pinyin": "shuǐ píng", "khmer": "កំរិត" },
  { "word": "司机", "pinyin": "sī jī", "khmer": "អ្នកបើកបរ" },
  { "word": "太阳", "pinyin": "tài yáng", "khmer": "ព្រះអាទិត្យ" },
  { "word": "特别", "pinyin": "tè bié", "khmer": "ជាពិសេស" },
  { "word": "疼", "pinyin": "téng", "khmer": "ឈឺចាប់" },
  { "word": "提高", "pinyin": "tí gāo", "khmer": "ធ្វើឱ្យប្រសើរឡើង/បង្កើន" },
  { "word": "体育", "pinyin": "tǐ yù", "khmer": "កីឡា" },
  { "word": "甜", "pinyin": "tián", "khmer": "ផ្អែម" },
  { "word": "条", "pinyin": "tiáo", "khmer": "ជួរ/ក្រឡា" },
  { "word": "同事", "pinyin": "tóng shì", "khmer": "មិត្តរួមការងារ" },
  { "word": "同意", "pinyin": "tóng yì", "khmer": "យល់ព្រម" },
  { "word": "头发", "pinyin": "tóu fa", "khmer": "សក់" },
  { "word": "突然", "pinyin": "tū rán", "khmer": "ភ្លាមៗ" },
  { "word": "图书馆", "pinyin": "tú shū guǎn", "khmer": "បណ្ណាល័យ" },
  { "word": "腿", "pinyin": "tuǐ", "khmer": "ជើង" },
  { "word": "完成", "pinyin": "wán chéng", "khmer": "អនុវត្ត" },
  { "word": "碗", "pinyin": "wǎn", "khmer": "ចាន" },
  { "word": "万", "pinyin": "wàn", "khmer": "មួយ​ម៉ឺន" },
  { "word": "忘记", "pinyin": "wàng jì", "khmer": "ភ្លេច" },
  { "word": "为", "pinyin": "wèi", "khmer": "សម្រាប់" },
  { "word": "为了", "pinyin": "wèi le", "khmer": "ដើម្បី" },
  { "word": "位", "pinyin": "wèi", "khmer": "ឯកតា" },
  { "word": "文化", "pinyin": "wén huà", "khmer": "វប្បធម៌" },
  { "word": "西", "pinyin": "xī", "khmer": "អូ" },
  { "word": "习惯", "pinyin": "xí guàn", "khmer": "ទំលាប់" },
  { "word": "洗手间", "pinyin": "xǐ shǒu jiān", "khmer": "បន្ទប់ទឹក" },
  { "word": "洗澡", "pinyin": "xǐ zǎo", "khmer": "ងូតទឹក" },
  { "word": "夏", "pinyin": "xià", "khmer": "រដូវក្តៅ" },
  { "word": "先", "pinyin": "xiān", "khmer": "ដំបូង" },
  { "word": "相信", "pinyin": "xiāng xìn", "khmer": "ជឿ/ទុកចិត្ត" },
  { "word": "香蕉", "pinyin": "xiāng jiāo", "khmer": "ចេក" },
  { "word": "像", "pinyin": "xiàng", "khmer": "ដូច/ស្រដៀង" },
  { "word": "向", "pinyin": "xiàng", "khmer": "ឆ្ពោះទៅ" },
  { "word": "小心", "pinyin": "xiǎo xīn", "khmer": "​ប្រុង​ប្រ​យ​ត្ន័" },
  { "word": "校长", "pinyin": "xiào zhǎng", "khmer": "នាយកសាលា" },
  { "word": "新闻", "pinyin": "xīn wén", "khmer": "ព័ត៌មាន" },
  { "word": "新鲜", "pinyin": "xīn xiān", "khmer": "ស្រស់" },
  { "word": "信用卡", "pinyin": "xìn yòng kǎ", "khmer": "កាត​ឥណទាន" },
  { "word": "行李箱", "pinyin": "xíng lǐ xiāng", "khmer": "ប្រអប់សំភារៈ" },
  { "word": "熊猫", "pinyin": "xióng māo", "khmer": "ផេនដា" },
  { "word": "需要", "pinyin": "xū yào", "khmer": "ត្រូវការ" },
  { "word": "选择", "pinyin": "xuǎn zé", "khmer": "ជ្រើសរើស" },
  { "word": "要求", "pinyin": "yāo qiú", "khmer": "ការទាមទារ/ត្រូវការ" },
  { "word": "爷爷", "pinyin": "yé ye", "khmer": "ជីតា" },
  { "word": "一直", "pinyin": "yī zhí", "khmer": "ជានិច្ច" },
  { "word": "一定", "pinyin": "yí dìng", "khmer": "​ប្រាកដ" },
  { "word": "一共", "pinyin": "yī gòng", "khmer": "សរុប" },
  { "word": "一会儿", "pinyin": "yī huì er", "khmer": "មួយរយៈ" },
  { "word": "一样", "pinyin": "yī yàng", "khmer": "ដូចគ្នា" },
  { "word": "以前", "pinyin": "yǐ qián", "khmer": "មុន" },
  { "word": "一般", "pinyin": "yī bān", "khmer": "ទូទៅ/ធម្មតា" },
  { "word": "一边", "pinyin": "yī biān", "khmer": "បណ្តើរ" },
  { "word": "音乐", "pinyin": "yīn yuè", "khmer": "តន្ត្រី" },
  { "word": "银行", "pinyin": "yín háng", "khmer": "ធនាគារ" },
  { "word": "饮料", "pinyin": "yǐn liào", "khmer": "ភេសជ្ជៈ" },
  { "word": "应该", "pinyin": "yīng gāi", "khmer": "គួរតែ" },
  { "word": "影响", "pinyin": "yǐng xiǎng", "khmer": "មាន​ឥទ្ធិពល/ប៉ះពាល់" },
  { "word": "用", "pinyin": "yòng", "khmer": "ប្រើ" },
  { "word": "游戏", "pinyin": "yóu xì", "khmer": "ហ្គេម" },
  { "word": "有名", "pinyin": "yǒu míng", "khmer": "ល្បីល្បាញ" },
  { "word": "又", "pinyin": "yòu", "khmer": "វិញ/ទៀត" },
  { "word": "遇到", "pinyin": "yù dào", "khmer": "ជួប" },
  { "word": "元", "pinyin": "yuán", "khmer": "យន់/ប្រាក់ចិន" },
  { "word": "愿意", "pinyin": "yuàn yì", "khmer": "មានឆន្ទៈ" },
  { "word": "月亮", "pinyin": "yuè liang", "khmer": "ព្រះ​ច័ន្ទ" },
  { "word": "越", "pinyin": "yuè", "khmer": "ច្រើនទៀត" },
  { "word": "站", "pinyin": "zhàn", "khmer": "ស្ថានីយ៍" },
  { "word": "张", "pinyin": "zhāng", "khmer": "សន្លឹក" },
  { "word": "长", "pinyin": "zhǎng", "khmer": "វែង (កិរិយាស័ព្ទ)" },
  { "word": "着急", "pinyin": "zháo jí", "khmer": "ព្រួយបារម្ភ" },
  { "word": "照顾", "pinyin": "zhào gu", "khmer": "ថែរក្សា" },
  { "word": "照片", "pinyin": "zhào piàn", "khmer": "រូបថត" },
  { "word": "照相机", "pinyin": "zhào xiàng jī", "khmer": "កាមេរ៉ា" },
  { "word": "只", "pinyin": "zhǐ", "khmer": "តែ (adverb)" },
  { "word": "只", "pinyin": "zhǐ", "khmer": "តែ/ប៉ុណ្ណោះ (ឧបករណ៍កំណត់)" },
  { "word": "只有…才…", "pinyin": "zhǐ yǒu …cái …", "khmer": "មានតែ ..." },
  { "word": "中间", "pinyin": "zhōng jiān", "khmer": "កម្រិតមធ្យម" },
  { "word": "中文", "pinyin": "zhōng wén", "khmer": "ភាសាចិន" },
  { "word": "终于", "pinyin": "zhōng yú", "khmer": "ចុងក្រោយ" },
  { "word": "种", "pinyin": "zhǒng", "khmer": "ប្រភេទ (បរិមាណ)" },
  { "word": "重要", "pinyin": "zhòng yào", "khmer": "សំខាន់" },
  { "word": "周末", "pinyin": "zhōu mò", "khmer": "ចុងសប្តាហ៍" },
  { "word": "主要", "pinyin": "zhǔ yào", "khmer": "មូលដ្ឋាន/សំខាន់" },
  { "word": "注意", "pinyin": "zhù yì", "khmer": "ចំណាំ/ប្រុងប្រយ័ត្ន" },
  { "word": "自己", "pinyin": "zì jǐ", "khmer": "ខ្លួនឯង" },
  { "word": "自行车", "pinyin": "zì xíng chē", "khmer": "កង់" },
  { "word": "总是", "pinyin": "zǒng shì", "khmer": "តែងតែ/គ្រប់ពេល" },
  { "word": "嘴", "pinyin": "zuǐ", "khmer": "មាត់" },
  { "word": "最后", "pinyin": "zuì hòu", "khmer": "ចុងក្រោយ" },
  { "word": "最近", "pinyin": "zuì jìn", "khmer": "ថ្មីៗនេះ" },
  { "word": "作业", "pinyin": "zuò yè", "khmer": "កិច្ចការផ្ទះ" }
 
];

const wordList = document.getElementById("word-list");

words.forEach(({ word, pinyin, khmer }) => {
  const card = document.createElement("div");
  card.className = "word-card";
  card.innerHTML = `
    <div class="word">${word}</div>
    <div class="pinyin">${pinyin}</div>
    <div class="khmer">${khmer}</div>
  `;
  wordList.appendChild(card);
});
