document.getElementById("vocab-title").textContent = "生词：ពាក្យថ្មី";

const words = [
  { word: "爱", pinyin: "ài", khmer: "ស្រឡាញ់" },
  { word: "八", pinyin: "bā", khmer: "ប្រាំបី" },
  { word: "爸爸", pinyin: "bà ba", khmer: "ឪពុក/ប៉ា" },
  { word: "杯子", pinyin: "bēi zi", khmer: "ពែង/កែ" },
  { word: "北京", pinyin: "běi jīng", khmer: "ទីក្រុងប៉េកាំង" },
  { word: "本", pinyin: "běn", khmer: "ឯកតាសៀវភៅ" },
  { word: "不客气", pinyin: "bú kè qi", khmer: "កុំ​គួរសម​អី" },
  { word: "不", pinyin: "bù", khmer: "កុំ" },
  { word: "菜", pinyin: "cài", khmer: "ម្ហូប" },
  { word: "茶", pinyin: "chá", khmer: "តែ" },
  { word: "吃", pinyin: "chī", khmer: "បរិភោគ" },
  { word: "出租车", pinyin: "chū zū chē", khmer: "តាក់ស៊ី" },
  { word: "打电话", pinyin: "dǎ diàn huà", khmer: "ការហៅទូរស័ព្ទ" },
  { word: "大", pinyin: "dà", khmer: "ធំ" },
  { word: "的", pinyin: "de", khmer: "របស់" },
  { word: "点", pinyin: "diǎn", khmer: "ម៉ោង" },
  { word: "电脑", pinyin: "diàn nǎo", khmer: "កុំព្យូទ័រ" },
  { word: "电视", pinyin: "diàn shì", khmer: "ទូរទស្សន៍" },
  { word: "电影", pinyin: "diàn yǐng", khmer: "ភាពយន្ត/កុន" },
  { word: "东西", pinyin: "dōng xi", khmer: "អីវ៉ាន/របស់របរ" },
  { word: "都", pinyin: "dōu", khmer: "ទាំងអស់/ទាំងពី" },
  { word: "读", pinyin: "dú", khmer: "អាន" },
  { word: "对不起", pinyin: "duì bu qǐ", khmer: "សុំទោស" },
  { word: "多", pinyin: "duō", khmer: "ច្រើន" },
  { word: "多少", pinyin: "duō shǎo", khmer: "ប៉ុន្មាន" },
  { word: "儿子", pinyin: "ér zi", khmer: "កូនប្រុស" },
  { word: "二", pinyin: "èr", khmer: "ពីរ" },
  { word: "饭店", pinyin: "fàn diàn", khmer: "ភោជនីយដ្ឋាន" },
  { word: "飞机", pinyin: "fēi jī", khmer: "យន្តហោះ" },
  { word: "分钟", pinyin: "fēn zhōng", khmer: "នាទី" },
  { word: "高兴", pinyin: "gāo xìng", khmer: "រីករាយ" },
  { word: "个", pinyin: "gè", khmer: "ឯកតាចំនួ​នមួយ" },
  { word: "工作", pinyin: "gōng zuò", khmer: "ការងារ" },
  { word: "狗", pinyin: "gǒu", khmer: "ឆ្កែ" },
  { word: "汉语", pinyin: "hàn yǔ", khmer: "ភាសាចិន" },
  { word: "好", pinyin: "hǎo", khmer: "វាល្អ" },
  { word: "号", pinyin: "hào", khmer: "ចំនួន" },
  { word: "喝", pinyin: "hē", khmer: "ផឹក" },
  { word: "和", pinyin: "hé", khmer: "ជាមួយ" },
  { word: "很", pinyin: "hěn", khmer: "ខ្លាំងណាស់" },
  { word: "后面", pinyin: "hòu miàn", khmer: "នៅខាងក្រោយ" },
  { word: "回", pinyin: "huí", khmer: "ត្រឡាប់ទៅ" },
  { word: "会", pinyin: "huì", khmer: "ចេះ/អាច" },
  { word: "几", pinyin: "jǐ", khmer: "ពីរ​ឬ​បី/ប៉ុន្មាន" },
  { word: "家", pinyin: "jiā", khmer: "ផ្ទះ" },
  { word: "叫", pinyin: "jiào", khmer: "ហៅ" },
  { word: "今天", pinyin: "jīn tiān", khmer: "ថ្ងៃ​នេះ" },
  { word: "九", pinyin: "jiǔ", khmer: "ប្រាំបួន" },
  { word: "开", pinyin: "kāi", khmer: "បើក" },
  { word: "看", pinyin: "kàn", khmer: "មើល" },
  { word: "看见", pinyin: "kàn jiàn", khmer: "ឃើញ" },
  { word: "块", pinyin: "kuài", khmer: "ដុំ" },
  { word: "来", pinyin: "lái", khmer: "មក" },
  { word: "老师", pinyin: "lǎo shī", khmer: "គ្រូ" },
  { word: "了", pinyin: "le", khmer: "ហើយ/បាន" },
  { word: "冷", pinyin: "lěng", khmer: "ត្រជាក់" },
  { word: "里", pinyin: "lǐ", khmer: "ក្នុង" },
  { word: "六", pinyin: "liù", khmer: "ប្រាំមួយ" },
  { word: "吗", pinyin: "ma", khmer: "តើ...ទេ?" },
  { word: "妈妈", pinyin: "mā ma", khmer: "ម៉ាក់" },
  { word: "买", pinyin: "mǎi", khmer: "ទិញ" },
  { word: "猫", pinyin: "māo", khmer: "ឆ្មា" },
  { word: "没关系", pinyin: "méi guān xi", khmer: "មិន​អី​ទេ" },
  { word: "没有", pinyin: "méi yǒu", khmer: "មិនមាន/គ្មាន" },
  { word: "米饭", pinyin: "mǐ fàn", khmer: "អង្ករ/បាយ" },
  { word: "名字", pinyin: "míng zi", khmer: "ឈ្មោះ" },
  { word: "明天", pinyin: "míng tiān", khmer: "ថ្ងៃស្អែក" },
  { word: "哪", pinyin: "nǎ", khmer: "កន្លែងណា" },
  { word: "哪儿", pinyin: "nǎ er", khmer: "កន្លែងណា" },
  { word: "那", pinyin: "nà", khmer: "នោះ" },
  { word: "呢", pinyin: "ne", khmer: "ចុះ..វិញ" },
  { word: "能", pinyin: "néng", khmer: "អាច" },
  { word: "你", pinyin: "nǐ", khmer: "អ្នក" },
  { word: "年", pinyin: "nián", khmer: "ឆ្នាំ" },
  { word: "女儿", pinyin: "nǚ ér", khmer: "កូនស្រី" },
  { word: "朋友", pinyin: "péng you", khmer: "មិត្តភក្តិ" },
  { word: "漂亮", pinyin: "piào liang", khmer: "ស្អាត" },
  { word: "苹果", pinyin: "píng guǒ", khmer: "ផ្លែប៉ោម" },
  { word: "七", pinyin: "qī", khmer: "ប្រាំពីរ" },
  { word: "前面", pinyin: "qián miàn", khmer: "មុខ" },
  { word: "钱", pinyin: "qián", khmer: "លុយ" },
  { word: "请", pinyin: "qǐng", khmer: "សូម" },
  { word: "去", pinyin: "qù", khmer: "ទៅ​" },
  { word: "热", pinyin: "rè", khmer: "ក្តៅ" },
  { word: "人", pinyin: "rén", khmer: "មនុស្ស" },
  { word: "认识", pinyin: "rèn shi", khmer: "ដឹង/ស្គាល់" },
  { word: "三", pinyin: "sān", khmer: "បី" },
  { word: "商店", pinyin: "shāng diàn", khmer: "ហាង" },
  { word: "上", pinyin: "shàng", khmer: "បើក" },
  { word: "上午", pinyin: "shàng wǔ", khmer: "ពេលព្រឹក" },
  { word: "少", pinyin: "shǎo", khmer: "តិច" },
  { word: "谁", pinyin: "shéi", khmer: "នរណា" },
  { word: "什么", pinyin: "shén me", khmer: "អ្វី" },
  { word: "十", pinyin: "shí", khmer: "ដប់" },
  { word: "时候", pinyin: "shí hou", khmer: "ពេលវេលា" },
  { word: "是", pinyin: "shì", khmer: "គឺជា/ជា" },
  { word: "书", pinyin: "shū", khmer: "សៀវភៅ" },
  { word: "水", pinyin: "shuǐ", khmer: "ទឹក" },
  { word: "水果", pinyin: "shuǐ guǒ", khmer: "ផ្លែឈើ" },
  { word: "睡觉", pinyin: "shuì jiào", khmer: "ចូលគេង" },
  { word: "说", pinyin: "shuō", khmer: "និយាយ" },
  { word: "四", pinyin: "sì", khmer: "បួន" },
  { word: "岁", pinyin: "suì", khmer: "អាយុ" },
  { word: "他", pinyin: "tā", khmer: "គាត់(សំដៅលើមនុស្សប្រុស)" },
  { word: "她", pinyin: "tā", khmer: "នាង(សំដៅលើមនុស្សស្រី)​" },
  { word: "太", pinyin: "tài", khmer: "ផងដែរ" },
  { word: "天气", pinyin: "tiān qì", khmer: "អាកាសធាតុ" },
  { word: "听", pinyin: "tīng", khmer: "ស្តាប់" },
  { word: "同学", pinyin: "tóng xué", khmer: "មិត្តរួមថ្នាក់" },
  { word: "喂", pinyin: "wèi", khmer: "សួស្តី (សំដៅលើការនិយាយទូរស័ព្ទ)" },
  { word: "我", pinyin: "wǒ", khmer: "ខ្ញុំ" },
  { word: "我们", pinyin: "wǒ men", khmer: "ពួកយើង" },
  { word: "五", pinyin: "wǔ", khmer: "ប្រាំ" },
  { word: "喜欢", pinyin: "xǐ huan", khmer: "ចូលចិត្ត" },
  { word: "下", pinyin: "xià", khmer: "នៅក្រោម" },
  { word: "下午", pinyin: "xià wǔ", khmer: "នៅពេល​រសៀល" },
  { word: "下雨", pinyin: "xià yǔ", khmer: "ភ្លៀង" },
  { word: "先生", pinyin: "xiān sheng", khmer: "លោក(លោកម្ចាស់" },
  { word: "现在", pinyin: "xiàn zài", khmer: "ឥឡូវនេះ" },
  { word: "想", pinyin: "xiǎng", khmer: "នឹក​/គិត/ចង់" },
  { word: "小", pinyin: "xiǎo", khmer: "តូច" },
  { word: "小姐", pinyin: "xiǎo jie", khmer: "នឹក" },
  { word: "些", pinyin: "xiē", khmer: "ខ្លះ" },
  { word: "写", pinyin: "xiě", khmer: "សរសេរ" },
  { word: "谢谢", pinyin: "xiè xie", khmer: "សូមអរគុណ" },
  { word: "星期", pinyin: "xīng qī", khmer: "សប្តាហ៍" },
  { word: "学生", pinyin: "xué sheng", khmer: "សិស្ស" },
  { word: "学习", pinyin: "xué xí", khmer: "រៀន/សិក្សា" },
  { word: "学校", pinyin: "xué xiào", khmer: "សាលារៀន" },
  { word: "一", pinyin: "yī", khmer: "មួយ" },
  { word: "一点儿", pinyin: "yī diǎnr", khmer: "បន្តិចបន្តួច" },
  { word: "医生", pinyin: "yī shēng", khmer: "គ្រូពេទ្យ" },
  { word: "医院", pinyin: "yī yuàn", khmer: "មន្ទីរពេទ្យ" },
  { word: "衣服", pinyin: "yī fu", khmer: "សម្លៀកបំពាក់/ខោអាវ" },
  { word: "椅子", pinyin: "yǐ zi", khmer: "កៅអី" },
  { word: "有", pinyin: "yǒu", khmer: "មាន" },
  { word: "月", pinyin: "yuè", khmer: "ខែ" },
  { word: "再见", pinyin: "zài jiàn", khmer: "លាហើយ/ជំរាបលា" },
  { word: "在", pinyin: "zài", khmer: "នៅ/កំពុង" },
  { word: "怎么", pinyin: "zěn me", khmer: "របៀប" },
  { word: "怎么样", pinyin: "zěn me yàng", khmer: "យ៉ាងមិចដែរ" },
  { word: "这", pinyin: "zhè", khmer: "នេះ" },
  { word: "中国", pinyin: "zhōng guó", khmer: "ប្រទេសចិន" },
  { word: "中午", pinyin: "zhōng wǔ", khmer: "ថ្ងៃត្រង់" },
  { word: "住", pinyin: "zhù", khmer: "រស់នៅ" },
  { word: "桌子", pinyin: "zhuō zi", khmer: "តុ" },
  { word: "字", pinyin: "zì", khmer: "ពាក្យ" },
  { word: "昨天", pinyin: "zuó tiān", khmer: "ម្សិលមិញ" },
  { word: "做", pinyin: "zuò", khmer: "ធ្វើ" },
  { word: "坐", pinyin: "zuò", khmer: "អង្គុយ" }
];

const wordList = document.getElementById("word-list");

words.forEach(({ word, pinyin, khmer }) => {
  const card = document.createElement("div");
  card.className = "word-card";
  card.innerHTML = `
    <div class="word">${word}</div>
    <div class="pinyin">${pinyin}</div>
    <div class="khmer">${khmer}</div>
  `;
  wordList.appendChild(card);
});
