document.getElementById("vocab-title").textContent = "生词：ពាក្យថ្មី";

const words = [
  { word: "吧", pinyin: "ba", khmer: "បារ" },
  { word: "白", pinyin: "bái", khmer: "ស" },
  { word: "百", pinyin: "bǎi", khmer: "រយ" },
  { word: "帮助", pinyin: "bāng zhù", khmer: "ជួយ" },
  { word: "报纸", pinyin: "bào zhǐ", khmer: "កាសែត" },
  { word: "比", pinyin: "bǐ", khmer: "សមាមាត្រ" },
  { word: "别", pinyin: "bié", khmer: "កុំ" },
  { word: "宾馆", pinyin: "bīn guǎn", khmer: "សណ្ឋាគារ" },
  { word: "长", pinyin: "cháng", khmer: "វែង (គុណនាម)" },
  { word: "唱歌", pinyin: "chàng gē", khmer: "ច្រៀង" },
  { word: "出", pinyin: "chū", khmer: "ចេញ" },
  { word: "穿", pinyin: "chuān", khmer: "ពាក់" },
  { word: "次", pinyin: "cì", khmer: "ដង" },
  { word: "从", pinyin: "cóng", khmer: "ពី" },
  { word: "错", pinyin: "cuò", khmer: "ខុស" },
  { word: "打篮球", pinyin: "dǎ lán qiú", khmer: "លេង​បាល់បោះ" },
  { word: "大家", pinyin: "dà jiā", khmer: "អ្នករាល់គ្នា" },
  { word: "到", pinyin: "dào", khmer: "ទៅ" },
  { word: "得", pinyin: "de", khmer: "ទទួលបាន" },
  { word: "等", pinyin: "děng", khmer: "រង់ចាំ (កិរិយាស័ព្ទ)" },
  { word: "弟弟", pinyin: "dì di", khmer: "ប្អូនប្រុស​" },
  { word: "第一", pinyin: "dì yī", khmer: "ដំបូង/ទីមួយ" },
  { word: "懂", pinyin: "dǒng", khmer: "យល់" },
  { word: "对", pinyin: "duì", khmer: "ស្តាំ (ធ្នាក់)" },
  { word: "对", pinyin: "duì", khmer: "បាទ (គុណនាម)" },
  { word: "房间", pinyin: "fáng jiān", khmer: "បន្ទប់" },
  { word: "非常", pinyin: "fēi cháng", khmer: "ច្រើនណាស់/ខ្លាំងណាស់" },
  { word: "服务员", pinyin: "fú wù yuán", khmer: "អ្នករត់តុ" },
  { word: "高", pinyin: "gāo", khmer: "ខ្ពស់" },
  { word: "告诉", pinyin: "gào su", khmer: "ប្រាប់" },
  { word: "哥哥", pinyin: "gē ge", khmer: "បងប្រុស" },
  { word: "给", pinyin: "gěi", khmer: "ផ្តល់ឱ្យ" },
  { word: "公共汽车", pinyin: "gōng gòng qì chē", khmer: "ឡានក្រុង" },
  { word: "公司", pinyin: "gōng sī", khmer: "ក្រុមហ៊ុន" },
  { word: "贵", pinyin: "guì", khmer: "ថ្លៃណាស់" },
  { word: "过", pinyin: "guo", khmer: "ហុច" },
  { word: "孩子", pinyin: "hái zi", khmer: "កូន" },
  { word: "还", pinyin: "hái", khmer: "ក៏ (adverb)" },
  { word: "好吃", pinyin: "hǎo chī", khmer: "ល្អក្នុងការបរិភោគ" },
  { word: "黑", pinyin: "hēi", khmer: "ខ្មៅ" },
  { word: "红", pinyin: "hóng", khmer: "ក្រហម" },
  { word: "火车站", pinyin: "huǒ chē zhàn", khmer: "ស្ថានីយ៍រថភ្លើង" },
  { word: "机场", pinyin: "jī chǎng", khmer: "ព្រលានយន្តហោះ" },
  { word: "鸡蛋", pinyin: "jī dàn", khmer: "ស៊ុត/ពង" },
  { word: "件", pinyin: "jiàn", khmer: "ឯកតាខោអាវ" },
  { word: "教室", pinyin: "jiào shì", khmer: "ថ្នាក់រៀន" },
  { word: "姐姐", pinyin: "jiě jie", khmer: "បងស្រី" },
  { word: "介绍", pinyin: "jiè shào", khmer: "ណែនាំខ្លួន" },
  { word: "近", pinyin: "jìn", khmer: "ជិត" },
  { word: "进", pinyin: "jìn", khmer: "ចូល" },
  { word: "就", pinyin: "jiù", khmer: "បើក" },
  { word: "觉得", pinyin: "jué de", khmer: "មានអារម្មណ៍" },
  { word: "咖啡", pinyin: "kā fēi", khmer: "កាហ្វេ" },
  { word: "开始", pinyin: "kāi shǐ", khmer: "ចាប់ផ្តើម" },
  { word: "考试", pinyin: "kǎo shì", khmer: "ប្រឡង" },
  { word: "可能", pinyin: "kě néng", khmer: "អាច" },
  { word: "可以", pinyin: "kě yǐ", khmer: "អាច" },
  { word: "课", pinyin: "kè", khmer: "ថ្នាក់" },
  { word: "快", pinyin: "kuài", khmer: "លឿន" },
  { word: "快乐", pinyin: "kuài lè", khmer: "រីករាយ" },
  { word: "累", pinyin: "lèi", khmer: "ហត់នឿយ" },
  { word: "离", pinyin: "lí", khmer: "ចេញពី / ឆ្ងាយពី" },
  { word: "两", pinyin: "liǎng", khmer: "ពីរ" },
  { word: "零", pinyin: "líng", khmer: "សូន្យ" },
  { word: "路", pinyin: "lù", khmer: "ផ្លូវ" },
  { word: "旅游", pinyin: "lǚ yóu", khmer: "ទេសចរណ៍" },
  { word: "卖", pinyin: "mài", khmer: "លក់" },
  { word: "慢", pinyin: "màn", khmer: "យឺត" },
  { word: "忙", pinyin: "máng", khmer: "រវល់" },
  { word: "每", pinyin: "měi", khmer: "គ្រប់" },
  { word: "妹妹", pinyin: "mèi mei", khmer: "ប្អូនស្រី" },
  { word: "门", pinyin: "mén", khmer: "ទ្វារ" },
  { word: "面条", pinyin: "miàn tiáo", khmer: "មី" },
  { word: "男", pinyin: "nán", khmer: "បុរស" },
  { word: "您", pinyin: "nín", khmer: "អ្នក (ដោយក្ដីគោរព)" },
  { word: "牛奶", pinyin: "niú nǎi", khmer: "ទឹកដោះគោ" },
  { word: "女", pinyin: "nǚ", khmer: "ស្រី" },
  { word: "旁边", pinyin: "páng biān", khmer: "នៅ​ក្បែរ" },
  { word: "跑步", pinyin: "pǎo bù", khmer: "រត់" },
  { word: "便宜", pinyin: "pián yi", khmer: "ថោក" },
  { word: "票", pinyin: "piào", khmer: "សំបុត្រ" },
  { word: "妻子", pinyin: "qī zi", khmer: "ប្រពន្ធ" },
  { word: "起床", pinyin: "qǐ chuáng", khmer: "ក្រោក​ពីគេង" },
  { word: "千", pinyin: "qiān", khmer: "ពាន់" },
  { word: "铅笔", pinyin: "qiān bǐ", khmer: "ខ្មៅដៃ" },
  { word: "晴", pinyin: "qíng", khmer: "ច្បាស់" },
  { word: "去年", pinyin: "qù nián", khmer: "ឆ្នាំមុន" },
  { word: "让", pinyin: "ràng", khmer: "សូមឱ្យ" },
  { word: "日", pinyin: "rì", khmer: "ថ្ងៃ" },
  { word: "上班", pinyin: "shàng bān", khmer: "ទៅធ្វើការ/ចូលធ្វើការ" },
  { word: "身体", pinyin: "shēn tǐ", khmer: "រាងកាយ" },
  { word: "生病", pinyin: "shēng bìng", khmer: "ឈឺ" },
  { word: "生日", pinyin: "shēng rì", khmer: "ថ្ងៃកំណើត" },
  { word: "时间", pinyin: "shí jiān", khmer: "ពេលវេលា" },
  { word: "事情", pinyin: "shì qing", khmer: "រឿង" },
  { word: "手表", pinyin: "shǒu biǎo", khmer: "នាឡិកាដៃ" },
  { word: "手机", pinyin: "shǒu jī", khmer: "ទូរស័ព្ទ​ចល័ត" },
  { word: "说话", pinyin: "shuō huà", khmer: "និយាយ" },
  { word: "送", pinyin: "sòng", khmer: "ឱ្យ/ជួន" },
  { word: "虽然…但是…", pinyin: "suī rán … dàn shì …", khmer: "ទោះយ៉ាងណា…តែ…" },
  { word: "它", pinyin: "tā", khmer: "វា" },
  { word: "踢足球", pinyin: "tī zú qiú", khmer: "លេង​បាល់ទាត់" },
  { word: "题", pinyin: "tí", khmer: "សំណួរ" },
  { word: "跳舞", pinyin: "tiào wǔ", khmer: "រាំ" },
  { word: "外", pinyin: "wài", khmer: "ខាងក្រៅ" },
  { word: "完", pinyin: "wán", khmer: "បញ្ចប់" },
  { word: "玩", pinyin: "wán", khmer: "លេង" },
  { word: "晚上", pinyin: "wǎn shang", khmer: "ពេលយប់" },
  { word: "往", pinyin: "wǎng", khmer: "ឆ្ពោះទៅ" },
  { word: "为什么", pinyin: "wèi shén me", khmer: "ហេតុអ្វី" },
  { word: "问", pinyin: "wèn", khmer: "សួរ" },
  { word: "问题", pinyin: "wèn tí", khmer: "បញ្ហា" },
  { word: "希望", pinyin: "xī wàng", khmer: "សង្ឃឹម" },
  { word: "西瓜", pinyin: "xī guā", khmer: "ឪឡឹក" },
  { word: "洗", pinyin: "xǐ", khmer: "លាង" },
  { word: "小时", pinyin: "xiǎo shí", khmer: "ម៉ោង" },
  { word: "笑", pinyin: "xiào", khmer: "សើច" },
  { word: "新", pinyin: "xīn", khmer: "ថ្មី" },
  { word: "姓", pinyin: "xìng", khmer: "ត្រកូល" },
  { word: "休息", pinyin: "xiū xi", khmer: "សម្រាក" },
  { word: "雪", pinyin: "xuě", khmer: "ព្រិល" },
  { word: "颜色", pinyin: "yán sè", khmer: "ពណ៌" },
  { word: "眼睛", pinyin: "yǎn jing", khmer: "ភ្នែក" },
  { word: "羊肉", pinyin: "yáng ròu", khmer: "ចៀម" },
  { word: "药", pinyin: "yào", khmer: "ថ្នាំ" },
  { word: "要", pinyin: "yào", khmer: "ត្រូវការ" },
  { word: "也", pinyin: "yě", khmer: "ក៍" },
  { word: "一下", pinyin: "yī xià", khmer: "បន្តិច" },
  { word: "已经", pinyin: "yǐ jīng", khmer: "រួចទៅហើយ" },
  { word: "一起", pinyin: "yī qǐ", khmer: "ជាមួយគ្នា" },
  { word: "意思", pinyin: "yì si", khmer: "អត្ថន័យ" },
  { word: "因为…所以…", pinyin: "yīn wèi … suǒ yǐ …", khmer: "ដោយសារតែ.....ដូច្នេះ…" },
  { word: "阴", pinyin: "yīn", khmer: "យិន" },
  { word: "游泳", pinyin: "yóu yǒng", khmer: "ហែលទឹក" },
  { word: "右边", pinyin: "yòu bian", khmer: "ត្រឹមត្រូវ" },
  { word: "鱼", pinyin: "yú", khmer: "ត្រី" },
  { word: "远", pinyin: "yuǎn", khmer: "ឆ្ងាយ" },
  { word: "运动", pinyin: "yùn dòng", khmer: "ចលនា" },
  { word: "再", pinyin: "zài", khmer: "ម្តងទៀត" },
  { word: "早上", pinyin: "zǎo shang", khmer: "ពេលព្រឹក" },
  { word: "丈夫", pinyin: "zhàng fu", khmer: "ប្តី" },
  { word: "找", pinyin: "zhǎo", khmer: "រក" },
  { word: "着", pinyin: "zhe", khmer: "ជាមួយ" },
  { word: "真", pinyin: "zhēn", khmer: "ពិត" },
  { word: "正在", pinyin: "zhèng zài", khmer: "ក្នុងនាម" },
  { word: "知道", pinyin: "zhī dào", khmer: "ដឹង" },
  { word: "准备", pinyin: "zhǔn bèi", khmer: "ត្រៀមខ្លួនជាស្រេច" },
  { word: "走", pinyin: "zǒu", khmer: "ទៅ" },
  { word: "最", pinyin: "zuì", khmer: "ភាគច្រើន" },
  { word: "左边", pinyin: "zuǒ bian", khmer: "ឆ្វេង" }
];

const wordList = document.getElementById("word-list");

words.forEach(({ word, pinyin, khmer }) => {
  const card = document.createElement("div");
  card.className = "word-card";
  card.innerHTML = `
    <div class="word">${word}</div>
    <div class="pinyin">${pinyin}</div>
    <div class="khmer">${khmer}</div>
  `;
  wordList.appendChild(card);
});
