document.getElementById("vocab-title").textContent = "生词(HSK5)：ពាក្យថ្មី";

const words = [
    { word: "哎", pinyin: "āi", khmer: "អ៊ៃ! (សំឡេងប្រើក្នុងការអំពាវនាវ ឬជះសម្លេងអំពីការភ្ញាក់ផ្អើល ឬការមិនពេញចិត្ត)" },
    { word: "唉", pinyin: "āi", khmer: "អ៊ៃ (សំឡេងស្នើសុំ ឬទទួលយល់); ការដកដង្ហើម" },
    { word: "爱护", pinyin: "ài hù", khmer: "ថែរក្សា; ស្រឡាញ់ និងការពារ" },
    { word: "爱惜", pinyin: "ài xī", khmer: "ថែរក្សា; សន្សំសម្រក់" },
    { word: "爱心", pinyin: "ài xīn", khmer: "ចិត្តស្រឡាញ់; សេចក្ដីអាណិតអាធ័រ" },
    { word: "安慰", pinyin: "ān wèi", khmer: "ដូចទំនៅ; ទះដៃថ្លៃទឹកចិត្ត" },
    { word: "安装", pinyin: "ān zhuāng", khmer: "ដំឡើង; ជួសជុល; តម្លើង" },
    { word: "岸", pinyin: "àn", khmer: "គាំ; ច្រាំង; ឆ្នេរ" },
    { word: "暗", pinyin: "àn", khmer: "ងងឹត; លាក់; សម្ងាត់" },
    { word: "熬夜", pinyin: "áo yè", khmer: "ភ្ញាក់យប់; មិនដេក; យាមយប់" },
    { word: "把握", pinyin: "bǎ wò", khmer: "ចាប់យក (ផ្ទាំងន័យ); មានទំនុកចិត្ត" },
    { word: "摆", pinyin: "bǎi", khmer: "ដាក់; រៀបចំ; ទាញទៅទាញមក; ខ្នងញញឹម" },
    { word: "办理", pinyin: "bàn lǐ", khmer: "ដោះស្រាយ; រៀបចំ; ធ្វើ" },
    { word: "傍晚", pinyin: "bàng wǎn", khmer: "ពេលល្ងាច; ពេលថ្ងៃរៀបលិច" },
    { word: "包裹", pinyin: "bāo guǒ", khmer: "ដាក់ទំពក់; កាដូ; កញ្ចប់" },
    { word: "包含", pinyin: "bāo hán", khmer: "រួមបញ្ចូល; មានក្នុងខ្លួន" },
    { word: "包括", pinyin: "bāo kuò", khmer: "រួមបញ្ចូល; រួមមាន" },
    { word: "薄", pinyin: "báo", khmer: "ស្តើង; ត្រជាក់ចិត្ត; ទាបនិមិត្ត" },
    { word: "保持", pinyin: "bǎo chí", khmer: "រក្សាទុក; ថែទាំ" },
    { word: "保存", pinyin: "bǎo cún", khmer: "រក្សាទុក; សន្សំទុក; រក្សាទុកឯកសារ" },
    { word: "保留", pinyin: "bǎo liú", khmer: "រក្សាទុក; រក្សាជាស្ថាពរ; ទុកសិន; ទុកជាថេរ" },
    { word: "保险", pinyin: "bǎo xiǎn", khmer: "ធានារ៉ាប់រង; ធានា; មានសុវត្ថិភាព; ប្រាកដ" },
    { word: "宝贝", pinyin: "bǎo bèi", khmer: "របស់មានតម្លៃ; កូនស្រឡាញ់; មនុស្សឆ្កួតៗខ្លួន" },
    { word: "宝贵", pinyin: "bǎo guì", khmer: "មានតម្លៃ; ត្រូវថែរក្សា; សុទ្ធសាធ" },
    { word: "报到", pinyin: "bào dào", khmer: "ចុះឈ្មោះ; រាយការណ៍ជាផ្លូវការចូលធ្វើការងារ" },
    { word: "报道", pinyin: "bào dào", khmer: "សេចក្ដីរាយការណ៍; រាយការណ៍ព័ត៌មាន" },
    { word: "报告", pinyin: "bào gào", khmer: "របាយការណ៍; បញ្ជាក់ព័ត៌មាន; សុន្ទរកថា" },
    { word: "报社", pinyin: "bào shè", khmer: "ការិយាល័យសារព័ត៌មាន; កន្លែងបោះពុម្ពសារព័ត៌មាន" },
    { word: "抱怨", pinyin: "bào yuàn", khmer: "ប្តឹងបង្ហូរ; រអ៊ូរទាំ" },
    { word: "悲观", pinyin: "bēi guān", khmer: "មើលអវិជ្ជមាន; មើលជាអាក្រក់" },
    { word: "背", pinyin: "bèi", khmer: "ខ្នង; ត្រឡប់ខ្នង; សូត្រចងចាំ; លាក់សម្ងាត់" },
    { word: "背景", pinyin: "bèi jǐng", khmer: "ផ្ទៃខាងក្រោយ; បរិបទ; បរិយាកាស" },
    { word: "被子", pinyin: "bèi zi", khmer: "ភួយ; ភួយគេង" },
    { word: "本科", pinyin: "běn kē", khmer: "វគ្គបរិញ្ញាបត្រ; មហាវិទ្យាល័យ" },
    { word: "本领", pinyin: "běn lǐng", khmer: "សមត្ថភាព; ជំនាញ" },
    { word: "本质", pinyin: "běn zhì", khmer: "សារសំខាន់; សារប្រភព; ទំនិញខាងក្នុង" },
    { word: "彼此", pinyin: "bǐ cǐ", khmer: "គ្នាទៅវិញទៅមក; ម្នាក់ទៅម្នាក់" },
    { word: "比例", pinyin: "bǐ lì", khmer: "សមាមាត្រ; ភាគរយ" },
    { word: "必然", pinyin: "bì rán", khmer: "ជាក់ស្ដែង; ដាច់ខាត; ប្រាកដ" },
    { word: "必要", pinyin: "bì yào", khmer: "ចាំបាច់; ត្រូវមាន; ត្រូវការជាចាំបាច់" },
    { word: "毕竟", pinyin: "bì jìng", khmer: "ចុងក្រោយបង្អស់; ទោះបីជាយ៉ាងណាក៏ដោយ" },
    { word: "避免", pinyin: "bì miǎn", khmer: "ជៀសវាង; កុំឲ្យកើតឡើង" },
    { word: "编辑", pinyin: "biān jí", khmer: "កែសម្រួល; ចងក្រង; អ្នកកែសម្រួល; អ្នកចងក្រង" },
    { word: "鞭炮", pinyin: "biān pào", khmer: "កាំជ្រួច; កាំជ្រួចខ្នាតតូចជាស្រទាប់" },
    { word: "便", pinyin: "biàn", khmer: "ងាយស្រួល; ធម្មតា; សាមញ្ញ; បន្ទាន់; នឹង; ជាប់នឹង; ទៅស្រុះទឹក (បង្គន់)" },
    { word: "辩论", pinyin: "biàn lùn", khmer: "ការជជែកធៀប; ជជែកដណ្តើមយោបល់" },
    { word: "标点", pinyin: "biāo diǎn", khmer: "សញ្ញាវាងវេញ; វាងវេញអក្សរ" },
    { word: "标志", pinyin: "biāo zhì", khmer: "សញ្ញាសម្គាល់; សញ្ញានាំបង្ហាញ; បដិសន្ធិ" },
    { word: "表达", pinyin: "biǎo dá", khmer: "បង្ហាញ; បញ្ជាក់; បកស្រាយយោបល់" },
    { word: "表面", pinyin: "biǎo miàn", khmer: "ផ្ទៃក្រៅ; រូបរាងខាងក្រៅ" },
    { word: "表明", pinyin: "biǎo míng", khmer: "បញ្ជាក់ឲ្យច្បាស់; បង្ហាញច្បាស់" },
    { word: "表情", pinyin: "biǎo qíng", khmer: "ការបង្ហាញអារម្មណ៍; ការបង្ហាញមុខម៉ាស" },
    { word: "表现", pinyin: "biǎo xiàn", khmer: "បង្ហាញខ្លួន; បង្ហាញសមត្ថភាព; សម្តែងខ្លួន; ប្រតិបត្តិការណ៍" },
    { word: "冰激凌", pinyin: "bīng jī líng", khmer: "ក្រឡុក; ការគ្រឿងទឹកកក" },
    { word: "病毒", pinyin: "bìng dú", khmer: "វីរុស; មេរោគ" },
    { word: "播放", pinyin: "bō fàng", khmer: "ផ្សាយ; ចាក់ (តន្ត្រី វីដេអូ)" },
    { word: "玻璃", pinyin: "bō li", khmer: "កញ្ចក់; ផ្លាស្ទិច; នាយឡុង" },
    { word: "博物馆", pinyin: "bó wù guǎn", khmer: "សារមន្ទីរ" },
    { word: "脖子", pinyin: "bó zi", khmer: "ក; កខាងមុខ" },
    { word: "不断", pinyin: "bú duàn", khmer: "មិនឈប់ឈរឡើយ; ជាប់ជាបន្តបន្ទាប់" },
    { word: "不见得", pinyin: "bú jiàn de", khmer: "មិនច្បាស់; មិនប្រាកដទេ; ប្រហែលជា​មិន" },
    { word: "不耐烦", pinyin: "bú nài fán", khmer: "ធុញធុរ; ខឹង; មិនអត់ធ្មត់" },
    { word: "不要紧", pinyin: "bú yào jǐn", khmer: "មិនអីទេ; មិនអាសន្នទេ; មិនបាច់បារម្ភទេ" },
    { word: "补充", pinyin: "bǔ chōng", khmer: "បន្ថែម; បំពេញ; បន្ថែមជាឧបត្ថម្ភ" },
    { word: "不安", pinyin: "bù ān", khmer: "មិនស្ងប់ស្ងាត់; មិនស្ថិតស្ថេរ; រំភើប" },
    { word: "不得了", pinyin: "bù dé liǎo", khmer: "អស្ចារ្យណាស់; អស្ចារ្យ; ឧក្រិដ្ឋ; ឧន្ដរឧន្ដរ" },
    { word: "不然", pinyin: "bù rán", khmer: "មិនដូច្នេះទេ; បើមិនដូច្នេះទេ; បើមិនដូច្នេះទេគឺ…" },
    { word: "不如", pinyin: "bù rú", khmer: "មិនស្មើនឹង; មិនប្រសើរជាង; ស្រួលតែ…" },
    { word: "不足", pinyin: "bù zú", khmer: "មិនគ្រប់គ្រាន់; ខ្វះខាត; អន់ជាងគេ" },
    { word: "布", pinyin: "bù", khmer: "ក្រណាត់; ប្រកាស; ផ្សាយ; បញ្ជាក់" },
    { word: "步骤", pinyin: "bù zhòu", khmer: "ជំហាន; វិធីធ្វើ; សកម្មភាពជាបន្ទាប់" },
    { word: "部门", pinyin: "bù mén", khmer: "នាយកដ្ឋាន; ផ្នែក; ដេប៉ាតឺម៉ង់" },
    { word: "财产", pinyin: "cái chǎn", khmer: "ទ្រព្យសម្បត្តិ; ទ្រព្យសម្បត្តិផ្ទាល់ខ្លួន" },
    { word: "彩虹", pinyin: "cǎi hóng", khmer: "ឥន្ទធនូ" },
    { word: "踩", pinyin: "cǎi", khmer: "ដើរលើ; កកិច; កិន; ចាប់ជើង (គ្រឿងយន្ត)" },
    { word: "采访", pinyin: "cǎi fǎng", khmer: "សម្ភាសន៍; ទៅយកព័ត៌មាន" },
    { word: "采取", pinyin: "cǎi qǔ", khmer: "អនុវត្ត; ធ្វើការយក (វិធានការណ៍/គន្លង)" },
    { word: "参考", pinyin: "cān kǎo", khmer: "យោង; សម្រង់; ពិនិត្យយោង" },
    { word: "参与", pinyin: "cān yù", khmer: "ចូលរួម; សកម្មភាពចូលរួម" },
    { word: "惭愧", pinyin: "cán kuì", khmer: "អាប់អួរ; ខ្មាស់អៀន; ខ្មាស់ខ្លាច" },
    { word: "操场", pinyin: "cāo chǎng", khmer: "ទីលានកីឡា; ទីលានហាត់ប្រាណ" },
    { word: "操心", pinyin: "cāo xīn", khmer: "បារម្ភ; ព្រួយព្រេង; ការព្រួយ" },
    { word: "册", pinyin: "cè", khmer: "សៀវភៅ; សៀវភៅតូច; ចំនួនសៀវភៅ (រាប់)" },
    { word: "测验", pinyin: "cè yàn", khmer: "តេស្ត; ការធ្វើតេស្ត; សាកល្បង" },
    { word: "曾经", pinyin: "céng jīng", khmer: "ធ្លាប់បាន; កាលពីមុន; បានធ្លាប់" },
    { word: "叉子", pinyin: "chā zi", khmer: "សម" },
    { word: "差距", pinyin: "chā jù", khmer: "ភាពខុសគ្នា; ចន្លោះ; គម្លាត" },
    { word: "插", pinyin: "chā", khmer: "ដាក់ចូល; ទាក់ចូល; ចាក់ចូល; លាយចូល" },
    { word: "拆", pinyin: "chāi", khmer: "បំបែក; កេះចេញ; បកចេញ" },
    { word: "产品", pinyin: "chǎn pǐn", khmer: "ផលិតផល; ទំនិញ" },
    { word: "产生", pinyin: "chǎn shēng", khmer: "បង្កើតឡើង; បង្កើតបាន; បង្កើត" },
    { word: "常识", pinyin: "cháng shí", khmer: "ចំណេះដឹងទូទៅ; បញ្ញាសាមញ្ញ" },
    { word: "长途", pinyin: "cháng tú", khmer: "ចម្ងាយឆ្ងាយ; ចម្ងាយវែង" },
    { word: "抄", pinyin: "chāo", khmer: "ចម្លង; លួចចម្លង; ស្កេនយក" },
    { word: "超级", pinyin: "chāo jí", khmer: "ជំរុញ; ខ្ពស់ជាង; លើសពីស្ដង់ដារ" },
    { word: "朝", pinyin: "cháo", khmer: "រាជស្ថាប័ន; រដ្ធាភិបាល; ទិសទៅ; មុខទៅ" },
    { word: "潮湿", pinyin: "cháo shī", khmer: "សើម; ងើប; ទឹកជ្រាប" },
    { word: "吵", pinyin: "chǎo", khmer: "រំខាន; ធ្វើឲ្យរំខានដោយសំលេង; ធ្វើសំឡេងខ្លាំង" },
    { word: "吵架", pinyin: "chǎo jià", khmer: "ឈ្លោះ; ឈ្លោះគ្នាដោយសំឡេងខ្លាំង" },
    { word: "炒", pinyin: "chǎo", khmer: "ចៀន; ចៀនស្ងួត; បំពង" },
    { word: "车库", pinyin: "chē kù", khmer: "រោងចតឡាន; ឃ្លាំងឡាន" },
    { word: "车厢", pinyin: "chē xiāng", khmer: "រថយន្តកាបូប; ឡានកាបូប" },
    { word: "彻底", pinyin: "chè dǐ", khmer: "ជ្រៅជ្រះ; ពេញលេញ; បញ្ចប់ល្អ" },
    { word: "沉默", pinyin: "chén mò", khmer: "ស្ងៀមស្ងាត់; មិននិយាយ" },
    { word: "趁", pinyin: "chèn", khmer: "ប្រើឱកាស; ស្រាប់តែ; អាស្រ័យទៅលើ" },
    { word: "称", pinyin: "chēng", khmer: "វាស់ទម្ងន់; ហៅថា; ពិពណ៌នា; អាប់អួរ" },
    { word: "称呼", pinyin: "chēng hu", khmer: "ហៅ; សរសេរឈ្មោះ; អនុស្សាវរីយ៍" },
    { word: "称赞", pinyin: "chēng zàn", khmer: "សរសើរ; គោរព; ឯកភាព" },
    { word: "成分", pinyin: "chéng fèn", khmer: "សមាសធាតុ; បរិមាណ; ស្ថានភាពសង្គម" },
    { word: "成果", pinyin: "chéng guǒ", khmer: "លទ្ធផល; ការសម្រេចបាន; ការឈ្នះ" },
    { word: "成就", pinyin: "chéng jiù", khmer: "សមិទ្ធផល; ការសម្រេចបាន; ក្ដីជោគជ័យ" },
    { word: "成立", pinyin: "chéng lì", khmer: "បង្កើតឡើង; បង្កើត; មានប្រសិទ្ធភាព" },
    { word: "成人", pinyin: "chéng rén", khmer: "មនុស្សពេញវ័យ" },
    { word: "成熟", pinyin: "chéng shú", khmer: "ស្រួលចិត្ត; ចាស់ដុះល្អ; រាក់ទាក់; ជាប់ល្អ" },
    { word: "成语", pinyin: "chéng yǔ", khmer: "សុភាសិតចិនបួនពាក្យ; គ្រឿងនិយាយប្រើពេញនិយម" },
    { word: "成长", pinyin: "chéng zhǎng", khmer: "លូតលាស់; អភិវឌ្ឍន៍" },
    { word: "承担", pinyin: "chéng dān", khmer: "ទទួលខុសត្រូវ; ទទួលអនុវត្តន៍" },
    { word: "承认", pinyin: "chéng rèn", khmer: "ទទួលស្គាល់; ញាប់ញ័រ; ញាប់" },
    { word: "承受", pinyin: "chéng shòu", khmer: "ទ្រាំទ្រ; ទទួលរង; ទទួល" },
    { word: "程度", pinyin: "chéng dù", khmer: "កម្រិត; ស្ទាត់ជំនាញ; ដំណាក់កាល" },
    { word: "程序", pinyin: "chéng xù", khmer: "លំដាប់ដំណើរ; កម្មវិធីកុំព្យូទ័រ" },
    { word: "诚恳", pinyin: "chéng kěn", khmer: "ស្មោះត្រង់; បុស្បត្តិភាព" },
    { word: "吃亏", pinyin: "chī kuī", khmer: "ខាតបង់; ទទួលរងខូចខាត; នៅក្នុងស្ថានភាពអាក្រក់" },
    { word: "持续", pinyin: "chí xù", khmer: "បន្ត; តបន់; រីកចម្រើនជាប់ៗគ្នា" },
    { word: "池塘", pinyin: "chí táng", khmer: "អណ្តូងទឹក; អាងទឹក" },
    { word: "迟早", pinyin: "chí zǎo", khmer: "យូរឬឆាប់; មិនយូរទេ" },
    { word: "尺子", pinyin: "chǐ zi", khmer: "បន្ទះវាស់; ដែកវាស់; ម៉ែត្រវាស់" },
    { word: "翅膀", pinyin: "chì bǎng", khmer: "ស្លាប" },
    { word: "充电器", pinyin: "chōng diàn qì", khmer: "ឧបករណ៍សាកថ្ម; ម៉ាស៊ីនសាក" },
    { word: "充分", pinyin: "chōng fèn", khmer: "ពេញលេញ; ធើ្វបានគ្រប់គ្រាន់" },
    { word: "充满", pinyin: "chōng mǎn", khmer: "ពេញទៅដោយ; លេចធ្លោដោយ" },
    { word: "冲", pinyin: "chōng", khmer: "បាញ់ទឹក; បោក; រំលេច; បោកចេញ" },
    { word: "重复", pinyin: "chóng fù", khmer: "ធ្វើសារជាថ្មី; ស្ទួន" },
    { word: "宠物", pinyin: "chǒng wù", khmer: "សត្វចិញ្ចឹម; សត្វសំណព្វ" },
    { word: "抽屉", pinyin: "chōu ti", khmer: "កន្សោម; ទូរលាងអីវ៉ាន់" },
    { word: "抽象", pinyin: "chōu xiàng", khmer: "អរូបី; សារពើភណ្ឌគំនិត" },
    { word: "丑", pinyin: "chǒu", khmer: "អាក្រក់; មិនស្អាត; តួអក្សរខ្សែកុន" },
    { word: "臭", pinyin: "chòu", khmer: "ស្អុយ; ក្រអូបអាក្រក់" },
    { word: "出版", pinyin: "chū bǎn", khmer: "បោះពុម្ពផ្សាយ; បោះពុម្ពចេញ" },
    { word: "出口", pinyin: "chū kǒu", khmer: "ច្រកចេញ; និយាយចេញ; នាំចេញ" },
    { word: "出色", pinyin: "chū sè", khmer: "លេចធ្លោ; ដ៏អស្ចារ្យ" },
    { word: "出示", pinyin: "chū shì", khmer: "បង្ហាញ; បង្ហាញឲ្យឃើញ" },
    { word: "出席", pinyin: "chū xí", khmer: "ចូលរួម; ចូលរួមវេទិកា" },
    { word: "初级", pinyin: "chū jí", khmer: "កម្រិតដំបូង; ជាដំបូង" },
    { word: "除非", pinyin: "chú fēi", khmer: "លុះត្រាតែ; បើមិនដូច្នេះទេ" },
    { word: "除夕", pinyin: "chú xī", khmer: "យប់ចុងឆ្នាំចិន; ថ្ងៃចុងឆ្នាំ" },
    { word: "处理", pinyin: "chǔ lǐ", khmer: "ដោះស្រាយ; ចាត់ចែង; ប្រើប្រាស់" },
    { word: "传播", pinyin: "chuán bō", khmer: "ផ្សាយ; បញ្ជូន; បញ្ជូនព័ត៌មាន" },
    { word: "传染", pinyin: "chuán rǎn", khmer: "ឆ្លង; ឆ្លងជំងឺ; មានឥទ្ធិពលឆ្លងចូលគ្នា" },
    { word: "传说", pinyin: "chuán shuō", khmer: "ទេពកថា; រឿងប្រលោមលោក; រឿងព្រេង; គេនិយាយថា" },
    { word: "传统", pinyin: "chuán tǒng", khmer: "ប្រពៃណី; ធម្មតា; ជំនឿដូងបុរាណ" },
    { word: "窗帘", pinyin: "chuāng lián", khmer: "កាំងបង្អួច; ផ្លុងបង្អួច" },
    { word: "闯", pinyin: "chuǎng", khmer: "វាយប្រហារ; ចូលបាញ់; ឆ្លងផុត; ប៉ះពាល់ឧបសគ្គដើម្បីពង្រឹងខ្លួន" },
    { word: "创造", pinyin: "chuàng zào", khmer: "បង្កើត; បង្កើតថ្មី; បង្កើតអ្វីមួយឡើង" },
    { word: "吹", pinyin: "chuī", khmer: "បក់; ផ្លុំ (ឧបករណ៍ភ្លេង); បប៉ៃបប៉ើ; ឆ្កឹះខ្លួនឯង; បរាជ័យ" },
    { word: "词汇", pinyin: "cí huì", khmer: "សព្ទ; វាក្យសព្ទ; បញ្ជីពាក្យ" },
    { word: "辞职", pinyin: "cí zhí", khmer: "លាឈប់ពីការងារ; បោះបង់ការងារ" },
    { word: "此外", pinyin: "cǐ wài", khmer: "ក្រៅពីនេះ; បន្ថែមទៀត" },
    { word: "刺激", pinyin: "cì jī", khmer: "រំខាន; ការលើកទឹកចិត្ត; បណ្ដាលឲ្យធ្វើអ្វីមួយ; ជំរុញ" },
    { word: "次要", pinyin: "cì yào", khmer: "អាទិភាពទីពីរ; មិនសំខាន់ណាស់" },
    { word: "匆忙", pinyin: "cōng máng", khmer: "ប្រញាប់; បំភ្លន់; ឆាប់រហ័ស" },
    { word: "从此", pinyin: "cóng cǐ", khmer: "ចាប់ពីពេលនោះតទៅ; ចាប់ពីពេលនេះ" },
    { word: "从而", pinyin: "cóng ér", khmer: "ដូច្នេះហើយបានជា; ដូច្នេះ" },
    { word: "从前", pinyin: "cóng qián", khmer: "ពីដើមមក; កាលពីមុន; សម័យមុន" },
    { word: "从事", pinyin: "cóng shì", khmer: "ចូលរួម; ធ្វើអាជីព; ធ្វើការ" },
    { word: "粗糙", pinyin: "cū cāo", khmer: "រឹងរាក់; មិនប្រុងប្រយ័ត្ន; ខ្ទិចខ្ទួន" },
    { word: "促进", pinyin: "cù jìn", khmer: "ជំរុញ; លើកស្ទួយ; ពង្រឹង" },
    { word: "促使", pinyin: "cù shǐ", khmer: "ជំរុញឲ្យ; បណ្តាលឲ្យ; ជម្រុញការអភិវឌ្ឍ" },
    { word: "醋", pinyin: "cù", khmer: "ទឹកខ្មេះ; ការច្រណែន (ស្នេហា)" },
    { word: "催", pinyin: "cuī", khmer: "ជំរុញ; ជំរុញឲ្យប្រញាប់; លើកទឹកចិត្ត" },
    { word: "存在", pinyin: "cún zài", khmer: "មាន; មានជីវិត; ស្ថិតនៅ" },
    { word: "措施", pinyin: "cuò shī", khmer: "វិធានការណ៍; ជំហាននយោបាយ" },
    { word: "答应", pinyin: "dā ying", khmer: "ព្រម; យល់ព្រម; សន្យា; ឆ្លើយតប" },
    { word: "达到", pinyin: "dá dào", khmer: "ឈានដល់; បំពេញបាន; សម្រេចបាន" },
    { word: "打工", pinyin: "dǎ gōng", khmer: "ធ្វើការងារថែមម៉ោង; ធ្វើការងារផ្នែកដៃ" },
    { word: "打交道", pinyin: "dǎ jiāo dào", khmer: "ទំនាក់ទំនងជាមួយ; ជួបប្រទះ; ធ្វើជាយ៉ាងជិតស្និទ្ធ" },
    { word: "打喷嚏", pinyin: "dǎ pēn tì", khmer: "ក្រហាយ" },
    { word: "打听", pinyin: "dǎ ting", khmer: "សួរព័ត៌មាន; សួរចោទ" },
    { word: "大方", pinyin: "dà fāng", khmer: "ចិត្តធំ; មិនស្ទាក់ស្ទើរ; មានស្ទីល" },
    { word: "大厦", pinyin: "dà shà", khmer: "អាគារធំ; អគារលំដាប់ខ្ពស់" },
    { word: "大象", pinyin: "dà xiàng", khmer: "ដំរី" },
    { word: "大型", pinyin: "dà xíng", khmer: "ទ្រង់ទ្រាយធំ; ជាសាធារណៈ; មាត្រដ្ឋានធំ" },
    { word: "呆", pinyin: "dāi", khmer: "ងងឹត; អះអាង; ឈរមើលស្ងៀម; នៅ (ជាស្ថានភាព)" },
    { word: "代表", pinyin: "dài biǎo", khmer: "តំណាង; អ្នកតំណាង; ជាសមាជិកប្រជាជន; ធ្វើតំណាងឲ្យ" },
    { word: "代替", pinyin: "dài tì", khmer: "ជំនួស; ជំនួសអោយ; ដាក់ជំនួស" },
    { word: "待遇", pinyin: "dài yù", khmer: "ការប្រព្រឹត្ត; ប្រាក់ខែ; ស្ថានភាពក្នុងការងារ" },
    { word: "贷款", pinyin: "dài kuǎn", khmer: "ការខ្ចីប្រាក់; ប្រាក់កម្ចី; ប្រាក់ខ្ចីពីធនាគារ" },
    { word: "单纯", pinyin: "dān chún", khmer: "ធម្មតា; មិនស្មុគស្មាញ; សុទ្ធ" },
    { word: "单调", pinyin: "dān diào", khmer: "ធុញថប់; មិនមានភាពផ្លាស់ប្តូរ; តែមួយ" },
    { word: "单独", pinyin: "dān dú", khmer: "ដោយខ្លួនឯង; ទោល; ម្នាក់ឯង" },
    { word: "单位", pinyin: "dān wèi", khmer: "អង្គភាព; ទីកន្លែងធ្វើការ; ឯកតាវាស់" },
    { word: "单元", pinyin: "dān yuán", khmer: "ផ្នែក; ឯកតា; ច្រកចូល (នៅអគារ)" },
    { word: "担任", pinyin: "dān rèn", khmer: "ស្របចំណាត់ថ្នាក់; ទទួលខុសត្រូវ; ជាជំនួយការ" },
    { word: "耽误", pinyin: "dān wu", khmer: "ពន្យាពេល; ធ្វើឲ្យពន្យាពេល; បាត់បង់ពេលវេលា" },
    { word: "胆小鬼", pinyin: "dǎn xiǎo guǐ", khmer: "អ្នកខ្លាច; អ្នកអួតអង្វែង" },
    { word: "淡", pinyin: "dàn", khmer: "ស្រាល; បែបឈ្ងុយតិច; ពណ៌ស្រាល; មិនខ្លាំង" },
    { word: "当地", pinyin: "dāng dì", khmer: "ក្នុងតំបន់; ដែនដីនោះ; ជីវភាពមូលដ្ឋាន" },
    { word: "当心", pinyin: "dāng xīn", khmer: "ប្រុងប្រយ័ត្ន; យកចិត្តទុកដាក់" },
    { word: "挡", pinyin: "dǎng", khmer: "រារាំង; បាំង; បង្ហៀរ; គាំង" },
    { word: "倒霉", pinyin: "dǎo méi", khmer: "អកុសល; ជួបរឿងអាក្រក់" },
    { word: "导演", pinyin: "dǎo yǎn", khmer: "អ្នកដឹកនាំភាពយន្ត; ធ្វើជាអ្នកដឹកនាំ" },
    { word: "导致", pinyin: "dǎo zhì", khmer: "បណ្ដាលឲ្យ; ធ្វើឲ្យកើតឡើង; នាំអោយ" },
    { word: "岛屿", pinyin: "dǎo yǔ", khmer: "កោះ" },
    { word: "到达", pinyin: "dào dá", khmer: "ឈានដល់; មកដល់" },
    { word: "道德", pinyin: "dào dé", khmer: "លំនាំនៃសីលធម៌; គំនិតល្អ; សីលធម៌" },
    { word: "道理", pinyin: "dào lǐ", khmer: "ហេតុផល; យល់ឃើញ; ចំណេះដឹង" },
    { word: "登记", pinyin: "dēng jì", khmer: "ចុះឈ្មោះ; ចុះបញ្ជី" },
    { word: "等待", pinyin: "děng dài", khmer: "រងចាំ" },
    { word: "等于", pinyin: "děng yú", khmer: "ស្មើនឹង; ដូចជា" },
    { word: "滴", pinyin: "dī", khmer: "មុំ; ចំណុច; ធ្លាក់ជាចំណុច" },
    { word: "敌人", pinyin: "dí rén", khmer: "សត្រូវ" },
    { word: "的确", pinyin: "dí què", khmer: "ពិតប្រាកដ" },
    { word: "地道", pinyin: "dì dao", khmer: "ដើមស្រុក; សុទ្ធសាធ; ពិតប្រាកដ" },
    { word: "地理", pinyin: "dì lǐ", khmer: "ភូមិសាស្ត្រ" },
    { word: "地区", pinyin: "dì qū", khmer: "តំបន់; ខេត្ត; ដែនដី" },
    { word: "地毯", pinyin: "dì tǎn", khmer: "កំរាលព្រំ" },
    { word: "地位", pinyin: "dì wèi", khmer: "ស្ថានភាព; ទីតាំង; ការចាត់តាំង" },
    { word: "地震", pinyin: "dì zhèn", khmer: "រញ្ជួយដី" },
    { word: "递", pinyin: "dì", khmer: "ផ្ញើ; បញ្ជូន; ឲ្យ; ចែកចាយ" },
    { word: "点心", pinyin: "diǎn xin", khmer: "បង្អែម; ម្ហូបតិចតួច; ដាំស៊ុបបែបចិន" },
    { word: "电池", pinyin: "diàn chí", khmer: "ថ្ម (សម្រាប់ឧបករណ៍អេឡិចត្រូនិច)" },
    { word: "电台", pinyin: "diàn tái", khmer: "ស្ថានីយ៍វិទ្យុ" },
    { word: "钓", pinyin: "diào", khmer: "បង្អាប់ដោយសំពាធ និងពង្រិល" },
    { word: "顶", pinyin: "dǐng", khmer: "កំពូល; សំពាធសើម; ពេញនិយម" },
    { word: "冻", pinyin: "dòng", khmer: "ត្រជាក់; បង្ខូច; ធ្វើឲ្យត្រជាក់" },
    { word: "动画片", pinyin: "dòng huà piān", khmer: "ភាពយន្តគូរ" },
    { word: "洞", pinyin: "dòng", khmer: "រូម; ផ្លូវចេញពីចង្កោម" },
    { word: "豆腐", pinyin: "dòu fu", khmer: "ទូហ្វ៊ូ" },
    { word: "逗", pinyin: "dòu", khmer: "លេង; ពិនិត្យ" },
    { word: "独立", pinyin: "dú lì", khmer: "ឯករាជ្យ" },
    { word: "独特", pinyin: "dú tè", khmer: "ពិសេស; មិនធម្មតា" },
    { word: "度过", pinyin: "dù guò", khmer: "កម្សត់" },
    { word: "断", pinyin: "duàn", khmer: "បំបែក; កាត់ចោល; លប់" },
    { word: "堆", pinyin: "duī", khmer: "បញ្ចូល; បញ្ចូលចំនួន; តំណែង" },
    { word: "兑换", pinyin: "duì huàn", khmer: "ប្ដូរ; ប្តូរពិភពជាមួយមួយ" },
    { word: "对比", pinyin: "duì bǐ", khmer: "ការប្រៀបធៀប" },
    { word: "对待", pinyin: "duì dài", khmer: "សំដៅ; ជាអ្វីដែលត្រូវ" },
    { word: "对方", pinyin: "duì fāng", khmer: "សត្រូវកាន់កាប់" },
    { word: "对手", pinyin: "duì shǒu", khmer: "មិត្តប្រយុទ្ធ" },
    { word: "对象", pinyin: "duì xiàng", khmer: "គោលបំណង; ប្រជាជន" },
    { word: "吨", pinyin: "dūn", khmer: "តោន" },
    { word: "蹲", pinyin: "dūn", khmer: "ក្រឡេកដើម្បីអង្គុយ" },
    { word: "顿", pinyin: "dùn", khmer: "ប្រណាំង; ប្រាកដចំពោះ" },
    { word: "多亏", pinyin: "duō kuī", khmer: "អរគុណទឹក" },
    { word: "多余", pinyin: "duō yú", khmer: "លុបចោល" },
    { word: "朵", pinyin: "duǒ", khmer: "មេត្រី" },
    { word: "躲藏", pinyin: "duǒ cáng", khmer: "លាក់ខ្លួន" },
    { word: "恶劣", pinyin: "è liè", khmer: "អាក្រក់; មិនល្អ" },
    { word: "耳环", pinyin: "ěr huán", khmer: "មួកក"},
    { word: "翻", pinyin: "fān", khmer: "បង្វិល; ការបកប្រែ" },
    { word: "繁荣", pinyin: "fán róng", khmer: "សំណាងល្អ; ពេញចិត្ត" },
    { word: "反而", pinyin: "fǎn ér", khmer: "វិញ; ទៅវិញទៅមក" },
    { word: "反复", pinyin: "fǎn fù", khmer: "ត្រឡប់ត្រឡេីប" },
    { word: "反应", pinyin: "fǎn yìng", khmer: "ឆ្លើយតប; ប្រតិកម្ម" },
    { word: "反映", pinyin: "fǎn yìng", khmer: "បង្ហាញ; ត្រឡប់" },
    { word: "反正", pinyin: "fǎn zhèng", khmer: "វិញវិញ; មិនអស់" },
    { word: "范围", pinyin: "fàn wéi", khmer: "ដែនកំណត់; ប្រព័ន្ធ" },
    { word: "方", pinyin: "fāng", khmer: "ជារាងប៉ារ៉ាឡែល; ស្ដង់ដារ" },
    { word: "方案", pinyin: "fāng àn", khmer: "ផែនការប្រតិបត្តិការ" },
    { word: "方式", pinyin: "fāng shì", khmer: "របៀប; គម្រោង" },
    { word: "妨碍", pinyin: "fáng ài", khmer: "រំខាន; ជ្រៀតជ្រែក" },
    { word: "仿佛", pinyin: "fǎng fú", khmer: "ទាំងអស់មើលទៅដូចគ្នា" },
    { word: "非", pinyin: "fēi", khmer: "មិន-; ព្រមទាំងមិន" },
    { word: "肥皂", pinyin: "féi zào", khmer: "សាប៊ូ" },
    { word: "废话", pinyin: "fèi huà", khmer: "ពាក្យចរាចរណ៍" },
    { word: "分别", pinyin: "fēn bié", khmer: "បំបែក; ផ្ដាច់" },
    { word: "分布", pinyin: "fēn bù", khmer: "ចែកចាយ" },
    { word: "分配", pinyin: "fēn pèi", khmer: "ចែកចាយ; ចាត់តាំង" },
    { word: "分手", pinyin: "fēn shǒu", khmer: "បំបែកក្រុម; ការបោះបង់" },
    { word: "分析", pinyin: "fēn xī", khmer: "វិភាគ" },
    { word: "纷纷", pinyin: "fēn fēn", khmer: "មួយៗ; ខុសៗគ្នា" },
    { word: "奋斗", pinyin: "fèn dòu", khmer: "ប្រយុទ្ធ" },
    { word: "疯狂", pinyin: "fēng kuáng", khmer: "គំរាមកំហែង; ខុសគ្នា" },
    { word: "风格", pinyin: "fēng gé", khmer: "ស្ទីល" },
    { word: "风景", pinyin: "fēng jǐng", khmer: "ទេសភាព; រូបភាព" },
    { word: "风俗", pinyin: "fēng sú", khmer: "ប្រពៃណីសង្គម" },
    { word: "风险", pinyin: "fēng xiǎn", khmer: "ហានិភ័យ" },
    { word: "讽刺", pinyin: "fěng cì", khmer: "ក្លែងក្លាយ; គិតលេង" },
    { word: "否定", pinyin: "fǒu dìng", khmer: "ការបដិសេធ" },
    { word: "否认", pinyin: "fǒu rèn", khmer: "បដិសេធ" },
    { word: "幅", pinyin: "fú", khmer: "ទទឹង; រូបភាព" },
    { word: "扶", pinyin: "fú", khmer: "ជួយ; អប់រំ" },
    { word: "服装", pinyin: "fú zhuāng", khmer: "សម្លៀកបំពាក់" },
    { word: "辅导", pinyin: "fǔ dǎo", khmer: "ណែនាំ; គ្រូបង្រៀន" },
    { word: "复制", pinyin: "fù zhì", khmer: "ចម្លង; ការបោះបង់" },
    { word: "妇女", pinyin: "fù nǚ", khmer: "ស្រ្តី" },
    { word: "改革", pinyin: "gǎi gé", khmer: "កែប្រែ/បម្លែង" },
    { word: "改进", pinyin: "gǎi jìn", khmer: "ធ្វើឲ្យប្រសើរ" },
    { word: "改善", pinyin: "gǎi shàn", khmer: "បង្កើនប្រសិទ្ធភាព" },
    { word: "改正", pinyin: "gǎi zhèng", khmer: "កែតម្រូវ" },
    { word: "概括", pinyin: "gài kuò", khmer: "សរុប; បង្ហាញទាំងមូល" },
    { word: "概念", pinyin: "gài niàn", khmer: "គំនិត; បញ្ញាសកល" },
    { word: "盖", pinyin: "gài", khmer: "គំរូ; បិទ" },
    { word: "干脆", pinyin: "gān cuì", khmer: "ច្បាស់; ការត្រឹមត្រូវ" },
    { word: "干燥", pinyin: "gān zào", khmer: "អារម្មណ៍ស្ងួត" },
    { word: "感激", pinyin: "gǎn jī", khmer: "ថ្លែងអំណរគុណ" },
    { word: "感受", pinyin: "gǎn shòu", khmer: "ទទួលស្គាល់; ប្រយោជន៍" },
    { word: "感想", pinyin: "gǎn xiǎng", khmer: "ការយល់ឃើញ; មតិ" },
    { word: "赶紧", pinyin: "gǎn jǐn", khmer: "អត្រាបន្ទាន់" },
    { word: "赶快", pinyin: "gǎn kuài", khmer: "ភ្លាមៗ" },
    { word: "干活儿", pinyin: "gàn huó r", khmer: "ការងារដៃ" },
    { word: "钢铁", pinyin: "gāng tiě", khmer: "សំរាប់ដែក; គុណភាពខ្ពស់" },
    { word: "高档", pinyin: "gāo dàng", khmer: "គុណភាពខ្ពស់" },
    { word: "高级", pinyin: "gāo jí", khmer: "មជ្ឈមណ្ឌលកម្រិតខ្ពស់" },
    { word: "搞", pinyin: "gǎo", khmer: "ធ្វើ" },
    { word: "告别", pinyin: "gào bié", khmer: "លះបង់" },
    { word: "格外", pinyin: "gé wài", khmer: "ជាពិសេស" },
    { word: "隔壁", pinyin: "gé bì", khmer: "ផ្ទះផ្ទាល់" },
    { word: "个别", pinyin: "gè bié", khmer: "ជាសកល" },
    { word: "个人", pinyin: "gè rén", khmer: "និរន្តរ; មនុស្សផ្ទាល់ខ្លួន" },
    { word: "个性", pinyin: "gè xìng", khmer: "អត្តសញ្ញាណ" },
    { word: "各自", pinyin: "gè zì", khmer: "គ្នា" },
    { word: "根", pinyin: "gēn", khmer: "មូលដ្ឋាន; ឧបករណ៍" },
    { word: "根本", pinyin: "gēn běn", khmer: "មូលដ្ឋាន; ពិតប្រាកដ" },
    { word: "公布", pinyin: "gōng bù", khmer: "ប្រកាស; បង្ហោះ" },
    { word: "公开", pinyin: "gōng kāi", khmer: "ធ្វើឲ្យប្រកាស; សាធារណៈ" },
    { word: "公平", pinyin: "gōng píng", khmer: "សមរម្យ; ត្រឹមត្រូវ" },
    { word: "公寓", pinyin: "gōng yù", khmer: "ផ្ទះល្វែង" },
    { word: "公元", pinyin: "gōng yuán", khmer: "ឆ្នាំក្រោយគ្រិស្ដសាសន៍" },
    { word: "公主", pinyin: "gōng zhǔ", khmer: "ព្រះនាង" },
    { word: "功能", pinyin: "gōng néng", khmer: "មុខងារ" },
    { word: "工厂", pinyin: "gōng chǎng", khmer: "រោងចក្រ" },
    { word: "工程师", pinyin: "gōng chéng shī", khmer: "វិស្វករ" },
    { word: "工具", pinyin: "gōng jù", khmer: "ឧបករណ៍" },
    { word: "工人", pinyin: "gōng rén", khmer: "ក្រុមការងារ; ជនការងារ" },
    { word: "工业", pinyin: "gōng yè", khmer: "ឧស្សាហកម្ម" },
    { word: "恭喜", pinyin: "gōng xǐ", khmer: "សូមអបអរសាទរ" },
    { word: "贡献", pinyin: "gòng xiàn", khmer: "ចូលរួម" },
    { word: "沟通", pinyin: "gōu tōng", khmer: "ទំនាក់ទំនង" },
    { word: "构成", pinyin: "gòu chéng", khmer: "បង្កើតឡើង; កសាង" },
    { word: "姑姑", pinyin: "gū gu", khmer: "បងប្អូនប្រុស" },
    { word: "姑娘", pinyin: "gū niang", khmer: "ស្រីក្មេង" },
    { word: "古代", pinyin: "gǔ dài", khmer: "សម័យបុរាណ" },
    { word: "古典", pinyin: "gǔ diǎn", khmer: "បុរាណ" },
    { word: "股票", pinyin: "gǔ piào", khmer: "ភាគហ៊ុន" },
    { word: "骨头", pinyin: "gǔ tou", khmer: "អង្គត្រាប់" },
    { word: "鼓舞", pinyin: "gǔ wǔ", khmer: "ការលើកទឹកចិត្ត" },
    { word: "鼓掌", pinyin: "gǔ zhǎng", khmer: "ចាប់ដៃទាន់" },
    { word: "固定", pinyin: "gù dìng", khmer: "កំណត់; សម្រាប់ប្រើជាប្រចាំ" },
    { word: "挂号", pinyin: "guà hào", khmer: "ចុះបញ្ជី" },
    { word: "乖", pinyin: "guāi", khmer: "អនុគ្រោះ; យ៉ាងល្អ" },
    { word: "拐弯", pinyin: "guǎi wān", khmer: "បង្វិលមុំ" },
    { word: "怪不得", pinyin: "guài bu de", khmer: "មិនអាចប្រើទោសបានទេ!" },
    { word: "关闭", pinyin: "guān bì", khmer: "បិទ; បិទសំរាប់" },
    { word: "官", pinyin: "guān", khmer: "មន្រ្តី; រដ្ឋាភិបាល" },
    { word: "观察", pinyin: "guān chá", khmer: "សិក្សា; ត្រួតពិនិត្យ" },
    { word: "观点", pinyin: "guān diǎn", khmer: "គំនិត; មุมមอง" },
    { word: "观念", pinyin: "guān niàn", khmer: "គំនិត; មតិ" },
    { word: "管子", pinyin: "guǎn zǐ", khmer: "បំពង់; ដំបូល; គន្លង" },
    { word: "冠军", pinyin: "guàn jūn", khmer: "ឈ្នះការប្រកួត" },
    { word: "光滑", pinyin: "guāng hua", khmer: "សូម្បី; លីង" },
    { word: "光临", pinyin: "guāng lín", khmer: "សូមអញ្ជើញ!" },
    { word: "光明", pinyin: "guāng míng", khmer: "ពន្លឺ; ភាពភ្លឺ" },
    { word: "光盘", pinyin: "guāng pán", khmer: "ឌីស៍កូមផាត; ស៊ីឌី" },
    { word: "广场", pinyin: "guǎng chǎng", khmer: "ចំណតសាធារណៈ" },
    { word: "广大", pinyin: "guǎng dà", khmer: "ទូលំទូលាយ" },
    { word: "广泛", pinyin: "guǎng fàn", khmer: "ទូលំទូលាយ" },
    { word: "归纳", pinyin: "guī nà", khmer: "សង្ខេប; បញ្ចូល" },
    { word: "规矩", pinyin: "guī ju", khmer: "ច្បាប់; នីតិវិធី" },
    { word: "规律", pinyin: "guī lǜ", khmer: "ច្បាប់ប្រព័ន្ធ; វិធាន" },
    { word: "规模", pinyin: "guī mó", khmer: "កម្រិត; ប្រវែង" },
    { word: "规则", pinyin: "guī zé", khmer: "ច្បាប់នីតិវិធី" },
    { word: "柜台", pinyin: "guì tái", khmer: "កន្លែងលក់; តុបម្រើ" },
    { word: "滚", pinyin: "gǔn", khmer: "បង្វិល; លាយឡំ; រុះត្បិត" },
    { word: "锅", pinyin: "guō", khmer: "ឆ្នាំង" },
    { word: "国庆节", pinyin: "guó qìng jié", khmer: "ថ្ងៃជាតិកុម្ភៈ" },
    { word: "国王", pinyin: "guó wáng", khmer: "ព្រះមហាក្សត្រ" },
    { word: "果然", pinyin: "guǒ rán", khmer: "ពិតណាស់; ហាក់ដូចជា" },
    { word: "果实", pinyin: "guǒ shí", khmer: "ផ្លែឈើ; ផលប៉ះពាល់" },
    { word: "过分", pinyin: "guò fèn", khmer: "លើសពីលក្ខណៈ; ច្រើនពេក" },
    { word: "过敏", pinyin: "guò mǐn", khmer: "ប្រតិកម្មចំពោះអាណិត; ធ្វើបែបប្រតិកម្ម" },
    { word: "过期", pinyin: "guò qī", khmer: "ឆាប់ផុតកំណត់; ថែមទាំងជាប់បញ្ចប់" },
    { word: "哈", pinyin: "hā", khmer: "ការញ័រឬអាឡាបមុខ" },
    { word: "海关", pinyin: "hǎi guān", khmer: "មន្ទីរផ្ទៃក្រៅ" },
    { word: "海鲜", pinyin: "hǎi xiān", khmer: "ម្ហូបទឹកដី; សត្វទឹក" },
    { word: "喊", pinyin: "hǎn", khmer: "ហៅ; ច្រៀង" },
    { word: "行业", pinyin: "háng yè", khmer: "មុខរបរ; អាជីព" },
    { word: "豪华", pinyin: "háo huá", khmer: "ប្រណីត; ស្រស់ស្អាត" },
    { word: "好客", pinyin: "hào kè", khmer: "សុភមង្គល; មិត្តភាគី" },
    { word: "好奇", pinyin: "hào qí", khmer: "ចង់ដឹង; ស្រលាញ់ការសួរ" },
    { word: "何必", pinyin: "hé bì", khmer: "មិនមានតម្រូវការទេ" },
    { word: "何况", pinyin: "hé kuàng", khmer: "លើសពីនេះ; ខណៈពេលណា" },
    { word: "合法", pinyin: "hé fǎ", khmer: "ត្រឹមត្រូវ; អតិភាពសាកល" },
    { word: "合理", pinyin: "hé lǐ", khmer: "មូលហេតុ; អតិភាពធម្មតា" },
    { word: "合同", pinyin: "hé tong", khmer: "កិច្ចសន្យា" },
    { word: "合影", pinyin: "hé yǐng", khmer: "រូបថតរួម" },
    { word: "合作", pinyin: "hé zuò", khmer: "សហការណ៍; បំពេញគ្នា" },
    { word: "和平", pinyin: "hé píng", khmer: "សន្តិភាព" },
    { word: "核心", pinyin: "hé xīn", khmer: "មជ្ឈមណ្ឌល" },
    { word: "恨", pinyin: "hèn", khmer: "សង្ស័យ; បិទចិត្ត" },
    { word: "猴子", pinyin: "hóu zi", khmer: "សត្វកណ្តាប់ដៃ" },
    { word: "后背", pinyin: "hòu bèi", khmer: "ផ្នែកក្រោយ" },
    { word: "后果", pinyin: "hòu guǒ", khmer: "ផលប៉ះពាល់; បញ្ហា" },
    { word: "呼吸", pinyin: "hū xī", khmer: "ដកដង្ហើម" },
    { word: "忽然", pinyin: "hū rán", khmer: "ភ្លាមៗ; មិនគិតសិន" },
    { word: "忽视", pinyin: "hū shì", khmer: "បង់ភ្លេច; មិនអនុញ្ញាត" },
    { word: "壶", pinyin: "hú", khmer: "កាហ្វេ; ចុងបាយកាក់" },
    { word: "糊涂", pinyin: "hú tu", khmer: "ច្របូកច្របល់; យ៉ាងគ្រប់គ្រាន់" },
    { word: "胡说", pinyin: "hú shuō", khmer: "និយាយអីចម្ងាយ; ឧស្សាហ៍ថត" },
    { word: "胡同", pinyin: "hú tòng", khmer: "ផ្លូវតូច; ស្រុក" },
    { word: "蝴蝶", pinyin: "hú dié", khmer: "ពស់; សត្វមានស្លាប" },
    { word: "花生", pinyin: "huā shēng", khmer: "ដុដែប" },
    { word: "华裔", pinyin: "huá yì", khmer: "ជនជាតិចិន; អ្នកដែលមានជាតិកាត់របស់ចិន" },
    { word: "滑", pinyin: "huá", khmer: "ផ្លាស់; ភ្លឺ; ហួសកំណត់" },
    { word: "划", pinyin: "huà", khmer: "បង្ហាត់; យកការដឹកជញ្ជូន" },
    { word: "化学", pinyin: "huà xué", khmer: "គីមីវិទ្យា" },
    { word: "话题", pinyin: "huà tí", khmer: "ប្រធានបទ" },
    { word: "怀念", pinyin: "huái niàn", khmer: "ចងចាំ; នឹកឃើញ" },
    { word: "怀孕", pinyin: "huái yùn", khmer: "មានផ្ទៃពោះ" },
    { word: "缓解", pinyin: "huǎn jiě", khmer: "បន្ថយ; ប្រើប្រាស់ការលំបាក" },
    { word: "幻想", pinyin: "huàn xiǎng", khmer: "ព្រលិត; ការរៀបចំ" },
    { word: "慌张", pinyin: "huāng zhāng", khmer: "ប្រហែល; មានការលំបាក" },
    { word: "黄金", pinyin: "huáng jīn", khmer: "ប្រាក់សុទ្ធ" },
    { word: "恢复", pinyin: "huī fù", khmer: "ត្រឡប់មកវិញ; រៀបចំឡើងវិញ" },
    { word: "挥", pinyin: "huī", khmer: "គោរព; ដាក់ទំនាក់ទំនង" },
    { word: "灰", pinyin: "huī", khmer: "សំរាម; ភាគខាងក្រោយ" },
    { word: "灰尘", pinyin: "huī chén", khmer: "សំរាម" },
    { word: "灰心", pinyin: "huī xīn", khmer: "បាត់បង់ចិត្ត" },
    { word: "汇率", pinyin: "huì lv4", khmer: "អត្រាការផ្លាស់ប្តូរ" },
    { word: "婚礼", pinyin: "hūn lǐ", khmer: "អនុស្សាវរីយ៍រៀបការក្រុម" },
    { word: "婚姻", pinyin: "hūn yīn", khmer: "អាពាហ៍ពិពាហ៍; នីតិវិធីរៀបការជាជីវភាព" },
    { word: "活跃", pinyin: "huó yuè", khmer: "សកម្ម; ការប្រារព្ធ" },
    { word: "伙伴", pinyin: "huǒ bàn", khmer: "ដៃគូ; មិត្ត" },
    { word: "火柴", pinyin: "huǒ chái", khmer: "ដែកភ្លើង" },
    { word: "或许", pinyin: "huò xǔ", khmer: "ប្រហែលជា" },
    { word: "基本", pinyin: "jī běn", khmer: "មូលដ្ឋាន; បេសកកម្ម" },
    { word: "机器", pinyin: "jī qì", khmer: "ម៉ាស៊ីន" },
    { word: "激烈", pinyin: "jī liè", khmer: "ធ្ងន់ធ្ងរ; ខ្ជិល" },
    { word: "肌肉", pinyin: "jī ròu", khmer: "សាច់ដុំ" },
    { word: "及格", pinyin: "jí gé", khmer: "ប្រកបដោយគុណភាព; សម្រាប់កំរិតតំរូវការ" },
    { word: "急忙", pinyin: "jí máng", khmer: "បន្ទាន់; ឆាប់រហ័ស" },
    { word: "急诊", pinyin: "jí zhěn", khmer: "ការជំនួយបន្ទាន់" },
    { word: "极其", pinyin: "jí qí", khmer: "យ៉ាងខ្លាំង" },
    { word: "集合", pinyin: "jí hé", khmer: "ចុះទីតាំង; រួមគ្នា" },
    { word: "集体", pinyin: "jí tǐ", khmer: "អង្គភាពរួម" },
    { word: "集中", pinyin: "jí zhōng", khmer: "ផ្តោតអារម្មណ៍; បញ្ចូលគ្នា" },
    { word: "寂寞", pinyin: "jì mò", khmer: "អៀកទុក្ខ" },
    { word: "系领带", pinyin: "jì lǐng dài", khmer: "ស្តុកម៉ូត" },
    { word: "纪录", pinyin: "jì lù", khmer: "កំណត់ត្រា; ប្រវត្តិកំណត់"},
    { word: "纪律", pinyin: "jì lv4", khmer: "វិន័យ" },
    { word: "纪念", pinyin: "jì niàn", khmer: "អនុស្សាវរីយ៍" },
    { word: "计算", pinyin: "jì suàn", khmer: "គណនាអ្វីមួយ" },
    { word: "记录", pinyin: "jì lù", khmer: "កំណត់ត្រា" },
    { word: "记忆", pinyin: "jì yì", khmer: "អង្គភាពចងចាំ" },
    { word: "嘉宾", pinyin: "jiā bīn", khmer: "ភ្ញៀវឧត្តម" },
    { word: "夹子", pinyin: "jiā zi", khmer: "ខ្នើម; ចំនាត់" },
    { word: "家庭", pinyin: "jiā tíng", khmer: "គ្រួសារ" },
    { word: "家务", pinyin: "jiā wù", khmer: "ការងារនៅផ្ទះ" },
    { word: "家乡", pinyin: "jiā xiāng", khmer: "ទីកន្លែងកំណើត" },
    { word: "假如", pinyin: "jiǎ rú", khmer: "ប្រសិនបើ" },
    { word: "假设", pinyin: "jiǎ shè", khmer: "ការប៉ាន់ប្រមាណ" },
    { word: "假装", pinyin: "jiǎ zhuāng", khmer: "បង្ហាញពី" },
    { word: "甲", pinyin: "jiǎ", khmer: "ទី១" },
    { word: "价值", pinyin: "jià zhí", khmer: "តម្លៃ" },
    { word: "嫁", pinyin: "jià", khmer: "រៀបការក្នុងជីវិតស្ត្រី" },
    { word: "驾驶", pinyin: "jià shǐ", khmer: "បើកបរ" },
    { word: "兼职", pinyin: "jiān zhí", khmer: "ការងារពេលវេលាចំណាយបន្ថែម" },
    { word: "坚决", pinyin: "jiān jué", khmer: "សម្រេចចិត្តយ៉ាងហ្មត" },
    { word: "坚强", pinyin: "jiān qiáng", khmer: "ស្ថិតរឹងមាំ" },
    { word: "肩膀", pinyin: "jiān bǎng", khmer: "ស្មា" },
    { word: "艰巨", pinyin: "jiān jù", khmer: "ការងារខ្ពស់បំផុត" },
    { word: "艰苦", pinyin: "jiān kǔ", khmer: "ខ្ពស់និងយ៉ាងលំបាក" },
    { word: "剪刀", pinyin: "jiǎn dāo", khmer: "កន្សោម" },
    { word: "捡", pinyin: "jiǎn", khmer: "ប្រមូល" },
    { word: "简历", pinyin: "jiǎn lì", khmer: "ប្រវត្តិរូប" },
    { word: "简直", pinyin: "jiǎn zhí", khmer: "អាចបញ្ជាក់បាន" },
    { word: "健身", pinyin: "jiàn shēn", khmer: "ហាត់ប្រាណ" },
    { word: "建立", pinyin: "jiàn lì", khmer: "បង្កើត" },
    { word: "建设", pinyin: "jiàn shè", khmer: "សំណង់" },
    { word: "建筑", pinyin: "jiàn zhù", khmer: "អាគារ" },
    { word: "键盘", pinyin: "jiàn pán", khmer: "គន្លងក្តារចុច" },
    { word: "讲究", pinyin: "jiǎng jiu", khmer: "យកចិត្តទុកដាក់" },
    { word: "讲座", pinyin: "jiǎng zuò", khmer: "វគ្គបង្រៀន" },
    { word: "酱油", pinyin: "jiàng yóu", khmer: "ស៊ូយ៉ូ" },
    { word: "交换", pinyin: "jiāo huàn", khmer: "ប្ដូរ" },
    { word: "交际", pinyin: "jiāo jì", khmer: "ទំនាក់ទំនងសង្គម" },
    { word: "交往", pinyin: "jiāo wǎng", khmer: "ទំនាក់ទំនង" },
    { word: "浇", pinyin: "jiāo", khmer: "បរិច្ឆេទទឹក" },
    { word: "胶水", pinyin: "jiāo shuǐ", khmer: "សែល" },
    { word: "狡猾", pinyin: "jiǎo huá", khmer: "មានភាពក្រឡាប់" },
    { word: "角度", pinyin: "jiǎo dù", khmer: "កូណ៏" },
    { word: "教材", pinyin: "jiào cái", khmer: "សម្ភារៈបង្រៀន" },
    { word: "教练", pinyin: "jiào liàn", khmer: "គ្រូបង្រៀន" },
    { word: "教训", pinyin: "jiào xun", khmer: "មេរៀន" },
    { word: "接触", pinyin: "jiē chù", khmer: "ទំនាក់ទំនង" },
    { word: "接待", pinyin: "jiē dài", khmer: "ទទួលភ្ញៀវ" },
    { word: "接近", pinyin: "jiē jìn", khmer: "ជិត" },
    { word: "结实", pinyin: "jiē shi", khmer: "រឹងមាំ" },
    { word: "阶段", pinyin: "jiē duàn", khmer: "ដំណាក់កាល" },
    { word: "结构", pinyin: "jié gòu", khmer: "រចនាសម្ព័ន្ធ" },
    { word: "结合", pinyin: "jié hé", khmer: "ភ្ជាប់" },
    { word: "结论", pinyin: "jié lùn", khmer: "សេចក្តីសន្និដ្ឋាន" },
    { word: "结账", pinyin: "jié zhàng", khmer: "បង់លុយ" },
    { word: "节省", pinyin: "jié shěng", khmer: "សន្សំ" },
    { word: "借口", pinyin: "jiè kǒu", khmer: "ការអះអាង" },
    { word: "届", pinyin: "jiè", khmer: "មួយកំណត់" },
    { word: "戒", pinyin: "jiè", khmer: "ធ្វើការពារផ្ទាំង; ពិធីបង្រៀន; ប្រាប់ឲ្យចាប់អារម្មណ៍; បញ្ចប់ឬបញ្ចប់ការប្រព្រឹត្តិការណ៍ណាមួយ; វិធានសាសនាបូកព្រះ" },
    { word: "戒指", pinyin: "jiè zhǐ", khmer: "ច្រកដៃ (សម្រាប់ម្រាមដៃ)" },
    { word: "金属", pinyin: "jīn shǔ", khmer: "ដែក; ប្រភេទ" },
    { word: "尽快", pinyin: "jǐn kuài", khmer: "ឲ្យបានលឿនជាងគេ; ទៅតាមពេលវេលាដែលអាចធ្វើទៅបាន" },
    { word: "紧急", pinyin: "jǐn jí", khmer: "បន្ទាន់; ព្រឹត្តិការណ៍បន្ទាន់" },
    { word: "谨慎", pinyin: "jǐn shèn", khmer: "ប្រុងប្រយត្ន៍; ប្រកបដោយការប្រុងប្រយ័ត្ន" },
    { word: "尽力", pinyin: "jìn lì", khmer: "ខិតខំធ្វើឲ្យបានប្រសើរ; មិនចូលចិត្តធ្វើការងារលើស" },
    { word: "尽量", pinyin: "jìn liàng", khmer: "ឲ្យបានល្អបំផុត; សំរាប់ការប្រើប្រាស់បំផុត" },
    { word: "近代", pinyin: "jìn dài", khmer: "សម័យទំនើប" },
    { word: "进步", pinyin: "jìn bù", khmer: "ជំហាន; បន្ទាប់ពីវឌ្ឍនភាព" },
    { word: "进口", pinyin: "jìn kǒu", khmer: "នាំចូល; ទំនិញនាំចូល" },
    { word: "精力", pinyin: "jīng lì", khmer: "ថាមពល" },
    { word: "精神", pinyin: "jīng shén", khmer: "វិញ្ញាណ; ចិត្ត; អារម្មណ៍" },
    { word: "经典", pinyin: "jīng diǎn", khmer: "ក្រមសាសនា; សាសនាចាស់" },
    { word: "经商", pinyin: "jīng shāng", khmer: "ធ្វើពាណិជ្ជកម្ម" },
    { word: "经营", pinyin: "jīng yíng", khmer: "ប្រតិបត្ដិពាណិជ្ជកម្ម" },
    { word: "酒吧", pinyin: "jiǔ bā", khmer: "ភោជនីយដ្ឋាន; ធ្វើមហាសន្និដ្ឋាន" },
    { word: "救", pinyin: "jiù", khmer: "ជួយសង្គ្រោះ" },
    { word: "救护车", pinyin: "jiù hù chē", khmer: "រថយន្តសង្គ្រោះជាតិកំឡាំង" },
    { word: "舅舅", pinyin: "jiù jiu", khmer: "បងប្រុសម៉ែ; អ្នកមួយគ្រិតសំរាប់ម៉ែ" },
    { word: "居然", pinyin: "jū rán", khmer: "គ្មានការរំពឹងទុក; ដោយអស្ចារ្យ" },
    { word: "桔子", pinyin: "jú zi", khmer: "ទាវ; ផ្លែទារិត" },
    { word: "俱乐部", pinyin: "jù lè bù", khmer: "ក្លិប (ក្រុមឬអង្គការមួយ)" },
    { word: "具备", pinyin: "jù bèi", khmer: "មាន; ស្របតាមការកំណត់" },
    { word: "具体", pinyin: "jù tǐ", khmer: "ជាក់លាក់; ពិសេស" },
    { word: "巨大", pinyin: "jù dà", khmer: "ធំនិងធំល្អ; អស្ចារ្យ" },
    { word: "据说", pinyin: "jù shuō", khmer: "វាគឺត្រូវបាននិយាយថា; មានការរាយការណ៍" },
    { word: "捐", pinyin: "juān", khmer: "បរិច្ចាគ; ដាក់បរិច្ឆេទ; បរិច្ចាគសាច់ប្រាក់" },
    { word: "决赛", pinyin: "jué sài", khmer: "ការប្រកួតចុងក្រោយ" },
    { word: "决心", pinyin: "jué xīn", khmer: "结论; ការកំណត់បំណង" },
    { word: "绝对", pinyin: "jué duì", khmer: "តែដាច់" },
    { word: "角色", pinyin: "jué sè", khmer: "តួនាទី; តួក្នុងរឿង" },
    { word: "军事", pinyin: "jūn shì", khmer: "យុទ្ធសាស្ត្រ; ការទប់ខ្លួន" },
    { word: "均匀", pinyin: "jūn yún", khmer: "ល្អជាច្រើន; ស្របតាមលំនាំ" },
    { word: "卡车", pinyin: "kǎ chē", khmer: "ឡានដឹកទំនិញ; ឡានទំនិញ" },
    { word: "开发", pinyin: "kāi fā", khmer: "បង្កើតឡើង; អភិវឌ្ឍន៍" },
    { word: "开放", pinyin: "kāi fàng", khmer: "លើកយក (មួយចំណុច); បើកឡើងទៅភាគីក្រៅ" },
    { word: "开幕式", pinyin: "kāi mù shì", khmer: "ពិធីបើកបង្ហាញ" },
    { word: "开水", pinyin: "kāi shuǐ", khmer: "ទឹកប៉ោប; ទឹកល្ងាច" },
    { word: "砍", pinyin: "kǎn", khmer: "កាត់; ដកដាច់" },
    { word: "看不起", pinyin: "kàn bu qǐ", khmer: "មើលដូចគ្មានការលើកទឹកចិត្ត; មិនគោរព" },
    { word: "看望", pinyin: "kàn wàng", khmer: "ទៅសួរសុខទុក្ខ; ដាក់ការអញ្ជើញ" },
    { word: "靠", pinyin: "kào", khmer: "អាស្រ័យលើ; ពឹងផ្អែក" },
    { word: "颗", pinyin: "kē", khmer: "ឯកតាសម្រាប់បាល់តូចៗ, ពុម្ព, ឬតំណាងអ្វីមួយ" },
    { word: "可见", pinyin: "kě jiàn", khmer: "អាចមើលឃើញបានច្បាស់" },
    { word: "可靠", pinyin: "kě kào", khmer: "អាចទុកចិត្តបាន" },
    { word: "可怕", pinyin: "kě pà", khmer: "អាក្រក់; គ្រោះថ្នាក់; ខ្លាច" },
    { word: "克", pinyin: "kè", khmer: "អាច; ដើរល្អ; ត្រួតពិនិត្យ; ទទួលបាន" },
    { word: "克服", pinyin: "kè fú", khmer: "ឆ្លងកាត់ឧបសគ្គ; ឈ្នះ; ប្រឹងប្រែង" },
    { word: "刻苦", pinyin: "kè kǔ", khmer: "ខិតខំប្រឹងប្រែង; ឈឺចាប់" },
    { word: "客观", pinyin: "kè guān", khmer: "មានទស្សនៈមនុស្សឬមួយគន្លងផ្ទាល់; មានវិចារណកថាគោល" },
    { word: "课程", pinyin: "kè chéng", khmer: "វគ្គសិក្សា; មុខវិជ្ជា; កម្មវិធី" },
    { word: "空间", pinyin: "kōng jiān", khmer: "ផ្ទៃត្រង់ (ក្នុងវិទ្យាសាស្ត្រ); បន្ទប់" },
    { word: "控制", pinyin: "kòng zhì", khmer: "គ្រប់គ្រង; អនុវត្តការគ្រប់គ្រង" },
    { word: "空闲", pinyin: "kòng xián", khmer: "ពេលទំនេរ; ពេលសម្រាក" },
    { word: "口味", pinyin: "kǒu wèi", khmer: "ចំណង់ចំណូលចិត្តរបស់មនុស្ស; រសជាតិកម្ចី" },
    { word: "夸", pinyin: "kuā", khmer: "ពោលការសរសើរ; ពង្រឹង; ពិចារណាមានច្រើន" },
    { word: "夸张", pinyin: "kuā zhāng", khmer: "ពេញនិយម; ការពិពណ៌នាពីពហុភាព; លើសព្រំដែន" },
    { word: "会计", pinyin: "kuài jì", khmer: "គណនេយ្យ; អ្នកគណនេយ្យ" },
    { word: "宽", pinyin: "kuān", khmer: "ទូលាយ; គ្រប់គ្រង; ទូលាយ" },
    { word: "昆虫", pinyin: "kūn chóng", khmer: "សត្វល្អិត; ប្រភេទ" },
    { word: "扩大", pinyin: "kuò dà", khmer: "ពង្រីក; បង្កើន" },
    { word: "辣椒", pinyin: "là jiāo", khmer: "ម្សៅតំណក់ក្តៅ; មីកិល" },
    { word: "拦", pinyin: "lán", khmer: "ចាក់ចាំ; បង្ហាញចំហាយ; បញ្ឈប់" },
    { word: "烂", pinyin: "làn", khmer: "បំពងនិងស្រួល; ឡើងក្នង; តិចល្អ" },
    { word: "朗读", pinyin: "lǎng dú", khmer: "អានបញ្ជាក់; អានឲ្យឮច្បាស់" },
    { word: "劳动", pinyin: "láo dòng", khmer: "ការងារផ្លូវស្រាល; សកម្មភាពផ្លូវគ្រួសារជាភាសាកម្ពុជា" },
    { word: "劳驾", pinyin: "láo jià", khmer: "សុំទោស" },
    { word: "姥姥", pinyin: "lǎo lao", khmer: "ម្ដាយម៉ែ; អ្នកប្រើប្រាស់របស់ម៉ែ" },
    { word: "老百姓", pinyin: "lǎo bǎi xìng", khmer: "មនុស្សធម្មតា; មនុស្សម្នាក់" },
    { word: "老板", pinyin: "lǎo bǎn", khmer: "ម្ចាស់អាជីវកម្ម; ម្ចាស់បណ្ដាញ" },
    { word: "老婆", pinyin: "lǎo pó", khmer: "ប្រពន្ធ" },
    { word: "老实", pinyin: "lǎo shi", khmer: "ស្មោះត្រង់; ជឿជាក់ក្នុងការបង្ហោះ" },
    { word: "老鼠", pinyin: "lǎo shǔ", khmer: "ទ squirrels; ម៉ាស" },
    { word: "乐观", pinyin: "lè guān", khmer: "មានមតិវិជ្ជាក្រសួង; មើលឃើញអនាគតក្នុងកម្រិតល្អ" },
    { word: "雷", pinyin: "léi", khmer: "ព្រិល; ការបង្ហូតប្រហែល" },
    { word: "类型", pinyin: "lèi xíng", khmer: "ប្រភេទ; ប្រភេទបែបបទ" },
    { word: "冷淡", pinyin: "lěng dàn", khmer: "ត្រជាក់; មិនបញ្ជាក់នោះទេ" },
    { word: "厘米", pinyin: "lí mǐ", khmer: "សង់ទីម៉ែត្រ" },
    { word: "梨", pinyin: "lí", khmer: "ផ្លែប៉ោម" },
    { word: "离婚", pinyin: "lí hūn", khmer: "បំបែកទំនាក់ទំនងបែបរុងរឿង" },
    { word: "理论", pinyin: "lǐ lùn", khmer: "ទ្រឹស្តី; ប្រព័ន្ធជំនឿ" },
    { word: "理由", pinyin: "lǐ yóu", khmer: "មូលហេតុ; ភាគហ៊ុន" },
    { word: "利润", pinyin: "lì rùn", khmer: "ប្រាក់ចំណេញ" },
    { word: "利息", pinyin: "lì xī", khmer: "ការប្រាក់ (លើការខ្ចី); ចំណាត់ការប្រាក់" },
    { word: "利益", pinyin: "lì yì", khmer: "អត្ថប្រយោជន៍; សំណង" },
    { word: "利用", pinyin: "lì yòng", khmer: "ប្រើប្រាស់; លើកយក" },
    { word: "力量", pinyin: "lì liang", khmer: "អំណាច; កម្លាំង" },
    { word: "立即", pinyin: "lì jí", khmer: "ភ្លាមៗ" },
    { word: "立刻", pinyin: "lì kè", khmer: "ភ្លាមៗ; ចំពោះករណីនេះ" },
    { word: "联合", pinyin: "lián hé", khmer: "ភាគីរួម; ប្រយុទ្ធ" },
    { word: "连忙", pinyin: "lián máng", khmer: "ភ្លាមៗ; នៅពេលដែល" },
    { word: "连续", pinyin: "lián xù", khmer: "បន្ត; ស៊េរី; បន្តដោយកម្រិត" },
    { word: "恋爱", pinyin: "liàn ài", khmer: "ស្រឡាញ់; មានស្នេហា" },
    { word: "粮食", pinyin: "liáng shi", khmer: "អាហារប្រើប្រាស់; គ្រឿងផ្សំសម្រាប់អាហារ" },
    { word: "良好", pinyin: "liáng hǎo", khmer: "ល្អ; ពេញចិត្ត" },
    { word: "亮", pinyin: "liàng", khmer: "ច្រៀង; សំរាប់; បង្ហាញ" },
    { word: "了不起", pinyin: "liǎo bu qǐ", khmer: "អស្ចារ្យ; ទម្លាប់មិនធម្មតា" },
    { word: "列车", pinyin: "liè chē", khmer: "រថភ្លើង" },
    { word: "临时", pinyin: "lín shí", khmer: "ស្ថិតនៅស្ថានភាពជាបណ្តោះអាសន្ន" },
    { word: "灵活", pinyin: "líng huó", khmer: "អាចបត់បែន; ឆ្អែត; បត់បែន" },
    { word: "铃", pinyin: "líng", khmer: "កណ្តឹងតូច; គ្រឿងកណ្តឹង" },
    { word: "零件", pinyin: "líng jiàn", khmer: "ផ្នែក; បរិក្ខារ" },
    { word: "零食", pinyin: "líng shí", khmer: "អាហារស្នេហ៍; អាហារទៅចន្លោះម៉ោង" },
    { word: "领导", pinyin: "lǐng dǎo", khmer: "ដឹកនាំ; ការដឹកនាំ; ប្រធាន" },
    { word: "领域", pinyin: "lǐng yù", khmer: "ដែនកំណត់; វិស័យ" },
    { word: "流传", pinyin: "liú chuán", khmer: "ចែករំលែក; រំលែក" },
    { word: "流泪", pinyin: "liú lèi", khmer: "លាស្រឡាយ; បញ្ចេញទឹកភ្នែក" },
    { word: "浏览", pinyin: "liú lǎn", khmer: "ស្កេមបក; ទស្សនាវីធី" },
    { word: "龙", pinyin: "lóng", khmer: "ភ្ញៀវ; គោរព" },
    { word: "漏", pinyin: "lòu", khmer: "ជ្រុលចេញ; ឬភ្លៀង" },
    { word: "录取", pinyin: "lù qǔ", khmer: "ពិចារណាទៅធ្វើបច្ចេកវិទ្យា" },
    { word: "录音", pinyin: "lù yīn", khmer: "កំណត់ថា" },
    { word: "陆地", pinyin: "lù dì", khmer: "ដីដទៃតាមបង្ហូរទឹក" },
    { word: "陆续", pinyin: "lù xù", khmer: "បន្តដោយភាព" },
    { word: "轮流", pinyin: "lún liú", khmer: "កាលលំហែរថ្មី" },
    { word: "论文", pinyin: "lùn wén", khmer: "បញ្ចូលកម្មវិធី" },
    { word: "逻辑", pinyin: "luó ji", khmer: "ជំនាញគណនា" },
    { word: "落后", pinyin: "luò hòu", khmer: "បត់បន្ថែម; ទៅជាបន្ទប់" },
    { word: "骂", pinyin: "mà", khmer: "ត្រួតត្រាប្រហែល" },
    { word: "麦克风", pinyin: "mài kè fēng", khmer: "មីក្រូហ្វូន" },
    { word: "馒头", pinyin: "mán tou", khmer: "គ្រឿងកញ្ចប់" },
    { word: "满足", pinyin: "mǎn zú", khmer: "ចេញបញ្ជូន" },
    { word: "毛病", pinyin: "máo bìng", khmer: "បញ្ហា; សារព័ត៌មាន" },
    { word: "矛盾", pinyin: "máo dùn", khmer: "ផ្តាច់ផែ; ស្គាល់ក្រុម" },
    { word: "冒险", pinyin: "mào xiǎn", khmer: "ពន្លត់" },
    { word: "贸易", pinyin: "mào yì", khmer: "ពាណិជ្ជកម្ម; ជួញដូរ" },
    { word: "媒体", pinyin: "méi tǐ", khmer: "ប្រព័ន្ធព័ត៌មាន; សារព័ត៌មាន" },
    { word: "煤炭", pinyin: "méi tàn", khmer: "ធ្យូងថ្ម" },
    { word: "眉毛", pinyin: "méi mao", khmer: "ចិញ្ចើម" },
    { word: "美术", pinyin: "měi shù", khmer: "វិចិត្រសិល្បៈ" },
    { word: "魅力", pinyin: "mèi lì", khmer: "ភាពទាក់ទាញ; សោភ័ណភាព" },
    { word: "梦想", pinyin: "mèng xiǎng", khmer: "សុបិន្ត; ប្រាថ្នា" },
    { word: "密切", pinyin: "mì qiè", khmer: "ជិតស្និទ្ធ; ទាក់ទងជាខ្លាំង" },
    { word: "秘密", pinyin: "mì mì", khmer: "អាថ៌កំបាំង; សម្ងាត់" },
    { word: "秘书", pinyin: "mì shū", khmer: "เลขា" },
    { word: "蜜蜂", pinyin: "mì fēng", khmer: "ឃ្មុំ" },
    { word: "面对", pinyin: "miàn duì", khmer: "ប្រឈមមុខ; ជួបប្រទៈ" },
    { word: "面积", pinyin: "miàn jī", khmer: "ផ្ទៃ; ដែនកំណត់" },
    { word: "面临", pinyin: "miàn lín", khmer: "ប្រឈមមុខនឹង; ជួបប្រទៈនឹង" },
    { word: "描写", pinyin: "miáo xiě", khmer: "ពិពណ៌នា; សរសេរពិពណ៌នា" },
    { word: "苗条", pinyin: "miáo tiáo", khmer: "រូបរាងស្រឡូន; សង្ហា" },
    { word: "敏感", pinyin: "mǐn gǎn", khmer: "មានការឆ្លើយតបឆាប់; រអិលរអួល" },
    { word: "名牌", pinyin: "míng pái", khmer: "ម៉ាកល្បី" },
    { word: "名片", pinyin: "míng piàn", khmer: "នាមប័ណ្ណ" },
    { word: "名胜古迹", pinyin: "míng shèng gǔ jì", khmer: "ទីកន្លែងទេសចរណ៍ប្រវត្តិសាស្ត្រ" },
    { word: "明确", pinyin: "míng què", khmer: "ច្បាស់លាស់; បញ្ជាក់ច្បាស់" },
    { word: "明显", pinyin: "míng xiǎn", khmer: "ច្បាស់; ងាយឃើញ" },
    { word: "明星", pinyin: "míng xīng", khmer: "តារា; វិចិត្រករច្បាស់លាស់" },
    { word: "命令", pinyin: "mìng lìng", khmer: "ពាក្យបញ្ជា" },
    { word: "命运", pinyin: "mìng yùn", khmer: "វាសនា; ជោគជ័យ" },
    { word: "摸", pinyin: "mō", khmer: "ប៉ះ; ខ្ទាប; ប៉ះបោល" },
    { word: "摩托车", pinyin: "mó tuō chē", khmer: "ម៉ូតូ" },
    { word: "模仿", pinyin: "mó fǎng", khmer: "សាមស្មាន; ក្លែង; ក្លែងបន្លំ" },
    { word: "模糊", pinyin: "mó hu", khmer: "មិនច្បាស់; ស្រពិចស្រពិល" },
    { word: "模特", pinyin: "mó tè", khmer: "ម៉ូដែល; នារីបង្ហាញម៉ូដ" },
    { word: "陌生", pinyin: "mò shēng", khmer: "មិនស្គាល់; អ្នកបរទេស" },
    { word: "某", pinyin: "mǒu", khmer: "មួយចំនួន; អ្នកណាម្នាក់" },
    { word: "木头", pinyin: "mù tou", khmer: "ឈើ; មនុស្សឧន្ទិល" },
    { word: "目标", pinyin: "mù biāo", khmer: "គោលដៅ" },
    { word: "目录", pinyin: "mù lù", khmer: "មាតិកា; បញ្ជីឈ្មោះ" },
    { word: "目前", pinyin: "mù qián", khmer: "បច្ចុប្បន្ន" },
    { word: "哪怕", pinyin: "nǎ pà", khmer: "បើទោះបីជា; សូម្បីតែ" },
    { word: "难怪", pinyin: "nán guài", khmer: "មិនចម្លែកទេ; មិនគួរឱ្យភ្ញាក់ផ្អើលទេ" },
    { word: "难免", pinyin: "nán miǎn", khmer: "ជៀសរើសមិនរួច" },
    { word: "脑袋", pinyin: "nǎo dài", khmer: "ក្បាល; ខួរក្បាល" },
    { word: "内部", pinyin: "nèi bù", khmer: "ខាងក្នុង; ផ្នែកខាងក្នុង" },
    { word: "内科", pinyin: "nèi kē", khmer: "ផ្នែកពេទ្យជំនាញខាងឱសថ" },
    { word: "嫩", pinyin: "nèn", khmer: "ទន់; ក្មេង; មិនមានបទពិសោធន៍" },
    { word: "能干", pinyin: "néng gàn", khmer: "ដែលមានសមត្ថភាព" },
    { word: "能源", pinyin: "néng yuán", khmer: "ថាមពល; ធនធានថាមពល" },
    { word: "嗯", pinyin: "ńg", khmer: "អ៊ឹ (សំឡេងយល់ព្រម)" },
    { word: "年代", pinyin: "nián dài", khmer: "សតវត្ស; ទសវត្ស" },
    { word: "年纪", pinyin: "nián jì", khmer: "ថ្នាក់រៀន; អាយុសិក្សា" },
    { word: "念", pinyin: "niàn", khmer: "នឹក; អាន; សិក្សា; គំនិត; ចងចាំ" },
    { word: "宁可", pinyin: "nìng kě", khmer: "ព្រមជ្រើសរើស; ចិត្តធ្វើ…ប្រសិនបើ" },
    { word: "牛仔裤", pinyin: "niú zǎi kù", khmer: "ខោជើងវែងស្បែកគោ (ជីន)" },
    { word: "农村", pinyin: "nóng cūn", khmer: "ជនបទ; ភូមិ" },
    { word: "农民", pinyin: "nóng mín", khmer: "ប្រជាកសិករ" },
    { word: "农业", pinyin: "nóng yè", khmer: "កសិកម្ម" },
    { word: "浓", pinyin: "nóng", khmer: "ខាប់; សម្បូរ; ដិត" },
    { word: "女士", pinyin: "nǚ shì", khmer: "លោកស្រី" },
    { word: "欧洲", pinyin: "ōu zhōu", khmer: "អឺរ៉ុប" },
    { word: "偶然", pinyin: "ǒu rán", khmer: "ដោយចៃដន្យ; ម្តងម្កាល" },
    { word: "拍", pinyin: "pāi", khmer: "ថត (រូបភាព); ទះ; បោះ" },
    { word: "派", pinyin: "pài", khmer: "派=派系=ក្រុម派遣=ផ្ញើ; បែងចែក" },
    { word: "盼望", pinyin: "pàn wàng", khmer: "សង្ឃឹម; រង់ចាំយ៉ាងអង្វរ" },
    { word: "培训", pinyin: "péi xùn", khmer: "បណ្ដុះបណ្ដាល; បណ្តុះនិងហ្វឹកហាត់" },
    { word: "培养", pinyin: "péi yǎng", khmer: "បង្រៀន; ឧបត្ថម្ភ; បណ្តុះបណ្តាល" },
    { word: "赔偿", pinyin: "péi cháng", khmer: "សងជំងឺ; សងប្រាក់សំណង" },
    { word: "佩服", pinyin: "pèi fú", khmer: "គោរព; ចាប់អារម្មណ៍" },
    { word: "配合", pinyin: "pèi hé", khmer: "សហការ; សម្របសម្រួល; សមស្រប" },
    { word: "盆", pinyin: "pén", khmer: "ចាន/ចានធំ; ផុងដាក់ផ្កា" },
    { word: "碰", pinyin: "pèng", khmer: "ប៉ះ; បុក; ជួបប្រទះ" },
    { word: "批", pinyin: "pī", khmer: "ចំនួន (សម្រាប់ការបែងចែក); វាយតម្លៃ; យល់ព្រម" },
    { word: "批准", pinyin: "pī zhǔn", khmer: "អនុម័ត; យល់ព្រម" },
    { word: "披", pinyin: "pī", khmer: "ពាក់; លាត; បកចេញ" },
    { word: "疲劳", pinyin: "pí láo", khmer: "នឿយហត់; អស់កម្លាំង" },
    { word: "匹", pinyin: "pǐ", khmer: "ក្បាល (សម្រាប់សេះ); អ្នកធម្មតា" },
    { word: "片", pinyin: "piàn", khmer: "ដុំ; សន្លឹក; ភាគច្រើន; សន្លឹកខ្សែភាពយន្ត" },
    { word: "片面", pinyin: "piàn miàn", khmer: "ឯកភាគ; មិនទាំងស្រុង" },
    { word: "飘", pinyin: "piāo", khmer: "រអិល; រសើប; ផ្អើលក្នុងខ្យល់" },
    { word: "拼音", pinyin: "pīn yīn", khmer: "ពិនយិន; អក្សរសំលៀងចិន" },
    { word: "频道", pinyin: "pín dào", khmer: "ឆានែល; ជួរប្រេកង់" },
    { word: "凭", pinyin: "píng", khmer: "ដោយផ្អែកលើ; ពឹងផ្អែកលើ" },
    { word: "平均", pinyin: "píng jūn", khmer: "មធ្យម; តាមមធ្យម; ដោយស្មើៗគ្នា" },
    { word: "平", pinyin: "píng", khmer: "ស្មើ; កម្រាលស្មើ; សុខសាន្ត" },
    { word: "平安", pinyin: "píng ān", khmer: "សុវត្ថិភាព; សុខសាន្ត; គ្មានហានិភ័យ" },
    { word: "平常", pinyin: "píng cháng", khmer: "ធម្មតា; ជាទូទៅ" },
    { word: "平等", pinyin: "píng děng", khmer: "សមភាព; ស្មើគ្នា" },
    { word: "平方", pinyin: "píng fāng", khmer: "ការេ (ឧ. ម៉ែត្រការេ)" },
    { word: "平衡", pinyin: "píng héng", khmer: "តុល្យភាព; សមតុល្យ" },
    { word: "平静", pinyin: "píng jìng", khmer: "ស្ងប់ស្ងាត់; សុខសាន្ត" },
    { word: "评价", pinyin: "píng jià", khmer: "វាយតម្លៃ; ប៉ាន់ប្រមាណ" },
    { word: "破产", pinyin: "pò chǎn", khmer: "ខាតបង់; ដល់ពេលលង់បង់; ដើមទុនខូច" },
    { word: "破坏", pinyin: "pò huài", khmer: "បំផ្លាញ; បំផ្លើល" },
    { word: "迫切", pinyin: "pò qiè", khmer: "បន្ទាន់; ដាច់ខាត; ជាបន្ទាន់" },
    { word: "期待", pinyin: "qī dài", khmer: "សង្ឃឹម; រំពឹងទុក" },
    { word: "期间", pinyin: "qī jiān", khmer: "អំឡុងពេល; រយៈពេល" },
    { word: "其余", pinyin: "qí yú", khmer: "ដទៃទៀត; សល់; អ្វីៗនៅសល់" },
    { word: "奇迹", pinyin: "qí jì", khmer: "អច្ឆរិយកម្ម; ការអស្ចារ្យ" },
    { word: "企业", pinyin: "qǐ yè", khmer: "សហគ្រាស; ក្រុមហ៊ុន" },
    { word: "启发", pinyin: "qǐ fā", khmer: "ជំរុញគំនិត; បណ្តាលឲ្យចង់ស្វែងយល់" },
    { word: "气氛", pinyin: "qì fēn", khmer: "បរិយាកាស; អារម្មណ៍" },
    { word: "汽油", pinyin: "qì yóu", khmer: "សាំង" },
    { word: "签", pinyin: "qiān", khmer: "ចុះហត្ថលេខា; ចុះឈ្មោះ" },
    { word: "谦虚", pinyin: "qiān xū", khmer: "ស្មូត្រស្មាញ; មិនអួតអាង" },
    { word: "前途", pinyin: "qián tú", khmer: "អនាគត; ទិសដៅអនាគត" },
    { word: "浅", pinyin: "qiǎn", khmer: "រំលិច; មិនជ្រៅ; ជ្រៅតិច" },
    { word: "欠", pinyin: "qiàn", khmer: "ខ្វះ; ជំពាក់; ខាន" },
    { word: "枪", pinyin: "qiāng", khmer: "កាំភ្លើង; ឧបករណ៍បាញ់" },
    { word: "墙", pinyin: "qiáng", khmer: "ជញ្ជាំង" },
    { word: "强调", pinyin: "qiáng diào", khmer: "សង្កត់ធ្ងន់; បង្កប់ចំណងជើង" },
    { word: "强烈", pinyin: "qiáng liè", khmer: "ខ្លាំង; ខ្លាំងណាស់" },
    { word: "抢", pinyin: "qiǎng", khmer: "កាច់យក; យកជាប្រញាប់; ប្រកួតយក" },
    { word: "悄悄", pinyin: "qiāo qiāo", khmer: "ស្ងៀមស្ងាត់; ពីរយៈពេលស្ងាត់ៗ" },
    { word: "瞧", pinyin: "qiáo", khmer: "មើល; ឃើញ" },
    { word: "巧妙", pinyin: "qiǎo miào", khmer: "ឆ្លាត; ឆ្លាតវៃ" },
    { word: "切", pinyin: "qiē", khmer: "កាត់; ច្រេះ" },
    { word: "亲爱", pinyin: "qīn ài", khmer: "ជាទីស្រឡាញ់; ស្នេហា" },
    { word: "亲切", pinyin: "qīn qiè", khmer: "ស្មោះស្លូតបូត; ស្និទស្នាល" },
    { word: "亲自", pinyin: "qīn zì", khmer: "ផ្ទាល់ខ្លួន; ដោយខ្លួនឯង" },
    { word: "勤奋", pinyin: "qín fèn", khmer: "ឧស្សាហ៍ព្យាយាម" },
    { word: "清淡", pinyin: "qīng dàn", khmer: "បរិបូណ៌តិច; ស្រាល; មិនខ្លាញ់" },
    { word: "轻视", pinyin: "qīng shì", khmer: "មើលងាយ; មើលស្មើ" },
    { word: "轻易", pinyin: "qīng yì", khmer: "ងាយស្រួល; មិនពិបាក; ឆាប់ជឿ" },
    { word: "青", pinyin: "qīng", khmer: "ពណ៌ខៀវ; ពណ៌បៃតងខ្មៅ" },
    { word: "青春", pinyin: "qīng chūn", khmer: "យុវវ័យ; អាយុវ័យជំទង់" },
    { word: "青少年", pinyin: "qīng shào nián", khmer: "យុវជន; វ័យក្មេង" },
    { word: "情景", pinyin: "qíng jǐng", khmer: "ឈុតភាព; ទស្សនភាព; ស្ថានភាព" },
    { word: "情绪", pinyin: "qíng xù", khmer: "អារម្មណ៍; ស្ថានភាពផ្លូវចិត្ត" },
    { word: "请求", pinyin: "qǐng qiú", khmer: "សំណើ; សុំ" },
    { word: "庆祝", pinyin: "qìng zhù", khmer: "អបអរប្រកាស" },
    { word: "球迷", pinyin: "qiú mí", khmer: "អ្នកគាំទ្រកីឡាបាល់; អ្នកស្រឡាញ់បាល់" },
    { word: "趋势", pinyin: "qū shì", khmer: "និន្នាការ; ទិសដៅ" },
    { word: "取消", pinyin: "qǔ xiāo", khmer: "លុបចោល; បោះបង់" },
    { word: "娶", pinyin: "qǔ", khmer: "រៀបការយកភរិយា" },
    { word: "去世", pinyin: "qù shì", khmer: "ស្លាប់; បាត់ពីលោក" },
    { word: "圈", pinyin: "quān", khmer: "រង្វង់; ស្រទាប់; រង្វិលជុំ" },
    { word: "全面", pinyin: "quán miàn", khmer: "ពេញលេញ; ទាំងស្រុង; ជាប្រកបដោយគ្រប់ទិស" },
    { word: "权利", pinyin: "quán lì", khmer: "សិទ្ធិ; អំណាច" },
    { word: "权力", pinyin: "quán lì", khmer: "អំណាច; អាជ្ញាធរ" },
    { word: "劝", pinyin: "quàn", khmer: "ណែនាំ; ព្យាយាមប្រាប់ឲ្យធ្វើ; ឧបត្ថម្ភ" },
    { word: "缺乏", pinyin: "quē fá", khmer: "ខ្វះខាត; មិនគ្រប់គ្រាន់" },
    { word: "确定", pinyin: "què dìng", khmer: "ធ្វើឲ្យប្រាកដ; បញ្ជាក់; ប្រាកដ" },
    { word: "确认", pinyin: "què rèn", khmer: "បញ្ជាក់ឡើងវិញ; ធ្វើឲ្យប្រាកដ" },
    { word: "群", pinyin: "qún", khmer: "ក្រុម; ពពួក; ប៉ុន្តែត្រូវប្រើជាសព្ទប្រើប្រាស់" },
    { word: "燃烧", pinyin: "rán shāo", khmer: "ដុតឲ្យឆេះ; ការដុត; ការរលកភ្លើង" },
    { word: "绕", pinyin: "rào", khmer: "រុំ; វង់ជុំ; ធ្វើជុំវិញ; ឆ្ពោះជុំវិញ" },
    { word: "热爱", pinyin: "rè ài", khmer: "ស្រលាញ់ខ្លាំង; មានចិត្តស្រឡាញ់ជាទីបំផុត" },
    { word: "热烈", pinyin: "rè liè", khmer: "ស្វាគមន៍ដោយក្ដីរំភើប; ក្តៅគគុក" },
    { word: "热心", pinyin: "rè xīn", khmer: "ចិត្តស្ម័គ្រ; ក្តីស្រឡាញ់; ក្តីព្យាយាម" },
    { word: "人才", pinyin: "rén cái", khmer: "មនុស្សមានទេពកោសល្យ; ឧកញ៉ា; មនុស្សល្អមានសមត្ថភាព" },
    { word: "人口", pinyin: "rén kǒu", khmer: "ប្រជាជន; ចំនួនប្រជាជន" },
    { word: "人类", pinyin: "rén lèi", khmer: "មនុស្សជាតិ" },
    { word: "人民币", pinyin: "rén mín bì", khmer: "រូបិយប័ណ្ណរបស់ប្រជាជនចិន; យួនចិន" },
    { word: "人生", pinyin: "rén shēng", khmer: "ជីវិតមនុស្ស" },
    { word: "人事", pinyin: "rén shì", khmer: "ធនធានមនុស្ស; បុគ្គលិក; ការកាត់បន្ថយ/ប្ដូរបុគ្គលិក" },
    { word: "人物", pinyin: "rén wù", khmer: "តួអង្គ; មនុស្សសំខាន់ៗ" },
    { word: "人员", pinyin: "rén yuán", khmer: "បុគ្គលិក; អ្នកបំពេញការងារ" },
    { word: "忍不住", pinyin: "rěn bu zhù", khmer: "មិនអាចទប់បានទេ; មិនអាចពង្រឹងចិត្តបានទេ" },
    { word: "日常", pinyin: "rì cháng", khmer: "ប្រចាំថ្ងៃ; រឿយៗ" },
    { word: "日程", pinyin: "rì chéng", khmer: "កាលវិភាគ; បញ្ជីការងារ" },
    { word: "日历", pinyin: "rì lì", khmer: "ប្រតិទិន" },
    { word: "日期", pinyin: "rì qī", khmer: "កាលបរិច្ឆេទ" },
    { word: "日用品", pinyin: "rì yòng pǐn", khmer: "វត្ថុប្រើប្រាស់ប្រចាំថ្ងៃ" },
    { word: "日子", pinyin: "rì zi", khmer: "ថ្ងៃ; ជីវិតប្រចាំថ្ងៃ" },
    { word: "如何", pinyin: "rú hé", khmer: "យ៉ាងដូចម្តេច; ដោយរបៀបណា" },
    { word: "如今", pinyin: "rú jīn", khmer: "សព្វថ្ងៃនេះ; បច្ចុប្បន្ននេះ" },
    { word: "软", pinyin: "ruǎn", khmer: "ទន់; ទន់ភ្លន់" },
    { word: "软件", pinyin: "ruǎn jiàn", khmer: "កម្មវិធីកុំព្យូទ័រ; សូហ្វវែ" },
    { word: "弱", pinyin: "ruò", khmer: "ខ្សោយ; ទន់ខ្សោយ" },
    { word: "洒", pinyin: "sǎ", khmer: "ចម្រាស់; បញ្ចេញទឹក; ស្រកទឹក" },
    { word: "嗓子", pinyin: "sǎng zi", khmer: "បំពង់ក; សំឡេង" },
    { word: "色彩", pinyin: "sè cǎi", khmer: "ពណ៌; លក្ខណៈពិសេស" },
    { word: "杀", pinyin: "shā", khmer: "សម្លាប់; កាប់; ធ្វើអោយបាត់បង់" },
    { word: "沙漠", pinyin: "shā mò", khmer: "វាលស្វាយ; ទីភ្នាក់ងារ" },
    { word: "沙滩", pinyin: "shā tān", khmer: "ឆ្នេរសមុទ្រ; វាលខ្សាច់" },
    { word: "傻", pinyin: "shǎ", khmer: "ឆ្កួត; ឈ្លោះៗ" },
    { word: "晒", pinyin: "shài", khmer: "ដាក់ទៅក្រោមថ្ងៃ; អះអាង (ប្រើសម្រាប់ឯកសារ/រូបថត)" },
    { word: "删除", pinyin: "shān chú", khmer: "លុបចេញ" },
    { word: "闪电", pinyin: "shǎn diàn", khmer: "ខ្យល់រន្ទះ; ភ្លើងរន្ទះ" },
    { word: "善良", pinyin: "shàn liáng", khmer: "ចិត្តល្អ; មនុស្សចិត្តសប្បុរស" },
    { word: "善于", pinyin: "shàn yú", khmer: "ឯកទេសក្នុងការ...; មានសមត្ថភាពក្នុងការ..." },
    { word: "扇子", pinyin: "shàn zi", khmer: "ព្រាលខ្យល់; អង្គុយខ្យល់" },
    { word: "伤害", pinyin: "shāng hài", khmer: "បង្កការឈឺចាប់; បង្កគ្រោះថ្នាក់" },
    { word: "商品", pinyin: "shāng pǐn", khmer: "ទំនិញ; ផលិតផល" },
    { word: "商务", pinyin: "shāng wù", khmer: "អាជីវកម្ម; ការជួញដូរ" },
    { word: "商业", pinyin: "shāng yè", khmer: "ពាណិជ្ជកម្ម; ឧស្សាហកម្មជួញដូរ" },
    { word: "上当", pinyin: "shàng dàng", khmer: "ជឿគេបោក; ត្រូវគេលោក; ត្រូវបន្លំ" },
    { word: "蛇", pinyin: "shé", khmer: "ពស់" },
    { word: "舍不得", pinyin: "shě bu de", khmer: "អាណិតអាសូរ; មិនចង់បោះបង់; ខ្មាស់ចិត្តក្នុងការបិទបាំង" },
    { word: "射击", pinyin: "shè jī", khmer: "បាញ់កាំភ្លើង; បាញ់" },
    { word: "摄影", pinyin: "shè yǐng", khmer: "ថតរូប; សកម្មភាពថត" },
    { word: "设备", pinyin: "shè bèi", khmer: "ឧបករណ៍; ឧបករណ៍បំរើ" },
    { word: "设计", pinyin: "shè jì", khmer: "រចនា; គម្រោងរចនា; អភិវឌ្ឍន៍គំនិត" },
    { word: "设施", pinyin: "shè shī", khmer: "បរិក្ខារ; ស្ថាបត្យកម្ម; ឧបករណ៍" },
    { word: "伸", pinyin: "shēn", khmer: "ដាក់ទៅខាងមុខ; លាតសន្ធឹង" },
    { word: "深刻", pinyin: "shēn kè", khmer: "ជ្រៅជ្រះ; យ៉ាងជ្រៅ" },
    { word: "身材", pinyin: "shēn cái", khmer: "រូបរាង; ទម្ងន់ និងកម្ពស់" },
    { word: "身份", pinyin: "shēn fèn", khmer: "អត្តសញ្ញាណ; មុខងារ; តួនាទី" },
    { word: "神话", pinyin: "shén huà", khmer: "រឿងព្រេងនិទាន; រឿងព្រេងបុរាណ" },
    { word: "神秘", pinyin: "shén mì", khmer: "អាថ៌កំបាំង; លាក់លៀម; អាថ៌កំបាំងសំងាត់" },
    { word: "升", pinyin: "shēng", khmer: "ឡើង; ផ្លាស់ទៅកាន់ជាន់ខ្ពស់; លីត្រ" },
    { word: "声调", pinyin: "shēng diào", khmer: "សូរសម័យ; សូរស្នាដៃ; សម្លេង" },
    { word: "生产", pinyin: "shēng chǎn", khmer: "ផលិត; កំណើត; បង្កើត" },
    { word: "生动", pinyin: "shēng dòng", khmer: "រស់រវើក; ច្បាស់លាស់" },
    { word: "生长", pinyin: "shēng zhǎng", khmer: "លូតលាស់; ធំធាត់ឡើង" },
    { word: "绳子", pinyin: "shéng zi", khmer: "ខ្សែ; ខ្សែរទំាងខ្សែរចង" },
    { word: "省略", pinyin: "shěng lüè", khmer: "លែងបញ្ជាក់; កាត់បន្ថយ; បន្លះ" },
    { word: "胜利", pinyin: "shèng lì", khmer: "ជ័យជម្នះ" },
    { word: "失眠", pinyin: "shī mián", khmer: "មិនអាចដេកបាន; ជម្ងឺអត់ដេក" },
    { word: "失去", pinyin: "shī qù", khmer: "បាត់បង់; ខាតបង់" },
    { word: "失业", pinyin: "shī yè", khmer: "គ្មានការងារ; ត្រូវបោះចោលពីការងារ" },
    { word: "湿润", pinyin: "shī rùn", khmer: "សើម; សើមសាច់" },
    { word: "狮子", pinyin: "shī zi", khmer: "សឹង្ហៈ; ខ្លាព្រៃ" },
    { word: "诗", pinyin: "shī", khmer: "កំណាព្យ; កំណាព្យសិល្បៈ" },
    { word: "实话", pinyin: "shí huà", khmer: "ពាក្យពិត; សេចក្ដីពិត" },
    { word: "实践", pinyin: "shí jiàn", khmer: "អនុវត្ត; ធ្វើជាការពិត" },
    { word: "实习", pinyin: "shí xí", khmer: "ហាត់ការជាក់ស្តែង; សិក្សាអនុវត្ត" },
    { word: "实现", pinyin: "shí xiàn", khmer: "ធ្វើឲ្យប្រសើរ; ធ្វើឲ្យខ្លាំងឡើង; អនុវត្ត" },
    { word: "实验", pinyin: "shí yàn", khmer: "សាកល្បង; ការប្រឡងសាកល្បង" },
    { word: "实用", pinyin: "shí yòng", khmer: "អាចប្រើបានជាក់ស្តែង; មានប្រយោជន៍" },
    { word: "时差", pinyin: "shí chā", khmer: "ការប្រែប្រួលពេលវេលា; ខុសគ្នារវាងម៉ោង" },
    { word: "时代", pinyin: "shí dài", khmer: "សម័យ; ជំនាន់" },
    { word: "时刻", pinyin: "shí kè", khmer: "ពេលវេលា; រយៈពេលខ្លី" },
    { word: "时髦", pinyin: "shí máo", khmer: "ទាន់សម័យ; ម៉ូដថ្មី" },
    { word: "时期", pinyin: "shí qī", khmer: "រយៈពេល; អំឡុងពេល" },
    { word: "时尚", pinyin: "shí shàng", khmer: "ម៉ូដ; ស្ទីលទំនើប" },
    { word: "石头", pinyin: "shí tou", khmer: "ថ្ម" },
    { word: "食物", pinyin: "shí wù", khmer: "អាហារ; ម្ហូប" },
    { word: "使劲儿", pinyin: "shǐ jìn r", khmer: "ប្រើសាខទាំងអស់; អភិវឌ្ឍន៍" },
    { word: "始终", pinyin: "shǐ zhōng", khmer: "ចាប់ពីដើមដល់ចុង; ទាំងអស់" },
    { word: "事实", pinyin: "shì shí", khmer: "ការពិត; ទំនងទៅ" },
    { word: "事物", pinyin: "shì wù", khmer: "អ្វីដែលធ្វើដំណើរ; បញ្ហា" },
    { word: "事先", pinyin: "shì xiān", khmer: "មុនពេល; ពេលដែលវាផុត" },
    { word: "似的", pinyin: "shì de", khmer: "ទៅលើ; ទៅលើវា" },
    { word: "士兵", pinyin: "shì bīng", khmer: "សេះមនុស្សពាណិជ្ជកម្ម" },
    { word: "市场", pinyin: "shì chǎng", khmer: "ផ្សារ; ពាណិជ្ជកម្ម; ផ្សារលក់" },
    { word: "试卷", pinyin: "shì juàn", khmer: "ប្រើពិនិត្យ; ស្នាក់ការពិនិត្យ" },
    { word: "收获", pinyin: "shōu huò", khmer: "ទទួលផល; សម្រេចជោគជ័យ" },
    { word: "收据", pinyin: "shōu jù", khmer: "វិក្កយបត្រ; ចំណាំ" },
    { word: "手工", pinyin: "shǒu gōng", khmer: "ការងារដោយដៃ" },
    { word: "手术", pinyin: "shǒu shù", khmer: "ការវះកាត់" },
    { word: "手套", pinyin: "shǒu tào", khmer: "ស្រាប់ដៃ" },
    { word: "手续", pinyin: "shǒu xù", khmer: "លទ្ធផល; អនុម័ត" },
    { word: "手指", pinyin: "shǒu zhǐ", khmer: "អាគុយ" },
    { word: "首", pinyin: "shǒu", khmer: "ប្រជាជនសូមគាំទ្រ" },
    { word: "受伤", pinyin: "shòu shāng", khmer: "ការប្រែប្រួល; ធ្វើឲ្យខូច" },
     { word: "寿命", pinyin: "shòu mìng", khmer: "អាយុ; ពេលវេលាជីវិត" },
    { word: "书架", pinyin: "shū jià", khmer: "ស្លាបីសៀវភៅ" },
    { word: "梳子", pinyin: "shū zi", khmer: "កាំបិត" },
    { word: "舒适", pinyin: "shū shì", khmer: "សំបុត្រអនុស្សាវរីយ៍; ស្រួល" },
    { word: "蔬菜", pinyin: "shū cài", khmer: "បន្លែ" },
    { word: "输入", pinyin: "shū rù", khmer: "បញ្ចូល" },
    { word: "熟练", pinyin: "shú liàn", khmer: "មានជំនាញ; មនុស្សដែលមានជំនាញ" },
    { word: "属于", pinyin: "shǔ yú", khmer: "ស្ថិតក្នុងក្រុម; 属于" },
    { word: "数", pinyin: "shǔ", khmer: "ចំនួន" },
    { word: "鼠标", pinyin: "shǔ biāo", khmer: "កណ្តុរ" },
    { word: "数据", pinyin: "shù jù", khmer: "ទិន្នន័យ; ចំនួន" },
    { word: "数码", pinyin: "shù mǎ", khmer: "លេខ; កូដ" },
    { word: "摔倒", pinyin: "shuāi dǎo", khmer: "ធ្លាក់; បែកសក់" },
    { word: "甩", pinyin: "shuǎi", khmer: "បោះចោល" },
    { word: "双方", pinyin: "shuāng fāng", khmer: "ពីរបុរស" },
    { word: "税", pinyin: "shuì", khmer: "ពន្ធ" },
    { word: "说不定", pinyin: "shuō bu dìng", khmer: "មិនអាចនិយាយថាបាន" },
    { word: "说服", pinyin: "shuō fú", khmer: "ព្យាយាមអោយជឿ" },
    { word: "丝绸", pinyin: "sī chóu", khmer: "សក់ដាក់" },
    { word: "丝毫", pinyin: "sī háo", khmer: "តិចបំផុត" },
    { word: "思考", pinyin: "sī kǎo", khmer: "គិតច្រើន" },
    { word: "思想", pinyin: "sī xiǎng", khmer: "គំនិត" },
    { word: "撕", pinyin: "sī", khmer: "កិន; ទូល" },
    { word: "私人", pinyin: "sī rén", khmer: "ផ្ទាល់ខ្លួន" },
    { word: "似乎", pinyin: "sì hū", khmer: "វាមើលទៅដូច" },
    { word: "搜索", pinyin: "sōu suǒ", khmer: "ស្វែងរក" },
    { word: "宿舍", pinyin: "sù shè", khmer: "បន្ទប់ស្នាក់នៅ" },
    { word: "随身", pinyin: "suí shēn", khmer: "តាមខ្លួន" },
    { word: "随时", pinyin: "suí shí", khmer: "គ្រប់ពេល" },
    { word: "随手", pinyin: "suí shǒu", khmer: "ដោយសមត្ថភាព" },
    { word: "碎", pinyin: "suì", khmer: "បែក; ខ្ទិះ" },
    { word: "损失", pinyin: "sǔn shī", khmer: "បាត់បង់; ភាពខូចខារ" },
    { word: "缩短", pinyin: "suō duǎn", khmer: "កាត់បន្ថយ" },
    { word: "所", pinyin: "suǒ", khmer: "កន្លែង; ទីតាំង; បន្ទាប់បន្សំ" },
    { word: "锁", pinyin: "suǒ", khmer: "ចាក់គ្រាប់សោ; បិទ" },
    { word: "台阶", pinyin: "tái jiē", khmer: "ជាន់; ជើងជាន់" },
    { word: "太极拳", pinyin: "tài jí quán", khmer: "ក្បាច់បរិស្ថានតៃជី" },
    { word: "太太", pinyin: "tài tai", khmer: "គ្រួសារប្រុស; ប៉ត៉ា; ព្រំជីវិត" },
    { word: "谈判", pinyin: "tán pàn", khmer: "ចរចា; សន្ទនាសំរាប់ការទូទាត់" },
    { word: "坦率", pinyin: "tǎn shuài", khmer: "ត្រូវការចាត់ចែងដោយស្រួល" },
    { word: "烫", pinyin: "tàng", khmer: "ក្តៅ; ញ៉ាំឈុត" },
    { word: "桃", pinyin: "táo", khmer: "ផ្លែពោត" },
    { word: "淘气", pinyin: "táo qì", khmer: "ទំលាក់; ខុសសីល" },
    { word: "逃", pinyin: "táo", khmer: "ត逃; លាយតាម" },
    { word: "逃避", pinyin: "táo bì", khmer: "ចាកចេញពីភាពស្មុគស្មាញ" },
    { word: "讨价还价", pinyin: "tǎo jià huán jià", khmer: "ចរចាលើតម្លៃ" },
    { word: "套", pinyin: "tào", khmer: "គ្រឿងមួយដដែល" },
    { word: "特色", pinyin: "tè sè", khmer: "លក្ខណៈពិសេស; ភាពផ្តាច់មុខ" },
    { word: "特殊", pinyin: "tè shū", khmer: "ពិសេស; ប្រសើរជាងធម្មតា" },
    { word: "特征", pinyin: "tè zhēng", khmer: "លក្ខណៈពិសេស" },
    { word: "疼爱", pinyin: "téng ài", khmer: "ស្រឡាញ់យ៉ាងជ្រាលជ្រៅ" },
    { word: "提倡", pinyin: "tí chàng", khmer: "ផ្សព្វផ្សាយ; សម្រង់ចេញ" },
    { word: "提纲", pinyin: "tí gāng", khmer: "បញ្ជី; ក្រមព្រៀង" },
     { word: "提问", pinyin: "tí wèn", khmer: "សំណួរ; សួរ" },
    { word: "题目", pinyin: "tí mù", khmer: "ប្រធានបទ; មុខវិជ្ជា" },
    { word: "体会", pinyin: "tǐ huì", khmer: "យល់ដឹង (តាមការរៀន ឬបទពិសោធន៍)" },
    { word: "体贴", pinyin: "tǐ tiē", khmer: "ពិចារណាអំពីការទាមទាររបស់អ្នកផ្សេង" },
    { word: "体现", pinyin: "tǐ xiàn", khmer: "បង្ហាញ; បញ្ជាក់" },
    { word: "体验", pinyin: "tǐ yàn", khmer: "បទពិសោធន៍ (សម្រាប់ខ្លួនឯង)" },
    { word: "天空", pinyin: "tiān kōng", khmer: "មេឃ" },
    { word: "天真", pinyin: "tiān zhēn", khmer: "បឋម; គ្មានបទពិសោធន៍" },
    { word: "调皮", pinyin: "tiáo pí", khmer: "ចូលចិត្តធ្វើឲ្យមានការលំបាក; យ៉ាងស៊ីសង" },
    { word: "调整", pinyin: "tiáo zhěng", khmer: "ការកែតម្រូវ; ការកំណត់ឡើងវិញ" },
    { word: "挑战", pinyin: "tiǎo zhàn", khmer: "ការប្រកួតប្រជែង" },
    { word: "通常", pinyin: "tōng cháng", khmer: "ធម្មតា; ជាៈម៉ាស៊ីន" },
    { word: "统一", pinyin: "tǒng yī", khmer: "រួមគ្នា; រៀបចំឡើងវិញ" },
    { word: "痛苦", pinyin: "tòng kǔ", khmer: "ការឈឺចាប់; ឈឺចាប់" },
    { word: "痛快", pinyin: "tòng kuài", khmer: "សប្បាយរីករាយ" },
    { word: "偷", pinyin: "tōu", khmer: "លួច; បន្លំ" },
    { word: "投入", pinyin: "tóu rù", khmer: "ចូលរួម; វិនិយោគ" },
    { word: "投资", pinyin: "tóu zī", khmer: "ការវិនិយោគ" },
    { word: "透明", pinyin: "tòu míng", khmer: "ពន្លឺរំលេច; មានភាពច្បាស់លាស់" },
    { word: "突出", pinyin: "tū chū", khmer: "ផ្ដោតលើ; សម្គាល់អំពី" },
    { word: "土地", pinyin: "tǔ dì", khmer: "ដី; ស្រុក" },
    { word: "土豆", pinyin: "tǔ dòu", khmer: "ប៉តាតូ" },
    { word: "兔子", pinyin: "tù zi", khmer: "ពងទា" },
    { word: "吐", pinyin: "tù", khmer: "ពង្រាំ" },
    { word: "团", pinyin: "tuán", khmer: "ក្រុម; សង្គម" },
    { word: "推辞", pinyin: "tuī cí", khmer: "បដិសេធ; បដិសេធសំណើ" },
    { word: "推广", pinyin: "tuī guǎng", khmer: "ផ្សព្វផ្សាយ; ការផ្សព្វផ្សាយ" },
    { word: "推荐", pinyin: "tuī jiàn", khmer: "ផ្តល់អនុសាសន៍" },
    { word: "退", pinyin: "tuì", khmer: "ក្រោយ; បដិសេធ" },
    { word: "退步", pinyin: "tuì bù", khmer: "ការចុះក្រោយ" },
    { word: "退休", pinyin: "tuì xiū", khmer: "ការចូលជីវិតវិស្សមកាល" },
    { word: "歪", pinyin: "wāi", khmer: "មិនត្រឹមត្រូវ; អាក្រក់" },
    { word: "外公", pinyin: "wài gōng", khmer: "ប៉ោនម្ដាយ; បុព្វបុត្រប្រយោល" },
    { word: "外交", pinyin: "wài jiāo", khmer: "ការទំនាក់ទំនងពាណិជ្ជកម្មក្រៅប្រទេស" },
    { word: "完美", pinyin: "wán měi", khmer: "ល្អឥតខ្ចោះ" },
    { word: "完善", pinyin: "wán shàn", khmer: "ពេញលេញ; ធ្វើឲ្យពេញលេញ" },
    { word: "完整", pinyin: "wán zhěng", khmer: "ពេញលេញ; ទាំងស្រុង" },
    { word: "玩具", pinyin: "wán jù", khmer: "សម្ភារៈលេង" },
    { word: "万一", pinyin: "wàn yī", khmer: "ប្រសិនបើមាន; ប្រសិនបើខុសគ្នា" },
    { word: "王子", pinyin: "wáng zǐ", khmer: "ព្រះរាជបុត្រា; ព្រះបាទ" },
    { word: "往返", pinyin: "wǎng fǎn", khmer: "ទៅ និងត្រឡប់មកវិញ" },
    { word: "网络", pinyin: "wǎng luò", khmer: "បណ្ដាញ; យន្តការទំនាក់ទំនង (ក្នុងវិស័យកុំព្យូទ័រ)" },
    { word: "危害", pinyin: "wēi hài", khmer: "គ្រោះថ្នាក់; បង្កឲ្យមានគ្រោះថ្នាក់" },
    { word: "威胁", pinyin: "wēi xié", khmer: "ការគំរាមគំរាស់" },
    { word: "微笑", pinyin: "wēi xiào", khmer: "ការញញឹម" },
    { word: "唯一", pinyin: "wéi yī", khmer: "តែមួយ; មានតែគត់" },
    { word: "围巾", pinyin: "wéi jīn", khmer: "កណ្ដាលកប្បាស; ឈុតក្បាល" },
    { word: "围绕", pinyin: "wéi rào", khmer: "បង្វិលជុំវិញ; អំពើរជុំវិញ" },
    { word: "维修", pinyin: "wéi xiū", khmer: "ការថែទាំ; សម្រួលឧបករណ៍" },
    { word: "违反", pinyin: "wéi fǎn", khmer: "ឈ្លោះបរ; លើកលែងច្បាប់" },
    { word: "伟大", pinyin: "wěi dà", khmer: "ធំនិងល្អ; សម្បូរតាមរយៈ" },
    { word: "委屈", pinyin: "wěi qū", khmer: "មានអារម្មណ៍ឈឺចាប់; មានសេចក្តីទុក្ខ" },
    { word: "尾巴", pinyin: "wěi ba", khmer: "បង្គោល" },
    { word: "位于", pinyin: "wèi yú", khmer: "ស្ថិតនៅ; មានទីតាំងនៅ" },
    { word: "位置", pinyin: "wèi zhi", khmer: "ទីតាំង; មុខតំណែង" },
    { word: "未必", pinyin: "wèi bì", khmer: "មិនប្រាកដទេ; មិនអាចនិយាយបាន" },
    { word: "未来", pinyin: "wèi lái", khmer: "អនាគត" },
    { word: "胃", pinyin: "wèi", khmer: "ពោះ" },
    { word: "胃口", pinyin: "wèi kǒu", khmer: "ការចូលចិត្តក្នុងការថែរក្សាពោះ" },
    { word: "温暖", pinyin: "wēn nuǎn", khmer: "ក្តៅទន់; យ៉ាងផុសស្រទាប់" },
    { word: "温柔", pinyin: "wēn róu", khmer: "ទន់ត្រង់និងទន់ស្រួល" },
    { word: "文件", pinyin: "wén jiàn", khmer: "ឯកសារ" },
    { word: "文具", pinyin: "wén jù", khmer: "ឧបករណ៍សិក្សា (សញ្ញាដូចជា ខ្មែរកាត់ ខ្មែរស្មាល)"},
    { word: "文明", pinyin: "wén míng", khmer: "សមត្ថភាព; គម្របមនុស្សសង្គម" },
    { word: "文学", pinyin: "wén xué", khmer: "អក្សរសិល្បៈ; សិល្បៈអក្សរ" },
    { word: "文字", pinyin: "wén zì", khmer: "អក្សរ; ស្ទីលសរសេរ" },
    { word: "闻", pinyin: "wén", khmer: "ស្តាប់; ការជឿន; ប្រជាជនពេញនិយម" },
    { word: "吻", pinyin: "wěn", khmer: "ជាស៊ីសរ" },
    { word: "稳定", pinyin: "wěn dìng", khmer: "ស្ថិតស្ថេរ; ស្ថិតជាស្ថិត" },
    { word: "问候", pinyin: "wèn hòu", khmer: "ផ្ញើសេចក្តីថ្លែងពរ" },
    { word: "卧室", pinyin: "wò shì", khmer: "បន្ទប់គេង" },
    { word: "握手", pinyin: "wò shǒu", khmer: "ចាប់ដៃ" },
    { word: "屋子", pinyin: "wū zi", khmer: "ផ្ទះ; បន្ទប់" },
    { word: "无奈", pinyin: "wú nài", khmer: "គ្មានជម្រើស; មិនអាចជួយបាន" },
    { word: "无数", pinyin: "wú shù", khmer: "មិនអាចគណនា; អតិផរណា" },
    { word: "无所谓", pinyin: "wú suǒ wèi", khmer: "មិនមានអ្វីដូចជាគ្រាប់កែប" },
    { word: "武术", pinyin: "wǔ shù", khmer: "កីឡាការពារខ្លួន; បច្ចេកទេសទាំមុខ" },
    { word: "勿", pinyin: "wù", khmer: "កុំ" },
    { word: "物理", pinyin: "wù lǐ", khmer: "មេធាវីវិទ្យា" },
    { word: "物质", pinyin: "wù zhì", khmer: "វត្ថុធាតុ; សម្ភារៈ" },
    { word: "雾", pinyin: "wù", khmer: "ពពក; មុត" },
    { word: "吸取", pinyin: "xī qǔ", khmer: "ទទួលយក; ប្រមូល" },
    { word: "吸收", pinyin: "xī shōu", khmer: "ទទួលយក; អង្កេត" },
    { word: "戏剧", pinyin: "xì jù", khmer: "រឿងល្ខោន" },
    { word: "系", pinyin: "xì", khmer: "ទំនាក់ទំនង; ទាក់ទង" },
    { word: "系统", pinyin: "xì tǒng", khmer: "ប្រព័ន្ធ" },
    { word: "细节", pinyin: "xì jié", khmer: "ព័ត៌មានលម្អិត" },
    { word: "瞎", pinyin: "xiā", khmer: "ពឹត; ស្រមោល" },
    { word: "下载", pinyin: "xià zǎi", khmer: "ទាញយក" },
    { word: "吓", pinyin: "xià", khmer: "ភ័យបារម្ភ; គ្រោះថ្នាក់" },
    { word: "夏令营", pinyin: "xià lìng yíng", khmer: "បៀវត្សកំសាន្តរដូវក្តៅ" },
    { word: "鲜艳", pinyin: "xiān yàn", khmer: "ពណ៌ស្រស់" },
    { word: "显得", pinyin: "xiǎn de", khmer: "បង្ហាញ; មានការបង្ហាញ" },
    { word: "显然", pinyin: "xiǎn rán", khmer: "ភាសាពិតប្រាកដ" },
    { word: "显示", pinyin: "xiǎn shì", khmer: "បង្ហាញ" },
    { word: "县", pinyin: "xiàn", khmer: "ស្រុក; តំបន់គ្រួសារ" },
    { word: "现代", pinyin: "xiàn dài", khmer: "សម័យទំនើប; សម័យទំនើប" },
    { word: "现实", pinyin: "xiàn shí", khmer: "ជាតិនិយម; ពិតប្រាកដ" },
    { word: "现象", pinyin: "xiàn xiàng", khmer: "លក្ខណៈ; ភាពរំលេច" },
    { word: "限制", pinyin: "xiàn zhì", khmer: "កំណត់; ការពិគ្រោះ" },
    { word: "相处", pinyin: "xiāng chǔ", khmer: "រស់នៅជាមួយគ្នា" },
    { word: "相当", pinyin: "xiāng dāng", khmer: "សមស្រប; ប្រៀបផ្គូរផ្គង" },
    { word: "相对", pinyin: "xiāng duì", khmer: "ប្រហែល; ការតវ៉ា" },
    { word: "相关", pinyin: "xiāng guān", khmer: "ទាក់ទងនឹងគ្នា" },
    { word: "相似", pinyin: "xiāng sì", khmer: "ស្រដៀងគ្នា" },
    { word: "香肠", pinyin: "xiāng cháng", khmer: "សាច់នំនាំ" },
    { word: "享受", pinyin: "xiǎng shòu", khmer: "រីករាយ; ប្រារព្ធ" },
    { word: "想念", pinyin: "xiǎng niàn", khmer: "គិតអំពី; ស្រលាញ់" },
    { word: "想象", pinyin: "xiǎng xiàng", khmer: "តំណាង; ចិត្ត" },
    { word: "象棋", pinyin: "xiàng qí", khmer: "ឆ្នោតចិន" },
    { word: "象征", pinyin: "xiàng zhēng", khmer: "សញ្ញា; សំរាប់ប្រើ" },
    { word: "项", pinyin: "xiàng", khmer: "របស់; ប្រភេទ" },
    { word: "项链", pinyin: "xiàng liàn", khmer: "កាលវ៉ា" },
    { word: "项目", pinyin: "xiàng mù", khmer: "កម្មវិធី; វិធីសាស្ត្រសាកល" },
    { word: "消费", pinyin: "xiāo fèi", khmer: "បរិភោគ" },
    { word: "消化", pinyin: "xiāo huà", khmer: "រំលាយ" },
    { word: "消极", pinyin: "xiāo jí", khmer: "អវិជ្ជមាន; មិនប្រើប្រាស់" },
    { word: "消失", pinyin: "xiāo shī", khmer: "បាត់ទៅ" },
    { word: "销售", pinyin: "xiāo shòu", khmer: "លក់; ពាណិជ្ជកម្ម" },
    { word: "小麦", pinyin: "xiǎo mài", khmer: "ដូនហាង" },
    { word: "小气", pinyin: "xiǎo qi", khmer: "ប្រហែលស្ថិតឯកបូណ៍" },
    { word: "孝顺", pinyin: "xiào shun", khmer: "ចេះកោតស្លាប់ត្រង់មាតិកា" },
    { word: "效率", pinyin: "xiào lv", khmer: "ប្រសិទ្ធភាព" },
    { word: "歇", pinyin: "xiē", khmer: "សម្រាក; ការអត់ធ្មត់" },
    { word: "斜", pinyin: "xié", khmer: "លាបតាម; បត់ដាក់" },
    { word: "写作", pinyin: "xiě zuò", khmer: "ការសរសេរ" },
    { word: "心理", pinyin: "xīn lǐ", khmer: "ចិត្តវិទ្យា" },
    { word: "心脏", pinyin: "xīn zàng", khmer: "បេះដូង" },
    { word: "欣赏", pinyin: "xīn shǎng", khmer: "ស្នាដៃ; សេចក្តីសរសើរ" },
    { word: "信号", pinyin: "xìn hào", khmer: "សញ្ញា" },
    { word: "信任", pinyin: "xìn rèn", khmer: "ទុកចិត្ត" },
    { word: "形成", pinyin: "xíng chéng", khmer: "បង្កើតកំណត់ទំនាក់ទំនង" },
    { word: "形容", pinyin: "xíng róng", khmer: "បរិយាយ" },
    { word: "形势", pinyin: "xíng shì", khmer: "ស្ថានភាព" },
    { word: "形式", pinyin: "xíng shì", khmer: "ទម្រង់" },
    { word: "形象", pinyin: "xíng xiàng", khmer: "រូបភាព" },
    { word: "形状", pinyin: "xíng zhuàng", khmer: "ទម្រង់; រូបរាង" },
    { word: "行动", pinyin: "xíng dòng", khmer: "សកម្មភាព; ធ្វើការ" },
    { word: "行人", pinyin: "xíng rén", khmer: "អ្នកដើរ; អ្នកដំណើរ" },
    { word: "行为", pinyin: "xíng wéi", khmer: "អាកប្បកិរិយា; ចរិត" },
    { word: "幸亏", pinyin: "xìng kuī", khmer: "សំណាងល្អ; កុំតែ" },
    { word: "幸运", pinyin: "xìng yùn", khmer: "សំណាង; បរិសុទ្ធ" },
    { word: "性质", pinyin: "xìng zhì", khmer: "លក្ខណៈ; ភាព" },
    { word: "兄弟", pinyin: "xiōng dì", khmer: "បងប្អូន; បងប្អូនប្រុស" },
    { word: "胸", pinyin: "xiōng", khmer: "ទ្រុងចិត្ត; ថេរ" },
    { word: "休闲", pinyin: "xiū xián", khmer: "សម្រាក; ការសម្រាក" },
    { word: "修改", pinyin: "xiū gǎi", khmer: "កែប្រែ; កែសម្រួល" },
    { word: "虚心", pinyin: "xū xīn", khmer: "អត់ភ័យនិងរាប់អាន" },
    { word: "叙述", pinyin: "xù shù", khmer: "រាយការណ៍; ការលើកឡើង" },
    { word: "宣布", pinyin: "xuān bù", khmer: "ប្រកាស; បញ្ជាក់" },
    { word: "宣传", pinyin: "xuān chuán", khmer: "ផ្សព្វផ្សាយ; សារព័ត៌មាន" },
    { word: "学历", pinyin: "xué lì", khmer: "ការអប់រំនិងការអភិវឌ្ឍន៍" },
    { word: "学术", pinyin: "xué shù", khmer: "វិទ្យាសាស្ត្រ; អត្ថាធិប្បាយ" },
    { word: "学问", pinyin: "xué wèn", khmer: "ចំណេះដឹង; ការសិក្សា" },
    { word: "血", pinyin: "xuè", khmer: "ឈាម" },
    { word: "寻找", pinyin: "xún zhǎo", khmer: "ស្វែងរក" },
    { word: "询问", pinyin: "xún wèn", khmer: "សួរ; សាកសួរ" },
    { word: "训练", pinyin: "xùn liàn", khmer: "ហ្វឹកហាត់; ការបង្ហាត់" },
    { word: "迅速", pinyin: "xùn sù", khmer: "លឿន; យ៉ាងឆាប់" },
    { word: "押金", pinyin: "yā jīn", khmer: "ប្រាក់តម្រូវ; ប្រាក់ដាក់ដោ" },
    { word: "牙齿", pinyin: "yá chǐ", khmer: "ធ្មេញ" },
    { word: "严肃", pinyin: "yán sù", khmer: "យ៉ាងតឹងតាំង; មិនសប្បាយ" },
    { word: "延长", pinyin: "yán cháng", khmer: "ពង្រីក; បន្ថែម" },
    { word: "演讲", pinyin: "yǎn jiǎng", khmer: "ការអានរឿង; និយាយប្រកាស" },
    { word: "宴会", pinyin: "yàn huì", khmer: "ពិធីបរិយាយ; បរិយាយ" },
    { word: "阳台", pinyin: "yáng tái", khmer: "កន្លែងផ្អែក" },
    { word: "痒", pinyin: "yǎng", khmer: "ជាំ; មិនសុខ" },
    { word: "样式", pinyin: "yàng shì", khmer: "ប្រភេទ; ទម្រង់" },
    { word: "腰", pinyin: "yāo", khmer: "មេរៀន; ខ្ចប់" },
    { word: "摇", pinyin: "yáo", khmer: "ដើរចុះឆេះ; ឆេះទាំងមុខ" },
    { word: "咬", pinyin: "yǎo", khmer: "ញ៉ាំ; ខល" },
    { word: "要不", pinyin: "yào bù", khmer: "បើមិនដូច្នោះទេ" },
    { word: "业务", pinyin: "yè wù", khmer: "អាជីព; អាជីវកម្ម" },
    { word: "业余", pinyin: "yè yú", khmer: "ការរៀនឆ្កួត; ភាពគ្មានប្រជាជន" },
    { word: "夜", pinyin: "yè", khmer: "រាត្រី" },
    { word: "依然", pinyin: "yī rán", khmer: "ដូចដើម" },
    { word: "一辈子", pinyin: "yí bèi zi", khmer: "ជីវិតទាំងអស់" },
    { word: "一旦", pinyin: "yí dàn", khmer: "ក្នុងករណីមួយ" },
    { word: "一律", pinyin: "yí lv4", khmer: "ជាទម្រង់ស្មើគ្នា; ដូចគ្នា" },
    { word: "一再", pinyin: "yí zài", khmer: "បន្តបន្ទាប់; ជាប្រចាំ" },
    { word: "一致", pinyin: "yí zhì", khmer: "យ៉ាងសាមញ្ញ; ស្រដៀងគ្នា" },
    { word: "疑问", pinyin: "yí wèn", khmer: "សំណួរ; ការសង្កេត" },
    { word: "移动", pinyin: "yí dòng", khmer: "ចលនា; បង្រ្កាប; អាចដើរតួបាន" },
    { word: "移民", pinyin: "yí mín", khmer: "អ្នកអនិគម; អ្នកអព្យាក្រឹត" },
    { word: "遗憾", pinyin: "yí hàn", khmer: "សោកស្តាយ; សេចក្តីសោកស្តាយ" },
    { word: "乙", pinyin: "yǐ", khmer: "លំដាប់ទីពីរ; អក្សរ B ឬរ៉ូម៉ាន II" },
    { word: "以及", pinyin: "yǐ jí", khmer: "ដូចជាក៏ដូចជា; និង" },
    { word: "以来", pinyin: "yǐ lái", khmer: "តាំងពី" },
    { word: "义务", pinyin: "yì wù", khmer: "បំណង; ភារកិច្ច; ភារកិច្ចត្រូវ" },
    { word: "亿", pinyin: "yì", khmer: "រយលាន; ១០០,០០០,០០០" },
    { word: "意外", pinyin: "yì wài", khmer: "មិនរំពឹង; រឿងមិនជឿ" },
    { word: "意义", pinyin: "yì yì", khmer: "អត្ថន័យ; សារៈសំខាន់" },
    { word: "议论", pinyin: "yì lùn", khmer: "ពិភាក្សា; ការពិភាក្សា" },
    { word: "因而", pinyin: "yīn ér", khmer: "ដូច្នេះ; ដោយសារតែ" },
    { word: "因素", pinyin: "yīn sù", khmer: "ធាតុ; បំណង" },
    { word: "银", pinyin: "yín", khmer: "ប្រាក់សុទ្ធ; សំបកប្រាក់" },
    { word: "印刷", pinyin: "yìn shuā", khmer: "បោះពុម្ព; បោះពុម្ពផ្ទាល់" },
    { word: "英俊", pinyin: "yīng jùn", khmer: "គួរឱ្យស្រល់; សម្រស់" },
    { word: "英雄", pinyin: "yīng xióng", khmer: "វីរបុរស; វីរលោក" },
    { word: "营养", pinyin: "yíng yǎng", khmer: "អាហារូបត្ថម្ភ; គុណភាពអាហារ" },
    { word: "营业", pinyin: "yíng yè", khmer: "អាជីវកម្ម; ធ្វើជាប្រព័ន្ធ" },
    { word: "迎接", pinyin: "yíng jiē", khmer: "ពិភាក្សា; ទទួលការពាក់ព័ន្ធ" },
    { word: "影子", pinyin: "yǐng zi", khmer: "ប្រហែល; រូបភាពឬស្រហយភាព" },
    { word: "应付", pinyin: "yìng fu", khmer: "ដោះសោ; បង្ហោះ" },
    { word: "应用", pinyin: "yìng yòng", khmer: "ប្រើប្រាស់; ការប្រើប្រាស់" },
    { word: "硬", pinyin: "yìng", khmer: "រឹងមាំ; អាចប្រើបាន" },
    { word: "硬件", pinyin: "yìng jiàn", khmer: "ឧបករណ៍硬; ឧបករណ៍" },
    { word: "拥抱", pinyin: "yōng bào", khmer: "ពឹងពុំ; កាន់ដៃ" },
    { word: "拥挤", pinyin: "yōng jǐ", khmer: "មនុស្សរងឯកភាព; ពិរុស, ស្រួល" },
    { word: "勇气", pinyin: "yǒng qì", khmer: "សេចក្តីអំណោយ; កម្លាំង" },
    { word: "用功", pinyin: "yòng gōng", khmer: "ព្យាយាម; អន្តរាគមន៍មួយ" },
    { word: "用途", pinyin: "yòng tú", khmer: "ប្រើប្រាស់; ការប្រើប្រាស់" },
    { word: "优惠", pinyin: "yōu huì", khmer: "សេចក្តីបញ្ញើ; ពិសេស" },
    { word: "优美", pinyin: "yōu měi", khmer: "ស្អាត, ពិសេស, ស្រស់" },
    { word: "优势", pinyin: "yōu shì", khmer: "អត្ថប្រយោជន៍; ភាពល្អ" },
    { word: "悠久", pinyin: "yōu jiǔ", khmer: "មានប្រវត្តិសាស្ត្រ, បន្ថយពេលវេលា" },
    { word: "油炸", pinyin: "yóu zhá", khmer: "បាញ់ប្រេងជីន" },
    { word: "游览", pinyin: "yóu lǎn", khmer: "ធ្វើការទស្សនាកន្លែង; ទេសចរណ៍" },
    { word: "犹豫", pinyin: "yóu yù", khmer: "ការស្ទាក់ស្ទើរ; ព្រងើយ" },
    { word: "有利", pinyin: "yǒu lì", khmer: "ប្រយោជន៍; មានភាពល្អ" },
    { word: "幼儿园", pinyin: "yòu ér yuán", khmer: "សាលារក្សា; សាលារៀនកុមារ" },
    { word: "娱乐", pinyin: "yú lè", khmer: "ការកម្សាន្ត; ភាពរំភើប" },
    { word: "与其", pinyin: "yǔ qí", khmer: "ជាង; ក្រៅពី" },
    { word: "语气", pinyin: "yǔ qì", khmer: "សំឡេង; បែបយោបាយ" },
    { word: "玉米", pinyin: "yù mǐ", khmer: "ល្ហុងទ័របី; សណ្តែកបៀ" },
    { word: "预报", pinyin: "yù bào", khmer: "ការព្យាករណ៍" },
    { word: "预订", pinyin: "yù dìng", khmer: "ការកក់, ការបញ្ជាទិញ" },
    { word: "预防", pinyin: "yù fáng", khmer: "ការពារតាមរយៈការទប់ស្កាត់" },
    { word: "元旦", pinyin: "yuán dàn", khmer: "ថ្ងៃបុណ្យចូលឆ្នាំថ្មី" },
    { word: "原料", pinyin: "yuán liào", khmer: "វត្ថុធាតុដើម" },
    { word: "原则", pinyin: "yuán zé", khmer: "គោលការណ៍, អត្ថន័យ" },
    { word: "员工", pinyin: "yuán gōng", khmer: "បុគ្គលិក, បុគ្គល" },
    { word: "圆", pinyin: "yuán", khmer: "រង្វង់; ទ្រង់ទ្រាយពង្រឹង" },
    { word: "愿望", pinyin: "yuàn wàng", khmer: "បំណង, ចិត្តស្រឡាញ់" },
    { word: "乐器", pinyin: "yuè qì", khmer: "ឧបករណ៍តន្ត្រី" },
    { word: "晕", pinyin: "yūn", khmer: "មានអារម្មណ៍ស្រវាំង; ដុស" },
    { word: "运气", pinyin: "yùn qi", khmer: "សំណាង" },
    { word: "运输", pinyin: "yùn shū", khmer: "ដឹកជញ្ជូន" },
    { word: "运用", pinyin: "yùn yòng", khmer: "ប្រើប្រាស់; ការប្រើប្រាស់" },
    { word: "灾害", pinyin: "zāi hài", khmer: "គ្រោះថ្នាក់; ភាពគ្រោះ" },
    { word: "再三", pinyin: "zài sān", khmer: "លើកទឹកឡើង" },
    { word: "在乎", pinyin: "zài hu", khmer: "ការយកចិត្តទុកដាក់" },
    { word: "在于", pinyin: "zài yú", khmer: "ស្ថិតនៅក្នុង; បញ្ជាក់ពី" },
    { word: "赞成", pinyin: "zàn chéng", khmer: "យល់ព្រម" },
    { word: "赞美", pinyin: "zàn měi", khmer: "សរសើរ; សេចក្ដីសង្ឃឹម" },
    { word: "糟糕", pinyin: "zāo gāo", khmer: "អាក្រក់; ការខូចខាត" },
    { word: "造成", pinyin: "zào chéng", khmer: "បង្កើត; ធ្វើអោយមាន" },
    { word: "则", pinyin: "zé", khmer: "ទំរង់; សេចក្ដីបញ្ជា" },
    { word: "责备", pinyin: "zé bèi", khmer: "ទោស; ត្រូវបានគេបំរាម" },
    { word: "摘", pinyin: "zhāi", khmer: "យក, ជ្រើសរើស, ស្ដារពីដើម" },
    { word: "窄", pinyin: "zhǎi", khmer: "ច្រកតូច, មិនទាន់ធំ" },
    { word: "粘贴", pinyin: "zhān tiē", khmer: "ភ្ជាប់, ត្រូវ" },
    { word: "展开", pinyin: "zhǎn kāi", khmer: "ពង្រីក, ចាប់ផ្តើម" },
    { word: "展览", pinyin: "zhǎn lǎn", khmer: "ការបង្ហាញ, បង្ហាញមុខ" },
    { word: "占", pinyin: "zhàn", khmer: "យក, យកទីតាំង" },
    { word: "战争", pinyin: "zhàn zhēng", khmer: "សង្គ្រាម" },
    { word: "掌握", pinyin: "zhǎng wò", khmer: "គ្រប់គ្រង, ដឹងល្អ" },
    { word: "涨", pinyin: "zhǎng", khmer: "ឡើង, កើនឡើង" },
    { word: "长辈", pinyin: "zhǎng bèi", khmer: "សមាជិកពូជកាយបង្រៀន" },
    { word: "账户", pinyin: "zhàng hù", khmer: "គណនី, គណនីធនាគារ" },
    { word: "招待", pinyin: "zhāo dài", khmer: "ទទួលភ្ញៀវ, រួមគ្នា" },
    { word: "着火", pinyin: "zháo huǒ", khmer: "ភ្លើង, រំលេច" },
    { word: "着凉", pinyin: "zháo liáng", khmer: "ឈឺប៉ុណ្ណោះ, បោកចាញ់ស្រស់" },
    { word: "召开", pinyin: "zhào kāi", khmer: "ជួបប្រជុំ, ប្រកាសការប្រជុំ" },
    { word: "照常", pinyin: "zhào cháng", khmer: "ដូចជាមុន, ដំណើរការផ្សេងទៀត" },
    { word: "哲学", pinyin: "zhé xué", khmer: "ទស្សនវិជ្ជា" },
    { word: "珍惜", pinyin: "zhēn xī", khmer: "ថ្លែងថ្លៃ, យកចិត្តទុកដាក់" },
    { word: "真实", pinyin: "zhēn shí", khmer: "ពិតប្រាកដ, ជាក់ស្តែង" },
    { word: "针对", pinyin: "zhēn duì", khmer: "ប្រឆាំង, ចាំបាច់" },
    { word: "诊断", pinyin: "zhěn duàn", khmer: "វិចារណះ, វិចារណញ្ញត្តិ" },
    { word: "振动", pinyin: "zhèn dòng", khmer: "ការលួចចេញ" },
    { word: "阵", pinyin: "zhèn", khmer: "ការតំណត់ត្រា, ស្ថានភាព" },
    { word: "争论", pinyin: "zhēng lùn", khmer: "ការជម្រះពាក្យ, ការពិចារណា" },
    { word: "争取", pinyin: "zhēng qǔ", khmer: "ប្រយត្ន, ស្វែងរក, ឈរឡើងប្រយត្ន" },
    { word: "征求", pinyin: "zhēng qiú", khmer: "ស្វែងរកមតិយោបល់, ស្វែងសួរ" },
    { word: "挣", pinyin: "zhēng", khmer: "ការតស៊ូ, ស្វែងរក" },
    { word: "睁", pinyin: "zhēng", khmer: "បើកភ្នែក" },
    { word: "整个", pinyin: "zhěng gè", khmer: "ទាំងអស់, ពេញលេញ" },
    { word: "整齐", pinyin: "zhěng qí", khmer: "សាមញ្ញ, ធៀប, ការពិត" },
    { word: "整体", pinyin: "zhěng tǐ", khmer: "សរុប, បច្ចេកទេស" },
    { word: "政府", pinyin: "zhèng fǔ", khmer: "រដ្ឋាភិបាល" },
    { word: "政治", pinyin: "zhèng zhì", khmer: "នយោបាយ" },
    { word: "正", pinyin: "zhèng", khmer: "ត្រឹមត្រូវ, គុណភាព, ពិត" },
    { word: "证件", pinyin: "zhèng jiàn", khmer: "ប័ណ្ណសញ្ញា, អាថ៌កំបាំង" },
    { word: "证据", pinyin: "zhèng jù", khmer: "ភស្តុតាង" },
    { word: "支", pinyin: "zhī", khmer: "គាំទ្រ, បញ្ចាំ" },
    { word: "支票", pinyin: "zhī piào", khmer: "លិខិតគោល, ស្នើសុំ" },
    { word: "执照", pinyin: "zhí zhào", khmer: "អាជ្ញាប័ណ្ណ" },
    { word: "直", pinyin: "zhí", khmer: "បណ្តោយ, ជាត្រឹមត្រូវ" },
    { word: "指导", pinyin: "zhǐ dǎo", khmer: "ណែនាំ, បញ្ជូន" },
    { word: "指挥", pinyin: "zhǐ huī", khmer: "ប្រធាន, បញ្ជារបៀប, ជំនួញ" },
    { word: "制定", pinyin: "zhì dìng", khmer: "ចុះបញ្ជី, កំណត់" },
    { word: "制度", pinyin: "zhì dù", khmer: "ប្រព័ន្ធ, កម្រិត" },
    { word: "制造", pinyin: "zhì zào", khmer: "ផលិត, បង្កើត" },
    { word: "制作", pinyin: "zhì zuò", khmer: "ផលិត, បង្កើត" },
    { word: "志愿者", pinyin: "zhì yuàn zhě", khmer: "អ្នកស្ម័គ្រចិត្ត" },
    { word: "智慧", pinyin: "zhì huì", khmer: "ប្រាជ្ញ, បញ្ញា" },
    { word: "治疗", pinyin: "zhì liáo", khmer: "ការព្យាបាល, ការព្យាបាលវេជ្ជសាស្ត្រ" },
    { word: "秩序", pinyin: "zhì xù", khmer: "លំដាប់, កម្រិត" },
    { word: "至今", pinyin: "zhì jīn", khmer: "មកទល់ពេលនេះ" },
    { word: "至于", pinyin: "zhì yú", khmer: "ទៅហើយ, យ៉ាងណា" },
    { word: "中介", pinyin: "zhōng jiè", khmer: "ជួបជុំ, តំណាង" },
    { word: "中心", pinyin: "zhōng xīn", khmer: "មជ្ឈមណ្ឌល" },
    { word: "中旬", pinyin: "zhōng xún", khmer: "តំបន់កណ្តាលខែ" },
    { word: "种类", pinyin: "zhǒng lèi", khmer: "ប្រភេទ, ក្រុមប្រភេទ" },
    { word: "重大", pinyin: "zhòng dà", khmer: "សំខាន់, ដ៏អស្ចារ្យ" },
    { word: "重量", pinyin: "zhòng liàng", khmer: "ទំងន់" },
    { word: "周到", pinyin: "zhōu dao", khmer: "គិតដល់គ្រប់ចំណុច, ពិចារណា" },
    { word: "猪", pinyin: "zhū", khmer: "សាច់គោ, សត្វជ្រូក" },
    { word: "竹子", pinyin: "zhú zi", khmer: "ដំលូ, ដំណាំដូង" },
    { word: "逐步", pinyin: "zhú bù", khmer: "តាមជំហាន" },
    { word: "逐渐", pinyin: "zhú jiàn", khmer: "យ៉ាងតិច, យ៉ាងតិចតួច" },
    { word: "主持", pinyin: "zhǔ chí", khmer: "ដឹកនាំ, នាំស្រាយ" },
    { word: "主动", pinyin: "zhǔ dòng", khmer: "ចរចារចំរូង, ធ្វើដោយខ្លួនឯង" },
    { word: "主观", pinyin: "zhǔ guān", khmer: "អារម្មណ៍ផ្ទាល់ខ្លួន" },
    { word: "主人", pinyin: "zhǔ rén", khmer: "ម្ចាស់, ម្ចាស់ផ្ទះ" },
    { word: "主任", pinyin: "zhǔ rèn", khmer: "អ្នកដឹកនាំ, ប្រធាន" },
    { word: "主题", pinyin: "zhǔ tí", khmer: "ប្រធានបទ, ប្រធាន" },
    { word: "主席", pinyin: "zhǔ xí", khmer: "ប្រធាន, អភិបាល" },
    { word: "主张", pinyin: "zhǔ zhāng", khmer: "គំនិត, ទស្សនៈ" },
    { word: "煮", pinyin: "zhǔ", khmer: "ដាំ, ដុត" },
    { word: "注册", pinyin: "zhù cè", khmer: "ចុះបញ្ជី, ធ្វើការចុះឈ្មោះ" },
    { word: "祝福", pinyin: "zhù fú", khmer: "ជួនពរ, ជូនពរថ្យ" },
    { word: "抓", pinyin: "zhuā", khmer: "ចាប់, ឃាត់" },
    { word: "抓紧", pinyin: "zhuā jǐn", khmer: "ទទួលយកយ៉ាងខ្លាំង" },
    { word: "专家", pinyin: "zhuān jiā", khmer: "អ្នកជំនាញ, អ្នកជំនាញពិសេស" },
    { word: "专心", pinyin: "zhuān xīn", khmer: "មានការយកចិត្តទុកដាក់, អត់បង់ចិត្ត" },
    { word: "转变", pinyin: "zhuǎn biàn", khmer: "ផ្លាស់ប្តូរ, បំលែង" },
    { word: "转告", pinyin: "zhuǎn gào", khmer: "ផ្សព្វផ្សាយ, ទទួលបាន" },
    { word: "装", pinyin: "zhuāng", khmer: "សំរួល, តុបតែង" },
    { word: "装饰", pinyin: "zhuāng shì", khmer: "តុបតែង, ការតុបតែង" },
    { word: "装修", pinyin: "zhuāng xiū", khmer: "កែសម្រួល, ផ្លាស់ប្តូរ" },
    { word: "撞", pinyin: "zhuàng", khmer: "ប៉ះ, ច撞" },
    { word: "状况", pinyin: "zhuàng kuàng", khmer: "ស្ថានភាព, ស្ថានភាព" },
    { word: "状态", pinyin: "zhuàng tài", khmer: "ស្ថានភាព, ស្ថានភាពផ្លូវការផ្សេងៗ" },
    { word: "追", pinyin: "zhuī", khmer: "បន្ត, ប្រមូល" },
    { word: "追求", pinyin: "zhuī qiú", khmer: "ប៉ុនប៉ង, រើស" },
    { word: "咨询", pinyin: "zī xún", khmer: "ពិគ្រោះយោបល់, សួរអំពី" },
    { word: "姿势", pinyin: "zī shì", khmer: "មុខងារ, ទីតាំង" },
    { word: "资格", pinyin: "zī gé", khmer: "សញ្ញាបត្រ, ភាពសមរម្យ" },
    { word: "资金", pinyin: "zī jīn", khmer: "មូលនិធិ, ទុន" },
    { word: "资料", pinyin: "zī liào", khmer: "សម្ភារៈ, ข้อมูล" },
    { word: "资源", pinyin: "zī yuán", khmer: "ធនធាន, ប្រភពធនធាន" },
    { word: "紫", pinyin: "zǐ", khmer: "ពណ៌ស្វាយ, ពណ៌ស្វាយ" },
    { word: "字母", pinyin: "zì mǔ", khmer: "តួអក្សរ, អក្សរដើម" },
    { word: "字幕", pinyin: "zì mù", khmer: "អត្ថបទបន្ថែម, អត្ថបទបញ្ជាក់" },
    { word: "自从", pinyin: "zì cóng", khmer: "ចាប់តាំងពី" },
    { word: "自动", pinyin: "zì dòng", khmer: "ដោយស្វ័យប្រវត្តិ, យ៉ាងស្វ័យប្រវត្តិ" },
    { word: "自豪", pinyin: "zì háo", khmer: "មោទនភាព, មានកិត្តិយស" },
    { word: "自觉", pinyin: "zì jué", khmer: "សកម្មភាព, ដោយខ្លួនឯង" },
    { word: "自私", pinyin: "zì sī", khmer: "អាណិតខ្លួនឯង, អាណិតខ្លួនឯង" },
    { word: "自由", pinyin: "zì yóu", khmer: "សេរីភាព, ជាតុល្យភាព" },
    { word: "自愿", pinyin: "zì yuàn", khmer: "ដោយស្មោះសំខាន់, ការជ្រើសរើសដោយចិត្តឯង" },
    { word: "综合", pinyin: "zōng hé", khmer: "សរុប, ជាសរុប" },
    { word: "总裁", pinyin: "zǒng cái", khmer: "ប្រធាន, ប្រធានប្រតិបត្តិការ" },
    { word: "总共", pinyin: "zǒng gòng", khmer: "សរុប, រាប់" },
    { word: "总理", pinyin: "zǒng lǐ", khmer: "ប្រមុខរដ្ឋមន្រ្តី, ព្រីមមីនិស្ត័រ" },
    { word: "总算", pinyin: "zǒng suàn", khmer: "ជាក្រោយៗ, នៅទីបញ្ចប់" },
    { word: "总统", pinyin: "zǒng tǒng", khmer: "ប្រធានាធិបតី, ប្រធានរដ្ឋ" },
    { word: "总之", pinyin: "zǒng zhī", khmer: "សរុប, ប៉ុន្តែមើលទាំងមូល" },
    { word: "组", pinyin: "zǔ", khmer: "បង្កើត, រៀបចំ, ក្រុម" },
    { word: "组成", pinyin: "zǔ chéng", khmer: "បង្កើត, សម្រួល" },
    { word: "组合", pinyin: "zǔ hé", khmer: "បញ្ចូលគ្នា, ការប្រមូល" },
    { word: "组织", pinyin: "zǔ zhī", khmer: "រៀបចំ, អង្គភាព" },
    { word: "阻止", pinyin: "zǔ zhǐ", khmer: "រាំងស្ទះ, បញ្ឈរ" },
    { word: "最初", pinyin: "zuì chū", khmer: "ដំបូង, ដំបូងបង្អស់" },
    { word: "醉", pinyin: "zuì", khmer: "មហិម, មហិម" },
    { word: "尊敬", pinyin: "zūn jìng", khmer: "គោរព, ស្មោះសំខាន់" },
    { word: "遵守", pinyin: "zūn shǒu", khmer: "គោរព, អនុវត្ត" },
    { word: "作品", pinyin: "zuò pǐn", khmer: "ស្នាដៃ, ធ្វើការងារ" },
    { word: "作为", pinyin: "zuò wéi", khmer: "ជាការប្រព្រឹត្ត, ធ្វើអាជីព" },
    { word: "作文", pinyin: "zuò wén", khmer: "ការសរសេរអត្ថបទ, ការសរសេរអត្ថបទ" }



];

const wordList = document.getElementById("word-list");

words.forEach(({ word, pinyin, khmer }) => {
  const card = document.createElement("div");
  card.className = "word-card";
  card.innerHTML = `
    <div class="word">${word}</div>
    <div class="pinyin">${pinyin}</div>
    <div class="khmer">${khmer}</div>
  `;
  wordList.appendChild(card);
});
