document.getElementById("vocab-title").textContent = "造句:(បង្កើតប្រយោគ)";

const words = [
    { cn: "我们走吧！", pinyin: "Wǒmen zǒu ba!", kh: "យើងទៅទៀតបាទ!" },
    { cn: "他穿了一件白衬衫。", pinyin: "Tā chuān le yí jiàn bái chènshān.", kh: "គាត់ពាក់អាវសមួយ។" },
    { cn: "这里有一百个人。", pinyin: "Zhèlǐ yǒu yì bǎi gè rén.", kh: "ទីនេះមានមនុស្សមួយរយនាក់។" },
    { cn: "谢谢你的帮助。", pinyin: "Xièxie nǐ de bāngzhù.", kh: "អរគុណសម្រាប់ការជួយរបស់អ្នក។" },
    { cn: "我每天早上看报纸。", pinyin: "Wǒ měitiān zǎoshang kàn bàozhǐ.", kh: "ខ្ញុំអានកាសែតរៀងរាល់ពេលព្រឹក។" },
    { cn: "他比我高。", pinyin: "Tā bǐ wǒ gāo.", kh: "គាត់ខ្ពស់ជាងខ្ញុំ។" },
    { cn: "别说话！", pinyin: "Bié shuōhuà!", kh: "កុំនិយាយ!" },
    { cn: "这家宾馆很干净。", pinyin: "Zhè jiā bīnguǎn hěn gānjìng.", kh: "សណ្ឋាគារនេះស្អាតណាស់។" },
    { cn: "这条路很长。", pinyin: "Zhè tiáo lù hěn cháng.", kh: "ផ្លូវនេះវែងណាស់។" },
    { cn: "我喜欢唱歌。", pinyin: "Wǒ xǐhuān chànggē.", kh: "ខ្ញុំចូលចិត្តច្រៀង។" },
    { cn: "他从房间里出来了。", pinyin: "Tā cóng fángjiān lǐ chūlái le.", kh: "គាត់ចេញពីបន្ទប់។" },
    { cn: "她穿了一条红裙子。", pinyin: "Tā chuān le yì tiáo hóng qúnzi.", kh: "នាងពាក់សំពត់ពណ៌ក្រហម។" },
    { cn: "我去过两次北京。", pinyin: "Wǒ qù guò liǎng cì Běijīng.", kh: "ខ្ញុំទៅប៉េកាំងពីរដង។" },
    { cn: "他从中国来。", pinyin: "Tā cóng Zhōngguó lái.", kh: "គាត់មកពីប្រទេសចិន។" },
    { cn: "你错了。", pinyin: "Nǐ cuò le.", kh: "អ្នកខុសហើយ។" },
    { cn: "我们下午去打篮球吧。", pinyin: "Wǒmen xiàwǔ qù dǎ lánqiú ba.", kh: "យើងទៅលេងបាល់បោះនៅរសៀល។" },
    { cn: "大家都来了。", pinyin: "Dàjiā dōu lái le.", kh: "អ្នកទាំងអស់គ្នាមកដល់ហើយ។" },
    { cn: "我明天到上海。", pinyin: "Wǒ míngtiān dào Shànghǎi.", kh: "ខ្ញុំទៅដល់សាងហៃស្អែក។" },
    { cn: "我跑得很快。", pinyin: "Wǒ pǎo de hěn kuài.", kh: "ខ្ញុំរត់បានលឿនណាស់។" },
    { cn: "请等一下。", pinyin: "Qǐng děng yíxià.", kh: "សូមរង់ចាំបន្តិច។" },
    { cn: "我有一个弟弟。", pinyin: "Wǒ yǒu yí gè dìdi.", kh: "ខ្ញុំមានប្អូនប្រុសម្នាក់។" },
    { cn: "他是第一名。", pinyin: "Tā shì dì yī míng.", kh: "គាត់ជាអ្នកលេខទីមួយ។" },
    { cn: "我听不懂中文。", pinyin: "Wǒ tīng bù dǒng Zhōngwén.", kh: "ខ្ញុំមិនយល់ភាសាចិនទេ។" },
    { cn: "你的答案是对的。", pinyin: "Nǐ de dá'àn shì duì de.", kh: "ចម្លើយរបស់អ្នកត្រឹមត្រូវ។" },
    { cn: "他对我很好。", pinyin: "Tā duì wǒ hěn hǎo.", kh: "គាត់ចំពោះខ្ញុំសប្បុរសណាស់។" },
    { cn: "这个房间很大。", pinyin: "Zhè gè fángjiān hěn dà.", kh: "បន្ទប់នេះធំណាស់។" },
    { cn: "我非常喜欢这里。", pinyin: "Wǒ fēicháng xǐhuān zhèlǐ.", kh: "ខ្ញុំចូលចិត្តទីនេះខ្លាំងណាស់។" },
    { cn: "服务员，请给我菜单。", pinyin: "Fúwùyuán, qǐng gěi wǒ càidān.", kh: "អ្នករត់តុ សូមផ្តល់ម៉ឺនុយឲ្យខ្ញុំ។" },
    { cn: "他比我高。", pinyin: "Tā bǐ wǒ gāo.", kh: "គាត់ខ្ពស់ជាងខ្ញុំ។" },
    { cn: "请告诉我你的名字。", pinyin: "Qǐng gàosu wǒ nǐ de míngzi.", kh: "សូមប្រាប់ខ្ញុំអំពីឈ្មោះរបស់អ្នក។" },
    { cn: "我哥哥很聪明。", pinyin: "Wǒ gēge hěn cōngmíng.", kh: "បងប្រុសរបស់ខ្ញុំឆ្លាតណាស់។" },
    { cn: "我给你一本书。", pinyin: "Wǒ gěi nǐ yì běn shū.", kh: "ខ្ញុំផ្តល់សៀវភៅមួយសន្លឹកឲ្យអ្នក។" },
    { cn: "我们坐公共汽车去学校。", pinyin: "Wǒmen zuò gōnggòng qìchē qù xuéxiào.", kh: "យើងជិះឡានក្រុងទៅសាលា។" },
    { cn: "我在一家公司工作。", pinyin: "Wǒ zài yì jiā gōngsī gōngzuò.", kh: "ខ្ញុំធ្វើការនៅក្រុមហ៊ុនមួយ។" },
    { cn: "这双鞋太贵了。", pinyin: "Zhè shuāng xié tài guì le.", kh: "ស្បែកជើងនេះថ្លៃពេកហើយ។" },
    { cn: "我去过北京。", pinyin: "Wǒ qù guo Běijīng.", kh: "ខ្ញុំធ្លាប់ទៅប៉េកាំង។" },
    { cn: "那个孩子很可爱。", pinyin: "Nà gè háizi hěn kě'ài.", kh: "កូននោះគួរឲ្យស្រលាញ់ណាស់។" },
    { cn: "我还在学习中文。", pinyin: "Wǒ hái zài xuéxí Zhōngwén.", kh: "ខ្ញុំនៅតែសិក្សាភាសាចិន។" },
    { cn: "这个饭真好吃！", pinyin: "Zhè gè fàn zhēn hǎochī!", kh: "ម្ហូបនេះឆ្ងាញ់ណាស់!" },
    { cn: "天空是黑的。", pinyin: "Tiānkōng shì hēi de.", kh: "មេឃគឺជាពណ៌ខ្មៅ។" },
    { cn: "她穿了一件红衣服。", pinyin: "Tā chuān le yí jiàn hóng yīfu.", kh: "នាងពាក់ខោអាវពណ៌ក្រហម។" },
    { cn: "我们在火车站见面。", pinyin: "Wǒmen zài huǒchēzhàn jiànmiàn.", kh: "យើងជួបគ្នានៅស្ថានីយ៍រថភ្លើង។" },
    { cn: "飞机从机场起飞。", pinyin: "Fēijī cóng jīchǎng qǐfēi.", kh: "យន្តហោះបើកពីព្រលានយន្តហោះ។" },
    { cn: "我每天早上吃鸡蛋。", pinyin: "Wǒ měitiān zǎoshang chī jīdàn.", kh: "ខ្ញុំញុំាស៊ុតរៀងរាល់ព្រឹក។" },
    { cn: "我买了一件新衣服。", pinyin: "Wǒ mǎi le yí jiàn xīn yīfu.", kh: "ខ្ញុំបានទិញខោអាវថ្មីមួយឯកតា។" },
    { cn: "教室里有很多学生。", pinyin: "Jiàoshì lǐ yǒu hěn duō xuéshēng.", kh: "មានសិស្សច្រើននៅក្នុងថ្នាក់រៀន។" },
    { cn: "我姐姐在上班。", pinyin: "Wǒ jiějie zài shàngbān.", kh: "បងស្រីខ្ញុំកំពុងធ្វើការ។" },
    { cn: "让我来介绍一下自己。", pinyin: "Ràng wǒ lái jièshào yíxià zìjǐ.", kh: "អនុញ្ញាតឲ្យខ្ញុំណែនាំខ្លួនបន្តិច។" },
    { cn: "学校离我家很近。", pinyin: "Xuéxiào lí wǒ jiā hěn jìn.", kh: "សាលាជិតផ្ទះខ្ញុំ។" },
    { cn: "请进来坐。", pinyin: "Qǐng jìnlái zuò.", kh: "សូមចូលមកអង្គុយ។" },
    { cn: "他下班就回家了。", pinyin: "Tā xiàbān jiù huí jiā le.", kh: "គាត់ត្រលប់ទៅផ្ទះភ្លាមៗក្រោយចប់ការងារ។" },
    { cn: "我觉得这个电影很好看。", pinyin: "Wǒ juéde zhè gè diànyǐng hěn hǎokàn.", kh: "ខ្ញុំមានអារម្មណ៍ថាភាពយន្ដនេះគួរឲ្យមើលណាស់។" },
    { cn: "你喝咖啡吗？", pinyin: "Nǐ hē kāfēi ma?", kh: "អ្នកផឹកកាហ្វេទេ?" },
    { cn: "我们八点开始上课。", pinyin: "Wǒmen bā diǎn kāishǐ shàngkè.", kh: "យើងចាប់ផ្តើមរៀនម៉ោងប្រាំមួយ។" },
    { cn: "明天我们要考试。", pinyin: "Míngtiān wǒmen yào kǎoshì.", kh: "ស្អែកយើងត្រូវប្រឡង។" },
    { cn: "今天可能会下雨。", pinyin: "Jīntiān kěnéng huì xià yǔ.", kh: "ថ្ងៃនេះប្រហែលជាព្រិលភ្លៀង។" },
    { cn: "你可以进来吗？", pinyin: "Nǐ kěyǐ jìnlái ma?", kh: "អ្នកអាចចូលមកបានទេ?" },
    { cn: "这节课很有意思。", pinyin: "Zhè jié kè hěn yǒuyìsi.", kh: "ថ្នាក់រៀននេះគួរឲ្យចាប់អារម្មណ៍ណាស់។" },
    { cn: "他跑得很快。", pinyin: "Tā pǎo de hěn kuài.", kh: "គាត់រត់លឿនណាស់។" },
    { cn: "祝你生日快乐！", pinyin: "Zhù nǐ shēngrì kuàilè!", kh: "សូមអបអរសាទរថ្ងៃកំណើត!" },
    { cn: "我今天很累。", pinyin: "Wǒ jīntiān hěn lèi.", kh: "ថ្ងៃនេះខ្ញុំហត់ណាស់។" },
    { cn: "我家离学校很远。", pinyin: "Wǒ jiā lí xuéxiào hěn yuǎn.", kh: "ផ្ទះខ្ញុំឆ្ងាយពីសាលា។" },
    { cn: "我有两个妹妹。", pinyin: "Wǒ yǒu liǎng gè mèimei.", kh: "ខ្ញុំមានប្អូនស្រីពីរនាក់។" },
    { cn: "现在是零点零五分。", pinyin: "Xiànzài shì líng diǎn líng wǔ fēn.", kh: "ឥឡូវម៉ោងសូន្យនិងប្រាំនាទី។" },
    { cn: "这条路很长。", pinyin: "Zhè tiáo lù hěn cháng.", kh: "ផ្លូវនេះវែងណាស់។" },
    { cn: "我喜欢旅游。", pinyin: "Wǒ xǐhuān lǚyóu.", kh: "ខ្ញុំចូលចិត្តធ្វើទេសចរណ៍។" },
    { cn: "他在市场卖水果。", pinyin: "Tā zài shìchǎng mài shuǐguǒ.", kh: "គាត់លក់ផ្លែឈើនៅផ្សារ។" },
    { cn: "你说得太慢了。", pinyin: "Nǐ shuō de tài màn le.", kh: "អ្នកនិយាយយឺតពេកហើយ។" },
    { cn: "今天我很忙。", pinyin: "Jīntiān wǒ hěn máng.", kh: "ថ្ងៃនេះខ្ញុំរវល់ណាស់។" },
    { cn: "我每天早上跑步。", pinyin: "Wǒ měitiān zǎoshang pǎobù.", kh: "ខ្ញុំរត់នៅព្រឹករៀងរាល់ថ្ងៃ។" },
    { cn: "我妹妹很可爱。", pinyin: "Wǒ mèimei hěn kě’ài.", kh: "ប្អូនស្រីខ្ញុំគួរឱ្យស្រឡាញ់ណាស់។" },
    { cn: "请关门。", pinyin: "Qǐng guān mén.", kh: "សូមបិទទ្វារ។" },
    { cn: "我想吃面条。", pinyin: "Wǒ xiǎng chī miàntiáo.", kh: "ខ្ញុំចង់ញុំាមី។" },
    { cn: "他是一个男学生。", pinyin: "Tā shì yí gè nán xuéshēng.", kh: "គាត់ជាសិស្សប្រុសម្នាក់។" },
    { "cn": "您好吗？", "pinyin": "Nín hǎo ma?", "kh": "អ្នកសុខសប្បាយទេ?" },
    { "cn": "我喜欢喝牛奶。", "pinyin": "Wǒ xǐ huān hē niú nǎi.", "kh": "ខ្ញុំចូលចិត្តផឹកទឹកដោះគោ។" },
    { "cn": "她是一个漂亮的女孩子。", "pinyin": "Tā shì yí gè piào liang de nǚ hái zi.", "kh": "គាត់ជាក្មេងស្រីស្អាតម្នាក់។" },
    { "cn": "我的手机在旁边。", "pinyin": "Wǒ de shǒu jī zài páng biān.", "kh": "ទូរស័ព្ទរបស់ខ្ញុំមាននៅក្បែរ។" },
    { "cn": "我每天早上跑步。", "pinyin": "Wǒ měi tiān zǎo shàng pǎo bù.", "kh": "ខ្ញុំរត់រាល់ព្រឹក។" },
    { "cn": "这件衣服很便宜。", "pinyin": "Zhè jiàn yī fú hěn pián yi.", "kh": "អាវនេះថោកណាស់។" },
    { "cn": "我买了一张票。", "pinyin": "Wǒ mǎi le yì zhāng piào.", "kh": "ខ្ញុំបានទិញសំបុត្រមួយ។" },
    { "cn": "她是我的妻子。", "pinyin": "Tā shì wǒ de qī zi.", "kh": "គាត់ជាប្រពន្ធរបស់ខ្ញុំ។" },
    { "cn": "我每天早上七点起床。", "pinyin": "Wǒ měi tiān zǎo shàng qī diǎn qǐ chuáng.", "kh": "ខ្ញុំត្រូវការក្រោកពីគេងម៉ោង៧ព្រឹករាល់ថ្ងៃ។" },
    { "cn": "这里有一千块钱。", "pinyin": "Zhè lǐ yǒu yì qiān kuài qián.", "kh": "ទីនេះមានប្រាក់មួយពាន់៕" },
    { "cn": "我用铅笔写字。", "pinyin": "Wǒ yòng qiān bǐ xiě zì.", "kh": "ខ្ញុំប្រើខ្មៅដៃសរសេរ។" },
    { "cn": "今天是晴天。", "pinyin": "Jīn tiān shì qíng tiān.", "kh": "ថ្ងៃនេះមានអាកាសធាតុច្បាស់។" },
    { "cn": "去年我们去了北京。", "pinyin": "Qù nián wǒ men qù le Běi jīng.", "kh": "ឆ្នាំមុនយើងបានទៅប៉េកាំង។" },
    { "cn": "让我帮你。", "pinyin": "Ràng wǒ bāng nǐ.", "kh": "សូមឱ្យខ្ញុំជួយអ្នក។" },
    { "cn": "今天是星期日。", "pinyin": "Jīn tiān shì xīng qī rì.", "kh": "ថ្ងៃនេះជាថ្ងៃអាទិត្យ។" },
    { "cn": "我每天都去上班。", "pinyin": "Wǒ měi tiān dōu qù shàng bān.", "kh": "ខ្ញុំទៅធ្វើការរាល់ថ្ងៃ។" },
    { "cn": "我很注意自己的身体。", "pinyin": "Wǒ hěn zhù yì zì jǐ de shēn tǐ.", "kh": "ខ្ញុំយកចិត្តទុកដាក់សុខភាពរបស់ខ្ញុំ។" },
    { "cn": "我生病了，不能去学校。", "pinyin": "Wǒ shēng bìng le, bù néng qù xué xiào.", "kh": "ខ្ញុំឈឺ ហើយមិនអាចទៅសាលា។" },
    { "cn": "今天是我的生日。", "pinyin": "Jīn tiān shì wǒ de shēng rì.", "kh": "ថ្ងៃនេះជាថ្ងៃកំណើតរបស់ខ្ញុំ។" },
    { "cn": "我没有时间去旅行。", "pinyin": "Wǒ méi yǒu shí jiān qù lǚ xíng.", "kh": "ខ្ញុំគ្មានពេលវេលាដើម្បីដំណើរកំសាន្ត។" },
    { "cn": "这是我的事情。", "pinyin": "Zhè shì wǒ de shì qing.", "kh": "នេះគឺជារឿងរបស់ខ្ញុំ។" },
    { "cn": "我看到了一个漂亮的手表。", "pinyin": "Wǒ kàn dào le yí gè piào liang de shǒu biǎo.", "kh": "ខ្ញុំបានឃើញនាឡិកាដៃស្អាតមួយ។" },
    { "cn": "我的手机坏了。", "pinyin": "Wǒ de shǒu jī huài le.", "kh": "ទូរស័ព្ទរបស់ខ្ញុំពុះចោល។" },
    { "cn": "他喜欢和朋友一起说话。", "pinyin": "Tā xǐ huān hé péng yǒu yī qǐ shuō huà.", "kh": "គាត់ចូលចិត្តនិយាយជាមួយមិត្តភក្តិ។" },
    { "cn": "我送给你一个礼物。", "pinyin": "Wǒ sòng gěi nǐ yí gè lǐ wù.", "kh": "ខ្ញុំបានផ្តល់អំណោយមួយឲ្យអ្នក។" },
    { "cn": "虽然他很忙，但是他还是来参加了会议。", "pinyin": "Suī rán tā hěn máng, dàn shì tā hái shì lái cān jiā le huì yì.", "kh": "ទោះយ៉ាងណាគាត់យ៉ាងជ្រុលប៉ុន្តែគាត់នៅតែបានមកចូលរួមកិច្ចប្រជុំ។" },
  { "cn": "它是我的朋友。", "pinyin": "Tā shì wǒ de péng yǒu.", "kh": "វាជាមិត្តរបស់ខ្ញុំ។" },
  { "cn": "我喜欢踢足球。", "pinyin": "Wǒ xǐ huān tī zú qiú.", "kh": "ខ្ញុំចូលចិត្តលេងបាល់ទាត់។" },
  { "cn": "这是一个很难的题。", "pinyin": "Zhè shì yí gè hěn nán de tí.", "kh": "នេះជាសំណួរដ៏លំបាកមួយ។" },
  { "cn": "我会跳舞。", "pinyin": "Wǒ huì tiào wǔ.", "kh": "ខ្ញុំអាចរាំបាន។" },
  { "cn": "我们去外面玩吧！", "pinyin": "Wǒ men qù wài miàn wán ba!", "kh": "យើងទៅខាងក្រៅលេងបន្តិច!" },
  { "cn": "我已经完成了任务。", "pinyin": "Wǒ yǐ jīng wán chéng le rèn wu.", "kh": "ខ្ញុំបានបញ្ចប់ភារកិច្ចហើយ។" },
  { "cn": "我喜欢和朋友一起玩游戏。", "pinyin": "Wǒ xǐ huān hé péng yǒu yī qǐ wán yóu xì.", "kh": "ខ្ញុំចូលចិត្តលេងហ្គេមជាមួយមិត្តភក្តិ។" },
  { "cn": "晚上我有空。", "pinyin": "Wǎn shang wǒ yǒu kòng.", "kh": "នៅពេលយប់ខ្ញុំមានពេលទំនេរ។" },
  { "cn": "我往学校走。", "pinyin": "Wǒ wǎng xué xiào zǒu.", "kh": "ខ្ញុំឆ្ពោះទៅសាលា។" },
  { "cn": "你为什么迟到？", "pinyin": "Nǐ wèi shén me chí dào?", "kh": "ហេតុអ្វីអ្នកទន្ទឹមមក?" },
  { "cn": "我想问你一个问题。", "pinyin": "Wǒ xiǎng wèn nǐ yí gè wèn tí.", "kh": "ខ្ញុំចង់សួរអ្នកសំណួរមួយ។" },
  { "cn": "这是一个很复杂的问题。", "pinyin": "Zhè shì yí gè hěn fù zá de wèn tí.", "kh": "នេះគឺជាបញ្ហាដ៏ស្មុគស្មាញមួយ។" },
  { "cn": "我希望明天会更好。", "pinyin": "Wǒ xī wàng míng tiān huì gèng hǎo.", "kh": "ខ្ញុំសង្ឃឹមថាថ្ងៃស្អែកនឹងប្រសើរជាងនេះ។" },
  { "cn": "我喜欢吃西瓜。", "pinyin": "Wǒ xǐ huān chī xī guā.", "kh": "ខ្ញុំចូលចិត្តបរិច្ឆេទឪឡឹក។" },
  { "cn": "你要洗手吗？", "pinyin": "Nǐ yào xǐ shǒu ma?", "kh": "អ្នកត្រូវការលាងដៃទេ?" },
  { "cn": "我每天都洗脸。", "pinyin": "Wǒ měi tiān dōu xǐ liǎn.", "kh": "ខ្ញុំលាងមុខរាល់ថ្ងៃ។" },
  { "cn": "我有两个小时的休息时间。", "pinyin": "Wǒ yǒu liǎng gè xiǎo shí de xiū xi shí jiān.", "kh": "ខ្ញុំមានពេលសម្រាកពីរម៉ោង។" },
  { "cn": "我喜欢笑。", "pinyin": "Wǒ xǐ huān xiào.", "kh": "ខ្ញុំចូលចិត្តសើច។" },
  { "cn": "这是新的一年。", "pinyin": "Zhè shì xīn de yī nián.", "kh": "នេះគឺជាឆ្នាំថ្មី។" },
  { "cn": "我的姓是王。", "pinyin": "Wǒ de xìng shì Wáng.", "kh": "ត្រកូលរបស់ខ្ញុំគឺវ៉ាង។" },
  { "cn": "我需要休息一下。", "pinyin": "Wǒ xū yào xiū xi yí xià.", "kh": "ខ្ញុំត្រូវការសម្រាកបន្តិច។" },
  { "cn": "外面下雪了。", "pinyin": "Wài miàn xià xuě le.", "kh": "ខាងក្រៅព្រិលបានធ្លាក់។" },
  { "cn": "这个颜色很漂亮。", "pinyin": "Zhè ge yán sè hěn piào liang.", "kh": "ពណ៌នេះស្អាតណាស់។" },
  { "cn": "他的眼睛很大。", "pinyin": "Tā de yǎn jing hěn dà.", "kh": "ភ្នែករបស់គាត់ធំមែនទែន។" },
  { "cn": "我喜欢吃羊肉。", "pinyin": "Wǒ xǐ huān chī yáng ròu.", "kh": "ខ្ញុំចូលចិត្តបរិច្ឆេទចៀម។" },
  { "cn": "你吃了药了吗？", "pinyin": "Nǐ chī le yào le ma?", "kh": "អ្នកបានបរិច្ឆេទថ្នាំរួចហើយទេ?" },
  { "cn": "我需要一些药。", "pinyin": "Wǒ xū yào yì xiē yào.", "kh": "ខ្ញុំត្រូវការថ្នាំមួយចំនួន។" },
  { "cn": "我要喝水。", "pinyin": "Wǒ yào hē shuǐ.", "kh": "ខ្ញុំត្រូវការផឹកទឹក។" },
  { "cn": "我也喜欢看电影。", "pinyin": "Wǒ yě xǐ huān kàn diàn yǐng.", "kh": "ខ្ញុំក៏ចូលចិត្តមើលភាពយន្ត។" },
  { "cn": "我等一下就回来。", "pinyin": "Wǒ děng yī xià jiù huí lái.", "kh": "ខ្ញុំនឹងត្រលប់មកវិញបន្ទាប់ពីបន្តិច។" },
  { "cn": "他已经离开了。", "pinyin": "Tā yǐ jīng lí kāi le.", "kh": "គាត់បានចាកចេញហើយ។" },
  { "cn": "我们一起去看电影吧！", "pinyin": "Wǒ men yī qǐ qù kàn diàn yǐng ba!", "kh": "យើងទៅមើលភាពយន្តជាមួយគ្នា!" },
  { "cn": "这个词的意思是什么？", "pinyin": "Zhè ge cí de yì si shì shén me?", "kh": "ពាក្យនេះមានអត្ថន័យអ្វី?" },
  { "cn": "因为天气不好，所以我们没去旅游。", "pinyin": "Yīn wèi tiān qì bù hǎo, suǒ yǐ wǒ men méi qù lǚ yóu.", "kh": "ដោយសារតែអាកាសធាតុមិនល្អដូច្នេះយើងមិនបានទៅទេសចរណ៍។" },
  { "cn": "今天是有阴天。", "pinyin": "Jīn tiān shì yīn tiān.", "kh": "ថ្ងៃនេះគឺមានពពក។" },
  { "cn": "我喜欢游泳。", "pinyin": "Wǒ xǐ huān yóu yǒng.", "kh": "ខ្ញុំចូលចិត្តហែលទឹក។" },
  { "cn": "他的右边有一个人。", "pinyin": "Tā de yòu bian yǒu yí gè rén.", "kh": "នៅខាងស្តាំរបស់គាត់មានមនុស្សម្នាក់។" },
  { "cn": "我喜欢吃鱼。", "pinyin": "Wǒ xǐ huān chī yú.", "kh": "ខ្ញុំចូលចិត្តបរិច្ឆេទត្រី។" },
  { "cn": "这家餐馆离我家很远。", "pinyin": "Zhè jiā cān guǎn lí wǒ jiā hěn yuǎn.", "kh": "ភោជនីយដ្ឋាននេះឆ្ងាយពីផ្ទះរបស់ខ្ញុំ។" },
  { "cn": "每天早上我都跑步。", "pinyin": "Měi tiān zǎo shang wǒ dōu pǎo bù.", "kh": "ខ្ញុំរត់រាល់ពេលព្រឹក។" },
  { "cn": "他是我的丈夫。", "pinyin": "Tā shì wǒ de zhàng fu.", "kh": "គាត់គឺជាប្តីរបស់ខ្ញុំ។" },
  { "cn": "我在找我的钥匙。", "pinyin": "Wǒ zài zhǎo wǒ de yào shi.", "kh": "ខ្ញុំកំពុងរកច្រកសោរបស់ខ្ញុំ។" },
  { "cn": "他穿着一件蓝色的衣服。", "pinyin": "Tā chuān zhe yí jiàn lán sè de yī fu.", "kh": "គាត់ស្លៀកអាវពណ៌ខៀវមួយ។" },
  { "cn": "这是真的！", "pinyin": "Zhè shì zhēn de!", "kh": "នេះពិតណាស់!" },
  { "cn": "我正在做作业。", "pinyin": "Wǒ zhèng zài zuò zuò yè.", "kh": "ខ្ញុំកំពុងធ្វើការងារផ្ទាល់ខ្លួន។" },
  { "cn": "你知道答案吗？", "pinyin": "Nǐ zhī dào dá àn ma?", "kh": "អ្នកដឹងចម្លើយទេ?" },
  { "cn": "我正在准备考试。", "pinyin": "Wǒ zhèng zài zhǔn bèi kǎo shì.", "kh": "ខ្ញុំកំពុងត្រៀមខ្លួនសម្រាប់ប្រឡង។" },
  { "cn": "我们一起走吧！", "pinyin": "Wǒ men yī qǐ zǒu ba!", "kh": "យើងទៅគ្នា!" },
  { "cn": "他是我最好的朋友。", "pinyin": "Tā shì wǒ zuì hǎo de péng yǒu.", "kh": "គាត់គឺជាមិត្តភក្តិដ៏ល្អបំផុតរបស់ខ្ញុំ។" },
  { "cn": "左边是我的房间。", "pinyin": "Zuǒ bian shì wǒ de fáng jiān.", "kh": "ខាងឆ្វេងគឺជាបន្ទប់របស់ខ្ញុំ។" }
];

const wordList = document.getElementById("word-list");

words.forEach(({ cn, pinyin, kh }) => {
  const card = document.createElement("div");
  card.className = "word-card";
  card.innerHTML = `
    <div class="word">${cn}</div>
    <div class="pinyin">${pinyin}</div>
    <div class="khmer">${kh}</div>
  `;
  wordList.appendChild(card);
});
