document.getElementById("vocab-title").textContent = "造句:(បង្កើតប្រយោគ)";

const words = [
  { cn: "啊！你来了。", pinyin: "A! Nǐ lái le.", kh: "អា! អ្នកមកហើយ។" },
  { cn: "我去看阿姨。", pinyin: "Wǒ qù kàn āyí.", kh: "ខ្ញុំទៅមើលមីង។" },
  { cn: "他很矮。", pinyin: "Tā hěn ǎi.", kh: "គាត់ទាបណាស់។" },
  { cn: "唱歌是我的爱好。", pinyin: "Chànggē shì wǒ de àihào.", kh: "ច្រៀងចម្រៀងគឺជាចំណង់ចំណូលចិត្តរបស់ខ្ញុំ។" },
  { cn: "请安静一下。", pinyin: "Qǐng ānjìng yīxià.", kh: "សូមស្ងៀមស្ងាត់បន្តិច។" },
  { cn: "把书给我。", pinyin: "Bǎ shū gěi wǒ.", kh: "តោះ! ឲ្យខ្ញុំសៀវភៅ។" },
  { cn: "我们要搬家了。", pinyin: "Wǒmen yào bānjiā le.", kh: "យើងនឹងផ្លាស់ទីផ្ទះ។" },
  { cn: "这个班有三十个学生。", pinyin: "Zhège bān yǒu sānshí gè xuéshēng.", kh: "ថ្នាក់នេះមានសិស្សសាមសិបនាក់។" },
  { cn: "我有一个好办法。", pinyin: "Wǒ yǒu yīgè hǎo bànfǎ.", kh: "ខ្ញុំមានវិធីសាស្រ្តមួយល្អ។" },
  { cn: "他在办公室工作。", pinyin: "Tā zài bàngōngshì gōngzuò.", kh: "គាត់ធ្វើការនៅការិយាល័យ។" },
  { cn: "他不但会唱歌，而且会跳舞。", pinyin: "Tā bùdàn huì chànggē, érqiě huì tiàowǔ.", kh: "គាត់មិនត្រឹមតែចេះច្រៀងទេ ថែមទាំងចេះរាំផងដែរ។" },
  { cn: "请给我菜单。", pinyin: "Qǐng gěi wǒ càidān.", kh: "សូមឲ្យខ្ញុំនូវម៉ឺនុយ។" },
  { cn: "我明天要参加比赛。", pinyin: "Wǒ míngtiān yào cānjiā bǐsài.", kh: "ខ្ញុំនឹងចូលរួមការប្រកួតថ្ងៃស្អែក។" },
  { cn: "花园里有很多草。", pinyin: "Huāyuán lǐ yǒu hěn duō cǎo.", kh: "នៅក្នុងសួនផ្កាមានស្មៅច្រើន។" },
  { cn: "我住在五层。", pinyin: "Wǒ zhù zài wǔ céng.", kh: "ខ្ញុំស្នាក់នៅជាន់ទីប្រាំ។" },
  { cn: "这次考试成绩很差。", pinyin: "Zhè cì kǎoshì chéngjì hěn chà.", kh: "លទ្ធផលប្រឡងលើកនេះអាក្រក់ណាស់។" },
  { cn: "我去超市买东西。", pinyin: "Wǒ qù chāoshì mǎi dōngxī.", kh: "ខ្ញុំទៅផ្សារទំនើបដើម្បីទិញអីវ៉ាន់។" },
  { cn: "他穿着一件白色的衬衫。", pinyin: "Tā chuānzhe yī jiàn báisè de chènshān.", kh: "គាត់ស្លៀកអាវពណ៌សមួយ។" },
  { cn: "我住在一个大城市。", pinyin: "Wǒ zhù zài yīgè dà chéngshì.", kh: "ខ្ញុំរស់នៅក្នុងទីក្រុងមួយធំ។" },
  { cn: "你这次考试成绩很好。", pinyin: "Nǐ zhè cì kǎoshì chéngjì hěn hǎo.", kh: "លទ្ធផលប្រឡងរបស់អ្នកលើកនេះល្អណាស់។" },
  { cn: "地上有很多树叶。", pinyin: "Dì shàng yǒu hěn duō shù yè.", kh: "លើដីមានស្លឹកឈើច្រើន។" },
  { cn: "请打开灯。", pinyin: "Qǐng dǎkāi dēng.", kh: "សូមបើកអំពូល។" },
  { cn: "这个地方很安静。", pinyin: "Zhè ge dìfang hěn ānjìng.", kh: "ទីកន្លែងនេះស្ងប់ស្ងាត់។" },
  { cn: "我们坐地铁去学校。", pinyin: "Wǒmen zuò dìtiě qù xuéxiào.", kh: "ពួកយើងជិះរថភ្លើងក្រោមដីទៅសាលា។" },
  { cn: "你有中国地图吗？", pinyin: "Nǐ yǒu Zhōngguó dìtú ma?", kh: "អ្នកមានផែនទីចិនទេ?" },
  { cn: "请乘电梯上去。", pinyin: "Qǐng chéng diàntī shàng qù.", kh: "សូមជិះជណ្តើរប្រអប់ឡើងលើ។" },
  { cn: "我每天查看电子邮件。", pinyin: "Wǒ měitiān chákàn diànzǐ yóujiàn.", kh: "ខ្ញុំពិនិត្យអ៊ីមែលរៀងរាល់ថ្ងៃ។" },
  { cn: "太阳从东边升起。", pinyin: "Tàiyáng cóng dōngbian shēngqǐ.", kh: "ថ្ងៃឡើងពីខាងកើត។" },
  { cn: "我不喜欢冬天。", pinyin: "Wǒ bù xǐhuān dōngtiān.", kh: "ខ្ញុំមិនចូលចិត្តរដូវរងារឡើយ។" },
  { cn: "动物园里有很多动物。", pinyin: "Dòngwùyuán lǐ yǒu hěn duō dòngwù.", kh: "ក្នុងសួនសត្វមានសត្វជាច្រើន។" },
  { cn: "这条裤子太短了。", pinyin: "Zhè tiáo kùzi tài duǎn le.", kh: "ខោនេះខ្លីពេក។" },
  { cn: "他写了一段话。", pinyin: "Tā xiě le yí duàn huà.", kh: "គាត់បានសរសេរចម្រៀកមួយ។" },
  { cn: "我每天早上锻炼身体。", pinyin: "Wǒ měitiān zǎoshang duànliàn shēntǐ.", kh: "ខ្ញុំហាត់ប្រាណនៅព្រឹករៀងរាល់ថ្ងៃ។" },
  { cn: "他多么聪明啊！", pinyin: "Tā duōme cōngmíng a!", kh: "គាត់ឆ្លាតប៉ុន្មានណា!" },
  { cn: "我很饿，想吃饭。", pinyin: "Wǒ hěn è, xiǎng chīfàn.", kh: "ខ្ញុំឃ្លាន ចង់ញុំាបាយ។" },
  { cn: "她的耳朵很小。", pinyin: "Tā de ěrduo hěn xiǎo.", kh: "ត្រចៀករបស់នាងតូចណាស់។" },
  { cn: "她的头发很长。", pinyin: "Tā de tóufa hěn cháng.", kh: "សក់របស់នាងវែងណាស់។" },
  { cn: "他发烧了，要去看医生。", pinyin: "Tā fāshāo le, yào qù kàn yīshēng.", kh: "គាត់គ្រុន ត្រូវទៅពិនិត្យគ្រូពេទ្យ។" },
  { cn: "我发现他很努力。", pinyin: "Wǒ fāxiàn tā hěn nǔlì.", kh: "ខ្ញុំរកឃើញថាគាត់ខំប្រឹងប្រែងណាស់។" },
  { cn: "坐地铁很方便。", pinyin: "Zuò dìtiě hěn fāngbiàn.", kh: "ជិះរថភ្លើងក្រោមដីងាយស្រួល។" },
  { cn: "请把书放在桌子上。", pinyin: "Qǐng bǎ shū fàng zài zhuōzi shàng.", kh: "សូមដាក់សៀវភៅលើតុ។" },
  { cn: "放心吧，我会帮你。", pinyin: "Fàngxīn ba, wǒ huì bāng nǐ.", kh: "កុំបារម្ភ ខ្ញុំនឹងជួយអ្នក។" },
  { cn: "现在是三点五分。", pinyin: "Xiànzài shì sān diǎn wǔ fēn.", kh: "ឥឡូវនេះម៉ោងបីនាទីប្រាំ។" },
  { cn: "我在复习明天的考试。", pinyin: "Wǒ zài fùxí míngtiān de kǎoshì.", kh: "ខ្ញុំកំពុងពិនិត្យឡើងវិញសម្រាប់ការប្រឡងស្អែក។" },
  { cn: "学校附近有一家咖啡店。", pinyin: "Xuéxiào fùjìn yǒu yì jiā kāfēi diàn.", kh: "នៅជិតសាលាមានហាងកាហ្វេមួយ។" },
  { cn: "你的房间很干净。", pinyin: "Nǐ de fángjiān hěn gānjìng.", kh: "បន្ទប់របស់អ្នកស្អាតណាស់។" },
  { cn: "我感冒了，不能出去。", pinyin: "Wǒ gǎnmào le, bù néng chūqù.", kh: "ខ្ញុំកំពុងផ្តាសាយ មិនអាចចេញទៅក្រៅបានទេ។" },
  { cn: "我对中国文化很感兴趣。", pinyin: "Wǒ duì Zhōngguó wénhuà hěn gǎn xìngqù.", kh: "ខ្ញុំចាប់អារម្មណ៍លើវប្បធម៌ចិន។" },
  { cn: "刚才他来了。", pinyin: "Gāngcái tā lái le.", kh: "ឥឡូវនេះគាត់បានមក។" },
  { cn: "他个子很高。", pinyin: "Tā gèzi hěn gāo.", kh: "គាត់មានកម្ពស់ខ្ពស់។" },
  { cn: "根据天气预报，明天会下雨。", pinyin: "Gēnjù tiānqì yùbào, míngtiān huì xià yǔ.", kh: "យោងតាមការទស្សន៍ទាយអាកាសធាតុ ថ្ងៃស្អែកមានភ្លៀង។" },
  { cn: "我跟他一起去超市。", pinyin: "Wǒ gēn tā yìqǐ qù chāoshì.", kh: "ខ្ញុំទៅផ្សារជាមួយគាត់។" },
  { cn: "这本书更有意思。", pinyin: "Zhè běn shū gèng yǒuyìsi.", kh: "សៀវភៅនេះមានអត្ថន័យច្រើនជាង។" },
  { cn: "这个西瓜有五公斤重。", pinyin: "Zhè ge xīguā yǒu wǔ gōngjīn zhòng.", kh: "ប៊ែរនេះមានទំងន់ប្រាំគីឡូក្រាម។" },
  { cn: "我们去公园散步吧。", pinyin: "Wǒmen qù gōngyuán sànbù ba.", kh: "យើងទៅដើរលេងក្នុងឧទ្យានទៅ។" },
  { cn: "这个故事很感人。", pinyin: "Zhè ge gùshi hěn gǎnrén.", kh: "រឿងនេះគួរឲ្យអារម្មណ៍។" },
  { cn: "今天刮风了，别忘了带帽子。", pinyin: "Jīntiān guā fēng le, bié wàng le dài màozi.", kh: "ថ្ងៃនេះមានខ្យល់ កុំភ្លេចពាក់មួក។" },
  { cn: "请把灯关掉。", pinyin: "Qǐng bǎ dēng guān diào.", kh: "សូមបិទភ្លើង។" },
  { cn: "他们的关系很好。", pinyin: "Tāmen de guānxì hěn hǎo.", kh: "ទំនាក់ទំនងរបស់ពួកគេល្អណាស់។" },
  { cn: "妈妈很关心我。", pinyin: "Māma hěn guānxīn wǒ.", kh: "ម៉ាក់ព្រួយបារម្ភខ្ញុំខ្លាំងណាស់។" },
  { cn: "我想知道关于这本书的内容。", pinyin: "Wǒ xiǎng zhīdào guānyú zhè běn shū de nèiróng.", kh: "ខ្ញុំចង់ដឹងអំពីមាតិកានៃសៀវភៅនេះ។" },
  { cn: "我爱我的国家。", pinyin: "Wǒ ài wǒ de guójiā.", kh: "ខ្ញុំស្រលាញ់ប្រទេសរបស់ខ្ញុំ។" },
  { cn: "他已经过了桥。", pinyin: "Tā yǐjīng guò le qiáo.", kh: "គាត់ឆ្លងស្ពានរួចហើយ។" },
  { cn: "过去的事情不要再想了。", pinyin: "Guòqù de shìqing bú yào zài xiǎng le.", kh: "កុំគិតអំពីអតីតកាលទៀត។" },
  { cn: "你还是早点休息吧。", pinyin: "Nǐ háishi zǎodiǎn xiūxi ba.", kh: "អ្នកនៅតែគួរតែសម្រាកឲ្យមានពេលល្ងាច។" },
  { cn: "她很害怕一个人走夜路。", pinyin: "Tā hěn hàipà yí ge rén zǒu yèlù.", kh: "នាងខ្លាចការដើរល្ងាចតែឯង។" },
  { cn: "老师在黑板上写字。", pinyin: "Lǎoshī zài hēibǎn shàng xiězì.", kh: "គ្រូកំពុងសរសេរនៅលើក្តារខៀន។" },
  { cn: "后来他去了美国。", pinyin: "Hòulái tā qù le Měiguó.", kh: "ក្រោយមកគាត់ទៅអាមេរិក។" },
  { cn: "请出示你的护照。", pinyin: "Qǐng chūshì nǐ de hùzhào.", kh: "សូមបង្ហាញលិខិតឆ្លងដែនរបស់អ្នក។" },
  { cn: "他每天花两个小时学习。", pinyin: "Tā měitiān huā liǎng ge xiǎoshí xuéxí.", kh: "គាត់ចំណាយពេលពីរម៉ោងរៀនរៀងរាល់ថ្ងៃ។" },
  { cn: "这是一朵漂亮的花。", pinyin: "Zhè shì yì duǒ piàoliang de huā.", kh: "នេះជាផ្កាស្អាតមួយ។" },
  { cn: "这幅画是谁画的？", pinyin: "Zhè fú huà shì shéi huà de?", kh: "គំនូរនេះអ្នកណាបានគូររបស់វា?" },
  { cn: "这台电视坏了。", pinyin: "Zhè tái diànshì huài le.", kh: "ទូរទស្សន៍នេះខូចហើយ។" },
  { cn: "欢迎来到我们的学校！", pinyin: "Huānyíng lái dào wǒmen de xuéxiào!", kh: "សូមស្វាគមន៍មកកាន់សាលារបស់យើង!" },
  { cn: "这里的环境很好。", pinyin: "Zhèlǐ de huánjìng hěn hǎo.", kh: "បរិស្ថាននៅទីនេះល្អណាស់។" },
  { cn: "他还没有回家。", pinyin: "Tā hái méiyǒu huíjiā.", kh: "គាត់នៅមិនទាន់ត្រឡប់ទៅផ្ទះនៅឡើយ។" },
  { cn: "我想换一件衣服。", pinyin: "Wǒ xiǎng huàn yí jiàn yīfu.", kh: "ខ្ញុំចង់ផ្លាស់ប្តូរសម្លៀកបំពាក់មួយ។" },
  { cn: "黄河是中国有名的河流。", pinyin: "Huánghé shì Zhōngguó yǒumíng de héliú.", kh: "ទន្លេលឿងគឺជាទន្លែដ៏ល្បីរបស់ចិន។" },
  { cn: "请回答我的问题。", pinyin: "Qǐng huídá wǒ de wèntí.", kh: "សូមឆ្លើយសំណួររបស់ខ្ញុំ។" },
  { cn: "我们明天有一个重要的会议。", pinyin: "Wǒmen míngtiān yǒu yí ge zhòngyào de huìyì.", kh: "យើងមានការប្រជុំសំខាន់មួយថ្ងៃស្អែក។" },
  { cn: "你想喝茶或者咖啡？", pinyin: "Nǐ xiǎng hē chá huòzhě kāfēi?", kh: "អ្នកចង់ផឹកតែឬក៏កាហ្វេ?" },
  { cn: "他几乎每天都跑步。", pinyin: "Tā jīhū měitiān dōu pǎobù.", kh: "គាត់ជិតៗរៀងរាល់ថ្ងៃរត់ហាត់ប្រាណ។" },
  { cn: "这次比赛是一个好机会。", pinyin: "Zhè cì bǐsài shì yí ge hǎo jīhuì.", kh: "ការប្រកួតនេះជាឱកាសល្អ។" },
  { cn: "这个地方美极了。", pinyin: "Zhège dìfāng měi jí le.", kh: "ទីកន្លែងនេះស្អាតខ្លាំងណាស់។" },
  { cn: "中国有四个季节。", pinyin: "Zhōngguó yǒu sì gè jìjié.", kh: "ប្រទេសចិនមានបួនរដូវ។" },
  { cn: "我还记得你说的话。", pinyin: "Wǒ hái jìde nǐ shuō de huà.", kh: "ខ្ញុំតើនៅចងចាំអ្វីដែលអ្នកបាននិយាយ។" },
  { cn: "医生在检查病人。", pinyin: "Yīshēng zài jiǎnchá bìngrén.", kh: "វេជ្ជបណ្ឌិតកំពុងត្រួតពិនិត្យអ្នកជំងឺ។" },
  { cn: "这个问题很简单。", pinyin: "Zhè ge wèntí hěn jiǎndān.", kh: "សំណួរនេះសាមញ្ញណាស់។" },
  { cn: "每天锻炼对健康有好处。", pinyin: "Měitiān duànliàn duì jiànkāng yǒu hǎochù.", kh: "ហាត់ប្រាណរៀងរាល់ថ្ងៃល្អសម្រាប់សុខភាព។" },
  { cn: "我们明天见面吧。", pinyin: "Wǒmen míngtiān jiànmiàn ba.", kh: "យើងជួបគ្នាថ្ងៃស្អែកទៅ។" },
  { cn: "老师正在讲课。", pinyin: "Lǎoshī zhèngzài jiǎngkè.", kh: "គ្រូកំពុងបង្រៀនមេរៀន។" },
  { cn: "他教我们汉语。", pinyin: "Tā jiào wǒmen Hànyǔ.", kh: "គាត់បង្រៀនភាសាចិនឲ្យយើង។" },
  { cn: "我的脚很疼。", pinyin: "Wǒ de jiǎo hěn téng.", kh: "ជើងខ្ញុំឈឺណាស់។" },
  { cn: "请你站在这个角。", pinyin: "Qǐng nǐ zhàn zài zhège jiǎo.", kh: "សូមអ្នកឈរនៅមុំនេះ។" },
  { cn: "我去机场接他。", pinyin: "Wǒ qù jīchǎng jiē tā.", kh: "ខ្ញុំទៅទទួលគាត់នៅអាកាសយានដ្ឋាន។" },
  { cn: "这条街道很热闹。", pinyin: "Zhè tiáo jiēdào hěn rènào.", kh: "ផ្លូវនេះសន្ធឹកសន្ធាប់ណាស់។" },
  { cn: "他们下个月要结婚了。", pinyin: "Tāmen xià gè yuè yào jiéhūn le.", kh: "ពួកគេនឹងរៀបការខែក្រោយ។" },
  { cn: "比赛已经结束了。", pinyin: "Bǐsài yǐjīng jiéshù le.", kh: "ការប្រកួតបានបញ្ចប់រួចហើយ។" },
  { cn: "我最喜欢这个节目。", pinyin: "Wǒ zuì xǐhuān zhège jiémù.", kh: "ខ្ញុំចូលចិត្តកម្មវិធីនេះបំផុត។" },
  { cn: "春节是中国的重要节日。", pinyin: "Chūnjié shì Zhōngguó de zhòngyào jiérì.", kh: "បុណ្យចូលឆ្នាំគឺជាពិធីបុណ្យសំខាន់របស់ចិន។" },
  { cn: "我们需要想办法解决问题。", pinyin: "Wǒmen xūyào xiǎng bànfǎ jiějué wèntí.", kh: "យើងត្រូវគិតវិធីដោះស្រាយបញ្ហា។" },
  { cn: "我可以借一下你的笔吗？", pinyin: "Wǒ kěyǐ jiè yíxià nǐ de bǐ ma?", kh: "ខ្ញុំអាចខ្ចីប៊ិចរបស់អ្នកបន្តិចបានទេ?" },
  { cn: "我经常去图书馆看书。", pinyin: "Wǒ jīngcháng qù túshūguǎn kànshū.", kh: "ខ្ញុំជាញឹកញាប់ទៅបណ្ណាល័យអានសៀវភៅ។" },
  { cn: "经过努力，他终于成功了。", pinyin: "Jīngguò nǔlì, tā zhōngyú chénggōng le.", kh: "បន្ទាប់ពីការខិតខំគាត់បានជោគជ័យជាទីបញ្ចប់។" },
  { cn: "他是我们公司的经理。", pinyin: "Tā shì wǒmen gōngsī de jīnglǐ.", kh: "គាត់គឺជាអ្នកគ្រប់គ្រងនៃក្រុមហ៊ុនយើង។" },
  { cn: "我等了他很久了。", pinyin: "Wǒ děng le tā hěn jiǔ le.", kh: "ខ្ញុំរង់ចាំគាត់យូរហើយ។" },
  { cn: "这辆车太旧了。", pinyin: "Zhè liàng chē tài jiù le.", kh: "រថយន្តនេះចាស់ហើយ។" },
  { cn: "请你造一个句子。", pinyin: "Qǐng nǐ zào yí gè jùzi.", kh: "សូមអ្នកបង្កើតប្រយោគមួយ។" },
  { cn: "我决定明年去中国。", pinyin: "Wǒ juédìng míngnián qù Zhōngguó.", kh: "ខ្ញុំសម្រេចចិត្តទៅប្រទេសចិនឆ្នាំក្រោយ។" },
  { cn: "这只小猫真可爱！", pinyin: "Zhè zhī xiǎo māo zhēn kě’ài!", kh: "កូនឆ្មានេះគួរឱ្យស្រឡាញ់ណាស់!" },
  { cn: "我很渴，想喝水。", pinyin: "Wǒ hěn kě, xiǎng hē shuǐ.", kh: "ខ្ញុំស្រកានេះចង់ផឹកទឹក។" },
  { cn: "现在是三点一刻。", pinyin: "Xiànzài shì sān diǎn yí kè.", kh: "ឥឡូវម៉ោងបីម៉ោងកន្លះ។" },
  { cn: "有客人来了。", pinyin: "Yǒu kèrén lái le.", kh: "មានភ្ញៀវមកហើយ។" },
  { cn: "我家有两台空调。", pinyin: "Wǒ jiā yǒu liǎng tái kōngtiáo.", kh: "ផ្ទះខ្ញុំមានម៉ាស៊ីនត្រជាក់ពីរដុំ។" },
  { cn: "张开你的口。", pinyin: "Zhāng kāi nǐ de kǒu.", kh: "បើកមាត់របស់អ្នក។" },
  { cn: "小孩在哭。", pinyin: "Xiǎohái zài kū.", kh: "ក្មេងកំពុងយំ។" },
  { cn: "他买了一条新裤子。", pinyin: "Tā mǎi le yì tiáo xīn kùzi.", kh: "គាត់ទិញខោថ្មីមួយ។" },
  { cn: "我不会用筷子。", pinyin: "Wǒ bú huì yòng kuàizi.", kh: "ខ្ញុំមិនចេះប្រើចង្កឹះទេ។" },
  { cn: "今天的天空很蓝。", pinyin: "Jīntiān de tiānkōng hěn lán.", kh: "មេឃថ្ងៃនេះខៀវណាស់។" },
  { cn: "他是一位老老师。", pinyin: "Tā shì yí wèi lǎo lǎoshī.", kh: "គាត់ជាគ្រូចាស់ម្នាក់។" },
  { cn: "他已经离开学校了。", pinyin: "Tā yǐjīng líkāi xuéxiào le.", kh: "គាត់បានចាកចេញពីសាលា។" },
  { cn: "这是我送给你的礼物。", pinyin: "Zhè shì wǒ sòng gěi nǐ de lǐwù.", kh: "នេះជាអំណោយខ្ញុំផ្ញើអោយអ្នក។" },
  { cn: "我对中国历史很感兴趣。", pinyin: "Wǒ duì Zhōngguó lìshǐ hěn gǎn xìngqù.", kh: "ខ្ញុំចូលចិត្តប្រវត្តិសាស្ត្រចិន។" },
  { cn: "她的脸红了。", pinyin: "Tā de liǎn hóng le.", kh: "មុខរបស់នាងក្រហម។" },
  { cn: "请大家认真练习。", pinyin: "Qǐng dàjiā rènzhēn liànxí.", kh: "សូមអ្នកទាំងអស់គ្នាធ្វើលំហាត់អោយម៉ត់ចត់។" },
  { cn: "我有一辆新车。", pinyin: "Wǒ yǒu yí liàng xīn chē.", kh: "ខ្ញុំមានរថយន្តថ្មីមួយគ្រឿង។" },
  { cn: "我们一起聊天吧。", pinyin: "Wǒmen yìqǐ liáotiān ba.", kh: "យើងជជែកគ្នាផង។" },
  { cn: "我很了解他。", pinyin: "Wǒ hěn liǎojiě tā.", kh: "ខ្ញុំយល់ច្បាស់អំពីគាត់។" },
  { cn: "我的邻居很友好。", pinyin: "Wǒ de línjū hěn yǒuhǎo.", kh: "អ្នកជិតខាងរបស់ខ្ញុំគឺរួសរាយណាស់។" },
  { cn: "他去美国留学了。", pinyin: "Tā qù Měiguó liúxué le.", kh: "គាត់ទៅសិក្សានៅអាមេរិក។" },
  { cn: "我住在五楼。", pinyin: "Wǒ zhù zài wǔ lóu.", kh: "ខ្ញុំស្នាក់នៅជាន់ទីប្រាំ។" },
  { cn: "他穿了一件绿衣服。", pinyin: "Tā chuān le yí jiàn lǜ yīfu.", kh: "គាត់ពាក់អាវបៃតងមួយ។" },
  { cn: "那是一匹马。", pinyin: "Nà shì yì pǐ mǎ.", kh: "នោះជាសេះមួយក្បាល។" },
  { cn: "他马上就回来。", pinyin: "Tā mǎshàng jiù huílái.", kh: "គាត់នឹងត្រលប់មកភ្លាមៗ។" },
  { cn: "我对这次服务很满意。", pinyin: "Wǒ duì zhè cì fúwù hěn mǎnyì.", kh: "ខ្ញុំពេញចិត្តសេវាកម្មនេះណាស់។" },
  { cn: "他戴了一顶帽子。", pinyin: "Tā dài le yì dǐng màozi.", kh: "គាត់ពាក់មួកមួយ។" },
  { cn: "我们买了一公斤米。", pinyin: "Wǒmen mǎi le yì gōngjīn mǐ.", kh: "យើងបានទិញអង្ករមួយគីឡូ។" },
  { cn: "早餐我吃了面包。", pinyin: "Zǎocān wǒ chī le miànbāo.", kh: "អាហារពេលព្រឹកខ្ញុំបានញ៉ាំនំបុ័ង។" },
  { cn: "我明白你的意思了。", pinyin: "Wǒ míngbai nǐ de yìsi le.", kh: "ខ្ញុំយល់ន័យរបស់អ្នកហើយ។" },
  { cn: "请你帮我拿一下那个。", pinyin: "Qǐng nǐ bāng wǒ ná yīxià nàgè.", kh: "សូមជួយយកអីវ៉ាន់នោះឲ្យខ្ញុំផង។" },
  { cn: "我奶奶住在农村。", pinyin: "Wǒ nǎinai zhù zài nóngcūn.", kh: "ជីដូនខ្ញុំរស់នៅជនបទ។" },
  { cn: "他们从南边走过来。", pinyin: "Tāmen cóng nánbian zǒu guòlái.", kh: "ពួកគេដើរមកពីខាងត្បូង។" },
  { cn: "这个问题很难。", pinyin: "Zhège wèntí hěn nán.", kh: "សំណួរនេះពិបាកណាស់។" },
  { cn: "她听到这个消息很难过。", pinyin: "Tā tīngdào zhège xiāoxi hěn nánguò.", kh: "នាងសោកសៅណាស់ពេលឮដំណឹងនេះ។" },
  { cn: "我现在上五年级。", pinyin: "Wǒ xiànzài shàng wǔ niánjí.", kh: "ខ្ញុំសុខស្រួលថ្នាក់ទីប្រាំ។" },
  { cn: "他看起来很年轻。", pinyin: "Tā kàn qǐlái hěn niánqīng.", kh: "គាត់មើលទៅវ័យក្មេងណាស់។" },
  { cn: "树上有一只鸟。", pinyin: "Shù shàng yǒu yì zhī niǎo.", kh: "មានបក្សីមួយនៅលើដើមឈើ។" },
  { cn: "她每天都很努力学习。", pinyin: "Tā měitiān dōu hěn nǔlì xuéxí.", kh: "នាងខិតខំសិក្សារៀងរាល់ថ្ងៃ។" },
  { cn: "我们周末去爬山吧！", pinyin: "Wǒmen zhōumò qù páshān ba!", kh: "ថ្ងៃចុងសប្ដាហ៍យើងទៅឡើងភ្នំណា!" },
  { cn: "请把盘子放在桌子上。", pinyin: "Qǐng bǎ pánzi fàng zài zhuōzi shàng.", kh: "សូមដាក់ចាននៅលើតុ។" },
  { cn: "他吃得太多，变胖了。", pinyin: "Tā chī de tài duō, biàn pàng le.", kh: "គាត់ញ៉ាំច្រើនពេក ប៉ុន្តែធាត់ទៅ។" },
  { cn: "我不喝啤酒。", pinyin: "Wǒ bù hē píjiǔ.", kh: "ខ្ញុំមិនញ៉ាំស្រាបៀរទេ។" },
  { cn: "这双皮鞋很贵。", pinyin: "Zhè shuāng píxié hěn guì.", kh: "ស្បែកជើងស្បែកនេះថ្លៃណាស់។" },
  { cn: "瓶子里有水。", pinyin: "Píngzi lǐ yǒu shuǐ.", kh: "មានទឹកក្នុងដប។" },
  { cn: "其实我早就知道了。", pinyin: "Qíshí wǒ zǎo jiù zhīdào le.", kh: "ពិតប្រាកដថាខ្ញុំដឹងហើយ។" },
  { cn: "除了他以外，其他人都到了。", pinyin: "Chúle tā yǐwài, qítā rén dōu dàole.", kh: "ក្រៅពីគាត់ មានអ្នកផ្សេងទៀតមកដល់អស់ហើយ។" },
  { cn: "这件事太奇怪了！", pinyin: "Zhè jiàn shì tài qíguài le!", kh: "រឿងនេះចម្លែកណាស់!" },
  { cn: "他每天骑自行车上学。", pinyin: "Tā měitiān qí zìxíngchē shàngxué.", kh: "គាត់ជិះកង់ទៅសាលារៀនរៀងរាល់ថ្ងៃ។" },
  { cn: "飞机马上就要起飞了。", pinyin: "Fēijī mǎshàng jiù yào qǐfēi le.", kh: "យន្តហោះនឹងហោះចេញឆាប់ៗនេះ។" },
  { cn: "他从地上站起来了。", pinyin: "Tā cóng dìshàng zhàn qǐlái le.", kh: "គាត់ឈរឡើងពីដី។" },
  { cn: "我听得很清楚。", pinyin: "Wǒ tīng de hěn qīngchu.", kh: "ខ្ញុំបានស្តាប់ច្បាស់ណាស់។" },
  { cn: "我明天想请假一天。", pinyin: "Wǒ míngtiān xiǎng qǐngjià yītiān.", kh: "ខ្ញុំចង់សុំឈប់សម្រាកមួយថ្ងៃស្អែក។" },
  { cn: "秋天的天气很凉爽。", pinyin: "Qiūtiān de tiānqì hěn liángshuǎng.", kh: "អាកាសធាតុរដូវស្លឹកឈើជ្រុះត្រជាក់តិចៗ។" },
  { cn: "她穿了一条新裙子。", pinyin: "Tā chuān le yì tiáo xīn qúnzi.", kh: "នាងស្លៀកសំពត់ថ្មីមួយ។" },
  { cn: "我先吃饭，然后看电影。", pinyin: "Wǒ xiān chīfàn, ránhòu kàn diànyǐng.", kh: "ខ្ញុំញ៉ាំបាយសិន បន្ទាប់មកមើលភាពយន្ត។" },
  { cn: "他是一个很热情的人。", pinyin: "Tā shì yí gè hěn rèqíng de rén.", kh: "គាត់ជាមនុស្សដែលមានភាពកក់ក្តៅ។" },
  { cn: "我认为这样做更好。", pinyin: "Wǒ rènwéi zhèyàng zuò gèng hǎo.", kh: "ខ្ញុំគិតថាធ្វើបែបនេះល្អជាង។" },
  { cn: "她学习很认真。", pinyin: "Tā xuéxí hěn rènzhēn.", kh: "នាងសិក្សាយ៉ាងយកចិត្តទុកដាក់។" },
  { cn: "这个问题很容易。", pinyin: "Zhège wèntí hěn róngyì.", kh: "សំណួរនេះងាយស្រួលណាស់។" },
  { cn: "如果你有问题，就问我吧。", pinyin: "Rúguǒ nǐ yǒu wèntí, jiù wèn wǒ ba.", kh: "ប្រសិនបើអ្នកមានសំណួរ សូមសួរខ្ញុំ។" },
  { cn: "别忘了带伞。", pinyin: "Bié wàng le dài sǎn.", kh: "កុំភ្លេចយកឆ័ត្រជាមួយផង។" },
  { cn: "我每天都上网学习中文。", pinyin: "Wǒ měitiān dōu shàngwǎng xuéxí zhōngwén.", kh: "ខ្ញុំឡើងអ៊ីនធឺណិតរៀងរាល់ថ្ងៃដើម្បីសិក្សាភាសាចិន។" },
  { cn: "我听不清楚你的声音。", pinyin: "Wǒ tīng bù qīngchu nǐ de shēngyīn.", kh: "ខ្ញុំមិនស្តាប់សំឡេងអ្នកបានច្បាស់ទេ។" },
  { cn: "她生气地走了。", pinyin: "Tā shēngqì de zǒu le.", kh: "នាងចេញទៅដោយសំណើចសម្បួន។" },
  { cn: "世界很大，我们要去看看。", pinyin: "Shìjiè hěn dà, wǒmen yào qù kànkan.", kh: "ពិភពលោកធំណាស់ យើងត្រូវទៅមើលផង។" },
  { cn: "你可以试试看这个方法。", pinyin: "Nǐ kěyǐ shì shìkàn zhège fāngfǎ.", kh: "អ្នកអាចសាកល្បងវិធីនេះមើលបាន។" },
  { cn: "他最近瘦了很多。", pinyin: "Tā zuìjìn shòu le hěn duō.", kh: "បច្ចុប្បន្នគាត់ស្គមទៅច្រើន។" },
  { cn: "叔叔给我买了礼物。", pinyin: "Shūshu gěi wǒ mǎi le lǐwù.", kh: "ពូបានទិញអំណោយឲ្យខ្ញុំ។" },
  { cn: "这个房间很舒服。", pinyin: "Zhège fángjiān hěn shūfu.", kh: "បន្ទប់នេះមានផាសុខភាពណាស់។" },
  { cn: "我喜欢数学课。", pinyin: "Wǒ xǐhuān shùxué kè.", kh: "ខ្ញុំចូលចិត្តម៉ោងគណិតវិទ្យា។" },
  { cn: "这是一棵大树。", pinyin: "Zhè shì yī kē dà shù.", kh: "នេះជាដើមឈើធំមួយ។" },
  { cn: "每天早上我要刷牙。", pinyin: "Měitiān zǎoshang wǒ yào shuāyá.", kh: "រៀងរាល់ព្រឹកខ្ញុំត្រូវដុសធ្មេញ។" },
  { cn: "我买了一双新鞋。", pinyin: "Wǒ mǎi le yī shuāng xīn xié.", kh: "ខ្ញុំទិញស្បែកជើងថ្មីមួយគូ។" },
  { cn: "你的中文水平很高。", pinyin: "Nǐ de zhōngwén shuǐpíng hěn gāo.", kh: "កំរិតភាសាចិនរបស់អ្នកខ្ពស់ណាស់។" },
  { cn: "司机开车很小心。", pinyin: "Sījī kāichē hěn xiǎoxīn.", kh: "អ្នកបើកបរបើកឡានយ៉ាងប្រុងប្រយ័ត្ន។" },
  { cn: "太阳从东边升起来。", pinyin: "Tàiyáng cóng dōngbiān shēng qǐlái.", kh: "ព្រះអាទិត្យរះពីខាងកើត។" },
  { cn: "今天特别冷。", pinyin: "Jīntiān tèbié lěng.", kh: "ថ្ងៃនេះត្រជាក់ជាពិសេស។" },
  { cn: "我头很疼。", pinyin: "Wǒ tóu hěn téng.", kh: "ខ្ញុំឈឺក្បាល។" },
  { cn: "我想提高我的汉语水平。", pinyin: "Wǒ xiǎng tígāo wǒ de hànyǔ shuǐpíng.", kh: "ខ្ញុំចង់បង្កើនកំរិតភាសាចិនរបស់ខ្ញុំ។" },
  { cn: "我们学校有很多体育活动。", pinyin: "Wǒmen xuéxiào yǒu hěn duō tǐyù huódòng.", kh: "សាលារបស់យើងមានសកម្មភាពកីឡាជាច្រើន។" },
  { cn: "这个苹果很甜。", pinyin: "Zhège píngguǒ hěn tián.", kh: "ផ្លែប៉ោមនេះផ្អែមណាស់។" },
  { cn: "这条裤子很漂亮。", pinyin: "Zhè tiáo kùzi hěn piàoliang.", kh: "ខោនេះស្អាតណាស់។" },
  { cn: "我和同事一起吃午饭。", pinyin: "Wǒ hé tóngshì yīqǐ chī wǔfàn.", kh: "ខ្ញុំហូបបាយថ្ងៃត្រង់ជាមួយមិត្តរួមការងារ។" },
  { cn: "我同意你的意见。", pinyin: "Wǒ tóngyì nǐ de yìjiàn.", kh: "ខ្ញុំយល់ព្រមនឹងយោបល់របស់អ្នក។" },
  { cn: "她的头发很长。", pinyin: "Tā de tóufa hěn cháng.", kh: "សក់របស់នាងវែងណាស់។" },
  { cn: "他突然跑了出去。", pinyin: "Tā tūrán pǎo le chūqù.", kh: "គាត់ភ្លាមៗរត់ចេញទៅ។" },
  { cn: "图书馆里很安静。", pinyin: "Túshūguǎn lǐ hěn ānjìng.", kh: "នៅក្នុងបណ្ណាល័យស្ងៀមស្ងាត់ណាស់។" },
  { cn: "我的腿有点疼。", pinyin: "Wǒ de tuǐ yǒudiǎn téng.", kh: "ជើងខ្ញុំឈឺបន្តិច។" },
  { cn: "我已经完成了作业。", pinyin: "Wǒ yǐjīng wánchéng le zuòyè.", kh: "ខ្ញុំបានអនុវត្តការងារផ្ទះរួចហើយ។" },
  { cn: "我吃了一碗米饭。", pinyin: "Wǒ chī le yī wǎn mǐfàn.", kh: "ខ្ញុំបានញ៉ាំបាយមួយចាន។" },
  { cn: "这里有一万个人。", pinyin: "Zhèlǐ yǒu yī wàn gè rén.", kh: "ទីនេះមានមនុស្សមួយម៉ឺននាក់។" },
  { cn: "我忘记带手机了。", pinyin: "Wǒ wàngjì dài shǒujī le.", kh: "ខ្ញុំភ្លេចយកទូរស័ព្ទ។" },
  { cn: "这本书是为你买的。", pinyin: "Zhè běn shū shì wèi nǐ mǎi de.", kh: "សៀវភៅនេះខ្ញុំទិញសម្រាប់អ្នក។" },
  { cn: "他努力学习是为了通过考试。", pinyin: "Tā nǔlì xuéxí shì wèile tōngguò kǎoshì.", kh: "គាត់ខិតខំសិក្សាដើម្បីឲ្យប្រឡងជាប់។" },
  { cn: "这位老师很有经验。", pinyin: "Zhè wèi lǎoshī hěn yǒu jīngyàn.", kh: "គ្រូរូបនេះមានបទពិសោធន៍ខ្លាំង។" },
  { cn: "中国有丰富的文化。", pinyin: "Zhōngguó yǒu fēngfù de wénhuà.", kh: "ប្រទេសចិនមានវប្បធម៌សម្បូរបែប។" },
  { cn: "太阳从西边落下。", pinyin: "Tàiyáng cóng xībiān luò xià.", kh: "ព្រះអាទិត្យលិចពីខាងលិច។" },
  { cn: "我已经养成了早起的习惯。", pinyin: "Wǒ yǐjīng yǎngchéng le zǎoqǐ de xíguàn.", kh: "ខ្ញុំបានមានទំលាប់ឡើងដើមថ្ងៃ។" },
  { cn: "请问洗手间在哪里？", pinyin: "Qǐngwèn xǐshǒujiān zài nǎlǐ?", kh: "សូមសួរ បន្ទប់ទឹកនៅឯណា?" },
  { cn: "我每天晚上都洗澡。", pinyin: "Wǒ měitiān wǎnshàng dōu xǐzǎo.", kh: "ខ្ញុំងូតទឹករៀងរាល់ល្ងាច។" },
  { cn: "夏天的天气很热。", pinyin: "Xiàtiān de tiānqì hěn rè.", kh: "អាកាសធាតុរដូវក្តៅក្តៅណាស់។" },
  { cn: "你先走吧，我马上来。", pinyin: "Nǐ xiān zǒu ba, wǒ mǎshàng lái.", kh: "អ្នកទៅដំបូងទៅ ខ្ញុំមកភ្លាមៗ។" },
  { cn: "我相信你能做到。", pinyin: "Wǒ xiāngxìn nǐ néng zuò dào.", kh: "ខ្ញុំជឿថាអ្នកអាចធ្វើបាន។" },
  { cn: "我喜欢吃香蕉。", pinyin: "Wǒ xǐhuān chī xiāngjiāo.", kh: "ខ្ញុំចូលចិត្តញ៉ាំចេក។" },
  { cn: "他长得像他的爸爸。", pinyin: "Tā zhǎng de xiàng tā de bàba.", kh: "គាត់មានរូបសម្បត្តិស្រដៀងឪពុក។" },
  { cn: "我们向老师请教问题。", pinyin: "Wǒmen xiàng lǎoshī qǐngjiào wèntí.", kh: "យើងសួរគ្រូអំពីសំណួរ។" },
  { cn: "过马路要小心。", pinyin: "Guò mǎlù yào xiǎoxīn.", kh: "ឆ្លងផ្លូវត្រូវប្រុងប្រយ័ត្ន។" },
  { cn: "我们的校长很严格。", pinyin: "Wǒmen de xiàozhǎng hěn yángé.", kh: "នាយកសាលារបស់យើងតឹងរ៉ឹងណាស់។" },
  { cn: "我每天都看新闻。", pinyin: "Wǒ měitiān dōu kàn xīnwén.", kh: "ខ្ញុំមើលព័ត៌មានរៀងរាល់ថ្ងៃ។" },
  { cn: "这些水果都很新鲜。", pinyin: "Zhèxiē shuǐguǒ dōu hěn xīnxiān.", kh: "ផ្លែឈើទាំងនេះស្រស់ណាស់។" },
  { cn: "我用信用卡付款。", pinyin: "Wǒ yòng xìnyòngkǎ fùkuǎn.", kh: "ខ្ញុំប្រើកាតឥណទានក្នុងការបង់ប្រាក់។" },
  { cn: "我带了一个行李箱。", pinyin: "Wǒ dài le yī gè xínglǐxiāng.", kh: "ខ្ញុំយកប្រអប់សំភារៈមួយទៅ។" },
  { cn: "熊猫是中国的国宝。", pinyin: "Xióngmāo shì Zhōngguó de guóbǎo.", kh: "ខ្លាឃ្មុំផេនដា គឺជាទ្រព្យសម្បត្តិជាតិរបស់ចិន។" },
  { cn: "我需要一杯水。", pinyin: "Wǒ xūyào yī bēi shuǐ.", kh: "ខ្ញុំត្រូវការទឹកមួយកែវ។" },
  { cn: "你可以选择你喜欢的颜色。", pinyin: "Nǐ kěyǐ xuǎnzé nǐ xǐhuān de yánsè.", kh: "អ្នកអាចជ្រើសរើសពណ៌ដែលអ្នកចូលចិត្ត។" },
  { cn: "我有很多要求。", pinyin: "Wǒ yǒu hěn duō yāoqiú.", kh: "ខ្ញុំមានការទាមទារជាច្រើន។" },
  { cn: "我的爷爷很喜欢钓鱼。", pinyin: "Wǒ de yéye hěn xǐhuān diàoyú.", kh: "ជីតារបស់ខ្ញុំចូលចិត្តលេងត្រី។" },
  { cn: "他一直在学习。", pinyin: "Tā yīzhí zài xuéxí.", kh: "គាត់ជានិច្ចកំពុងសិក្សា។" },
  { cn: "你一定会成功的。", pinyin: "Nǐ yídìng huì chénggōng de.", kh: "អ្នកប្រាកដជោជ័យបាន។" },
  { cn: "一共多少钱？", pinyin: "Yī gòng duōshǎo qián?", kh: "សរុបមានថ្លៃប៉ុន្មាន?" },
  { cn: "等一会儿，我马上来。", pinyin: "Děng yī huì er, wǒ mǎ shàng lái.", kh: "រង់ចាំមួយរយៈ ខ្ញុំនឹងមកភ្លាមៗ។" },
  { cn: "你看起来和我一样。", pinyin: "Nǐ kàn qǐlái hé wǒ yīyàng.", kh: "អ្នកមើលទៅដូចខ្ញុំ។" },
  { cn: "我以前住在北京。", pinyin: "Wǒ yǐqián zhù zài Běijīng.", kh: "ខ្ញុំបានរស់នៅប៉េគិចមុននេះ។" },
  { cn: "这个问题一般都很简单。", pinyin: "Zhège wèntí yī bān dōu hěn jiǎndān.", kh: "សំណួរនេះទូទៅគឺអាចចុះចេញបានយ៉ាងងាយស្រួល។" },
  { cn: "我一边做作业一边听音乐。", pinyin: "Wǒ yī biān zuò zuòyè yī biān tīng yīnyuè.", kh: "ខ្ញុំធ្វើការងាររៀននៅក្នុងពេលកំណត់ខ្សែអក្សរដូចគ្នា។" },
  { cn: "我喜欢听音乐。", pinyin: "Wǒ xǐhuān tīng yīnyuè.", kh: "ខ្ញុំចូលចិត្តស្តាប់តន្ត្រី។" },
  { cn: "银行就在前面。", pinyin: "Yínháng jiù zài qiánmiàn.", kh: "ធនាគារមាននៅខាងមុខ។" },
  { cn: "我喝了一杯饮料。", pinyin: "Wǒ hē le yī bēi yǐnliào.", kh: "ខ្ញុំផឹកភេសជ្ជៈមួយកែវ។" },
  { cn: "你应该早一点起床。", pinyin: "Nǐ yīng gāi zǎo yīdiǎn qǐchuáng.", kh: "អ្នកគួរតែភ្លាមៗត្រូវបានឡើងរាប់លើពេលព្រឹក។" },
  { cn: "这会影响我的决定。", pinyin: "Zhè huì yǐngxiǎng wǒ de juédìng.", kh: "រឿងនេះនឹងមានឥទ្ធិពលលើការសម្រេចចិត្តរបស់ខ្ញុំ។" },
  { cn: "我用手机看电影。", pinyin: "Wǒ yòng shǒujī kàn diànyǐng.", kh: "ខ្ញុំប្រើទូរស័ព្ទដើម្បីមើលភាពយន្ត។" },
  { cn: "我喜欢玩游戏。", pinyin: "Wǒ xǐhuān wán yóuxì.", kh: "ខ្ញុំចូលចិត្តលេងហ្គេម។" },
  { cn: "他是一个有名的歌手。", pinyin: "Tā shì yīgè yǒumíng de gēshǒu.", kh: "គាត់ជាកូនក្មេងល្បីនៅក្នុងវិស័យសេដ្ឋកិច្ច។" },
  { cn: "我又忘记带钥匙了。", pinyin: "Wǒ yòu wàngjì dài yàoshi le.", kh: "ខ្ញុំវិញភ្លេចយកសោចូលទ្វារ។" },
  { cn: "我们遇到了一些困难。", pinyin: "Wǒmen yù dào le yīxiē kùn nán.", kh: "យើងជួបប្រទៈនឹងការលំបាកខ្លះៗ។" },
  { cn: "这件衣服是100元。", pinyin: "Zhè jiàn yīfú shì 100 yuán.", kh: "សម្លៀកបំពាក់នេះមានតម្លៃ100យន់។" },
  { cn: "我愿意帮忙。", pinyin: "Wǒ yuànyì bāngmáng.", kh: "ខ្ញុំមានឆន្ទៈជួយឱ្យ។" },
  { cn: "月亮今晚很明亮。", pinyin: "Yuèliàng jīn wǎn hěn míng liàng.", kh: "ព្រះច័ន្ទនៅយប់នេះច្បាស់ណាស់។" },
  { cn: "越努力越成功。", pinyin: "Yuè nǔlì yuè chénggōng.", kh: "ច越ខិតខំធ្វើអោយបានតែលើអាកាសធាតុប្រកួតប្រជែង។" },
  { cn: "火车站就在前面。", pinyin: "Huǒchē zhàn jiù zài qián miàn.", kh: "ស្ថានីយ៍រថភ្លើងនៅកន្លែងខាងមុខ។" },
  { cn: "我张开嘴巴。", pinyin: "Wǒ zhāng kāi zuǐ ba.", kh: "ខ្ញុំបើកមាត់។" },
  { cn: "这个问题很长。", pinyin: "Zhège wèntí hěn cháng.", kh: "សំណួរនេះវែងណាស់។" },
  { cn: "他很着急。", pinyin: "Tā hěn zháo jí.", kh: "គាត់ព្រួយបារម្ភណាស់។" },
  { cn: "她照顾我。", pinyin: "Tā zhào gu wǒ.", kh: "នាងថែរក្សាខ្ញុំ។" },
  { cn: "这是我最喜欢的照片。", pinyin: "Zhè shì wǒ zuì xǐhuān de zhàopiàn.", kh: "នេះគឺរូបថតដែលខ្ញុំចូលចិត្តបំផុត។" },
  { cn: "我有一台照相机。", pinyin: "Wǒ yǒu yī tái zhàoxiàngjī.", kh: "ខ្ញុំមានកាមេរ៉ាមួយ។" },
  { cn: "我只喝水。", pinyin: "Wǒ zhǐ hē shuǐ.", kh: "ខ្ញុំតែផឹកទឹក។" },
  { cn: "这只是一个例子。", pinyin: "Zhè zhǐ shì yīgè lìzi.", kh: "នេះគឺតែជាឧទាហរណ៍មួយ។" },
  { cn: "只有努力才会成功。", pinyin: "Zhǐ yǒu nǔlì cái huì chénggōng.", kh: "តែការខិតខំប្រឹងប្រែងប៉ុណ្ណោះដែលនឹងធ្វើអោយបានជោគជ័យ។" },
  { cn: "书在桌子中间。", pinyin: "Shū zài zhuōzi zhōngjiān.", kh: "សៀវភៅនៅចំកណ្តាលតុ។" },
  { cn: "我会说中文。", pinyin: "Wǒ huì shuō zhōng wén.", kh: "ខ្ញុំអាចនិយាយភាសាចិន។" },
  { cn: "我们终于到了。", pinyin: "Wǒmen zhōng yú dào le.", kh: "យើងបានមកដល់ចុងក្រោយហើយ។" },
  { cn: "这是一种新的方式。", pinyin: "Zhè shì yī zhǒng xīn de fāngshì.", kh: "នេះគឺជាវិធីថ្មីមួយ។" },
  { cn: "这件事非常重要。", pinyin: "Zhè jiàn shì fēicháng zhòng yào.", kh: "រឿងនេះសំខាន់ណាស់។" },
  { cn: "周末我们去旅游。", pinyin: "Zhōumò wǒmen qù lǚyóu.", kh: "ចុងសប្តាហ៍យើងទៅធ្វើដំណើរ។" },
  { cn: "这是我主要的工作。", pinyin: "Zhè shì wǒ zhǔ yào de gōngzuò.", kh: "នេះគឺជាការងារមូលដ្ឋានរបស់ខ្ញុំ។" },
  { cn: "请注意安全。", pinyin: "Qǐng zhù yì ānquán.", kh: "សូមប្រុងប្រយ័ត្នអំពីសុវត្ថិភាព។" },
  { cn: "我自己做的。", pinyin: "Wǒ zìjǐ zuò de.", kh: "ខ្ញុំធ្វើវាដោយខ្លួនឯង។" },
  { cn: "我骑自行车去学校。", pinyin: "Wǒ qí zìxíngchē qù xuéxiào.", kh: "ខ្ញុំជិះកង់ទៅសាលា។" },
  { cn: "他总是很高兴。", pinyin: "Tā zǒng shì hěn gāo xìng.", kh: "គាត់តែងតែរីករាយ។" },
  { cn: "他的嘴很大。", pinyin: "Tā de zuǐ hěn dà.", kh: "មាត់របស់គាត់ធំណាស់។" },
  { cn: "这是最后一次机会。", pinyin: "Zhè shì zuì hòu yīcì jīhuì.", kh: "នេះគឺជាឱកាសចុងក្រោយ។" },
  { cn: "最近我很忙。", pinyin: "Zuìjìn wǒ hěn máng.", kh: "ថ្មីៗនេះខ្ញុំត្រូវការងារច្រើន។" },
  { cn: "你做作业了吗？", pinyin: "Nǐ zuò zuòyè le ma?", kh: "អ្នកធ្វើកិច្ចការផ្ទះរួចហើយទេ?" }

];

const wordList = document.getElementById("word-list");

words.forEach(({ cn, pinyin, kh }) => {
  const card = document.createElement("div");
  card.className = "word-card";
  card.innerHTML = `
    <div class="word">${cn}</div>
    <div class="pinyin">${pinyin}</div>
    <div class="khmer">${kh}</div>
  `;
  wordList.appendChild(card);
});
