document.getElementById("vocab-title").textContent = "造句:(បង្កើតប្រយោគ)";

const words = [
  { cn: "我爱我的家人。", pinyin: "Wǒ ài wǒ de jiārén.", kh: "ខ្ញុំស្រលាញ់គ្រួសាររបស់ខ្ញុំ។" },
  { cn: "我有八本书。", pinyin: "Wǒ yǒu bā běn shū.", kh: "ខ្ញុំមានសៀវភៅប្រាំបីក្បាល។" },
  { cn: "爸爸在工作។", pinyin: "Bàba zài gōngzuò.", kh: "ឪពុកកំពុងធ្វើការ។" },
  { cn: "这是我的杯子។", pinyin: "Zhè shì wǒ de bēizi.", kh: "នេះគឺជាពែងរបស់ខ្ញុំ។" },
  { cn: "我想去北京旅游។", pinyin: "Wǒ xiǎng qù Běijīng lǚyóu.", kh: "ខ្ញុំចង់ទៅធ្វើដំណើរនៅទីក្រុងប៉េកាំង។" },
  { cn: "这本书很好看។", pinyin: "Zhè běn shū hěn hǎokàn.", kh: "សៀវភៅនេះគួរឱ្យចាប់អារម្មណ៍។" },
  { cn: "谢谢你！——不客气។", pinyin: "Xièxie nǐ! —— Bú kèqi.", kh: "អរគុណអ្នក! —— មិនអីទេ។" },
  { cn: "我不喜欢下雨។", pinyin: "Wǒ bù xǐhuān xiàyǔ.", kh: "ខ្ញុំមិនចូលចិត្តភ្លៀងទេ។" },
  { cn: "今天的菜很好吃។", pinyin: "Jīntiān de cài hěn hǎochī.", kh: "ម្ហូបថ្ងៃនេះឆ្ងាញ់ណាស់។" },
  { cn: "我喜欢喝中国茶។", pinyin: "Wǒ xǐhuān hē Zhōngguó chá.", kh: "ខ្ញុំចូលចិត្តផឹកតែចិន។" },
  { cn: "我正在吃饭។", pinyin: "Wǒ zhèngzài chī fàn.", kh: "ខ្ញុំកំពុងបរិភោគអាហារ។" },
  { cn: "我们坐出租车去机场។", pinyin: "Wǒmen zuò chūzūchē qù jīchǎng.", kh: "ពួកយើងជិះតាក់ស៊ីទៅអាកាសយានដ្ឋាន។" },
  { cn: "我每天给妈妈打电话។", pinyin: "Wǒ měitiān gěi māma dǎ diànhuà.", kh: "ខ្ញុំហៅទូរស័ព្ទទៅឪម៉ាក់រៀងរាល់ថ្ងៃ។" },
  { cn: "这个房子很大។", pinyin: "Zhège fángzi hěn dà.", kh: "ផ្ទះនេះធំណាស់។" },
  { cn: "这是我的电脑។", pinyin: "Zhè shì wǒ de diànnǎo.", kh: "នេះជាកុំព្យូទ័ររបស់ខ្ញុំ។" },
  { cn: "现在是三点។", pinyin: "Xiànzài shì sān diǎn.", kh: "ឥឡូវនេះម៉ោងបី។" },
  { cn: "我在用电脑写作业។", pinyin: "Wǒ zài yòng diànnǎo xiě zuòyè.", kh: "ខ្ញុំកំពុងប្រើកុំព្យូទ័រសរសេរការងារ។" },
  { cn: "我喜欢看电视。", pinyin: "Wǒ xǐ huān kàn diàn shì.", kh: "ខ្ញុំចូលចិត្តមើលទូរទស្សន៍。" },
{ cn: "这部电影很有意思。", pinyin: "Zhè bù diàn yǐng hěn yǒu yì si.", kh: "ភាពយន្តនេះពិតជាសម្បូរបែប។" },
{ cn: "你买了很多东西。", pinyin: "Nǐ mǎi le hěn duō dōng xi.", kh: "អ្នកទិញរបស់ជាច្រើន។" },
{ cn: "他们都很忙。", pinyin: "Tā men dōu hěn máng.", kh: "ពួកគេទាំងអស់មានការងារតូចៗ។" },
{ cn: "我每天读书。", pinyin: "Wǒ měi tiān dú shū.", kh: "ខ្ញុំអានសៀវភៅរាល់ថ្ងៃ។" },
{ cn: "对不起，我迟到了。", pinyin: "Duì bu qǐ, wǒ chí dào le.", kh: "សូមទោស ខ្ញុំមកដល់យឺត។" },
{ cn: "这里的食物很多。", pinyin: "Zhè lǐ de shí wù hěn duō.", kh: "អាហារនៅទីនេះមានច្រើន។" },
{ cn: "这本书多少钱？", pinyin: "Zhè běn shū duō shǎo qián?", kh: "សៀវភៅនេះតើមានតម្លៃប៉ុន្មាន?" },
{ cn: "我的儿子很聪明。", pinyin: "Wǒ de ér zi hěn cōng míng.", kh: "កូនប្រុសរបស់ខ្ញុំមានបញ្ញា។" },
{ cn: "我有两个苹果。", pinyin: "Wǒ yǒu liǎng gè píng guǒ.", kh: "ខ្ញុំមានផ្លែប៉ោមពីរម៉ា។" },
{ cn: "这个饭店很好吃。", pinyin: "Zhè gè fàn diàn hěn hǎo chī.", kh: "ភោជនីយដ្ឋាននេះអីស្រួលដល់ចិត្ត។" },
{ cn: "我坐飞机去北京。", pinyin: "Wǒ zuò fēi jī qù Běi jīng.", kh: "ខ្ញុំកំពុងជិះយន្តហោះទៅប៉េកាំង។" },
{ cn: "还有五分钟就到达了。", pinyin: "Hái yǒu wǔ fēn zhōng jiù dào dá le.", kh: "នៅតែមាននាទីប្រាំដើម្បីឈានដល់។" },
{ cn: "我很高兴认识你。", pinyin: "Wǒ hěn gāo xìng rèn shi nǐ.", kh: "ខ្ញុំរីករាយណាស់ដែលបានស្គាល់អ្នក។" },
{ cn: "这是一个大问题。", pinyin: "Zhè shì yí gè dà wèn tí.", kh: "នេះគឺជាបញ្ហាធំ។" },
{ cn: "他每天都工作到很晚。", pinyin: "Tā měi tiān dōu gōng zuò dào hěn wǎn.", kh: "គាត់ធ្វើការម្នាក់ៗរហូតដល់យប់យឺត។" },
{ cn: "我家有一只狗。", pinyin: "Wǒ jiā yǒu yì zhī gǒu.", kh: "ខ្ញុំមានឆ្កែធំមួយនៅផ្ទះ។" },
{ cn: "我在学习汉语。", pinyin: "Wǒ zài xué xí hàn yǔ.", kh: "ខ្ញុំកំពុងរៀនភាសាចិន។" },
{ cn: "今天的天气很好。", pinyin: "Jīn tiān de tiān qì hěn hǎo.", kh: "អាកាសធាតុថ្ងៃនេះវាល្អណាស់។" },
{ cn: "我的电话号码是123456。", pinyin: "Wǒ de diàn huà hào mǎ shì 123456.", kh: "លេខទូរស័ព្ទរបស់ខ្ញុំគឺ123456។" },
{ cn: "我喜欢喝茶。", pinyin: "Wǒ xǐ huān hē chá.", kh: "ខ្ញុំចូលចិត្តផឹកតែ។" },
{ cn: "我喜欢和朋友一起玩。", pinyin: "Wǒ xǐ huān hé péng yǒu yī qǐ wán.", kh: "ខ្ញុំចូលចិត្តលេងជាមួយមិត្តភក្តិ។" },
{ cn: "今天很冷。", pinyin: "Jīn tiān hěn lěng.", kh: "ថ្ងៃនេះត្រជាក់ណាស់។" },
{ cn: "我们回家吧。", pinyin: "Wǒ men huí jiā ba.", kh: "យើងត្រឡាប់ទៅផ្ទះបានហើយ។" },
{ cn: "你会说中文吗？", pinyin: "Nǐ huì shuō zhōng wén ma?", kh: "តើអ្នកចេះនិយាយភាសាចិនទេ?" },
{ cn: "我买了很多东西。", pinyin: "Wǒ mǎi le hěn duō dōng xi.", kh: "ខ្ញុំបានទិញរបស់ជាច្រើន។" },
{ cn: "你看见那只猫了吗？", pinyin: "Nǐ kàn jiàn nà zhī māo le ma?", kh: "តើអ្នកឃើញឆ្មានោះទេ?" },
{ cn: "我家里有很多书。", pinyin: "Wǒ jiā lǐ yǒu hěn duō shū.", kh: "នៅផ្ទះខ្ញុំមានសៀវភៅច្រើន។" },
{ cn: "明天我们去看电影。", pinyin: "Míng tiān wǒ men qù kàn diàn yǐng.", kh: "ស្អែកយើងទៅមើលភាពយន្ត។" },
{ cn: "这块蛋糕很好吃。", pinyin: "Zhè kuài dàn gāo hěn hǎo chī.", kh: "ដុំព័ន្ធនេះរសជាតិឆ្ងាញ់ណាស់។" },
{ cn: "我叫李华。", pinyin: "Wǒ jiào Lǐ Huá.", kh: "ខ្ញុំហៅឈ្មោះលីហ្វា។" },
{ cn: "老师今天很忙。", pinyin: "Lǎo shī jīn tiān hěn máng.", kh: "គ្រូថ្ងៃនេះមិនមានពេលទេ។" },
{ cn: "这本书很有意思。", pinyin: "Zhè běn shū hěn yǒu yì si.", kh: "សៀវភៅនេះមានភាពចាប់អារម្មណ៍។" },
{ cn: "妈妈给我买了很多礼物。", pinyin: "Mā ma gěi wǒ mǎi le hěn duō lǐ wù.", kh: "ម៉ាក់បានទិញអំណោយជាច្រើនសម្រាប់ខ្ញុំ។" },
{ cn: "你要喝什么？", pinyin: "Nǐ yào hē shén me?", kh: "តើអ្នកចង់ផឹកអ្វី?" },
{ cn: "这是什么东西？", pinyin: "Zhè shì shén me dōng xi?", kh: "នេះគឺជារបស់អ្វី?" },
{ cn: "我昨天去了商店。", pinyin: "Wǒ zuó tiān qù le shāng diàn.", kh: "ខ្ញុំបានទៅហាងតំណាងម្សិលមិញ។" },
{ cn: "那是我的朋友。", pinyin: "Nà shì wǒ de péng yǒu.", kh: "នោះគឺជាមិត្តភក្តិរបស់ខ្ញុំ។" },
{ cn: "你能帮我吗？", pinyin: "Nǐ néng bāng wǒ ma?", kh: "តើអ្នកអាចជួយខ្ញុំបានទេ?" },
{ cn: "今年是2025年。", pinyin: "Jīn nián shì 2025 nián.", kh: "ឆ្នាំនេះគឺឆ្នាំ2025។" },
{ cn: "她的女儿很漂亮。", pinyin: "Tā de nǚ ér hěn piào liang.", kh: "កូនស្រីរបស់នាងស្អាតណាស់។" },
{ cn: "我买了一个苹果。", pinyin: "Wǒ mǎi le yí gè píng guǒ.", kh: "ខ្ញុំបានទិញផ្លែប៉ោមមួយ។" },
{ cn: "前面有一个商店。", pinyin: "Qián miàn yǒu yí gè shāng diàn.", kh: "មុខមានហាងមួយ។" },
{ cn: "请给我一些水。", pinyin: "Qǐng gěi wǒ yì xiē shuǐ.", kh: "សូមឲ្យខ្ញុំទឹកខ្លះ។" },
{ cn: "我去商店买东西。", pinyin: "Wǒ qù shāng diàn mǎi dōng xi.", kh: "ខ្ញុំទៅហាងទិញរបស់។" },
{ cn: "现在是上午十点。", pinyin: "Xiàn zài shì shàng wǔ shí diǎn.", kh: "ពេលនេះជាព្រឹកម៉ោងដប់។" },
{ cn: "今天很热。", pinyin: "Jīn tiān hěn rè.", kh: "ថ្ងៃនេះក្តៅណាស់។" },
{ cn: "你认识他吗？", pinyin: "Nǐ rèn shi tā ma?", kh: "តើអ្នកស្គាល់គាត់ទេ?" },
{ cn: "谁在门口？", pinyin: "Shéi zài mén kǒu?", kh: "នរណាដែលនៅជាប់ទ្វារ?" },
{ cn: "我知道他是谁。", pinyin: "Wǒ zhī dào tā shì shéi.", kh: "ខ្ញុំដឹងគាត់គឺនរណា។" },
{ cn: "十点的时候我在家。", pinyin: "Shí diǎn de shí hou wǒ zài jiā.", kh: "នៅពេលម៉ោងដប់ ខ្ញុំនៅផ្ទះ។" },
{ cn: "书在桌子上。", pinyin: "Shū zài zhuō zi shàng.", kh: "សៀវភៅនៅលើតុ។" },
{ cn: "我喝水。", pinyin: "Wǒ hē shuǐ.", kh: "ខ្ញុំផឹកទឹក។" },
{ cn: "今天我吃了水果。", pinyin: "Jīn tiān wǒ chī le shuǐ guǒ.", kh: "ថ្ងៃនេះខ្ញុំបានបរិភោគផ្លែឈើ។" },
{ cn: "我每天晚上睡觉。", pinyin: "Wǒ měi tiān wǎn shàng shuì jiào.", kh: "ខ្ញុំគេងរៀងរាល់យប់។" },
{ cn: "他说中文。", pinyin: "Tā shuō zhōng wén.", kh: "គាត់និយាយភាសាចិន។" },
{ cn: "我有四本书。", pinyin: "Wǒ yǒu sì běn shū.", kh: "ខ្ញុំមានសៀវភៅបួនក្បាល។" },
{ cn: "她三岁。", pinyin: "Tā sān suì.", kh: "នាងអាយុបីឆ្នាំ។" },
{ cn: "他是老师。", pinyin: "Tā shì lǎo shī.", kh: "គាត់គឺជាគ្រូបង្រៀន។" },
{ cn: "她是我的朋友。", pinyin: "Tā shì wǒ de péng yǒu.", kh: "នាងគឺជាមិត្តភក្តិរបស់ខ្ញុំ។" },
{ cn: "今天太热了。", pinyin: "Jīn tiān tài rè le.", kh: "ថ្ងៃនេះក្តៅពេក។" },
{ cn: "今天的天气很好。", pinyin: "Jīn tiān de tiān qì hěn hǎo.", kh: "អាកាសធាតុថ្ងៃនេះល្អណាស់។" },
{ cn: "我在听音乐。", pinyin: "Wǒ zài tīng yīn yuè.", kh: "ខ្ញុំកំពុងស្តាប់តន្ត្រី។" },
{ cn: "我们是同学。", pinyin: "Wǒ men shì tóng xué.", kh: "ពួកយើងជាមិត្តរួមថ្នាក់។" },
{ cn: "喂，你在吗？", pinyin: "Wèi, nǐ zài ma?", kh: "សួស្តី អ្នកនៅទីនោះទេ?" },
{ cn: "我喜欢读书。", pinyin: "Wǒ xǐ huān dú shū.", kh: "ខ្ញុំចូលចិត្តអានសៀវភៅ។" },
{ cn: "我们去学校。", pinyin: "Wǒ men qù xué xiào.", kh: "ពួកយើងទៅសាលារៀន។" },
{ cn: "今天是星期五。", pinyin: "Jīn tiān shì xīng qī wǔ.", kh: "ថ្ងៃនេះជាសៅទីហ្វូ។" },
{ cn: "我会写字。", pinyin: "Wǒ huì xiě zì.", kh: "ខ្ញុំអាចសរសេរអក្សរ។" },
{ cn: "谢谢你的帮助。", pinyin: "Xiè xiè nǐ de bāng zhù.", kh: "សូមអរគុណចំពោះការជួយរបស់អ្នក។" },
{ cn: "他去医院看病。", pinyin: "Tā qù yī yuàn kàn bìng.", kh: "គាត់ទៅមន្ទីរពេទ្យដើម្បីពិនិត្យជំងឺ។" },
{ cn: "我穿了新的衣服。", pinyin: "Wǒ chuān le xīn de yī fu.", kh: "ខ្ញុំបានពាក់សម្លៀកបំពាក់ថ្មី។" },
{ cn: "我坐在椅子上。", pinyin: "Wǒ zuò zài yǐ zi shàng.", kh: "ខ្ញុំអង្គុយនៅលើកៅអី។" },
{ cn: "我有很多书。", pinyin: "Wǒ yǒu hěn duō shū.", kh: "ខ្ញុំមានសៀវភៅច្រើន។" },
{ cn: "一月是冬天。", pinyin: "Yī yuè shì dōng tiān.", kh: "ខែមករាគឺជារដូវរងារ។" },
{ cn: "我们明天再见。", pinyin: "Wǒmen míngtiān zài jiàn.", kh: "ស្អែកយើងជួបគ្នាវិញ។" },
{ cn: "我在家。", pinyin: "Wǒ zài jiā.", kh: "ខ្ញុំនៅផ្ទះ។" },
{ cn: "你怎么去学校？", pinyin: "Nǐ zěnme qù xuéxiào?", kh: "អ្នកទៅសាលាដោយរបៀបណា?" },
{ cn: "今天天气怎么样？", pinyin: "Jīntiān tiānqì zěnme yàng?", kh: "អាកាសធាតុថ្ងៃនេះយ៉ាងដូចម្តេច?" },
{ cn: "这是我的书。", pinyin: "Zhè shì wǒ de shū.", kh: "នេះជាសៀវភៅរបស់ខ្ញុំ។" },
{ cn: "我来自中国。", pinyin: "Wǒ lái zì Zhōngguó.", kh: "ខ្ញុំមកពីប្រទេសចិន។" },
{ cn: "我中午吃饭。", pinyin: "Wǒ zhōngwǔ chīfàn.", kh: "ខ្ញុំបរិភោគអាហារថ្ងៃត្រង់។" },
{ cn: "我住在金边。", pinyin: "Wǒ zhù zài Jīnbiān.", kh: "ខ្ញុំពីរស់នៅក្នុងក្រុងភ្នំពេញ។" },
{ cn: "书在桌子上。", pinyin: "Shū zài zhuōzi shàng.", kh: "សៀវភៅស្ថិតនៅលើតុ។" },
{ cn: "我会写汉字。", pinyin: "Wǒ huì xiě hànzì.", kh: "ខ្ញុំអាចសរសេរពាក្យចិនបាន។" },
{ cn: "昨天我去超市了。", pinyin: "Zuótiān wǒ qù chāoshì le.", kh: "ម្សិលមិញខ្ញុំបានទៅផ្សារទំនើប។" },
{ cn: "你在做什么？", pinyin: "Nǐ zài zuò shénme?", kh: "អ្នកកំពុងធ្វើអ្វី?" },
{ cn: "请坐在这里。", pinyin: "Qǐng zuò zài zhèlǐ.", kh: "សូមអង្គុយនៅទីនេះ។" }
];

const wordList = document.getElementById("word-list");

words.forEach(({ cn, pinyin, kh }) => {
  const card = document.createElement("div");
  card.className = "word-card";
  card.innerHTML = `
    <div class="word">${cn}</div>
    <div class="pinyin">${pinyin}</div>
    <div class="khmer">${kh}</div>
  `;
  wordList.appendChild(card);
});
