document.getElementById("vocab-title").textContent = "造句:(បង្កើតប្រយោគ)";

const words = [
    { cn: "他们之间的爱情非常感人。", pinyin: "Tāmen zhījiān de àiqíng fēicháng gǎnrén.", kh: "ក្តីស្រឡាញ់របស់ពួកគេគួរឲ្យអស់សំណើច។" },
    { cn: "我们需要安排明天的会议。", pinyin: "Wǒmen xūyào ānpái míngtiān de huìyì.", kh: "ពួកយើងត្រូវរៀបចំសន្និសីទស្អែក។" },
    { cn: "晚上一个人走路不太安全。", pinyin: "Wǎnshàng yí gè rén zǒulù bù tài ānquán.", kh: "នៅពេលល្ងាចដើរតែម្ខាងមិនសូវមានសុវត្ថិភាពទេ។" },
    { cn: "他每天按时上班。", pinyin: "Tā měitiān ànshí shàngbān.", kh: "គាត់ទៅធ្វើការទាន់ពេលរៀងរាល់ថ្ងៃ។" },
    { cn: "请按照老师的要求去做。", pinyin: "Qǐng ànzhào lǎoshī de yāoqiú qù zuò.", kh: "សូមធ្វើតាមតម្រូវការរបស់គ្រូ។" },
    { cn: "这个产品的合格率是百分之九十五。", pinyin: "Zhège chǎnpǐn de hégé lǜ shì bǎifēnzhī jiǔshíwǔ.", kh: "ផលិតផលនេះមានអត្រាសមរម្យ ៩៥ភាគរយ។" },
    { cn: "你真棒，做得很好！", pinyin: "Nǐ zhēn bàng, zuò de hěn hǎo!", kh: "អ្នកអស្ចារ្យណាស់ បង្កើតបានល្អណាស់!" },
    { cn: "我早上吃了两个包子。", pinyin: "Wǒ zǎoshang chīle liǎng gè bāozi.", kh: "ខ្ញុំបានញាំនំប៉ាវពីរមុនព្រឹកនេះ។" },
    { cn: "我们应该保护环境。", pinyin: "Wǒmen yīnggāi bǎohù huánjìng.", kh: "ពួកយើងគួរការពារបរិស្ថាន។" },
    { cn: "我保证不再迟到。", pinyin: "Wǒ bǎozhèng bú zài chídào.", kh: "ខ្ញុំសន្យាថានឹងមិនយឺតទៀតឡើយ។" },
    { cn: "他已经报名参加比赛了。", pinyin: "Tā yǐjīng bàomíng cānjiā bǐsài le.", kh: "គាត់បានចុះឈ្មោះចូលរួមការប្រកួតរួចហើយ។" },
    { cn: "她抱着孩子在唱歌。", pinyin: "Tā bàozhe háizi zài chànggē.", kh: "នាងអោបក្មេងហើយកំពុងចម្រៀង។" },
    { cn: "对不起，我来晚了，请你原谅我。", pinyin: "Duìbuqǐ, wǒ lái wǎn le, qǐng nǐ yuánliàng wǒ.", kh: "សុំទោស ខ្ញុំមកយឺត សូមអភ័យទោស។" },
    { cn: "这个房子的价格是以前的两倍。", pinyin: "Zhège fángzi de jiàgé shì yǐqián de liǎng bèi.", kh: "តម្លៃផ្ទះនេះជាពីរដងនៃតម្លៃដើម។" },
    { cn: "我本来打算周末去旅行的。", pinyin: "Wǒ běnlái dǎsuàn zhōumò qù lǚxíng de.", kh: "ដំបូងខ្ញុំគិតថានឹងទៅធ្វើដំណើរថ្ងៃចុងសប្ដាហ៍។" },
    { cn: "他很笨，但他很努力。", pinyin: "Tā hěn bèn, dàn tā hěn nǔlì.", kh: "គាត់ឆោតបន្តិច ប៉ុន្តែក៏ខំប្រឹងប្រែង។" },
    { cn: "比如说，苹果和香蕉都是水果。", pinyin: "Bǐrú shuō, píngguǒ hé xiāngjiāo dōu shì shuǐguǒ.", kh: "ឧទាហរណ៍ ដូចជាប៉ោម និងចេក ជាផ្លែឈើ។" },
    { cn: "我明年就要毕业了。", pinyin: "Wǒ míngnián jiù yào bìyè le.", kh: "ខ្ញុំនឹងបញ្ចប់ការសិក្សាឆ្នាំក្រោយ។" },
    { cn: "我这本书看了三遍了。", pinyin: "Wǒ zhè běn shū kànle sān biàn le.", kh: "ខ្ញុំបានអានសៀវភៅនេះបីដងហើយ។" },
    { cn: "这家公司对产品质量有很高的标准。", pinyin: "Zhè jiā gōngsī duì chǎnpǐn zhìliàng yǒu hěn gāo de biāozhǔn.", kh: "ក្រុមហ៊ុននេះមានស្តង់ដារខ្ពស់ចំពោះគុណភាពផលិតផល។" },
    { cn: "请填写这份表格。", pinyin: "Qǐng tiánxiě zhè fèn biǎogé.", kh: "សូមបំពេញសំណុំបែបបទនេះ។" },
    { cn: "这只是表示我的感激之情。", pinyin: "Zhè zhǐ shì biǎoshì wǒ de gǎnjī zhī qíng.", kh: "នេះគ្រាន់តែជាការបង្ហាញពីអារម្មណ៍ស្រឡាញ់របស់ខ្ញុំ។" },
    { cn: "他在舞台上表演得非常好。", pinyin: "Tā zài wǔtái shàng biǎoyǎn dé fēicháng hǎo.", kh: "គាត់បានសម្តែងយ៉ាងល្អនៅលើឆាក។" },
    { cn: "老师表扬了他努力的精神。", pinyin: "Lǎoshī biǎoyáng le tā nǔlì de jīngshén.", kh: "គ្រូបានសរសើរអំពីការខំប្រឹងប្រែងរបស់គាត់។" },
    { cn: "我喜欢吃饼干，特别是巧克力味的。", pinyin: "Wǒ xǐhuān chī bǐnggān, tèbié shì qiǎokèlì wèi de.", kh: "ខ្ញុំចូលចិត្តញាំនំខូឃី ជាពិសេសមានរសជាតិឈីកូឡេ។" },
    { cn: "他喜欢游泳，并且擅长跑步。", pinyin: "Tā xǐhuān yóuyǒng, bìngqiě shàncháng pǎobù.", kh: "គាត់ចូលចិត្តហែលទឹក និងមួយចំណុចក៏ចេះរត់ផងដែរ។" },
    { cn: "他是一位博士，研究了很多年。", pinyin: "Tā shì yī wèi bóshì, yánjiū le hěn duō nián.", kh: "គាត់គឺជាបណ្ឌិត ដែលបានស្រាវជ្រាវជាច្រើនឆ្នាំ។" },
    { cn: "不过，今天的天气比昨天更热。", pinyin: "Bùguò, jīntiān de tiānqì bǐ zuótiān gèng rè.", kh: "តែថ្ងៃនេះអាកាសធាតុរងចាំកាន់តែមានក្ដៅជាងថ្ងៃមុន។" },
    { cn: "他不得不放弃他的计划。", pinyin: "Tā bùdé bù fàngqì tā de jìhuà.", kh: "គាត់ត្រូវតែបោះបង់ផែនការរបស់គាត់។" },
    { cn: "不管天气如何，我们都要去旅行。", pinyin: "Bùguǎn tiānqì rúhé, wǒmen dōu yào qù lǚxíng.", kh: "ដោយមិនគិតពីអាកាសធាតុ យើងគ្រប់គ្នាត្រូវតែទៅធ្វើដំណើរ។" },
    { cn: "不仅他的汉语很好，他的英语也很流利。", pinyin: "Bùjǐn tā de hànyǔ hěn hǎo, tā de yīngyǔ yě hěn liúlì.", kh: "មិនត្រឹមតែភាសាចិនរបស់គាត់ល្អទេ គាត់ក៏ភាសាអង់គ្លេសបានឆាប់ផងដែរ។" },
    { cn: "这个部分的内容我已经学会了。", pinyin: "Zhège bùfen de nèiróng wǒ yǐjīng xuéhuì le.", kh: "ខ្ញុំបានរៀនបាននូវមាតិកាផ្នែកនេះរួចហើយ។" },
    { cn: "他擦了擦桌子，继续工作。", pinyin: "Tā cāle cā zhuōzi, jìxù gōngzuò.", kh: "គាត់បានជូតតុ ហើយបន្តធ្វើការងារ។" },
    { cn: "我猜他已经知道了这个消息。", pinyin: "Wǒ cāi tā yǐjīng zhīdào le zhège xiāoxī.", kh: "ខ្ញុំគោលថាគាត់បានដឹងដល់ព័ត៌មាននេះហើយ។" },
    { cn: "我们需要更多的材料来完成报告。", pinyin: "Wǒmen xūyào gèng duō de cáiliào lái wánchéng bàogào.", kh: "យើងត្រូវការសម្ភារៈបន្ថែមដើម្បីបញ្ចប់របាយការណ៍។" },
    { cn: "我参观了那座博物馆。", pinyin: "Wǒ cānguān le nà zuò bówùguǎn.", kh: "ខ្ញុំបានទស្សនាសារមន្ទីរនោះ។" },
    { cn: "这家餐厅的菜非常好吃。", pinyin: "Zhè jiā cāntīng de cài fēicháng hǎo chī.", kh: "ម្ហូបនៅភោជនីយដ្ឋាននេះអាចជួយបញ្ជាក់ភាពរីករាយបាន។" },
    { cn: "厕所里没有纸巾了。", pinyin: "Cè suǒ lǐ méiyǒu zhǐjīn le.", kh: "បន្ទប់ទឹកគ្មានក្រដាសទឹកនោះទេ។" },
    { cn: "差不多到时间了，我们该走了。", pinyin: "Chà bù duō dào shíjiān le, wǒmen gāi zǒu le.", kh: "ស្ទើរតែពេលវេលាមកដល់ហើយ យើងគួរតែទៅហើយ។" },
    { cn: "他想尝试新的东西。", pinyin: "Tā xiǎng chángshì xīn de dōngxi.", kh: "គាត់ចង់សាកល្បងអ្វីថ្មីៗ។" },
    { cn: "长城是中国最著名的景点之一。", pinyin: "Cháng chéng shì zhōngguó zuì zhùmíng de jǐngdiǎn zhī yī.", kh: "មហាកំពែងគឺជាកន្លែងទេសចរណ៍ដែលមានប្រជាប្រិយភាពបំផុតនៅចិន។" },
    { cn: "长江是中国最长的河流。", pinyin: "Cháng jiāng shì zhōngguó zuì cháng de héliú.", kh: "ទន្លេឈាងហ្សៀងគឺជាធំតែបំផុតនៅចិន។" },
    { cn: "这个场地非常适合举行婚礼。", pinyin: "Zhège chǎngdì fēicháng shìhé jǔxíng hūnlǐ.", kh: "ទីកន្លែងនេះសមស្របណាស់សម្រាប់ប្រព្រឹត្តកម្មមង្គលការ។" },
    { cn: "他超过了所有人的期望。", pinyin: "Tā chāoguò le suǒyǒu rén de qīwàng.", kh: "គាត់បានលើសការរងចាំទាំងអស់របស់មនុស្សគ្រប់គ្នា។" },
    { cn: "我将乘坐高铁去北京。", pinyin: "Wǒ jiāng chéngzuò gāotiě qù Běijīng.", kh: "ខ្ញុំត្រូវជិះរថភ្លើងលឿនទៅប៉េកាំង។" },
    { cn: "他成功地完成了这个项目。", pinyin: "Tā chénggōng de wánchéng le zhège xiàngmù.", kh: "គាត់បានជោគជ័យក្នុងការបញ្ចប់គម្រោងនេះ។" },
    { cn: "她终于成为了我们团队的一员。", pinyin: "Tā zhōngyú chéngwéi le wǒmen tuánduì de yī yuán.", kh: "នាងបានក្លាយជា១ក្នុងក្រុមរបស់យើង។" },
    { cn: "诚实的人很受欢迎。", pinyin: "Chéng shí de rén hěn shòu huān yíng.", kh: "មនុស្សស្មោះត្រង់តែងតែមានអ្នកអរគុណ។" },
    { cn: "他对结果感到吃惊。", pinyin: "Tā duì jié guǒ gǎn dào chī jīng.", kh: "គាត់មានអារម្មណ៍ភ្ញាក់ផ្អើលចំពោះលទ្ធផល។" },
    { cn: "我需要重新开始工作。", pinyin: "Wǒ xū yào chóngxīn kāi shǐ gōngzuò.", kh: "ខ្ញុំត្រូវការចាប់ផ្តើមការងារថ្មីម្តងទៀត។" },
    { cn: "他已经戒烟了。", pinyin: "Tā yǐ jīng jiè yān le.", kh: "គាត់បានបោះបង់ការជក់បារីរួចហើយ។" },
    { cn: "我出差到北京去了。", pinyin: "Wǒ chū chāi dào běi jīng qù le.", kh: "ខ្ញុំបានដំណើរអាជីវកម្មទៅប៉េកាំង។" },
    { cn: "我们计划明天出发。", pinyin: "Wǒmen jì huà míng tiān chū fā.", kh: "យើងមានផែនការចេញដំណើរ​នៅថ្ងៃស្អែក។" },
    { cn: "我在上海出生。", pinyin: "Wǒ zài shàng hǎi chū shēng.", kh: "ខ្ញុំកើតនៅក្នុងទីក្រុងសៀងហៃ។" },
    { cn: "突然间他出现在我面前。", pinyin: "Tū rán jiān tā chū xiàn zài wǒ miàn qián.", kh: "គាត់លេចឡើងមកមុខខ្ញុំយ៉ាងចេញពីខ្លួន។" },
    { cn: "我喜欢在厨房做饭。", pinyin: "Wǒ xǐ huān zài chú fáng zuò fàn.", kh: "ខ្ញុំចូលចិត្តធ្វើម្ហូបនៅក្នុងផ្ទះបាយ។" },
    { cn: "传真机在办公室里。", pinyin: "Chuán zhēn jī zài bàng gōng shì lǐ.", kh: "ម៉ាស៊ីនផ្ញើសារតាមទូរសារមាននៅក្នុងការិយាល័យ។" },
    { cn: "这扇窗户已经破了。", pinyin: "Zhè shàn chuāng hu yǐ jīng pò le.", kh: "បង្អួចនេះបានខូចហើយ។" },
    { cn: "我不懂这个词语。", pinyin: "Wǒ bù dǒng zhè ge cí yǔ.", kh: "ខ្ញុំមិនយល់ពាក្យនេះទេ។" },
    { cn: "从来没有人告诉我这个。", pinyin: "Cóng lái méi yǒu rén gào su wǒ zhè ge.", kh: "មិនដែលមានអ្នកណាដែលប្រាប់ខ្ញុំពីរឿងនេះទេ។" },
    { cn: "他粗心地丢了他的手机。", pinyin: "Tā cū xīn de diū le tā de shǒu jī.", kh: "គាត់ធ្វេសប្រហែសបានបាត់ទូរស័ព្ទរបស់គាត់។" },
    { cn: "我把所有的文件都存好了。", pinyin: "Wǒ bǎ suǒ yǒu de wén jiàn dōu cún hǎo le.", kh: "ខ្ញុំបានរក្សាទុកឯកសារទាំងអស់បានយ៉ាងល្អ។" },
    { cn: "这是一个错误的答案。", pinyin: "Zhè shì yí gè cuò wù de dá àn.", kh: "នេះគឺជាចម្លើយខុស។" },
    { cn: "她打扮得非常漂亮。", pinyin: "Tā dǎ ban de fēi cháng piào liàng.", kh: "គាត់តុបតែងខ្លួនបានស្រស់ស្អាតណាស់។" },
    { cn: "不要打扰我。", pinyin: "Bù yào dǎ rǎo wǒ.", kh: "កុំរំខានខ្ញុំ។" },
    { cn: "我需要打印一些文件。", pinyin: "Wǒ xū yào dǎ yìn yì xiē wén jiàn.", kh: "ខ្ញុំត្រូវការបោះពុម្ពឯកសារខ្លះៗ។" },
    { cn: "他向我打招呼。", pinyin: "Tā xiàng wǒ dǎ zhāo hu.", kh: "គាត់បានស្វាគមន៍ខ្ញុំ។" },
    { cn: "他们正在打折促销。", pinyin: "Tā men zhèng zài dǎ zhé cù xiāo.", kh: "ពួកគេកំពុងធ្វើការបញ្ចុះតម្លៃ។" },
    { cn: "我需要打针。", pinyin: "Wǒ xū yào dǎ zhēn.", kh: "ខ្ញុំត្រូវការចាក់ថ្នាំ។" },
    { cn: "我大概下午三点到。", pinyin: "Wǒ dà gài xià wǔ sān diǎn dào.", kh: "ខ្ញុំនឹងមកដល់ប្រហែលម៉ោងបីល្ងាច។" },
    { cn: "他是大使馆的工作人员。", pinyin: "Tā shì dà shǐ guǎn de gōng zuò rén yuán.", kh: "គាត់ជាខុពលិករបស់ស្ថានទូត។" },
    { cn: "大约十个人参加了会议。", pinyin: "Dà yuē shí ge rén cān jiā le huì yì.", kh: "ប្រហែលជា១០នាក់បានចូលរួមក្នុងការជួបប្រជុំ។" },
    { cn: "他是一位大夫。", pinyin: "Tā shì yí wèi dài fu.", kh: "គាត់គឺជាវេជ្ជបណ្ឌិតម្នាក់។" },
    { cn: "她戴上了漂亮的帽子。", pinyin: "Tā dài shàng le piào liàng de mào zi.", kh: "គាត់ពាក់តុក្កតាដ៏ស្រស់ស្អាត។" },
    { cn: "当我到达时，他已经走了。", pinyin: "Dāng wǒ dào dá shí, tā yǐ jīng zǒu le.", kh: "ពេលខ្ញុំទៅដល់ គាត់បានចេញរួចហើយ។" },
    { cn: "当时我不知道该怎么办。", pinyin: "Dāng shí wǒ bù zhī dào gāi zěn me bàn.", kh: "បន្ទាប់មក ខ្ញុំមិនដឹងថាត្រូវធ្វើអ្វីទេ។" },
    { cn: "他用刀切开了蛋糕。", pinyin: "Tā yòng dāo qiē kāi le dàn gāo.", kh: "គាត់ប្រើកាំបិតកាត់នំ។" },
    { cn: "导游带我们参观了很多地方。", pinyin: "Dǎo yóu dài wǒ men cān guān le hěn duō dì fāng.", kh: "មគ្គុទេសក៍បាននាំយើងទៅទស្សនាទីកន្លែងច្រើន។" },
    { cn: "请倒掉这些垃圾。", pinyin: "Qǐng dào diào zhè xiē lā jī.", kh: "សូមបញ្ចប់ការប្រមូលសំរាមទាំងនេះ។" },
    { cn: "到处都是美丽的风景。", pinyin: "Dào chù dōu shì měi lì de fēng jǐng.", kh: "នៅគ្រប់ទីកន្លែងមានទេសភាពស្អាតៗ។" },
    { cn: "你到底想要什么？", pinyin: "Nǐ dào dǐ xiǎng yào shén me?", kh: "តើអ្នកចង់បានអ្វីគจริงៗ?" },
    { cn: "我向他道歉。", pinyin: "Wǒ xiàng tā dào qiàn.", kh: "ខ្ញុំសុំទោសពីគាត់។" },
    { cn: "我得到了一个好成绩。", pinyin: "Wǒ dé dào le yí gè hǎo chéng jì.", kh: "ខ្ញុំទទួលបានលទ្ធផលល្អមួយ។" },
    { cn: "他得意地看着自己的成绩。", pinyin: "Tā dé yì de kàn zhe zì jǐ de chéng jì.", kh: "គាត់មានមោទនភាពមើលលទ្ធផលរបស់គាត់។" },
    { cn: "我拿到了登机牌。", pinyin: "Wǒ ná dào le dēng jī pái.", kh: "ខ្ញុំបានយកប័ណ្ណបើកបរ។" },
    { cn: "请等一下。", pinyin: "Qǐng děng yí xià.", kh: "សូមរងចាំមួយភ្លែត។" },
    { cn: "这条路很低，开车要小心。", pinyin: "Zhè tiáo lù hěn dī, kāi chē yào xiǎo xīn.", kh: "ផ្លូវនេះទាប ដូច្នេះអ្នកត្រូវចំរូវយ៉ាងប្រុងប្រយ័ត្ន។" },
    { cn: "书掉到了地底。", pinyin: "Shū diào dào le dì dǐ.", kh: "សៀវភៅបានធ្លាក់ទៅក្រោមដី។" },
    { cn: "这个地点非常适合拍照。", pinyin: "Zhè ge dì diǎn fēi cháng shì hé pāi zhào.", kh: "ទីតាំងនេះសមស្របណាស់សម្រាប់ថតរូប។" },
    { cn: "地球是我们共同的家园。", pinyin: "Dì qiú shì wǒ men gòng tóng de jiā yuán.", kh: "ផែនដីគឺជាប្រទេសរួមគ្នារបស់យើង។" },
    { cn: "我需要更新我的地址。", pinyin: "Wǒ xū yào gēng xīn wǒ de dì zhǐ.", kh: "ខ្ញុំត្រូវការអាប់ដេតអាសយដ្ឋានរបស់ខ្ញុំ។" },
    { cn: "手机掉了。", pinyin: "Shǒu jī diào le.", kh: "ទូរស័ព្ទធ្លាក់។" },
    { cn: "他正在做调查。", pinyin: "Tā zhèng zài zuò diào chá.", kh: "គាត់កំពុងធ្វើការស្ទង់មតិ។" },
    { cn: "我丢了我的钥匙。", pinyin: "Wǒ diū le wǒ de yào shi.", kh: "ខ្ញុំបានបោះចោលសោររបស់ខ្ញុំ។" },
    { cn: "他做了一个很大的动作。", pinyin: "Tā zuò le yí gè hěn dà de dòng zuò.", kh: "គាត់បានធ្វើសកម្មភាពធំមួយ។" },
    { cn: "今天早上有很多堵车。", pinyin: "Jīn tiān zǎo shàng yǒu hěn duō dǔ chē.", kh: "ថ្ងៃនេះព្រឹកមានស្ទះចរាចរណ៍ជាច្រើន។" },
    { cn: "我的肚子饿了。", pinyin: "Wǒ de dù zi è le.", kh: "ពោះរបស់ខ្ញុំឆាប់ស្រកខ្លាំង។" },
    { cn: "我给你发了一条短信。", pinyin: "Wǒ gěi nǐ fā le yì tiáo duǎn xìn.", kh: "ខ្ញុំបានផ្ញើសារ​មួយទៅអ្នក។" },
    { cn: "他们正在进行对话。", pinyin: "Tā men zhèng zài jìn xíng duì huà.", kh: "ពួកគេកំពុងធ្វើការសន្ទនាដែលមានអត្ថន័យ។" },
    { cn: "我们对面有一家餐馆。", pinyin: "Wǒ men duì miàn yǒu yì jiā cān guǎn.", kh: "នៅខាងមុខយើងមានភោជនីយដ្ឋានមួយ។" },
    { cn: "对于这个问题，我们有不同的看法。", pinyin: "Duì yú zhè ge wèn tí, wǒ men yǒu bù tóng de kàn fǎ.", kh: "សម្រាប់សំណួរនេះ យើងមានការយល់ឃើញខុសគ្នា។" },
    { cn: "他是一个儿童心理学家。", pinyin: "Tā shì yí gè ér tóng xīn lǐ xué jiā.", kh: "គាត់ជាអ្នកវិទ្យាសាស្ត្រខាងចិត្តវិទ្យាសម្រាប់កុមារ។" },
    { cn: "我喜欢这个而不是那个。", pinyin: "Wǒ xǐ huān zhè ge ér bù shì nà ge.", kh: "ខ្ញុំចូលចិត្តនេះជាងនោះ។" },
    { cn: "发生了什么事情？", pinyin: "Fā shēng le shén me shì qíng?", kh: "មានអ្វីកើតឡើង?" },
    { cn: "他的事业正在发展中。", pinyin: "Tā de shì yè zhèng zài fā zhǎn zhōng.", kh: "អាជីវកម្មរបស់គាត់កំពុងអភិវឌ្ឍន៍។" },
    { cn: "每个国家都有自己的法律。", pinyin: "Měi gè guó jiā dōu yǒu zì jǐ de fǎ lǜ.", kh: "ប្រទេសរៀងរាល់មានច្បាប់ផ្ទាល់ខ្លួន។" },
    { cn: "我需要翻译这本书。", pinyin: "Wǒ xū yào fān yì zhè běn shū.", kh: "ខ្ញុំត្រូវការបកប្រែសៀវភៅនេះ។" },
    { cn: "他有很多烦恼。", pinyin: "Tā yǒu hěn duō fán nǎo.", kh: "គាត់មានតូចចិត្តច្រើន។" },
    { cn: "我们反对这个提议。", pinyin: "Wǒ men fǎn duì zhè ge tí yì.", kh: "ពួកយើងប្រឆាំងនឹងសំណើនេះ។" },
    { cn: "这是一种有效的方法。", pinyin: "Zhè shì yì zhǒng yǒu xiào de fāng fǎ.", kh: "នេះគឺជាវិធីសាស្រ្តប្រសិទ្ធិភាពមួយ។" },
    { cn: "他在各个方面都有优点。", pinyin: "Tā zài gè ge fāng miàn dōu yǒu yōu diǎn.", kh: "គាត់មានអត្ថប្រយោជន៍នៅក្នុងផ្នែកជាច្រើន។" },
    { cn: "我们向左转，改变方向。", pinyin: "Wǒ men xiàng zuǒ zhuǎn, gǎi biàn fāng xiàng.", kh: "យើងបង្វែរទៅឆ្វេង ប្តូរទិសដៅ។" },
    { cn: "房东要求我们按时交租。", pinyin: "Fáng dōng yāo qiú wǒ men àn shí jiāo zū.", kh: "ម្ចាស់ផ្ទះស្នើសុំឲ្យយើងបង់ថ្លៃជួលតាមពេលវេលា។" },
    { cn: "他决定放弃这次机会。", pinyin: "Tā jué dìng fàng qì zhè cì jī huì.", kh: "គាត់បានសម្រេចចិត្តបោះបង់ឱកាសនេះ។" },
    { cn: "暑假我们会去旅行。", pinyin: "Shǔ jià wǒ men huì qù lǚ xíng.", kh: "នៅវិស្សមកាលរដូវក្តៅ យើងនឹងទៅដំណើរកំសាន្ត។" },
    { cn: "我需要放松一下。", pinyin: "Wǒ xū yào fàng sōng yí xià.", kh: "ខ្ញុំត្រូវការសម្រាកបន្តិច។" },
    { cn: "请把这份文件交给我。", pinyin: "Qǐng bǎ zhè fèn wén jiàn jiāo gěi wǒ.", kh: "សូមអញ្ជើញប្រើឯកសារនេះផ្តល់ឲ្យខ្ញុំ។" },
    { cn: "这道菜的味道很丰富。", pinyin: "Zhè dào cài de wèi dào hěn fēng fù.", kh: "រសជាតិរបស់ម្ហូបនេះមានភាពសម្បូរ។" },
    { cn: "否则，我们就无法完成任务。", pinyin: "Fǒu zé, wǒ men jiù wú fǎ wán chéng rèn wu.", kh: "បើមិនដូច្នេះទេ យើងនឹងមិនអាចបញ្ចប់ភារកិច្ចបានទេ។" },
    { cn: "这个方案符合我们的要求。", pinyin: "Zhè ge fāng àn fú hé wǒ men de yāo qiú.", kh: "ផែនការនេះស្របគ្នា។" },
    { cn: "我们已经付款了。", pinyin: "Wǒ men yǐ jīng fù kuǎn le.", kh: "យើងបានបង់ប្រាក់រួចរាល់ហើយ។" },
    { cn: "请复印这份文件。", pinyin: "Qǐng fù yìn zhè fèn wén jiàn.", kh: "សូមចម្លងឯកសារនេះ។" },
    { cn: "这个问题太复杂了。", pinyin: "Zhè ge wèn tí tài fù zá le.", kh: "សំណួរនេះស្មុគស្មាញពិតៗ។" },
    { cn: "他非常富有。", pinyin: "Tā fēi cháng fù yǒu.", kh: "គាត់មានទ្រព្យសម្បត្តិខ្លាំង។" },
    { cn: "他的父亲是一位医生。", pinyin: "Tā de fù qīn shì yí wèi yī shēng.", kh: "ឪពុករបស់គាត់គឺជាគ្រូពេទ្យម្នាក់។" },
    { cn: "你负责这个项目的所有工作。", pinyin: "Nǐ fù zé zhè ge xiàng mù de suǒ yǒu gōng zuò.", kh: "អ្នកទទួលខុសត្រូវចំពោះការងារទាំងអស់នៃគម្រោងនេះ។" },
    { cn: "我们决定改变计划。", pinyin: "Wǒ men jué dìng gǎi biàn jì huà.", kh: "យើងបានសម្រេចចិត្តផ្លាស់ប្តូរ ផែនការ។" },
    { cn: "干杯！", pinyin: "Gān bēi!", kh: "លើកទឹកចិត្ត!" },
    { cn: "他被电影感动了。", pinyin: "Tā bèi diàn yǐng gǎn dòng le.", kh: "គាត់ត្រូវបានភាពយន្តលើកទឹកចិត្ត។" },
    { cn: "我感觉很开心。", pinyin: "Wǒ gǎn jué hěn kāi xīn.", kh: "ខ្ញុំមានអារម្មណ៍សប្បាយរីករាយ។" },
    { cn: "他们之间有很深的感情。", pinyin: "Tā men zhī jiān yǒu hěn shēn de gǎn qíng.", kh: "ពួកគេមានអារម្មណ៍និងចំណងទំនាក់ទំនងខ្លាំង។" },
    { cn: "我感谢你的帮助。", pinyin: "Wǒ gǎn xiè nǐ de bāng zhù.", kh: "ខ្ញុំសូមអរគុណចំពោះជំនួយរបស់អ្នក។" },
    { cn: "你敢挑战我吗？", pinyin: "Nǐ gǎn tiǎo zhàn wǒ ma?", kh: "អ្នកហ៊ានទស្សនាខ្ញុំទេ?" },
    { cn: "你赶紧完成作业吧！", pinyin: "Nǐ gǎn jǐn wán chéng zuò yè ba!", kh: "អ្នកប្រញាប់បញ្ចប់ការងារផ្ទះផង!" },
    { cn: "天气很干，记得多喝水。", pinyin: "Tiān qì hěn gān, jì de duō hē shuǐ.", kh: "អាកាសធាតុស្ងួត គួរឱ្យចងចាំផឹកទឹកច្រើន។" },
    { cn: "他刚刚离开。", pinyin: "Tā gāng gāng lí kāi.", kh: "គាត់ទើបតែចាកចេញ។" },
    { cn: "我们正在高速公路上行驶。", pinyin: "Wǒ men zhèng zài gāo sù gōng lù shàng xíng shǐ.", kh: "ពួកយើងកំពុងបើកឡាននៅលើផ្លូវហាយវេ។" },
    { cn: "他的胳膊受伤了。", pinyin: "Tā de gē bo shòu shāng le.", kh: "ដៃរបស់គាត់បានរបួស។" },
    { cn: "各国的文化不同。", pinyin: "Gè guó de wén huà bù tóng.", kh: "វប្បធម៌នៃប្រទេសផ្សេងៗគ្នាមានភាពខុសគ្នា។" },
    { cn: "我每天跑三公里。", pinyin: "Wǒ měi tiān pǎo sān gōng lǐ.", kh: "ខ្ញុំរត់បីគីឡូម៉ែត្រក្នុងមួយថ្ងៃ។" },
    { cn: "他学了很多功夫。", pinyin: "Tā xué le hěn duō gōng fu.", kh: "គាត់បានរៀនកុងហ្វូច្រើន។" },
    { cn: "他的工资很高。", pinyin: "Tā de gōng zī hěn gāo.", kh: "ប្រាក់ឈ្នួលរបស់គាត់ខ្ពស់ខ្លាំង។" },
    { cn: "我们有共同的兴趣爱好。", pinyin: "Wǒ men yǒu gòng tóng de xìng qù ài hào.", kh: "ពួកយើងមានចំណាប់អារម្មណ៍ទូទៅដូចគ្នា។" },
    { cn: "这够了吗？", pinyin: "Zhè gòu le ma?", kh: "នេះគ្រប់គ្រាន់ទេ?" },
    { cn: "她喜欢购物。", pinyin: "Tā xǐ huān gòu wù.", kh: "គាត់ចូលចិត្តការដើរទិញឥវ៉ាន់។" },
    { cn: "我估计明天会下雨。", pinyin: "Wǒ gū jì míng tiān huì xià yǔ.", kh: "ខ្ញុំប៉ាន់ស្មានថាព្រឹកថ្ងៃស្អែកមានភ្លៀង។" },
    { cn: "老师鼓励我们多读书。", pinyin: "Lǎo shī gǔ lì wǒ men duō dú shū.", kh: "គ្រូសាលាបើកទឹកចិត្តឲ្យយើងអានសៀវភៅច្រើន។" },
    { cn: "他故意迟到了。", pinyin: "Tā gù yì chí dào le.", kh: "គាត់ត្រូវការច្បាស់ថាត្រូវធ្វើយ៉ាងចេតនា។" },
    { cn: "顾客正在排队。", pinyin: "Gù kè zhèng zài pái duì.", kh: "អតិថិជនកំពុងបន្ទុកបន្ទាប់។" },
    { cn: "你可以挂这幅画在墙上。", pinyin: "Nǐ kě yǐ guà zhè fú huà zài qiáng shàng.", kh: "អ្នកអាចព្យួរពិចនេះនៅលើជញ្ជាំងបាន។" },
    { cn: "这个问题是关键。", pinyin: "Zhè ge wèn tí shì guān jiàn.", kh: "សំណួរនេះជាផ្នែកចាំបាច់។" },
    { cn: "观众都在看演出。", pinyin: "Guān zhòng dōu zài kàn yǎn chū.", kh: "ទស្សនិកជនគ្រប់គ្នាកំពុងមើលការបង្ហាញ។" },
    { cn: "公司需要加强管理。", pinyin: "Gōng sī xū yào jiā qiáng guǎn lǐ.", kh: "ក្រុមហ៊ុនត្រូវការកែលម្អការគ្រប់គ្រង។" },
    { cn: "窗外的光很明亮。", pinyin: "Chuāng wài de guāng hěn míng liàng.", kh: "ពន្លឺនៅខាងក្រៅចេញបំផុត។" },
    { cn: "我们听到了广播通知。", pinyin: "Wǒ men tīng dào le guǎng bō tōng zhī.", kh: "យើងបានស្តាប់ព័ត៌មានផ្សាយ។" },
    { cn: "他在电视上看到了广告。", pinyin: "Tā zài diàn shì shàng kàn dào le guǎng gào.", kh: "គាត់បានមើលការផ្សាយពាណិជ្ជកម្មនៅលើទូរទស្សន៍។" },
    { cn: "我喜欢逛街。", pinyin: "Wǒ xǐ huān guàng jiē.", kh: "ខ្ញុំចូលចិត្តទស្សនាគ្រឿងសង្ហារិម។" },
    { cn: "公司有严格的规定。", pinyin: "Gōng sī yǒu yán gé de guī dìng.", kh: "ក្រុមហ៊ុនមានបទបញ្ជាដ៏តឹងរឹង។" },
    { cn: "他的国籍是中国。", pinyin: "Tā de guó jí shì zhōng guó.", kh: "សញ្ជាតិរបស់គាត់គឺជា​ចិន។" },
    { cn: "国际形势很复杂。", pinyin: "Guó jì xíng shì hěn fù zá.", kh: "ស្ថានភាពអន្តរជាតិកាន់តែស្មុគស្មាញ។" },
    { cn: "我喜欢喝果汁。", pinyin: "Wǒ xǐ huān hē guǒ zhī.", kh: "ខ្ញុំចូលចិត្តផឹកទឹកផ្លែឈើ។" },
    { cn: "这个过程很复杂。", pinyin: "Zhè ge guò chéng hěn fù zá.", kh: "ដំណើរការនេះពិបាកណាស់។" },
    { cn: "海洋非常广阔。", pinyin: "Hǎi yáng fēi cháng guǎng kuò.", kh: "មហាសមុទ្រលំបាកខ្លាំង។" },
    { cn: "她有点害羞。", pinyin: "Tā yǒu diǎn hài xiū.", kh: "គាត់ខ្មាស់អៀនបន្តិច។" },
    { cn: "寒假快到了。", pinyin: "Hán jià kuài dào le.", kh: "វិស្សមកាលរដូវរងារកំពុងមកដល់។" },
    { cn: "他满头是汗。", pinyin: "Tā mǎn tóu shì hàn.", kh: "គាត់គ្របដណ្តប់ដោយញើស។" },
    { cn: "我们的航班延误了。", pinyin: "Wǒ men de háng bān yán wù le.", kh: "ការហោះហើររបស់យើងបានពន្យារពេល។" },
    { cn: "运动有很多好处。", pinyin: "Yùn dòng yǒu hěn duō hǎo chu.", kh: "ការហាត់ប្រាណមានអត្ថប្រយោជន៍ច្រើន។" },
    { cn: "她好像很忙。", pinyin: "Tā hǎo xiàng hěn máng.", kh: "គាត់ចូលចិត្តមានការងារច្រើន។" },
    { cn: "请告诉我你的号码。", pinyin: "Qǐng gào su wǒ nǐ de hào mǎ.", kh: "សូមប្រាប់ខ្ញុំអំពីចំនួនរបស់អ្នក។" },
    { cn: "他考试合格了。", pinyin: "Tā kǎo shì hé gé le.", kh: "គាត់បានប្រឡងឈរជាសំណួរដោយសមរម្យ។" },
    { cn: "这件衣服合适我。", pinyin: "Zhè jiàn yī fú hé shì wǒ.", kh: "សម្លៀកបំពាក់នេះសមរម្យខ្ញុំ។" },
    { cn: "把书放进盒子里。", pinyin: "Bǎ shū fàng jìn hé zi lǐ.", kh: "ដាក់សៀវភៅទៅក្នុងប្រអប់។" },
    { cn: "这本书很厚。", pinyin: "Zhè běn shū hěn hòu.", kh: "សៀវភៅនេះក្រាស់ណាស់។" },
    { cn: "我后悔没有早点起床。", pinyin: "Wǒ hòu huǐ méi yǒu zǎo diǎn qǐ chuáng.", kh: "ខ្ញុំសោកស្តាយដែលមិនលើកព្រឹកឲ្យម៉ោង។" },
    { cn: "我常常上网浏览新闻。", pinyin: "Wǒ cháng cháng shàng wǎng liú lǎn xīn wén.", kh: "ខ្ញុំជាញឹកញាប់ប្រើអ៊ីនធឺណិតដើម្បីមើលព័ត៌មាន។" },
    { cn: "我们应该互相帮助。", pinyin: "Wǒ men yīng gāi hù xiāng bāng zhù.", kh: "ពួកយើងគួរឱ្យជួយគ្នា។" },
    { cn: "护士在医院工作。", pinyin: "Hù shi zài yī yuàn gōng zuò.", kh: "គិលានុបដ្ឋាយិកាកំពុងធ្វើការនៅមន្ទីរពេទ្យ។" },
    { cn: "他怀疑我在说谎。", pinyin: "Tā huái yí wǒ zài shuō huǎng.", kh: "គាត់សង្ស័យថាខ្ញុំកំពុងក្លែងក្លាយ។" },
    { cn: "我喜欢回忆我的旅行。", pinyin: "Wǒ xǐ huān huí yì wǒ de lǚ xíng.", kh: "ខ្ញុំចូលចិត្តអនុស្សាវរីយ៍ពីការធ្វើដំណើររបស់ខ្ញុំ។" },
    { cn: "我们参加了许多活动。", pinyin: "Wǒ men cān jiā le xǔ duō huó dòng.", kh: "ពួកយើងបានចូលរួមក្នុងសកម្មភាពជាច្រើន។" },
    { cn: "她是一个活泼的女孩。", pinyin: "Tā shì yī gè huó po de nǚ hái.", kh: "គាត់គឺជានារីដែលរស់រវើក។" },
    { cn: "火灾发生了。", pinyin: "Huǒ zāi fā shēng le.", kh: "ភ្លើងឆេះបានកើតឡើង។" },
    { cn: "他获得了第一名。", pinyin: "Tā huò dé le dì yī míng.", kh: "គាត់ទទួលបានទីមួយ។" },
    { cn: "这项工作需要良好的基础。", pinyin: "Zhè xiàng gōng zuò xū yào liáng hǎo de jī chǔ.", kh: "ការងារនេះត្រូវការមូលដ្ឋានល្អ។" },
    { cn: "她非常激动。", pinyin: "Tā fēi cháng jī dòng.", kh: "គាត់រំភើបណាស់។" },
    { cn: "他是一个积极的人。", pinyin: "Tā shì yī gè jī jí de rén.", kh: "គាត់គឺជាមនុស្សវិជ្ជមាន។" },
    { cn: "他积累了很多经验。", pinyin: "Tā jī lěi le hěn duō jīng yàn.", kh: "គាត់បានបន្សំបទពិសោធន៍ច្រើន។" },
    { cn: "即使下雨，我也要去。", pinyin: "Jí shǐ xià yǔ, wǒ yě yào qù.", kh: "បើទោះបីជាភ្លៀងធ្លាក់ ខ្ញុំនឹងទៅ។" },
    { cn: "我会及时回复你的消息。", pinyin: "Wǒ huì jí shí huí fù nǐ de xiāo xī.", kh: "ខ្ញុំនឹងឆ្លើយតបសាររបស់អ្នកទាន់ពេលវេលា។" },
    { cn: "我将寄一封信给你。", pinyin: "Wǒ jiāng jì yī fēng xìn gěi nǐ.", kh: "ខ្ញុំនឹងផ្ញើសារមួយទៅអ្នក។" },
    { cn: "他很擅长技术。", pinyin: "Tā hěn shàn cháng jì shù.", kh: "គាត់មានជំនាញក្នុងបច្ចេកវិទ្យាខ្លាំង។" },
    { cn: "既然你来了，我们开始吧。", pinyin: "Jì rán nǐ lái le, wǒ men kāi shǐ ba.", kh: "ចាប់តាំងពីអ្នកបានមក យើងចាប់ផ្តើមផង។" },
    { cn: "请继续努力。", pinyin: "Qǐng jì xù nǔ lì.", kh: "សូមអនុវត្តលើការខិតខំធ្វើការរបស់អ្នក។" },
    { cn: "我的计划是去旅行。", pinyin: "Wǒ de jì huà shì qù lǚ xíng.", kh: "ផែនការរបស់ខ្ញុំគឺធ្វើដំណើរ។" },
    { cn: "记者正在采访他。", pinyin: "Jì zhě zhèng zài cǎi fǎng tā.", kh: "អ្នកយកព័ត៌មានកំពុងសម្ភាសគាត់។" },
    { cn: "他要加班工作。", pinyin: "Tā yào jiā bān gōng zuò.", kh: "គាត់ត្រូវការធ្វើការថែមម៉ោង។" },
    { cn: "我们在加油站停下来。", pinyin: "Wǒ men zài jiā yóu zhàn tíng xià lái.", kh: "ពួកយើងបានបញ្ឈប់នៅស្ថានីយ៍ប្រេង។" },
    { cn: "家里有很多家具。", pinyin: "Jiā lǐ yǒu hěn duō jiā jù.", kh: "នៅផ្ទះមានគ្រឿងសង្ហារឹមច្រើន។" },
    { cn: "他的假期是下个月。", pinyin: "Tā de jiǎ qī shì xià gè yuè.", kh: "ចុងតែមួយគាត់គឺមានឈប់សំរាកក្នុងខែក្រោយ។" },
    { cn: "价格很高。", pinyin: "Jià gé hěn gāo.", kh: "តម្លៃខ្ពស់ណាស់។" },
    { cn: "坚持下去。", pinyin: "Jiān chí xià qù.", kh: "ត្រូវតែតស៊ូតទៅ។" },
    { cn: "我在减肥。", pinyin: "Wǒ zài jiǎn féi.", kh: "ខ្ញុំកំពុងស្រកទម្ងន់។" },
    { cn: "我们应该减少浪费。", pinyin: "Wǒmen yīnggāi jiǎn shǎo làng fèi.", kh: "យើងគួរតែលិខិតបន្ថយការបំពាន។" },
    { cn: "我有一个建议。", pinyin: "Wǒ yǒu yīgè jiàn yì.", kh: "ខ្ញុំមានសំណូមពរមួយ។" },
    { cn: "我想在将来去旅行。", pinyin: "Wǒ xiǎng zài jiāng lái qù lǚ xíng.", kh: "ខ្ញុំចង់ទៅធ្វើដំណើរនៅក្នុងអនាគត។" },
    { cn: "他得到了奖金。", pinyin: "Tā dédào le jiǎng jīn.", kh: "គាត់ទទួលបានប្រាក់រង្វាន់។" },
    { cn: "我们需要降低成本。", pinyin: "Wǒmen xū yào jiàng dī chéng běn.", kh: "យើងត្រូវការកាត់បន្ថយចំណាយ។" },
    { cn: "飞机降落了。", pinyin: "Fēi jī jiàng luò le.", kh: "យន្តហោះបានចុះចត។" },
    { cn: "我把书交给了老师。", pinyin: "Wǒ bǎ shū jiāo gěi le lǎo shī.", kh: "ខ្ញុំបានប្រគល់សៀវភៅឲ្យគ្រូ។" },
    { cn: "我们可以交流经验。", pinyin: "Wǒmen kěyǐ jiāo liú jīng yàn.", kh: "យើងអាចទំនាក់ទំនងជាមួយបទពិសោធន៍។" },
    { cn: "交通非常拥挤。", pinyin: "Jiāo tōng fēi cháng yōng jǐ.", kh: "ចរាចរណ៍ពោរពេញទៅដោយអារម្មណ៍តានតឹង។" },
    { cn: "郊区的房子很便宜。", pinyin: "Jiāo qū de fáng zi hěn pián yí.", kh: "ផ្ទះក្នុងតំបន់ជាយក្រុងមានតម្លៃថោក។" },
    { cn: "我为我的成功感到骄傲。", pinyin: "Wǒ wèi wǒ de chéng gōng gǎn dào jiāo ào.", kh: "ខ្ញុំមានមោទនភាពចំពោះជោគជ័យរបស់ខ្ញុំ។" },
    { cn: "我喜欢吃饺子。", pinyin: "Wǒ xǐ huān chī jiǎo zi.", kh: "ខ្ញុំចូលចិត្តបរិច្ឆេទ។" },
    { cn: "他是我的教授。", pinyin: "Tā shì wǒ de jiào shòu.", kh: "គាត់គឺជាសាស្រ្តាចារ្យរបស់ខ្ញុំ។" },
    { cn: "教育是非常重要的。", pinyin: "Jiào yù shì fēi cháng zhòng yào de.", kh: "ការអប់រំគឺមានសារៈសំខាន់ណាស់។" },
    { cn: "我接受了邀请。", pinyin: "Wǒ jiē shòu le yāo qǐng.", kh: "ខ្ញុំបានទទួលការអញ្ជើញ។" },
    { cn: "接着我们去吃饭。", pinyin: "Jiē zhe wǒmen qù chī fàn.", kh: "បន្ទាប់មកយើងទៅញ៉ាំម្ហូប។" },
    { cn: "结果他赢了比赛。", pinyin: "Jié guǒ tā yíng le bǐ sài.", kh: "លទ្ធផលគាត់ឈ្នះការប្រកួត។" },
    { cn: "春节是最重要的节日。", pinyin: "Chūn jié shì zuì zhòng yào de jié rì.", kh: "បុណ្យចុងឆ្នាំជាពិធីបុណ្យសំខាន់បំផុត។" },
    { cn: "我们要节约用水。", pinyin: "Wǒmen yào jié yuē yòng shuǐ.", kh: "យើងត្រូវសន្សំប្រើទឹក។" },
    { cn: "我可以解释这个问题。", pinyin: "Wǒ kě yǐ jiě shì zhè gè wèn tí.", kh: "ខ្ញុំអាចពន្យល់បញ្ហានេះ។" },
    { cn: "尽管下雨，我们还是去游泳了。", pinyin: "Jǐn guǎn xià yǔ, wǒmen hái shì qù yóu yǒng le.", kh: "ទោះបីថាមុតចរន្តក៏ដោយ យើងនៅតែមុខទៅហែលទឹក។" },
    { cn: "我很紧张。", pinyin: "Wǒ hěn jǐn zhāng.", kh: "ខ្ញុំមានភាពតានតឹង។" },
    { cn: "禁止吸烟。", pinyin: "Jìn zhǐ xī yān.", kh: "ហាមឃាត់ការសក់ភៅ។" },
    { cn: "我们正在进行会议。", pinyin: "Wǒmen zhèng zài jìn xíng huì yì.", kh: "យើងកំពុងអនុវត្តកិច្ចប្រជុំ។" },
    { cn: "我喜欢看京剧。", pinyin: "Wǒ xǐ huān kàn jīng jù.", kh: "ខ្ញុំចូលចិត្តមើលល្ខោនប៉េកាំង។" },
    { cn: "这场比赛非常精彩。", pinyin: "Zhè chǎng bǐ sài fēi cháng jīng cǎi.", kh: "ការប្រកួតនេះអស្ចារ្យណាស់។" },
    { cn: "中国的经济发展很快。", pinyin: "Zhōng guó de jīng jì fā zhǎn hěn kuài.", kh: "សេដ្ឋកិច្ចរបស់ចិនកំពុងអភិវឌ្ឍន៍យ៉ាងលឿន។" },
    { cn: "我有很多经历。", pinyin: "Wǒ yǒu hěn duō jīng lì.", kh: "ខ្ញុំមានបទពិសោធន៍ច្រើន។" },
    { cn: "这次旅行给我带来了很多经验。", pinyin: "Zhè cì lǚ xíng gěi wǒ dài lái le hěn duō jīng yàn.", kh: "ដំណើរទៅកាន់ប្រទេសនេះបានផ្តល់បទពិសោធន៍មួយច្រើនសម្រាប់ខ្ញុំ។" },
    { cn: "这里的景色非常美丽。", pinyin: "Zhè lǐ de jǐng sè fēi cháng měi lì.", kh: "ទេសភាពនៅទីនេះស្អាតខ្លាំងណាស់។" },
    { cn: "警察在路上巡逻。", pinyin: "Jǐng chá zài lù shàng xún luó.", kh: "ប៉ូលីសកំពុងធ្វើការត្រួតពិនិត្យនៅលើផ្លូវ។" },
    { cn: "他们之间有很强的竞争。", pinyin: "Tā men zhī jiān yǒu hěn qiáng de jìng zhēng.", kh: "ពួកគេមានការប្រកួតប្រជែងខ្លាំង។" },
    { cn: "他竟然赢了比赛。", pinyin: "Tā jìng rán yíng le bǐ sài.", kh: "គាត់ដល់ថ្នាក់នោះឈ្នះការប្រកួត។" },
    { cn: "我在镜子前整理衣服。", pinyin: "Wǒ zài jìng zi qián zhěng lǐ yī fú.", kh: "ខ្ញុំកំពុងរៀបចំសម្លៀកបំពាក់នៅមុខកញ្ចក់។" },
    { cn: "究竟发生了什么事情？", pinyin: "Jiū jìng fā shēng le shén me shì qíng?", kh: "ដូចម្តេចបានជា កើតមានអ្វី?" },
    { cn: "他举起了手。", pinyin: "Tā jǔ qǐ le shǒu.", kh: "គាត់បានលើកដៃ។" },
    { cn: "我们将举办一个会议。", pinyin: "Wǒmen jiāng jǔ bàn yí gè huì yì.", kh: "យើងនឹងរៀបចំកិច្ចប្រជុំមួយ។" },
    { cn: "他将在周末举行一个聚会。", pinyin: "Tā jiāng zài zhōu mò jǔ xíng yí gè jù huì.", kh: "គាត់នឹងធ្វើការជួបជុំនៅចុងសប្ដាហ៍។" },
    { cn: "我拒绝了他的请求。", pinyin: "Wǒ jù jué le tā de qǐng qiú.", kh: "ខ្ញុំបានបដិសេធការស្នើសុំរបស់គាត់។" },
    { cn: "我们今天有一个聚会。", pinyin: "Wǒmen jīn tiān yǒu yí gè jù huì.", kh: "យើងមានកម្មវិធីជប់លៀងមួយនៅថ្ងៃនេះ។" },
    { cn: "他们之间的距离很远。", pinyin: "Tā men zhī jiān de jù lí hěn yuǎn.", kh: "ចម្ងាយរវាងពួកគេពិបាក។" },
    { cn: "不要开玩笑！", pinyin: "Bù yào kāi wán xiào!", kh: "កុំកំប្លែងទេ!" },
    { cn: "她看起来很开心。", pinyin: "Tā kàn qǐ lái hěn kāi xīn.", kh: "គាត់មើលទៅរីករាយណាស់។" },
    { cn: "他的看法和我不一样。", pinyin: "Tā de kàn fǎ hé wǒ bù yī yàng.", kh: "ទស្សនៈរបស់គាត់ខុសពីខ្ញុំ។" },
    { cn: "我想吃烤鸭。", pinyin: "Wǒ xiǎng chī kǎo yā.", kh: "ខ្ញុំចង់បរិច្ឆេទទាអាំង។" },
    { cn: "你考虑过这个问题吗？", pinyin: "Nǐ kǎo lǜ guò zhè gè wèn tí ma?", kh: "តើអ្នកបានពិចារណាអំពីបញ្ហានេះហើយទេ?" },
    { cn: "院子里有几棵树。", pinyin: "Yuàn zi lǐ yǒu jǐ kē shù.", kh: "នៅក្នុងសួនមានដើមឈើពីរដើម។" },
    { cn: "科学的发展很快。", pinyin: "Kē xué de fā zhǎn hěn kuài.", kh: "ការអភិវឌ្ឍវិទ្យាសាស្ត្រមានល្បឿនខ្លាំង។" },
    { cn: "他有点咳嗽。", pinyin: "Tā yǒu diǎn ké sou.", kh: "គាត់មានក្អកបន្តិច។" },
    { cn: "这真是个可怜的人。", pinyin: "Zhè zhēn shì gè kě lián de rén.", kh: "នរណាម្នាក់នេះមានអាណិតអាសូរណាស់។" },
    { cn: "可是我不想去。", pinyin: "Kě shì wǒ bù xiǎng qù.", kh: "ប៉ុន្តែខ្ញុំមិនចង់ទៅទេ។" },
    { cn: "真可惜，我们没有机会再见面。", pinyin: "Zhēn kě xī, wǒ men méi yǒu jī huì zài jiàn miàn.", kh: "ជាអកុសល ដែលយើងមិនមានឱកាសជួបគ្នាជាការពិតទេ។" },
    { cn: "这是我的客厅。", pinyin: "Zhè shì wǒ de kè tīng.", kh: "នេះគឺជាបន្ទប់ទទួលភ្ញៀវរបស់ខ្ញុំ។" },
    { cn: "我肯定他会来。", pinyin: "Wǒ kěn dìng tā huì lái.", kh: "ខ្ញុំប្រាកដថាគាត់នឹងមក។" },
    { cn: "这个箱子是空的。", pinyin: "Zhè gè xiāng zi shì kōng de.", kh: "ប្រអប់នេះទទេ។" },
    { cn: "空气新鲜极了。", pinyin: "Kōng qì xīn xiān jí le.", kh: "ខ្យល់ស្រស់ណាស់។" },
    { cn: "恐怕他已经走了。", pinyin: "Kǒng pà tā yǐ jīng zǒu le.", kh: "ខ្ញុំខ្លាចថាគាត់បានចាកចេញហើយ។" },
    { cn: "这道菜很苦。", pinyin: "Zhè dào cài hěn kǔ.", kh: "ម្ហូបនេះជូរចត់ណាស់។" },
    { cn: "我喝了一瓶矿泉水。", pinyin: "Wǒ hē le yī píng kuàng quán shuǐ.", kh: "ខ្ញុំបានផឹកទឹករ៉ែបូកមួយដបទៅ។" },
    { cn: "我感到困了。", pinyin: "Wǒ gǎn dào kùn le.", kh: "ខ្ញុំមានអារម្មណ៍ងងុយគេង។" },
    { cn: "我们遇到了困难。", pinyin: "Wǒ men yù dào le kùn nan.", kh: "យើងប្រទៈមានការលំបាក។" },
    { cn: "请把垃圾扔进垃圾桶里。", pinyin: "Qǐng bǎ lājī rēng jìn lājī tǒng lǐ.", kh: "សូមទម្លាក់សំរាមចូលទៅក្នុងធុងសំរាម។" },
    { cn: "他拉着我的手。", pinyin: "Tā lā zhe wǒ de shǒu.", kh: "គាត់បានទាញដៃខ្ញុំ។" },
    { cn: "这道菜有点辣。", pinyin: "Zhè dào cài yǒu diǎn là.", kh: "ម្ហូបនេះហិរណាស់។" },
    { cn: "我来不及做作业了。", pinyin: "Wǒ lái bù jí zuò zuò yè le.", kh: "ខ្ញុំមិនទាន់មានពេលធ្វើការងារផ្ទះទេ។" },
    { cn: "你来得及赶上火车吗？", pinyin: "Nǐ lái de jí gǎn shàng huǒ chē ma?", kh: "តើអ្នកមានពេលទាន់ទៅរថភ្លើងទេ?" },
    { cn: "他来自北京。", pinyin: "Tā lái zì Běi jīng.", kh: "គាត់មកពីប៉េកាំង។" },
    { cn: "他是一个懒人。", pinyin: "Tā shì yí gè lǎn rén.", kh: "គាត់គឺជាមនុស្សខ្ជិល។" },
    { cn: "你不要浪费时间。", pinyin: "Nǐ bù yào làng fèi shí jiān.", kh: "កុំខ្ជះខ្ជាយពេលវេលា។" },
    { cn: "这个电影很浪漫。", pinyin: "Zhè gè diàn yǐng hěn làng màn.", kh: "ភាពយន្តនេះមានមនោសញ្ចេតនា។" },
    { cn: "老虎是一种危险的动物。", pinyin: "Lǎo hǔ shì yī zhǒng wēi xiǎn de dòng wù.", kh: "ខ្លាជាគល់សត្វគ្រោះថ្នាក់។" },
    { cn: "请保持冷静。", pinyin: "Qǐng bǎo chí lěng jìng.", kh: "សូមស្ងប់ស្ងាត់។" },
    { cn: "我去理发了。", pinyin: "Wǒ qù lǐ fà le.", kh: "ខ្ញុំបានទៅកាត់សក់។" },
    { cn: "我理解你的意思。", pinyin: "Wǒ lǐ jiě nǐ de yì si.", kh: "ខ្ញុំយល់ដឹងអំពីអត្ថន័យរបស់អ្នក។" },
    { cn: "他有一个理想。", pinyin: "Tā yǒu yí gè lǐ xiǎng.", kh: "គាត់មានល្អបំផុត។" },
    { cn: "我们礼拜天见。", pinyin: "Wǒ men lǐ bài tiān jiàn.", kh: "យើងនឹងជួបគ្នានៅថ្ងៃអាទិត្យ។" },
    { cn: "他说话很有礼貌。", pinyin: "Tā shuō huà hěn yǒu lǐ mào.", kh: "គាត់និយាយដោយមានសុភាពរាបសា។" },
    { cn: "例如，我们可以去游泳。", pinyin: "Lì rú, wǒ men kě yǐ qù yóu yǒng.", kh: "ឧទាហរណ៍ យើងអាចទៅហែលទឹកបាន។" },
    { cn: "他有很多力气。", pinyin: "Tā yǒu hěn duō lì qi.", kh: "គាត់មានកម្លាំងច្រើន។" },
    { cn: "他很厉害。", pinyin: "Tā hěn lì hai.", kh: "គាត់អស្ចារ្យណាស់។" },
    { cn: "我们俩一起去旅行。", pinyin: "Wǒ men liǎ yī qǐ qù lǚ xíng.", kh: "ពួកយើងទាំងពីរទៅដំណើរទៅជាមួយគ្នា។" },
    { cn: "保持联系！", pinyin: "Bǎo chí lián xì!", kh: "ទំនាក់ទំនងគ្នាទាំងអស់!" },
    { cn: "他连中文都不会说。", pinyin: "Tā lián zhōng wén dōu bù huì shuō.", kh: "គាត់សូម្បីតែភាសាចិនក៏មិនអាចនិយាយបានទេ។" },
    { cn: "今天天气凉快，适合出去玩。", pinyin: "Jīn tiān tiān qì liáng kuai, shì hé chū qù wán.", kh: "អាកាសធាតុទល់ថ្ងៃនេះត្រជាក់ ហើយសមស្របសម្រាប់ការចូលលេងក្រៅ។" },
    { cn: "我没有零钱，可以找给你吗？", pinyin: "Wǒ méi yǒu líng qián, kě yǐ zhǎo gěi nǐ ma?", kh: "ខ្ញុំគ្មានការផ្លាស់ប្តូរតិចតួច ទើបអាចផ្តល់ជូនអ្នកបានទេ?" },
    { cn: "另外，我还要买一些东西。", pinyin: "Lìng wài, wǒ hái yào mǎi yī xiē dōng xī.", kh: "លើសពីនេះទៀត ខ្ញុំនឹងទិញអ្វីផ្សេងទៀត។" },
    { cn: "她的中文说得非常流利。", pinyin: "Tā de zhōng wén shuō de fēi cháng liú lì.", kh: "ភាសាចិនរបស់គាត់និយាយបានស្ទាត់ណាស់។" },
    { cn: "这种衣服很流行，很多人都穿。", pinyin: "Zhè zhǒng yī fú hěn liú xíng, hěn duō rén dōu chuān.", kh: "សម្លៀកបំពាក់នេះពេញនិយមណាស់ មនុស្សច្រើននិយាយខ្លួនពាក់។" },
    { cn: "你打算留在这里多久？", pinyin: "Nǐ dǎ suàn liú zài zhè lǐ duō jiǔ?", kh: "អ្នកគ្រោងស្នាក់នៅទីនេះប៉ុន្មានថ្ងៃ?" },
    { cn: "我们计划去旅行。", pinyin: "Wǒ men jì huà qù lǚ xíng.", kh: "យើងគ្រោងធ្វើដំណើរ។" },
    { cn: "办公室里有点乱。", pinyin: "Bàng gōng shì lǐ yǒu diǎn luàn.", kh: "ក្នុងការិយាល័យមានភាពវឹកវរ។" },
    { cn: "他是个优秀的律师。", pinyin: "Tā shì gè yōu xiù de lǜ shī.", kh: "គាត់គឺជាមេធាវីល្អឥតខ្ចោះ។" },
    { cn: "这件事给我们带来了很多麻烦。", pinyin: "Zhè jiàn shì gěi wǒ men dài lái le hěn duō má fan.", kh: "បញ្ហានេះបានបង្កើតបញ្ហាច្រើនសម្រាប់យើង។" },
    { cn: "他做事很马虎。", pinyin: "Tā zuò shì hěn mǎ hu.", kh: "គាត់ធ្វើការប្រហែលស្មើគ្នា។" },
    { cn: "这杯水已经满了。", pinyin: "Zhè bēi shuǐ yǐ jīng mǎn le.", kh: "ពែងទឹកនេះពេញហើយ។" },
    { cn: "他有一头浓密的毛。", pinyin: "Tā yǒu yī tóu nóng mì de máo.", kh: "គាត់មានសក់ដែលគ្របដណ្តប់។" },
    { cn: "我用毛巾擦干脸。", pinyin: "Wǒ yòng máo jīn cā gān liǎn.", kh: "ខ្ញុំប្រើកន្សែងសម្អាតមុខ។" },
    { cn: "她真是一个美丽的女孩。", pinyin: "Tā zhēn shì yí gè měi lì de nǚ hái.", kh: "គាត់ជានារីស្រស់ស្អាតម្នាក់។" },
    { cn: "我做了一个美好的梦。", pinyin: "Wǒ zuò le yī gè měi hǎo de mèng.", kh: "ខ្ញុំបានសុបិន្តដ៏ល្អមួយ។" },
    { cn: "我们迷路了，找不到回家的路。", pinyin: "Wǒ men mí lù le, zhǎo bù dào huí jiā de lù.", kh: "យើងវង្វេងផ្លូវ ហើយរកមិនឃើញផ្លូវត្រលប់មកផ្ទះ។" },
    { cn: "请输入密码。", pinyin: "Qǐng shū rù mì mǎ.", kh: "សូមបញ្ចូលពាក្យសម្ងាត់។" },
    { cn: "这个软件是免费的。", pinyin: "Zhè gè ruǎn jiàn shì miǎn fèi de.", kh: "កម្មវិធីនេះឥតគិតថ្លៃ។" },
    { cn: "一秒钟的时间非常宝贵。", pinyin: "Yī miǎo zhōng de shí jiān fēi cháng bǎo guì.", kh: "ពេលវេលាអ្នកចំណាយក្នុងមួយទីពីរមានតំលៃខ្ពស់ណាស់។" },
    { cn: "中国有56个民族。", pinyin: "Zhōng guó yǒu 56 gè mín zú.", kh: "ប្រទេសចិនមានជនជាតិ56ប្រភេទ។" },
    { cn: "我的母亲是最好的。", pinyin: "Wǒ de mǔ qīn shì zuì hǎo de.", kh: "ម្តាយរបស់ខ្ញុំគឺល្អបំផុត។" },
    { cn: "他的目标是成为医生。", pinyin: "Tā de mù dì shì chéng wéi yī shēng.", kh: "គោលបំណងរបស់គាត់គឺក្លាយជាគ្រូពេទ្យ។" },
    { cn: "她有很强的耐心。", pinyin: "Tā yǒu hěn qiáng de nài xīn.", kh: "គាត់មានអត់ធ្មត់ខ្ពស់។" },
    { cn: "难道你不想去吗？", pinyin: "Nán dào nǐ bù xiǎng qù ma?", kh: "តើវាប្រហែលគួរតែចង់ទៅទេ?" },
    { cn: "我感觉有点难受。", pinyin: "Wǒ gǎn jué yǒu diǎn nán shòu.", kh: "ខ្ញុំមានអារម្មណ៍មិនស្រួល។" },
    { cn: "这个盒子在里面。", pinyin: "Zhè gè hé zi zài nèi miàn.", kh: "ប្រអប់នេះនៅខាងក្នុង។" },
    { cn: "这个问题的内容很复杂。", pinyin: "Zhè gè wèn tí de nèi róng hěn fù zá.", kh: "មាតិកានៃសំណួរនេះស្មុគស្មាញណាស់។" },
    { cn: "他有很强的能力。", pinyin: "Tā yǒu hěn qiáng de néng lì.", kh: "គាត់មានសមត្ថភាពខ្ពស់។" },
    { cn: "他的年龄很小。", pinyin: "Tā de nián líng hěn xiǎo.", kh: "អាយុរបស់គាត់មិនសូវចាស់ទេ។" },
    { cn: "你能帮我弄这个吗？", pinyin: "Nǐ néng bāng wǒ nòng zhè gè ma?", kh: "តើអ្នកអាចជួយខ្ញុំធ្វើអ្វីនេះបានទេ?" },
    { cn: "天气暖和了，我们可以出去玩。", pinyin: "Tiān qì nuǎn huo le, wǒ men kě yǐ chū qù wán.", kh: "អាកាសធាតុកក់ក្តៅហើយ យើងអាចទៅលេងក្រៅបាន។" },
    { cn: "偶尔我会去跑步。", pinyin: "ǒu ěr wǒ huì qù pǎo bù.", kh: "ខ្ញុំទៅរត់ជាពេលក្រោម។" },
    { cn: "排队的时候要保持安静。", pinyin: "Pái duì de shí hòu yào bǎo chí ān jìng.", kh: "នៅពេលដែលនៅក្នុងជួរ គួរតែរក្សាសន្តិភាព។" },
    { cn: "他会排列这些数字。", pinyin: "Tā huì pái liè zhèxiē shùzì.", kh: "គាត់អាចរៀបចំលេខទាំងនេះបាន។" },
    { cn: "你能判断他在说真话吗？", pinyin: "Nǐ néng pàn duàn tā zài shuō zhēn huà ma?", kh: "អ្នកអាចវិនិច្ឆ័យបានទេថាគាត់កំពុងនិយាយពិត?" },
    { cn: "我陪你一起去。", pinyin: "Wǒ péi nǐ yī qǐ qù.", kh: "ខ្ញុំនឹងទៅជាមួយអ្នក។" },
    { cn: "老师批评了他的作业。", pinyin: "Lǎo shī pī píng le tā de zuò yè.", kh: "គ្រូបានរិះគន់កិច្ចការផ្ទះរបស់គាត់។" },
    { cn: "他的皮肤很白。", pinyin: "Tā de pí fū hěn bái.", kh: "ស្បែករបស់គាត់ពណ៌សខ្លាំង។" },
    { cn: "他脾气很坏。", pinyin: "Tā pí qi hěn huài.", kh: "គាត់មានកំហឹងខ្លាំង។" },
    { cn: "我读了一篇有趣的文章。", pinyin: "Wǒ dú le yī piān yǒu qù de wén zhāng.", kh: "ខ្ញុំបានអានអត្ថបទដែលមានចំណាប់អារម្មណ៍។" },
    { cn: "他骗了我一笔钱。", pinyin: "Tā piàn le wǒ yī bǐ qián.", kh: "គាត់បានបោកខ្ញុំដោយប្រាក់មួយចំនួន។" },
    { cn: "我们一起打乒乓球。", pinyin: "Wǒ men yī qǐ dǎ pīng pāng qiú.", kh: "យើងកំពុងលេងពីងប៉ុងជាមួយគ្នា។" },
    { cn: "平时他很少出门。", pinyin: "Píng shí tā hěn shǎo chū mén.", kh: "ជាធម្មតាគាត់មិនធ្លាប់ចេញពីផ្ទះទេ។" },
    { cn: "这本书破了。", pinyin: "Zhè běn shū pò le.", kh: "សៀវភៅនេះខូចហើយ។" },
    { cn: "我喜欢吃葡萄。", pinyin: "Wǒ xǐ huān chī pú táo.", kh: "ខ្ញុំចូលចិត្តបរិភោគទំពាំងបាយជូរ។" },
    { cn: "这种现象在普遍存在。", pinyin: "Zhè zhǒng xiàn xiàng zài pǔ biàn cún zài.", kh: "ស្ថានការណ៍នេះមានសកម្មភាពជាសកល។" },
    { cn: "普通话是中国的官方语言。", pinyin: "Pǔ tōng huà shì zhōng guó de guān fāng yǔ yán.", kh: "ភាសាចិនកុកងឺគឺជាភាសារដ្ឋាភិបាលរបស់ប្រទេសចិន។" },
    { cn: "首先，我们需要做这个。", pinyin: "Shǒu xiān, wǒ men xū yào zuò zhè ge.", kh: "ទីមុន បញ្ជីនេះយើងត្រូវការធ្វើរឿងនេះ។" },
    { cn: "其中一个非常重要。", pinyin: "Qí zhōng yī ge fēi cháng zhòng yào.", kh: "ក្នុងចំណោមពួកគេចំណែកមួយមានសារៈសំខាន់ខ្លាំង។" },
    { cn: "气候变得越来越热。", pinyin: "Qì hòu biàn dé yuè lái yuè rè.", kh: "អាកាសធាតុកំពុងក្តៅឡើងទៀតៗ។" },
    { cn: "千万不要忘记带护照。", pinyin: "Qiān wàn bù yào wàng jì dài hù zhào.", kh: "មិនគួរឲ្យភ្លេចយកពասពកទេសចរណ៍ទេ។" },
    { cn: "我申请了签证。", pinyin: "Wǒ shēn qǐng le qiān zhèng.", kh: "ខ្ញុំបានដាក់ពាក្យស្នាក់ការទិដ្ឋាការ។" },
    { cn: "他敲了敲门。", pinyin: "Tā qiāo le qiāo mén.", kh: "គាត់បានគោះទ្វារ។" },
    { cn: "我们过了一个桥。", pinyin: "Wǒ men guò le yī ge qiáo.", kh: "យើងបានឆ្លងកាត់ស្ពានមួយ។" },
    { cn: "我喜欢巧克力。", pinyin: "Wǒ xǐ huān qiǎo kè lì.", kh: "ខ្ញុំចូលចិត្តសូកូឡា។" },
    { cn: "她是我的亲戚。", pinyin: "Tā shì wǒ de qīn qi.", kh: "នាងគឺជាសាច់ញាតិរបស់ខ្ញុំ។" },
    { cn: "他看起来很轻松。", pinyin: "Tā kàn qǐ lái hěn qīng sōng.", kh: "គាត់មើលទៅងាយស្រួល។" },
    { cn: "情况越来越严重。", pinyin: "Qíng kuàng yuè lái yuè yán zhòng.", kh: "ស្ថានការណ៍កំពុងកើតឡើងធ្ងន់ធ្ងរ។" },
    { cn: "他家很穷。", pinyin: "Tā jiā hěn qióng.", kh: "គ្រួសាររបស់គាត់ក្រីក្រ។" },
    { cn: "他们之间有很大的区别。", pinyin: "Tā men zhī jiān yǒu hěn dà qū bié.", kh: "មានភាពខុសគ្នា​យ៉ាងច្រើនរវាងពួកគេ។" },
    { cn: "我要取一些文件。", pinyin: "Wǒ yào qǔ yī xiē wén jiàn.", kh: "ខ្ញុំត្រូវយកឯកសារខ្លះៗ។" },
    { cn: "全部都是他的错。", pinyin: "Quán bù dōu shì tā de cuò.", kh: "ទាំងអស់គឺជាកំហុសរបស់គាត់។" },
    { cn: "缺点是他不够细心。", pinyin: "Quē diǎn shì tā bù gòu xì xīn.", kh: "គុណវិបត្តិគឺគាត់មិនម៉ត់ចត់គ្រប់គ្រាន់។" },
    { cn: "我们缺少一些资金。", pinyin: "Wǒ men quē shǎo yī xiē zījīn.", kh: "យើងខ្វះខាតប្រាក់ចំណេញខ្លះៗ។" },
    { cn: "他却没有答应。", pinyin: "Tā què méi yǒu dā yìng.", kh: "គាត់ប៉ុន្តែមិនបានទទួលយល់ព្រមទេ។" },
    { cn: "这确实是个问题。", pinyin: "Zhè què shí shì gè wèn tí.", kh: "នេះជា​ការ​ពិត​ជា​បញ្ហាមួយ។" },
    { cn: "然而，我们没有足够的时间。", pinyin: "Rán ér, wǒ men méi yǒu zú gòu de shí jiān.", kh: "ទោះយ៉ាងណាក៏ដោយ យើងគ្មានពេលវេលាផ đủនោះទេ។" },
    { cn: "街道上非常热闹。", pinyin: "Jiē dào shàng fēi cháng rè nao.", kh: "ផ្លូវតាមលើគឺរស់រវើកណាស់។" },
    { cn: "任何人都可以参加比赛。", pinyin: "Rèn hé rén dōu kě yǐ cān jiā bǐ sài.", kh: "ណាមួយអាចចូលរួមការប្រកួតបាន។" },
    { cn: "我有一个重要的任务。", pinyin: "Wǒ yǒu yī gè zhòng yào de rèn wu.", kh: "ខ្ញុំមានភារកិច្ចសំខាន់មួយ។" },
    { cn: "我扔掉了所有的垃圾。", pinyin: "Wǒ rēng diào le suǒ yǒu de lājī.", kh: "ខ្ញុំបានបោះបញ្ជីទាំងអស់នៃសំរាម។" },
    { cn: "他仍然在等待。", pinyin: "Tā réng rán zài děng dài.", kh: "គាត់នៅតែគាំងស្ថិតស្ថេរ។" },
    { cn: "我每天都写日记。", pinyin: "Wǒ měi tiān dōu xiě rì jì.", kh: "ខ្ញុំបានសរសេរកំណត់ហេតុប្រចាំថ្ងៃរៀងរាល់ថ្ងៃ។" },
    { cn: "这是商店的入口。", pinyin: "Zhè shì shāng diàn de rù kǒu.", kh: "នេះគឺជាច្រកចូលរបស់ហាង។" },
    { cn: "我们去散步吧。", pinyin: "Wǒ men qù sàn bù ba.", kh: "យើងទៅដើរលំហែគ្នាថាតើ។" },
    { cn: "森林里有很多动物。", pinyin: "Sēn lín lǐ yǒu hěn duō dòng wù.", kh: "ក្នុងព្រៃឈើមានសត្វច្រើន។" },
    { cn: "这张沙发很舒服。", pinyin: "Zhè zhāng shā fā hěn shū fu.", kh: "កៅអីនេះមានសុខភាពខ្លាំង។" },
    { cn: "她听到这个消息感到伤心。", pinyin: "Tā tīng dào zhè ge xiāo xī gǎn dào shāng xīn.", kh: "នាងបានស្តាប់ព័ត៍មាននេះហើយមានអារម្មណ៍សោកស្តាយ។" },
    { cn: "我们一起商量这个问题。", pinyin: "Wǒ men yī qǐ shāng liáng zhè ge wèn tí.", kh: "យើងពិភាក្សារឿងនេះរួមគ្នា។" },
    { cn: "他稍微迟到了。", pinyin: "Tā shāo wēi chí dào le.", kh: "គាត់យឺតមកបន្តិចបន្តួច។" },
    { cn: "我需要一把勺子。", pinyin: "Wǒ xū yào yī bǎ sháo zi.", kh: "ខ្ញុំត្រូវការស្លាបព្រាមួយ។" },
    { cn: "我们生活在一个复杂的社会中。", pinyin: "Wǒ men shēng huó zài yī gè fù zá de shè huì zhōng.", kh: "យើងរស់នៅក្នុងសង្គមដែលមានភាពស្មុគស្មាញ។" },
    { cn: "这条河很深。", pinyin: "Zhè tiáo hé hěn shēn.", kh: "ទន្លេនេះជ្រៅណាស់។" },
    { cn: "我申请了一个职位。", pinyin: "Wǒ shēn qǐng le yī gè zhí wèi.", kh: "ខ្ញុំបានដាក់ពាក្យស្នាក់ការងារមួយ។" },
    { cn: "他甚至不敢开口。", pinyin: "Tā shèn zhì bù gǎn kāi kǒu.", kh: "គាត់សូម្បីតែមិន敢និយាយ។" },
    { cn: "他的生活很简单。", pinyin: "Tā de shēng huó hěn jiǎn dān.", kh: "ជីវិតរបស់គាត់សាមញ្ញណាស់។" },
    { cn: "生命是宝贵的。", pinyin: "Shēng mìng shì bǎo guì de.", kh: "ជីវិតគឺជាការសំខាន់និងមានតម្លៃ។" },
    { cn: "他的生意非常成功。", pinyin: "Tā de shēng yì fēi cháng chéng gōng.", kh: "ពាណិជ្ជកម្មរបស់គាត់មានជោគជ័យយ៉ាងខ្លាំង។" },
    { cn: "我们省了很多钱。", pinyin: "Wǒ men shěng le hěn duō qián.", kh: "យើងបានបន្ថយប្រាក់ចំណេញជាច្រើន។" },
    { cn: "剩下的都放在这里。", pinyin: "Shèng xià de dōu fàng zài zhè lǐ.", kh: "អ្វីដែលនៅសល់ត្រូវដាក់នៅទីនេះ។" },
    { cn: "这次考试我失败了。", pinyin: "Zhè cì kǎo shì wǒ shī bài le.", kh: "ការប្រឡងនេះខ្ញុំបានបរាជ័យ។" },
    { cn: "他对结果感到失望。", pinyin: "Tā duì jié guǒ gǎn dào shī wàng.", kh: "គាត់មានអារម្មណ៍ខកចិត្តចំពោះលទ្ធផល។" },
    { cn: "这位师傅非常有经验。", pinyin: "Zhè wèi shī fu fēi cháng yǒu jīng yàn.", kh: "គ្រូម្នាក់នេះមានបទពិសោធន៍ខ្ពស់ណាស់។" },
    { cn: "他十分喜欢运动。", pinyin: "Tā shí fēn xǐ huān yùn dòng.", kh: "គាត់ចូលចិត្តកីឡាយ៉ាងខ្លាំង។" },
    { cn: "实际情况比我们预想的要复杂。", pinyin: "Shí jì qíng kuàng bǐ wǒ men yù xiǎng de yào fù zá.", kh: "ស្ថានភាពពិតប្រាកដមានភាពស្មុគស្មាញជាងដែលយើងគិត។" },
    { cn: "他实在是太聪明了。", pinyin: "Tā shí zài shì tài cōng míng le.", kh: "គាត់ពិតជាឆ្លាតស្រឡងណាស់។" },
    { cn: "这件事使我感到很惊讶。", pinyin: "Zhè jiàn shì shǐ wǒ gǎn dào hěn jīng yà.", kh: "រឿងនេះធ្វើឲ្យខ្ញុំមានការភ្ញាក់ផ្អើល។" },
    { cn: "他每天都使用电脑。", pinyin: "Tā měi tiān dōu shǐ yòng diàn nǎo.", kh: "គាត់ប្រើកុំព្យូទ័ររៀងរាល់ថ្ងៃ។" },
    { cn: "21世纪是科技发展的时代。", pinyin: "21 Shì jì shì kē jì fā zhǎn de shí dài.", kh: "សតវត្សទី 21 គឺជាការអភិវឌ្ឍន៍បច្ចេកវិទ្យា។" },
    { cn: "你是否喜欢这本书？", pinyin: "Nǐ shì fǒu xǐ huān zhè běn shū?", kh: "តើអ្នកចូលចិត្តសៀវភៅនេះឬទេ?" },
    { cn: "这件衣服很适合你。", pinyin: "Zhè jiàn yī fú hěn shì hé nǐ.", kh: "សម្លៀកបំពាក់នេះសមរម្យខ្លាំងសម្រាប់អ្នក។" },
    { cn: "他适应了新环境。", pinyin: "Tā shì yìng le xīn huán jìng.", kh: "គាត់បានអាចសម្របខ្លួនជាមួយបរិស្ថានថ្មី។" },
    { cn: "我收到了你的信。", pinyin: "Wǒ shōu dào le nǐ de xìn.", kh: "ខ្ញុំទទួលបានសំបុត្ររបស់អ្នក។" },
    { cn: "今年的收入很可观。", pinyin: "Jīn nián de shōu rù hěn kě guān.", kh: "ប្រាក់ចំណូលឆ្នាំនេះគឺគួរឲ្យអបអរសាទរ។" },
    { cn: "他收拾好房间后出去玩了。", pinyin: "Tā shōu shi hǎo fáng jiān hòu chū qù wán le.", kh: "គាត់បានធ្វើសម្ដែងសន្លឹកបន្ទប់ហើយចេញទៅលេង។" },
    { cn: "北京是中国的首都。", pinyin: "Běi jīng shì zhōng guó de shǒu dū.", kh: "ប៉េកាំងគឺជារដ្ឋធានីនៃប្រទេសចិន។" },
    { cn: "首先，你需要了解项目的背景。", pinyin: "Shǒu xiān, nǐ xū yào liǎo jiě xiàng mù de bèi jǐng.", kh: "ជាដំបូង អ្នកត្រូវតែស្វែងយល់អំពីផ្ទាំងបរិយាកាសរបស់គម្រោង។" },
    { cn: "我受不了这个噪音。", pinyin: "Wǒ shòu bù liǎo zhè ge zào yīn.", kh: "ខ្ញុំទ្រាំមិនបាននឹងសម្លេងកាចនេះទេ។" },
    { cn: "他受到了很好的待遇。", pinyin: "Tā shòu dào le hěn hǎo de dài yù.", kh: "គាត់ទទួលបានការប៉ះពាល់ដ៏ល្អ។" },
    { cn: "她是一个售货员。", pinyin: "Tā shì yī gè shòu huò yuán.", kh: "នាងគឺជាបុគ្គលិកលក់ទំនិញម្នាក់។" },
    { cn: "我们输掉了比赛。", pinyin: "Wǒ men shū diào le bǐ sài.", kh: "យើងបានចាញ់ការប្រកួត។" },
    { cn: "我熟悉这个地方。", pinyin: "Wǒ shú xī zhè ge dì fāng.", kh: "ខ្ញុំស្គាល់កន្លែងនេះល្អ។" },
    { cn: "这个城市的数量在不断增加。", pinyin: "Zhè ge chéng shì de shù liàng zài bù duàn zēng jiā.", kh: "បរិមាណនៃទីក្រុងនេះកំពុងបន្ថែមឡើងជាបន្តបន្ទាប់។" },
    { cn: "这是一组数字。", pinyin: "Zhè shì yī zǔ shù zì.", kh: "នេះគឺជាក្រុមលេខមួយ។" },
    { cn: "他是个帅哥。", pinyin: "Tā shì gè shuài gē.", kh: "គាត់គឺជាប្រុសសង្ហា។" },
    { cn: "顺便告诉我一声。", pinyin: "Shùn biàn gào sù wǒ yī shēng.", kh: "ប្រាប់ខ្ញុំផងដោយឡែកផង។" },
    { cn: "她顺利完成了任务。", pinyin: "Tā shùn lì wán chéng le rèn wu.", kh: "នាងបានបញ្ចប់ភារកិច្ចដោយរលូន។" },
    { cn: "请按顺序排列这些书。", pinyin: "Qǐng àn shùn xù pái liè zhè xiē shū.", kh: "សូមបញ្ជូនសៀវភៅទាំងនេះតាមលំដាប់។" },
    { cn: "请详细说明情况。", pinyin: "Qǐng xiáng xì shuō míng qíng kuàng.", kh: "សូមពន្យល់អំពីស្ថានភាពនេះឲ្យច្បាស់។" },
    { cn: "他获得了硕士学位。", pinyin: "Tā huò dé le shuò shì xué wèi.", kh: "គាត់ទទួលបានបរិញ្ញាបត្រជាន់ខ្ពស់ (Master)។" },
    { cn: "她的父亲去世了。", pinyin: "Tā de fù qīn qù shì le.", kh: "ប៉ាដែលនាងស្លាប់ហើយ។" },
    { cn: "请不要乱丢塑料袋。", pinyin: "Qǐng bù yào luàn diū sù liào dài.", kh: "សូមកុំបោះថង់ប្លាស្ទិកដោយគ្មានគោលបំណង។" },
    { cn: "速度很快。", pinyin: "Sù dù hěn kuài.", kh: "ល្បឿនគឺអាចជួយបានយ៉ាងរហ័ស។" },
    { cn: "这个水果酸酸的。", pinyin: "Zhè ge shuǐ guǒ suān suān de.", kh: "ផ្លែឈើនេះជូរចិន។" },
    { cn: "你随便选择一个吧。", pinyin: "Nǐ suí biàn xuǎn zé yī gè ba.", kh: "អ្នកតាមចិត្តជ្រើសរើសមួយទេ។" },
    { cn: "随着天气的变化，气温下降了。", pinyin: "Suí zhe tiān qì de biàn huà, qì wēn xià jiàng le.", kh: "ជាមួយនឹងការផ្លាស់ប្តូរទីតាំង អាកាសធាតុស្លាប់សញ្ញាប្រតិបត្តិការ។" },
    { cn: "他的孙子很聪明。", pinyin: "Tā de sūn zi hěn cōng míng.", kh: "ចៅប្រុសរបស់គាត់ចេះច្បាស់។" },
    { cn: "所有的学生都来了。", pinyin: "Suǒ yǒu de xué shēng dōu lái le.", kh: "សិស្សទាំងអស់បានមកហើយ។" },
    { cn: "他在台上表演。", pinyin: "Tā zài tái shàng biǎo yǎn.", kh: "គាត់កំពុងបង្ហាញនៅលើវេទិកា។" },
    { cn: "我抬不起这个箱子。", pinyin: "Wǒ tái bù qǐ zhè ge xiāng zi.", kh: "ខ្ញុំមិនអាចលើកប្រអប់នេះបានទេ។" },
    { cn: "她的态度很积极。", pinyin: "Tā de tài dù hěn jī jí.", kh: "ទស្សនៈរបស់គាត់មានវិជ្ជមាន។" },
    { cn: "我会弹钢琴。", pinyin: "Wǒ huì tán gāng qín.", kh: "ខ្ញុំអាចលេងភ្លេងព្យាណូបាន។" },
    { cn: "我们可以谈一谈。", pinyin: "Wǒ men kě yǐ tán yī tán.", kh: "យើងអាចពិភាក្សាកกันបាន។" },
    { cn: "我喝了一碗汤。", pinyin: "Wǒ hē le yī wǎn tāng.", kh: "ខ្ញុំបានផឹកស៊ុបមួយចាន។" },
    { cn: "她喜欢吃糖。", pinyin: "Tā xǐ huān chī táng.", kh: "គាត់ចូលចិត្តបរិច្ឆេទស្ករ។" },
    { cn: "他躺在床上休息。", pinyin: "Tā tǎng zài chuáng shàng xiū xī.", kh: "គាត់បានដេកលើគ្រែសម្រាប់សម្រាក។" },
    { cn: "我去了一趟超市。", pinyin: "Wǒ qù le yī tàng chāo shì.", kh: "ខ្ញុំបានទៅដល់ផ្សារមួយដង។" },
    { cn: "我们讨论了很多问题。", pinyin: "Wǒ men tǎo lùn le hěn duō wèn tí.", kh: "យើងបានពិភាក្សាបញ្ហាជាច្រើន។" },
    { cn: "他讨厌吃蔬菜。", pinyin: "Tā tǎo yàn chī shū cài.", kh: "គាត់ស្អប់ការទទួលទានបន្លែ។" },
    { cn: "这个产品的特点是耐用。", pinyin: "Zhè ge chǎn pǐn de tè diǎn shì nài yòng.", kh: "លក្ខណៈពិសេសនៃផលិតផលនេះគឺអាចប្រើប្រាស់បានយូរ។" },
    { cn: "他提出了一个好建议。", pinyin: "Tā tí chū le yī ge hǎo jiàn yì.", kh: "គាត់បានដាក់សំណើល្អមួយ។" },
    { cn: "这家公司提供优质的服务。", pinyin: "Zhè jiā gōng sī tí gōng yōu zhì de fú wù.", kh: "ក្រុមហ៊ុននេះផ្តល់សេវាកម្មដែលមានគុណភាពខ្ពស់។" },
    { cn: "他提前完成了任务。", pinyin: "Tā tí qián wán chéng le rèn wu.", kh: "គាត់បានបញ្ចប់ភារកិច្ចជាមុន។" },
    { cn: "我提醒你带上护照。", pinyin: "Wǒ tí xǐng nǐ dài shàng hù zhào.", kh: "ខ្ញុំបានរំលឹកអ្នកឲ្យយកលិខិតអត្តសញ្ញាណ។" },
    { cn: "请填空。", pinyin: "Qǐng tián kòng.", kh: "សូមបំពេញចន្លោះទទេ។" },
    { cn: "我没有条件参加。", pinyin: "Wǒ méi yǒu tiáo jiàn cān jiā.", kh: "ខ្ញុំគ្មានលក្ខខណ្ឌចូលរួម។" },
    { cn: "请停车。", pinyin: "Qǐng tíng chē.", kh: "សូមចតរថយន្ត។" },
    { cn: "她挺喜欢运动的。", pinyin: "Tā tǐng xǐ huān yùn dòng de.", kh: "គាត់ពិតជាចូលចិត្តកីឡា។" },
    { cn: "我们通过了考试。", pinyin: "Wǒ men tōng guò le kǎo shì.", kh: "យើងបានឆ្លងកាត់ការប្រឡង។" },
    { cn: "老师通知了我们考试时间。", pinyin: "Lǎo shī tōng zhī le wǒ men kǎo shì shí jiān.", kh: "គ្រូបានជូនដំណឹងអំពីពេលវេលាប្រឡង។" },
    { cn: "我对他的同情。", pinyin: "Wǒ duì tā de tóng qíng.", kh: "ខ្ញុំមានមនោសញ្ចេតនាចំពោះគាត់។" },
    { cn: "我们同时工作。", pinyin: "Wǒ men tóng shí gōng zuò.", kh: "យើងធ្វើការជាមួយគ្នាក្នុងពេលដូចគ្នា។" },
    { cn: "他推我一把。", pinyin: "Tā tuī wǒ yī bǎ.", kh: "គាត់បានលើកខ្ញុំមួយទឹក។" },
    { cn: "他推迟了会议时间。", pinyin: "Tā tuī chí le huì yì shí jiān.", kh: "គាត់បានពន្យាពេលពេលវេលាជួបប្រជុំ។" },
    { cn: "他脱掉了外套。", pinyin: "Tā tuō diào le wài tào.", kh: "គាត់បានដកពាក់អាវក្រៅ។" },
    { cn: "我穿上了新袜子。", pinyin: "Wǒ chuān shàng le xīn wà zi.", kh: "ខ្ញុំបានពាក់ស្រោមជើងថ្មី។" },
    { cn: "这是一件完全正确的事。", pinyin: "Zhè shì yī jiàn wán quán zhèng què de shì.", kh: "នេះគឺជាការពិតដែលពេញលេញ។" },
    { cn: "往往他们都迟到。", pinyin: "Wǎng wǎng tā men dōu chí dào.", kh: "ពួកគេភាគច្រើនយឺតចូលមក។" },
    { cn: "我喜欢打网球。", pinyin: "Wǒ xǐ huān dǎ wǎng qiú.", kh: "ខ្ញុំចូលចិត្តលេងបាល់ទង់។" },
    { cn: "这个网站很受欢迎。", pinyin: "Zhè ge wǎng zhàn hěn shòu huān yíng.", kh: "វេបសាយនេះគឺពេញនិយម។" },
    { cn: "这是一个危险的地方。", pinyin: "Zhè shì yī ge wēi xiǎn de dì fāng.", kh: "នេះគឺជាផ្ទៃដីដែលគ្រោះថ្នាក់។" },
    { cn: "卫生间在哪里？", pinyin: "Wèi shēng jiān zài nǎ lǐ?", kh: "បន្ទប់ទឹកនៅកន្លែងណា?" },
    { cn: "这道菜的味道很好。", pinyin: "Zhè dào cài de wèi dào hěn hǎo.", kh: "រសជាតិរបស់ម្ហូបនេះល្អណាស់។" },
    { cn: "今天的温度很高。", pinyin: "Jīn tiān de wēn dù hěn gāo.", kh: "សីតុណ្ហភាពថ្ងៃនេះខ្ពស់ណាស់។" },
    { cn: "我喜欢读文章。", pinyin: "Wǒ xǐ huān dú wén zhāng.", kh: "ខ្ញុំចូលចិត្តអានអត្ថបទ។" },
    { cn: "空气污染越来越严重。", pinyin: "Kōng qì wū rǎn yuè lái yuè yán zhòng.", kh: "ការបំពុលខ្យល់កំពុងធ្ងន់ធ្ងរឡើង។" },
    { cn: "我无钱去旅行。", pinyin: "Wǒ wú qián qù lǚ xíng.", kh: "ខ្ញុំគ្មានប្រាក់ទៅធ្វើដំណើរ។" },
    { cn: "这个电影真无聊。", pinyin: "Zhè ge diàn yǐng zhēn wú liáo.", kh: "ខ្សែភាពយន្តនេះពិតជាគ្មានអ្វីធ្វើ។" },
    { cn: "无论发生什么，我们都要保持冷静。", pinyin: "Wú lùn fā shēng shén me, wǒ men dōu yào bǎo chí lěng jìng.", kh: "មិនថាអ្វីដែលកើតឡើងទេ យើងគួរតែរក្សាទុកការសម្រាក។" },
    { cn: "我们有一些误会。", pinyin: "Wǒ men yǒu yī xiē wù huì.", kh: "យើងមានការយល់ច្រឡំខ្លះ។" },
    { cn: "他的演讲吸引了很多人。", pinyin: "Tā de yǎn jiǎng xī yǐn le hěn duō rén.", kh: "ការបង្ហាញរបស់គាត់ទាក់ទាញមនុស្សជាច្រើន។" },
    { cn: "我喜欢吃西红柿。", pinyin: "Wǒ xǐ huān chī xī hóng shì.", kh: "ខ្ញុំចូលចិត្តបរិច្ឆេទប៉េងប៉ោះ។" },
    { cn: "这道菜有点咸。", pinyin: "Zhè dào cài yǒu diǎn xián.", kh: "ម្ហូបនេះមានអាកប្បកិរិយាខ្លះៗ។" },
    { cn: "我付了现金。", pinyin: "Wǒ fù le xiàn jīn.", kh: "ខ្ញុំបានបង់ប្រាក់សន្សំ។" },
    { cn: "她羡慕他的成功。", pinyin: "Tā xiàn mù tā de chéng gōng.", kh: "គាត់ចង់មានភាពជោគជ័យដូចគាត់។" },
    { cn: "这两者是相反的。", pinyin: "Zhè liǎng zhě shì xiāng fǎn de.", kh: "ស្ថានភាពទាំងពីរនេះប្រឆាំងគ្នា។" },
    { cn: "我们的意见相同。", pinyin: "Wǒ men de yì jiàn xiāng tóng.", kh: "គំនិតរបស់យើងស្មើគ្នា។" },
    { cn: "这花香气扑鼻。", pinyin: "Zhè huā xiāng qì pū bí.", kh: "ផ្កានេះមានក្លិនស្រស់ប្លែក។" },
    { cn: "我会详细解释。", pinyin: "Wǒ huì xiáng xì jiě shì.", kh: "ខ្ញុំនឹងពន្យល់យ៉ាងលម្អិត។" },
    { cn: "那声音很响。", pinyin: "Nà shēng yīn hěn xiǎng.", kh: "សម្លេងនោះគឺខ្លាំងណាស់។" },
    { cn: "我需要一个橡皮。", pinyin: "Wǒ xū yào yī ge xiàng pí.", kh: "ខ្ញុំត្រូវការយ៉ូសដុតសរសេរ។" },
    { cn: "我听到了好消息。", pinyin: "Wǒ tīng dào le hǎo xiāo xi.", kh: "ខ្ញុំបានឮព័ត៌មានល្អមួយ។" },
    { cn: "我喜欢吃小吃。", pinyin: "Wǒ xǐ huān chī xiǎo chī.", kh: "ខ្ញុំចូលចិត្តបរិច្ឆេទតូចៗ។" },
    { cn: "那个小伙子很有才华。", pinyin: "Nà ge xiǎo huǒ zi hěn yǒu cái huá.", kh: "ក្មេងប្រុសនោះមានទេពកោសល្យខ្ពស់។" },
    { cn: "我在读一本小说。", pinyin: "Wǒ zài dú yī běn xiǎo shuō.", kh: "ខ្ញុំកំពុងអានប្រលោមពិភពមួយ។" },
    { cn: "这个药的效果很好。", pinyin: "Zhè ge yào de xiào guǒ hěn hǎo.", kh: "ថ្នាំនេះមានផលប៉ះពាល់ល្អ។" },
    { cn: "他讲了一个笑话。", pinyin: "Tā jiǎng le yī gè xiào huà.", kh: "គាត់បាននិយាយរឿងកំប្លែងមួយ។" },
    { cn: "今天他的心情很好。", pinyin: "Jīn tiān tā de xīn qíng hěn hǎo.", kh: "ថ្ងៃនេះអារម្មណ៍របស់គាត់ល្អណាស់។" },
    { cn: "这份工作很辛苦。", pinyin: "Zhè fèn gōng zuò hěn xīn kǔ.", kh: "ការងារនេះយ៉ាងពិបាក។" },
    { cn: "我收到了一个信封。", pinyin: "Wǒ shōu dào le yī ge xìn fēng.", kh: "ខ្ញុំបានទទួលសំបុត្រផ្តល់ព័ត៌មានមួយ។" },
    { cn: "我把钥匙放在桌子上了。", pinyin: "Wǒ bǎ yào shi fàng zài zhuō zi shàng le.", kh: "ខ្ញុំបានដាក់សោនៅលើតុ។" },
    { cn: "也许明天会下雨。", pinyin: "Yě xǔ míng tiān huì xià yǔ.", kh: "ប្រហែលជាពីរថ្ងៃនេះនឹងភ្លៀង។" },
    { cn: "树上有很多叶子。", pinyin: "Shù shàng yǒu hěn duō yè zi.", kh: "មានស្លឹកឈើច្រើននៅលើដើមឈើ។" },
    { cn: "请翻到下一页。", pinyin: "Qǐng fān dào xià yī yè.", kh: "សូមបង្រ្កាបទៅទំព័របន្ទាប់។" },
    { cn: "一切都准备好了。", pinyin: "Yī qiè dōu zhǔn bèi hǎo le.", kh: "អ្វីទាំងអស់បានត្រៀមរួចរាល់។" },
    { cn: "我以为他已经回家了。", pinyin: "Wǒ yǐ wéi tā yǐ jīng huí jiā le.", kh: "ខ្ញុំគិតថាគាត់បានត្រឡប់ទៅផ្ទះហើយ។" },
    { cn: "我有不同的意见。", pinyin: "Wǒ yǒu bù tóng de yì jiàn.", kh: "ខ្ញុំមានមតិផ្សេងទៀត។" },
    { cn: "他是一个很有艺术天赋的人。", pinyin: "Tā shì yī gè hěn yǒu yì shù tiān fù de rén.", kh: "គាត់គឺជាអ្នកមានទេពកោសល្យសិល្បៈ។" },
    { cn: "因此，我们必须加快进度。", pinyin: "Yīn cǐ, wǒ men bì xū jiā kuài jìn dù.", kh: "ដោយហេតុផលនេះ យើងត្រូវតែបង្កើនល្បឿន។" },
    { cn: "他的行为引起了大家的注意。", pinyin: "Tā de xíng wéi yǐn qǐ le dà jiā de zhù yì.", kh: "អាកប្បកិរិយារបស់គាត់បណ្ដាលឲ្យមានការចាប់អារម្មណ៍ពីមនុស្សគ្រប់គ្នា។" },
    { cn: "这给我留下了深刻的印象。", pinyin: "Zhè gěi wǒ liú xià le shēn kè de yìn xiàng.", kh: "នេះបានទាក់ទាញភាពច្បាស់លាស់ខ្លាំង។" },
    { cn: "我们赢了比赛。", pinyin: "Wǒ men yíng le bǐ sài.", kh: "យើងឈ្នះការប្រកួត។" },
    { cn: "他正在应聘这份工作。", pinyin: "Tā zhèng zài yìng pìn zhè fèn gōng zuò.", kh: "គាត់កំពុងទទួលការផ្តល់ការងារនេះ។" },
    { cn: "他是一个非常勇敢的人。", pinyin: "Tā shì yī gè fēi cháng yǒng gǎn de rén.", kh: "គាត់គឺជាមនុស្សមានកម្លាំងចិត្តខ្ពស់។" },
    { cn: "我们永远是朋友。", pinyin: "Wǒ men yǒng yuǎn shì péng yǒu.", kh: "យើងគឺជាមិត្តភាពរយៈពេលអតិបរិមា។" },
    { cn: "他的优点很多。", pinyin: "Tā de yōu diǎn hěn duō.", kh: "គុណសម្បត្តិរបស់គាត់មានច្រើន។" },
    { cn: "她是一个优秀的学生。", pinyin: "Tā shì yī gè yōu xiù de xué shēng.", kh: "គាត់គឺជាសិស្សឯកទេស។" },
    { cn: "这个电影很幽默。", pinyin: "Zhè ge diàn yǐng hěn yōu mò.", kh: "ខ្សែភាពយន្តនេះមានការសើចចិត្ត។" },
    { cn: "我尤其喜欢这本书。", pinyin: "Wǒ yóu qí xǐ huān zhè běn shū.", kh: "ខ្ញុំចូលចិត្តសៀវភៅនេះជាពិសេស។" },
    { cn: "由我来决定。", pinyin: "Yóu wǒ lái jué dìng.", kh: "ដោយខ្ញុំត្រូវសម្រេចចិត្ត។" },
    { cn: "由于天气原因，我们不能出门。", pinyin: "Yóu yú tiān qì yuán yīn, wǒ men bù néng chū mén.", kh: "ដោយសារតែហេតុផលអាកាសធាតុ យើងមិនអាចចេញក្រៅបានទេ។" },
    { cn: "我去邮局寄了信。", pinyin: "Wǒ qù yóu jú jì le xìn.", kh: "ខ្ញុំទៅការិយាល័យផ្តល់សំបុត្រដើម្បីផ្ញើសំបុត្រ។" },
    { cn: "他们是非常友好的朋友。", pinyin: "Tā men shì fēi cháng yǒu hǎo de péng yǒu.", kh: "ពួកគេគឺជាមិត្តភាពល្អណាស់។" },
    { cn: "友谊是非常宝贵的。", pinyin: "Yǒu yì shì fēi cháng bǎo guì de.", kh: "មិត្តភាពគឺជាអារម្មណ៍ថ្លៃថ្មួយ។" },
    { cn: "这个故事很有趣。", pinyin: "Zhè ge gù shì hěn yǒu qù.", kh: "រឿងនេះគួរឱ្យចាប់អារម្មណ៍ណាស់។" },
    { cn: "他很忙，于是他没有来参加会议。", pinyin: "Tā hěn máng, yú shì tā méi yǒu lái cān jiā huì yì.", kh: "គាត់ពិបាកពេល, ដូច្នេះគាត់មិនបានមកចូលរួមសន្និសីទទេ។" },
    { cn: "今天我感到非常愉快。", pinyin: "Jīn tiān wǒ gǎn dào fēi cháng yú kuài.", kh: "ថ្ងៃនេះខ្ញុំមានអារម្មណ៍រីករាយណាស់។" },
    { cn: "我与他是朋友。", pinyin: "Wǒ yǔ tā shì péng yǒu.", kh: "ខ្ញុំជាមិត្តជាមួយគាត់។" },
    { cn: "我喜欢打羽毛球。", pinyin: "Wǒ xǐ huān dǎ yǔ máo qiú.", kh: "ខ្ញុំចូលចិត្តវាយសី។" },
    { cn: "语法是学习语言的重要部分。", pinyin: "Yǔ fǎ shì xué xí yǔ yán de zhòng yào bù fen.", kh: "រយៈការប្រាប់ភាសាគឺជាផ្នែកសំខាន់នៃការសិក្សាភាសា។" },
    { cn: "中文是我学习的语言。", pinyin: "Zhōng wén shì wǒ xué xí de yǔ yán.", kh: "ភាសាចិនគឺជាភាសាដែលខ្ញុំរៀន។" },
    { cn: "我已经预习了明天的课。", pinyin: "Wǒ yǐ jīng yù xí le míng tiān de kè.", kh: "ខ្ញុំបានរៀបចំមុនសម័យការសិក្សារបស់ថ្ងៃស្អែក។" },
    { cn: "原来他是我小时候的朋友。", pinyin: "Yuán lái tā shì wǒ xiǎo shí hòu de péng yǒu.", kh: "ដើមត្រូវគាត់គឺជាមិត្តរបស់ខ្ញុំនៅពេលក្មេង។" },
    { cn: "我希望你能原谅我。", pinyin: "Wǒ xī wàng nǐ néng yuán liàng wǒ.", kh: "ខ្ញុំសង្ឃឹមថាអ្នកអាចទោសខ្ញុំបាន។" },
    { cn: "这件事的原因很复杂。", pinyin: "Zhè jiàn shì de yuán yīn hěn fù zá.", kh: "មូលហេតុនៃរឿងនេះស្មុគស្មាញណាស់។" },
    { cn: "我们有一个约会。", pinyin: "Wǒ men yǒu yī gè yuē huì.", kh: "យើងមានការណាត់ជួបមួយ។" },
    { cn: "我每天都喜欢阅读书籍。", pinyin: "Wǒ měi tiān dōu xǐ huān yuè dú shū jí.", kh: "ខ្ញុំចូលចិត្តអានសៀវភៅរៀងរាល់ថ្ងៃ។" },
    { cn: "天空中有很多云。", pinyin: "Tiān kōng zhōng yǒu hěn duō yún.", kh: "នៅមេឃមានពពកច្រើន។" },
    { cn: "他允许我提前离开。", pinyin: "Tā yǔn xǔ wǒ tí qián lí kāi.", kh: "គាត់អនុញ្ញាតឲ្យខ្ញុំចាកចេញមុនពេល។" },
    { cn: "我买了一本杂志。", pinyin: "Wǒ mǎi le yī běn zá zhì.", kh: "ខ្ញុំបានទិញកាសែតមួយ។" },
    { cn: "咱们一起去旅行吧！", pinyin: "Zán men yī qǐ qù lǚ xíng ba!", kh: "យើងរាល់គ្នាដំណើរទៅធ្វើដំណើរជាមួយគ្នាដោយ!" },
    { cn: "这只是暂时的情况。", pinyin: "Zhè zhǐ shì zàn shí de qíng kuàng.", kh: "នេះគឺជាស្ថានភាពបណ្តោះអាសន្ន។" },
    { cn: "房间有点脏。", pinyin: "Fáng jiān yǒu diǎn zāng.", kh: "បន្ទប់គឺកខ្វក់ខ្លះៗ។" },
    { cn: "每个人都有自己的责任。", pinyin: "Měi gè rén dōu yǒu zì jǐ de zé rèn.", kh: "មនុស្សគ្រប់រូបមានការទទួលខុសត្រូវផ្ទាល់ខ្លួន។" },
    { cn: "他的工资增加了。", pinyin: "Tā de gōng zī zēng jiā le.", kh: "ប្រាក់ខែរបស់គាត់បានបន្ថែម។" },
    { cn: "电话占线了，请稍后再打。", pinyin: "Diàn huà zhàn xiàn le, qǐng shāo hòu zài dǎ.", kh: "ទូរស័ព្ទរវល់ហើយ សូមទូរស័ព្ទម្តងទៀតក្រោយមក។" },
    { cn: "公司正在招聘新员工。", pinyin: "Gōng sī zhèng zài zhāo pìn xīn yuán gōng.", kh: "ក្រុមហ៊ុនកំពុងជ្រើសរើសបុគ្គលិកថ្មី។" },
    { cn: "他照顾着病人。", pinyin: "Tā zhào gù zhe bìng rén.", kh: "គាត់ថតរូបអ្នកជំងឺ។" },
    { cn: "这是真正的艺术作品。", pinyin: "Zhè shì zhēn zhèng de yì shù zuò pǐn.", kh: "នេះគឺជាការងារផ្សេងៗដែលពិតប្រាកដ។" },
    { cn: "我正在整理我的房间。", pinyin: "Wǒ zhèng zài zhěng lǐ wǒ de fáng jiān.", kh: "ខ្ញុំកំពុងរៀបចំបន្ទប់របស់ខ្ញុំ។" },
    { cn: "他过得很正常。", pinyin: "Tā guò dé hěn zhèng cháng.", kh: "គាត់រស់នៅយ៉ាងធម្មតា។" },
    { cn: "现在正好是下午三点。", pinyin: "Xiàn zài zhèng hǎo shì xià wǔ sān diǎn.", kh: "ពេលនេះបានត្រឹមត្រូវគឺម៉ោងបីល្ងាច។" },
    { cn: "你的答案是正确的。", pinyin: "Nǐ de dá àn shì zhèng què de.", kh: "ចម្លើយរបស់អ្នកត្រឹមត្រូវ។" },
    { cn: "他是正式的代表。", pinyin: "Tā shì zhèng shì de dài biǎo.", kh: "គាត់គឺជាតំណាងផ្លូវការ។" },
    { cn: "我可以证明这是我的错。", pinyin: "Wǒ kě yǐ zhèng míng zhè shì wǒ de cuò.", kh: "ខ្ញុំអាចបង្ហាញថាអំពើនេះគឺខុសពីខ្ញុំ។" },
    { cn: "这是我之中的问题。", pinyin: "Zhè shì wǒ zhī zhōng de wèn tí.", kh: "នេះគឺជាបញ្ហាដែលមាននៅក្នុងខ្ញុំ។" },
    { cn: "我们需要他的支持。", pinyin: "Wǒ men xū yào tā de zhī chí.", kh: "យើងត្រូវការជួយគាំទ្រពីគាត់។" },
    { cn: "他有丰富的知识。", pinyin: "Tā yǒu fēng fù de zhī shi.", kh: "គាត់មានចំណេះដឹងទូលំទូលាយ។" },
    { cn: "这项工作值得你付出努力。", pinyin: "Zhè xiàng gōng zuò zhí de nǐ fù chū nǔ lì.", kh: "ការងារនេះគួរឱ្យអ្នកចំណាយកម្លាំងព្យាយាម។" },
    { cn: "这些植物很美丽。", pinyin: "Zhè xiē zhí wù hěn měi lì.", kh: "រុក្ខជាតិទាំងនេះស្អាតណាស់។" },
    { cn: "他直接回答了我的问题。", pinyin: "Tā zhí jiē huí dá le wǒ de wèn tí.", kh: "គាត់បានឆ្លើយតបសំណួររបស់ខ្ញុំដោយផ្ទាល់។" },
    { cn: "她的职业是医生。", pinyin: "Tā de zhí yè shì yī shēng.", kh: "មុខរបររបស់នាងគឺជាគ្រូពេទ្យ។" },
    { cn: "我只好放弃了。", pinyin: "Wǒ zhǐ hǎo fàng qì le.", kh: "ខ្ញុំគ្មានជម្រើសទេ ប៉ុណ្ណោះបោះបង់ទៅ។" },
    { cn: "只要你努力，你就能成功。", pinyin: "Zhǐ yào nǐ nǔ lì, nǐ jiù néng chéng gōng.", kh: "តែត្រូវការព្យាយាម ប៉ុណ្ណោះ អ្នកអាចទទួលបានជោគជ័យ។" },
    { cn: "请指着那个地方。", pinyin: "Qǐng zhǐ zhe nà ge dì fāng.", kh: "សូមជួបបង្ហាញកន្លែងនោះ។" },
    { cn: "至少我可以帮你。", pinyin: "Zhì shǎo wǒ kě yǐ bāng nǐ.", kh: "យ៉ាងតិចខ្ញុំអាចជួយអ្នកបាន។" },
    { cn: "这个商品的质量很好。", pinyin: "Zhè ge shāng pǐn de zhì liàng hěn hǎo.", kh: "គុណភាពនៃទំនិញនេះអ很好។" },
    { cn: "这个包包很重。", pinyin: "Zhè ge bāo bāo hěn zhòng.", kh: "កាបូបនេះធ្ងន់ណាស់។" },
    { cn: "这个问题的重点是时间。", pinyin: "Zhè ge wèn tí de zhòng diǎn shì shí jiān.", kh: "ចំណុចសំខាន់នៃបញ្ហានេះគឺសម័យវេលា។" },
    { cn: "我们要重视这个问题。", pinyin: "Wǒ men yào zhòng shì zhè ge wèn tí.", kh: "យើងត្រូវផ្តល់សារៈសំខាន់ទៅលើបញ្ហានេះ។" },
    { cn: "周围的环境很安静。", pinyin: "Zhōu wéi de huán jìng hěn ān jìng.", kh: "បរិវេណជុំវិញមានសន្តិភាព។" },
    { cn: "我有一个好主意。", pinyin: "Wǒ yǒu yí gè hǎo zhǔ yi.", kh: "ខ្ញុំមានគំនិតល្អមួយ។" },
    { cn: "大家祝贺他成功了。", pinyin: "Dàjiā zhù hè tā chénggōng le.", kh: "មនុស្សទាំងអស់អបអរសាទរចំពោះជោគជ័យរបស់គាត់។" },
    { cn: "他是一个著名的演员。", pinyin: "Tā shì yí gè zhù míng de yǎn yuán.", kh: "គាត់គឺជាតារាសម្តែងល្បីល្បាញ។" },
    { cn: "这是我专门为你准备的礼物。", pinyin: "Zhè shì wǒ zhuān mén wèi nǐ zhǔnbèi de lǐwù.", kh: "នេះគឺជាអំណោយដែលខ្ញុំបានរៀបចំសម្រាប់អ្នកជាពិសេស។" },
    { cn: "你学的是什么专业？", pinyin: "Nǐ xué de shì shénme zhuān yè?", kh: "អ្នកសិក្សាអំពីវិស័យឯកទេសអ្វី?" },
    { cn: "请把椅子转过来。", pinyin: "Qǐng bǎ yǐzi zhuǎn guòlai.", kh: "សូមបង្វិលកៅអីមកបែបនេះ។" },
    { cn: "他做生意赚了很多钱。", pinyin: "Tā zuò shēngyì zhuàn le hěn duō qián.", kh: "គាត់បានរកប្រាក់ច្រើនពីអាជីវកម្ម។" },
    { cn: "你的答案很准确。", pinyin: "Nǐ de dá'àn hěn zhǔn què.", kh: "ចម្លើយរបស់អ្នកត្រឹមត្រូវណាស់។" },
    { cn: "我们要准时到达机场。", pinyin: "Wǒmen yào zhǔn shí dàodá jīchǎng.", kh: "យើងត្រូវទៅដល់ព្រលានយន្តហោះទាន់ពេល។" },
    { cn: "他做事很仔细。", pinyin: "Tā zuò shì hěn zǐ xì.", kh: "គាត់ធ្វើការយ៉ាងប្រុងប្រយ័ត្ន។" },
    { cn: "我们应该保护自然环境。", pinyin: "Wǒmen yīnggāi bǎohù zìrán huánjìng.", kh: "យើងគួរតែថែរក្សាបរិស្ថានធម្មជាតិ។" },
    { cn: "她很自信地回答了问题。", pinyin: "Tā hěn zì xìn de huídá le wèntí.", kh: "នាងបានឆ្លើយសំណួរយ៉ាងទំនុកចិត្ត។" },
    { cn: "老师总结了这次的学习内容。", pinyin: "Lǎoshī zǒng jié le zhè cì de xuéxí nèiróng.", kh: "គ្រូបានសង្ខេបមាតិកាសិក្សារបស់ពេលនេះ។" },
    { cn: "我们想租一间公寓。", pinyin: "Wǒmen xiǎng zū yì jiān gōngyù.", kh: "យើងចង់ជួលអាផាតមិនមួយ។" },
    { cn: "你最好现在就去看医生。", pinyin: "Nǐ zuì hǎo xiànzài jiù qù kàn yīshēng.", kh: "អ្នកគួរជាទីបំផុតទៅជួបវេជ្ជបណ្ឌិតឥឡូវនេះ។" },
    { cn: "我们应该尊重别人的意见。", pinyin: "Wǒmen yīnggāi zūn zhòng biérén de yìjiàn.", kh: "យើងគួរតែគោរពយោបល់របស់អ្នកដទៃ។" },
    { cn: "这个房子大概有一百平方米左右。", pinyin: "Zhège fángzi dàgài yǒu yì bǎi píngfāng mǐ zuǒ yòu.", kh: "ផ្ទះនេះប្រហែលមានប្រហាក់ប្រហែល 100 ម៉ែត្រការ៉េ។" },
    { cn: "他是一位著名的作家。", pinyin: "Tā shì yí wèi zhùmíng de zuòjiā.", kh: "គាត់ជាអ្នកនិពន្ធល្បីល្បាញ។" },
    { cn: "运动对身体有很大的作用。", pinyin: "Yùndòng duì shēntǐ yǒu hěn dà de zuòyòng.", kh: "ការហាត់ប្រាណមានអាទិភាពខ្លាំងចំពោះសុខភាព។" },
    { cn: "这本书的作者是谁？", pinyin: "Zhè běn shū de zuò zhě shì shéi?", kh: "អ្នកនិពន្ធសៀវភៅនេះជាអ្នកណា?" },
    { cn: "请坐在你的座位上。", pinyin: "Qǐng zuò zài nǐ de zuò wèi shàng.", kh: "សូមអង្គុយនៅកន្លែងរបស់អ្នក។" }


];

const wordList = document.getElementById("word-list");

words.forEach(({ cn, pinyin, kh }) => {
  const card = document.createElement("div");
  card.className = "word-card";
  card.innerHTML = `
    <div class="word">${cn}</div>
    <div class="pinyin">${pinyin}</div>
    <div class="khmer">${kh}</div>
  `;
  wordList.appendChild(card);
});
